fcrepo/fcrepo

fcrepo-boms/fcrepo4-bom/pom.xml

As described in https://github.com/fcrepo4/fcrepo4/issues/683, the fcrepo4-bom module contains references to version 4.0.0-beta for some dependencies. This PR removes that.

The beta artifacts used in the fcrepo4-bom module

---

README.md

See: https://jira.duraspace.org/browse/FCREPO-1306
The link to the HTTP documentation was incorrect.

fixed outdated link in documentation

---

.travis.yml

This adds travis-ci support to the Java8 branch

updated travis-ci configuration

---

fcrepo-auth-common/src/test/java/org/fcrepo/auth/integration/AbstractResourceIT.java
fcrepo-auth-common/src/test/resources/spring-test/test-container.xml
fcrepo-configs/src/main/resources/config/activemq.xml
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/AbstractResourceIT.java
fcrepo-http-api/src/test/resources/spring-test/test-container.xml
fcrepo-integration-ldp/pom.xml
fcrepo-integration-ldp/src/test/java/org/fcrepo/integration/ldp/LdpTestSuiteIT.java
fcrepo-integration-ldp/src/test/resources/spring-test/test-container.xml
fcrepo-integration-rdf/pom.xml
fcrepo-integration-rdf/src/test/resources/spring-test/test-container.xml
fcrepo-mint/src/test/java/org/fcrepo/integration/mint/HttpPidMinterIT.java
fcrepo-mint/src/test/resources/test-container.xml
fcrepo-transform/src/test/java/org/fcrepo/integration/AbstractResourceIT.java
fcrepo-transform/src/test/resources/spring-test/test-container.xml
fcrepo-webapp/pom.xml
fcrepo-webapp/src/main/resources/spring/jms.xml
fcrepo-webapp/src/test/java/org/fcrepo/integration/AbstractResourceIT.java
fcrepo-webapp/src/test/java/org/fcrepo/integration/SanityCheckIT.java
pom.xml

A couple of system properties are referenced throughout the POMs and code but never declared in any POM. These properties can be set in Maven command line executions: ```mvn ... -Dfcrepo.test.port=8080```
The properties should be declared in the man POM using some default values. They can than be overridden by command line arguments.

Add default properties to pom.xml

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/FedoraResourceImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/rdf/impl/LdpContainerRdfContext.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/rdf/impl/LdpContainerRdfContextTest.java

* Handle 'insertedContainerProperty' that has been converted to a reference property
* Provide current session to RdfContexts when constructed in FedoraResourceImpl
Resolves: https://jira.duraspace.org/browse/FCREPO-1383

Enable LDP indirect containers to update referenced container

---

fcrepo-http-api/src/main/resources/views/common-node-header.vsl
fcrepo-http-api/src/main/resources/views/mode-root.vsl

This is a minor change that will allow for better presentation. The nav element should be exclusive of the container element for flow to be consistent with other sites using bootstrap.

Make header and body markup consistent with BS standards

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/url/HttpApiResources.java

Remove serialization label triple

---

fcrepo-jms/pom.xml
fcrepo-kernel-impl/pom.xml
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/observer/DefaultFilter.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/observer/SuppressByMixinFilter.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/integration/kernel/impl/observer/SuppressByMixinFilterIT.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/observer/DefaultFilterTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/observer/SuppressByMixinFilterTest.java
fcrepo-kernel-impl/src/test/resources/spring-test/eventing-suppress.xml
pom.xml

Fixes https://jira.duraspace.org/browse/FCREPO-1456

Adding SuppressByMixinFilter to suppress events related to nodes with any of a given set of mixins

---

fcrepo-http-api/pom.xml
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraBaseResource.java
fcrepo-http-commons/pom.xml
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/exceptionhandlers/JsonParseExceptionMapper.java
fcrepo-jms/pom.xml
fcrepo-jms/src/main/java/org/fcrepo/jms/headers/DefaultMessageFactory.java
fcrepo-metrics/pom.xml
fcrepo-transform/pom.xml
fcrepo-webapp/pom.xml
pom.xml

Resolves: https://jira.duraspace.org/browse/FCREPO-1476

convert gson to jackson2 for JSON handling

---

fcrepo-kernel/pom.xml

Related to https://jira.duraspace.org/browse/FCREPO-1501
As the package name has changed, that change should be reflected in the OSGi export

fix osgi export

---

fcrepo-kernel/pom.xml

Resolves: https://jira.duraspace.org/browse/FCREPO-1608

Remove javaee-api dependency from fcrepo-kernel

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java

Remove use of Jena-atlas runtime exception, 
...which added a non-OSGi friendly dependency.

Follow-on to https://jira.duraspace.org/browse/FCREPO-1667

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/AbstractResourceIT.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/services/TransactionServiceImpl.java
fcrepo-mint/src/main/java/org/fcrepo/mint/HttpPidMinter.java

See: https://jira.duraspace.org/browse/FCREPO-1778
Now the only stack traces in the integration tests are from the LDP test suite (which we have no control over) and the WildcardExceptionManager tests, and there, the stack trace appears to be by design(?).

clean up stack traces from integration tests

---

fcrepo-http-commons/pom.xml
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/AbstractResource.java
pom.xml

See: https://jira.duraspace.org/browse/FCREPO-1776
This change causes integration testing in fcrepo-http-api to generate more error output (the tests do not fail, though). That error output, however, is currently only _masked_ in the integration tests. In a live system (e.g. in tomcat) that error output still appears.

remove jul-to-slf4j dependency; import * in osgi config

---

fcrepo-connector-file/pom.xml
fcrepo-http-api/src/test/java/org/fcrepo/http/api/FedoraLdpTest.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/rdf/impl/PropertiesRdfContext.java

See: https://jira.duraspace.org/browse/FCREPO-1822
This does not address the Jersey injection (runtime) warnings described in FCREPO-1785

clean up trivial build warnings

---

fcrepo-auth-common/src/main/java/org/fcrepo/auth/common/HttpHeaderPrincipalProvider.java
fcrepo-auth-common/src/main/java/org/fcrepo/auth/common/ServletContainerAuthenticationProvider.java

Also log the list of all principals for an authenticated fedoraUser in ServletContainerAuthenticationProvider.
Resolves: https://jira.duraspace.org/browse/FCREPO-1835

Added debug logging to HttpHeaderPrincipalProvider.

---

fcrepo-configs/src/main/resources/config/infinispan/jdbc-postgresql/infinispan.xml
fcrepo-configs/src/main/resources/config/jdbc-postgresql/repository.json
fcrepo-webapp/pom.xml

Fixes https://jira.duraspace.org/browse/FCREPO-1916

Adding configuration for PostgreSQL and generic JDBC databases

---

fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/rdf/impl/RootRdfContext.java

https://jira.duraspace.org/browse/FCREPO-1934 introduced the use of a deprecated API, this PR fixes that.

replace deprecated API

---

fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/observer/DefaultFilter.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/observer/EventFilter.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/observer/SimpleObserver.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/observer/eventmappings/AllNodeEventsOneEvent.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/observer/eventmappings/InternalExternalEventMapper.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/observer/eventmappings/OneToOne.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/observer/SimpleObserverTest.java

Resolves: https://jira.duraspace.org/browse/FCREPO-1866
These interfaces rely on JCR types and are therefore relocated to the modeshape implementation.

move JCR-based eventing interfaces into the modeshape impl

---

index.html

This adds a link to the new `fcrepo-java-client` documentation.

Update link to current fcrepo-java-client documentation

---

fcrepo-integration-rdf/src/test/java/org/fcrepo/integration/rdf/BibframeIT.java

Ignore the Bibframe test until we can come up with a real fix for how requests without UTF8 charset encodings are handled.

Ignore Bibframe IT test, pending resolution in FCREPO-1979

---

fcrepo-http-api/src/main/resources/views/common.js

Resolved [FCREPO-1981](https://jira.duraspace.org/browse/FCREPO-1981)
Tested with Firefox 45.0.1 on OS X 
Should be tested on Linux and Windows.

Only return false after the ajax call is complete.

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraFixity.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraVersioning.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraVersions.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/domain/MultiPrefer.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/domain/PreferTag.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/domain/SinglePrefer.java
pom.xml

2.8 does not have the memory leak reported in
https://java.net/jira/browse/HK2-216
A possible fix was applied in Jersey 2.17, but this and newer
Jersey versions aren't drop-in compatible with 2.13/2.8.

FCREPO-2025: Switch to a version of Jersey that does not leak memory

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/FedoraTypes.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/models/FedoraResource.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/FedoraBinaryImpl.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/FedoraResourceImpl.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/observer/SimpleObserver.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/rdf/impl/PropertiesRdfContext.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/services/BinaryServiceImpl.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/services/ContainerServiceImpl.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/services/NodeServiceImpl.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/utils/FedoraTypesUtils.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/utils/PropertyChangedListener.java
fcrepo-kernel-modeshape/src/main/resources/fedora-node-types.cnd
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/integration/kernel/modeshape/FedoraBinaryImplIT.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/integration/kernel/modeshape/FedoraResourceImplIT.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/integration/kernel/modeshape/observer/SimpleObserverIT.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/ContainerImplTest.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/FedoraResourceImplTest.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/services/ContainerServiceImplTest.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/services/NodeServiceImplTest.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/utils/PropertyChangedListenerTest.java

Resolves: https://jira.duraspace.org/browse/FCREPO-1742
Resolves: https://jira.duraspace.org/browse/FCREPO-1498
Supersedes #917

Use a userspace lastmodified property instead of jcr:lastModified

---

fcrepo-webapp/pom.xml

By upgrading the postgresql JDBC connector to the latest version, I was able to build and run a postgres-based Fedora-on-Modeshape5 repository locally.
Relates to: https://jira.duraspace.org/browse/FCREPO-1994

use correct postgres JDBC connector

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraFixity.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraVersioning.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/FedoraLdpTest.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/AbstractResource.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/api/rdf/HttpResourceConverter.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/services/NamespaceService.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/services/NamespaceServiceImpl.java

Partially resolves: https://jira.duraspace.org/browse/FCREPO-1694
In particular, this removes the dependency on the modeshape-based namespace service,
~~and extracts the TransactionServiceImpl from the HTTP layer.~~

Remove more modeshape dependencies from the HTTP layers

---

fcrepo-connector-file/pom.xml
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/session/SessionFactory.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/session/SessionFactoryTest.java
fcrepo-jms/pom.xml
fcrepo-kernel-api/pom.xml
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/services/CredentialsService.java
fcrepo-kernel-modeshape/pom.xml
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/services/CredentialsServiceImpl.java

Addresses: https://jira.duraspace.org/browse/FCREPO-1694
I am taking these one at a time now. Please bear with me. The `Repository::login` method requires a `javax.jcr.Credentials` object (which is a simple marker class: it doesn't do anything on its own), and the fcrepo-auth-* modules expect that the `Credentials` object is an `instanceof` modeshape's `ServletCredentials`.
Thus, in order to remove this particular modeshape dependency from `fcrepo-http-commons`, I added a `CredentialsService` as an injected "shim". There may be other ways to implement this, but I couldn't think of another way to do this without extensive changes. I would appreciate a review of this.

Remove modeshape's ServletCredentials from the HTTP layers

---

fcrepo-kernel-api/pom.xml
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/services/CredentialsService.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/services/CredentialsServiceImpl.java

Addresses: https://jira.duraspace.org/browse/FCREPO-1664
`javax.jcr.Credentials` is just a marker class, and as such it there is no need for it to make `fcrepo-kernel-api` depend on `javax.servlet.http`. (Modeshape _does_ require a dependency on `javax.servlet.http`, but this PR isolates that dependency in the `fcrepo-kernel-modeshape` module).

Remove fcrepo-kernel-api dependency on javax.servlet.http package

---

fcrepo-auth-common/src/main/java/org/fcrepo/auth/common/ServletContainerAuthenticationProvider.java
fcrepo-auth-common/src/test/java/org/fcrepo/auth/common/ServletContainerAuthenticationProviderTest.java

ServletContainerAuthenticationProvider already handles DelegateHeaderPrincipalProvider differently
from other providers in authenticate() and getDelegatedPrincipal(). The same pattern was added into
collectPrincipals() to prevent instances of this class from filling FEDORA_ALL_PRINCIPALS.
Resolves: https://jira.duraspace.org/browse/FCREPO-2065

FCREPO-2065 DelegateHeaderPrincipalProvider leaking on-behalf-of header when called with non-admin

---

index.html

There is a new version of fcrepo-java-client: https://github.com/fcrepo4-exts/fcrepo-java-client/releases/tag/fcrepo-java-client-0.2.0

update docs with new version of fcrepo-java-client

---

fcrepo-connector-file/src/main/java/org/fcrepo/connector/file/FedoraFileSystemConnector.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/FedoraLdpTest.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraFixityIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/test/util/TestHelpers.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/FedoraTypes.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/models/FedoraBinary.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/utils/ContentDigest.java
fcrepo-kernel-api/src/test/java/org/fcrepo/kernel/api/utils/ContentDigestTest.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/FedoraBinaryImpl.java
fcrepo-kernel-modeshape/src/main/resources/fedora-node-types.cnd
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/integration/kernel/modeshape/FedoraBinaryImplIT.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/integration/kernel/modeshape/observer/SimpleObserverIT.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/FedoraBinaryImplTest.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/utils/FixityInputStreamTest.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/utils/TestHelpers.java

- Enable users to configure the default digest algorithm
** This is set with the property: fedoraconfig:defaultDigestAlgorithm
- Note: This update modifies the main CND:
** from: premis:hasMessageDigest (URI) COPY
** to: premis:hasMessageDigest (URI) COPY multiple
Resolves: https://jira.duraspace.org/browse/FCREPO-1842

Enable multiple user-provided content digests

---

fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/utils/NamespaceTools.java

Resolves: https://jira.duraspace.org/browse/FCREPO-2244

Exclude internal (jcr, mode) prefixes from namespace map

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/responses/StreamingBaseHtmlProvider.java

Resolves: https://jira.duraspace.org/browse/FCREPO-2260
I hold no brief for the use of Velocity templates, but this makes it possible to at least configure the location of `velocity.log`. Otherwise, it shows up in all sorts of inconvenient locations.

Make it possible to set the location for velocity.log

---

fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/FedoraRepository.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/FedoraSession.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/services/BatchService.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/FedoraRepositoryImpl.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/FedoraSessionImpl.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/services/BatchServiceImpl.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/services/BatchServiceImplTest.java

I have a complete implementation for this, but so as not to make the PR too massive, these are the new interfaces being added which will be used to replace instances of `jcr.Session`, `jcr.Repository`, and the existing `org.fcrepo.kernel.api.services.TransactionService`.
Begins to address: https://jira.duraspace.org/browse/FCREPO-1868
Supersedes #968

Add core types to be used to replace the use of jcr.Session in the kernel API

---

fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/rdf/impl/VersionsRdfContext.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/services/VersionServiceImpl.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/services/VersionServiceImplTest.java

Also adds test coverage for invalid version labels.
Resolves: https://jira.duraspace.org/browse/FCREPO-1984:

Prevents whitespace characters from being used in version labels.

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/FedoraNodesTest.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/responses/ViewHelpers.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/responses/ViewHelpersTest.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/test/util/TestHelpers.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/models/FedoraResource.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/FedoraResourceImpl.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/rdf/impl/FixityRdfContext.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/integration/kernel/modeshape/FedoraBinaryImplIT.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/integration/kernel/modeshape/FedoraResourceImplIT.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/FedoraBinaryImplTest.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/FedoraResourceImplTest.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/NonRdfSourceDescriptionImplTest.java

- Wherever possible java.util.Date and Calendar have been replaced
Resolves: https://jira.duraspace.org/browse/FCREPO-1995

Replaces uses of java.util.Date/Cal with java.time options

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/FedoraLdpTest.java

RFC 7232 explicitly states that 304 "Not Modified" responses to conditional requests MUST not contain an entity body: 
"A 304 response cannot contain a message-body; it is always terminated 
by the first empty line after the header fields." 
Responses from Fedora *do* have an entity body. When Fedora accessed via clients such as Apache Httpclient, this can cause apparent corruption of responses from Fedora. HttpClient does not consume entity bodies from requests that return a 304. The bytes from the errant entity body returned from Fedora can remain in internal HttpClient buffers, corrupting reads from subsequent responses. 
* Addresses https://jira.duraspace.org/browse/FCREPO-2313

Insure 304 responses do not contain an entity body. (master)

---

fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/FedoraResourceImpl.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/rdf/impl/SkolemNodeRdfContext.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/rdf/impl/mappings/PropertyToTriple.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/integration/kernel/modeshape/FedoraResourceImplIT.java

The first commit recursively removes inbound references to child of deleted containers.
The second commit ignores non-existent referents.
Resolves: https://jira.duraspace.org/browse/FCREPO-2323
Note: These two commits should not be squashed.

Fcrepo 2323

---

fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/exceptionhandlers/WebApplicationExceptionMapper.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/exceptionhandlers/WebApplicationExceptionMapperTest.java

FCREPO-2313 addressed an issue where entity bodies were being included in responses that MUST NOT carry entity bodies, per RFC 2616. 
Unfortunately, the fix for FCREPO-2313 was incomplete. The WebApplicationExceptionMapper adds entity bodies to responses without regard for their status code. In particular ContentExposingResource#evaluateRequestPreconditions(...) may lead to an exception being thrown with a 304 response code. 
The consequences of this issue are the same as the consequences for FCREPO-2313- that is, application servers and clients get confused when processing responses that contain entity bodies when they otherwise shouldn't. 
In addition, the request logic is a bit unclear to me, but it seems that the intent is that if preconditions fail, an exception should be thrown by …

WebApplicationExceptionMapper adds entity bodies on 304 responses

---

fcrepo-http-api/src/main/resources/views/common.js

@whikloj's [patch](https://jira.duraspace.org/browse/FCREPO-2341?focusedCommentId=53173&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-53173) for [FCREPO-2341](https://jira.duraspace.org/browse/FCREPO-2341) seems to work.
This PR corrects the parsing of HTTP `Link` headers in the Fedora HTML UI to be more rigorous when multiple `Link` headers are present in the response (as is the case when API-X is set up as a proxy to the Fedora repository).  The `describedBy` link header will always be used, even in the presence of multiple link headers in the response.
When multiple `Link` headers are present in the response, the browser seems to pick one of them at random.  This is problematic, for example, when API-X adds additional `Link` headers, such as a link to a …

Correctly parse 'described-by' Link header. (FCREPO-2341)

---

fcrepo-configs/src/main/resources/config/file-s3/repository.json
fcrepo-configs/src/main/resources/config/jdbc-mysql-s3/repository.json
fcrepo-configs/src/main/resources/config/jdbc-postgresql-s3/repository.json
fcrepo-webapp/pom.xml
pom.xml

Adds new repository.json files to support binary storage in S3 along with object storage in mysql, postgresql, and as a file.
Performance of these configuration options have been tested and recorded (by Daniel Bernstein) here: https://wiki.duraspace.org/display/FF/Many+Members+Performance+Testing
Configuration to support binary storage in S3 is currently listed here: https://github.com/fcrepo4-labs/fcrepo-webapp-plus-cloud. In short, the additional parameters are as follows:
JAVA_OPTS="${JAVA_OPTS} -Daws.accessKeyId=<AWS Access ID>"
JAVA_OPTS="${JAVA_OPTS} -Daws.secretKey=<AWS Secret Key>"
JAVA_OPTS="${JAVA_OPTS} -Daws.bucket=<S3 Bucket Name>"

Completes https://jira.duraspace.org/browse/FCREPO-2402

---

fcrepo-integration-rdf/src/test/java/org/fcrepo/integration/rdf/AbstractIntegrationRdfIT.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/rdf/JcrRdfTools.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/utils/JcrPropertyStatementListener.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/utils/iterators/PersistingRdfStreamConsumer.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/integration/kernel/modeshape/FedoraResourceImplIT.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/rdf/JcrRdfToolsTest.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/utils/JcrPropertyStatementListenerTest.java

Skolemizing blank nodes to hash URI resources (prefixed with "#genid") instead of external nodes prefixed with "/.well-known/genid/".
Fixes https://jira.duraspace.org/browse/FCREPO-2108
See also https://github.com/fcrepo/fcrepo-specification/issues/82

Skolemizing blank nodes with hash URIs

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/FedoraLdpTest.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/exceptionhandlers/CannotCreateResourceExceptionMapper.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/exception/CannotCreateResourceException.java
fcrepo-webapp/src/main/webapp/static/constraints/CannotCreateResourceException.rdf
fcrepo-webapp/src/test/java/org/fcrepo/integration/SanityCheckIT.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2378
When a client requests creation of a ldp:Resource via link header they will get the usual error message and now will also get a ldp:constrainedBy link header in the response, pointing to a constraints file. 
This PR adds a new type of exception to cover this scenario. 
Build the fcrepo.war file and deploy it. Then test this out via: 
curl -i http://localhost:8080/fcrepo/rest -XPOST -H"Link: <http://www.w3.org/ns/ldp#Resource>; rel=\"type\""
This will fail and the message will have a pointer to a constraint file. Verify via curl that you can get that file. 
@awoods, @acoburn

Adds ldp:constrainedBy header to creation of ldp:Resource

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraVersioning.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersionsIT.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2511 & https://jira.duraspace.org/browse/FCREPO-2415
Adds 2 Link headers to the response to a `{path}/fcr:versions` request and adds an Integration Test to look for the RDFSource header.
1. Create a container.
2. Create a version of the container.
3. `curl -i -I "http://path/to/the/container/fcr:versions"`
You should see 
```
Link: <http://www.w3.org/ns/ldp#RDFSource>;rel="type"
```
This also solved FCREPO-2415 as described in my duplicate ticket [FCREPO-2525](https://jira.duraspace.org/browse/FCREPO-2525)
Basically, we assume that if a HEAD request gets a `200 OK` status code and there **aren't** any Link headers then it is a NonRdfSource resource. Then it appends …

Add Link headers to /fcr:versions listing and add IT

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraFixity.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraFixityIT.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2526
Related to https://jira.duraspace.org/browse/FCREPO-1247 subsequent PR #1203 
Adds RDFSource and Resource Link headers as well as IT to test.
Copy of work in #1202 
2 new Link headers on /fcr:fixity results
Same as #1202 for but for `/fcr:fixity`
Example:
@awoods

Add Link headers to fcr:fixity and integration test

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraVersions.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersionsIT.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-1247
https://groups.google.com/forum/#!msg/fedora-tech/qw3GlptWBQw/CaGXHMuiRXIJ
Follow-on ticket: https://jira.duraspace.org/browse/FCREPO-2526 - 
To fix the HTML UI as it still fails to follow links on versions to their fixity results (see [FCREPO-2415](https://jira.duraspace.org/browse/FCREPO-2415)), but going direct in the browser to the URI now works.
Causes requests to `fcr:fixity` results of a `fcr:versions` to be handled by `FedoraFixity` instead of `FedoraVersions`.
This is the same as changing the URI `http://localhost:8080/rest/picture/fcr:versions/v0/fcr:fixity` to `http://localhost:8080/rest/picture/fcr%3Aversions/v0/fcr:fixity`
This was educational, it is a [negative …

Skip fcr:versions handler for fcr:fixity requests

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java

***
**JIRA Ticket**:  https://jira.duraspace.org/browse/FCREPO-2508
Adds a check for csv file type in the code that determines if something being PUT should be a binary or container. 
Along with that check described above, a few new tests are added.  One test specifically related to CSV files. and one test is for binaries created with mime type that's correct, but with capitol letters in the name. 
Test by added a file with mime-type 'text/csv' to fedora. See that the binary is properly created and that you can retrieve it successfully. 
* create a container
* upload a csv file as a binary in that container
* verify that you can retrieve it back successfully. 
This partially addresses https://jira.duraspace.org/browse/FCREPO-2516  (nc …

Ensures that CSV files are not considered RDF

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/FedoraLdpTest.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/exceptionhandlers/PreconditionExceptionMapper.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/exceptionhandlers/PreconditionExceptionMapperTest.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/exception/PreconditionException.java

Resolves https://jira.duraspace.org/browse/FCREPO-2386
**Adds PreconditionException for handling precondition failures.**
* * *
**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2386
Mostly housecleaning.  No functionality changes or bug fixes.
A in-depth description of the changes made by this PR. Technical details and possible side effects.
This PR does a bit of housecleaning by ensuring that precondition exceptions follow the same exception handling pattern used by similar api exceptions and adds assurance that precondition exceptions will only return appropriate http codes.
Not necessary.  Unit and integration tests already cover the functionality.
Any additional information that you think would be …

Adds PreconditionException type to replace WebapplicationException.

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/responses/RangeRequestInputStreamTest.java

**Do Not merge until 4.7.4 has been released**
Fixes https://jira.duraspace.org/browse/FCREPO-2536

Using range length for content-length header

---

pom.xml

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2581
* [Modeshape 5.4.0.Final Release Notes](http://docs.jboss.org/modeshape/5.4.0.Final/release.html)
* [MODE-2670](https://issues.jboss.org/browse/MODE-2670)
* [Tomcat stuck thread issue on fedora-tech](https://groups.google.com/d/topic/fedora-tech/b8Eap28sL1M/discussion)
Upgrades to Modeshape 5.4.0.Final.
Updates the Modeshape dependency from 5.3.0.Final to 5.4.0.Final in the main pom.xml. UMD's interest in this is for the fix to [MODE-2670](https://issues.jboss.org/browse/MODE-2670), which we believe is responsible for some of our stuck thread issues.
* Run all unit and integration tests
This is a minor version upgrade of Modeshape, so it should not have any breaking changes or cause disruption to existing repositories.
@awoods

Upgrade to Modeshape 5.4.0.Final

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/FedoraLdpTest.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/exceptionhandlers/UnsupportedAlgorithmExceptionMapper.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/exception/UnsupportedAlgorithmException.java

- Adds new UnsupportedAlgorithmException and mapper
- Updates FedoraLdp class to throw new exception appropriately
- Updates FedoraLdpTest and FedoraLdpIT
Resolves: https://jira.duraspace.org/browse/FCREPO-2593
This PR is a contribution toward the API Alignment sprint (9/11/17-9/22/17).

Ensures correct response codes for creating LDP-NR

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/FedoraLdpTest.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/AbstractResourceIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraRelaxedLdpIT.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/models/FedoraResource.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/FedoraResourceImpl.java
fcrepo-webapp/src/main/webapp/static/js/common.js

Use `Link rel="type"` header to determine interaction type, instead of checking the MIME type
and `Content-Disposition` headers.
Fixes https://jira.duraspace.org/browse/FCREPO-2584

Use Link header to determine interaction model, instead of mime type sniffing

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java

Fixes https://jira.duraspace.org/browse/FCREPO-2588
Added Content-Location header to GET and HEAD responses for external contents.

Include Content-Location header in external content GET and HEAD responses.

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/AbstractResourceIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java

Adds support for depth headers to http DELETE method
- Adds logic to FedoraLdp.deleteObject() to check depth header for
containers
- Adds two new IT test cases
- Adds helper method to abstract IT class
Resolves: https://jira.duraspace.org/browse/FCREPO-2600

Fcrepo 2600 new

---

fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/FedoraSession.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/FedoraSessionImpl.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/integration/kernel/modeshape/FedoraSessionImplIT.java
fcrepo-kernel-modeshape/src/test/resources/config/testing/repository.json

Fixes #https://jira.duraspace.org/browse/FCREPO-2608
Make user identities available as URIs in kernel API through method getUserAgent().

Make user identities available as URIs in kernel API.

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraNodes.java

Fixes https://jira.duraspace.org/browse/FCREPO-2641
Deprecate MOVE and COPY.
Add {{@Deprecation}} attributes to the FedoraNodes methods for MOVE and COPY.

Deprecate MOVE and COPY.

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/url/HttpApiResources.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/FedoraLdpTest.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/RdfLexicon.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/FedoraResourceImpl.java

Note:  this is not currently working for binaries.  There is an integration test in this PR (FedoraLdpIT.testCreateVersionedBinaryResource) that covers binaries but is currently @Ignored until the https://jira.duraspace.org/browse/FCREPO-2644 is resolved.
Resolves: https://jira.duraspace.org/browse/FCREPO-2624
**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2624
A in-depth description of the changes made by this PR. Technical details and possible side effects.
Example:
* Changes x feature to such that y
* Added x
* Removed y
1. mvn clean install -Pone-click …

Enable Versioning on a new LDPR

---

fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/URIConstants.java
fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/WebACAuthorization.java
fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/WebACRolesProvider.java
fcrepo-auth-webac/src/test/java/org/fcrepo/auth/webac/WebACAuthorizationTest.java
fcrepo-auth-webac/src/test/java/org/fcrepo/auth/webac/WebACRolesProviderTest.java
fcrepo-auth-webac/src/test/resources/acls/09/authorization.ttl
fcrepo-auth-webac/src/test/resources/acls/09/group.ttl

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2633
Changes WebAC groups implementation from acl:agentClass to acl:agentGroup.
Implements the SOLID WebAC spec “Groups of Agents” section (https://github.com/solid/web-access-control-spec#groups-of-agents) by using acl:agentGroup / vcard:Group / vcard:hasMember to create lists of users. Use of acl:agentClass / foaf:Group / foaf:member is no longer supported.
Standard `mvn clean test verify` in the fcrepo-auth-webac module.
This will require updates to the wiki documentation on how to set up user groups for WebAC:
* https://wiki.duraspace.org/display/FEDORA5x/How+to+Use+WebAC+agentClass+Groups
@dannylamb, @awoods

Change groups from acl:agentClass to acl:agentGroup

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/RdfLexicon.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/FedoraResourceImpl.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/services/BinaryServiceImpl.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/services/ServiceHelpers.java
fcrepo-kernel-modeshape/src/main/resources/fedora-node-types.cnd
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/integration/kernel/modeshape/FedoraBinaryImplIT.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/integration/kernel/modeshape/observer/SimpleObserverIT.java

Enable Binary TimeMap test
**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2644
Creates a new nodetype based on the nt:file but with an additional nt:folder child called fedora:timemap to hold the timemap and mementos.
Integration and unit tests run. There are additional example actions, but with the resource called **TimeMap**, so change this to **fedora:timemap** now.
Example:
* Does this change require documentation to be updated? Hopefully not
* Does this change add any new dependencies? No
* Does this change require any other modifications to be made to the repository (ie. Regeneration activity, etc.)? No
* Could this change impact execution of existing code? Possibly
SPRINTERS ASSEMBLE
@awoods

Create new versionFile nodeType with nt:folder inside

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2645
Disallows any interaction if any part of the path (or Slug) uses a fedora: namespace prefix.
Spin up a Fedora
Try to PUT a resource to http://localhost:8080/rest/fedora:resource, it should succeed
Pull in this PR
Try to PUT a resource to http://localhost:8080/rest/fedora:resource, it should fail.
Same for GET, POST, DELETE, HEAD or OPTIONS.
Example:
@awoods

Disallow interactions on paths with fedora: in it.

---

fcrepo-boms/fcrepo-jcr-bom/pom.xml
fcrepo-http-commons/pom.xml
fcrepo-kernel-modeshape/pom.xml
pom.xml

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2649
Fedora-tech thread where upgrading to Narayana was suggested by @birkland: https://groups.google.com/d/topic/fedora-tech/r4qR2mF4eGk/discussion
Switch from outdated JBoss JTA to up-to-date Narayana JTA.
The JBoss JTA library was at version 4.16.6.Final, which was approximately 5 years old. Switched to the Narayana JTA, which is actually the replacement for the old JBoss JTA. Using version 5.7.0.Final, which was released in September 2017.
Run a standard `mvn clean install`
* Adds a dependency on Narayana JTA
* Removes dependency on JBoss JTA
@awoods

Switch from JBoss JTA to Narayana JTA (#2649)

---

fcrepo-boms/fcrepo-jcr-bom/pom.xml
fcrepo-http-commons/pom.xml
fcrepo-kernel-modeshape/pom.xml
pom.xml

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2649
Fedora-tech thread where upgrading to Narayana was suggested by @birkland: https://groups.google.com/d/topic/fedora-tech/r4qR2mF4eGk/discussion
Switch from outdated JBoss JTA to up-to-date Narayana JTA.
The JBoss JTA library was at version 4.16.6.Final, which was approximately 5 years old. Switched to the Narayana JTA, which is actually the replacement for the old JBoss JTA. Using version 5.7.0.Final, which was released in September 2017.
Run a standard `mvn clean install`
* Adds a dependency on Narayana JTA
* Removes dependency on JBoss JTA
@awoods

Switch from JBoss JTA to Narayana JTA (4.7-maintenance) (#2649)

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java

Accept-Post response header.
Resolves: https://jira.duraspace.org/browse/FCREPO-2585
1. Fire up the one-click
2. `curl -v -XOPTIONS http://localhost:8080/rest/`
3. Verify that the Accept-Post header containers the following option: 
message/external-body; access-type=URL

Each supported external content type is now advertised in

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersioningIT.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/api/rdf/HttpResourceConverter.java

**JIRA Ticket**: https://jira.duraspace.org/projects/FCREPO/issues/FCREPO-2653
TimeMaps are FedoraResources located at `/fedora:timemap` inside a versionable resource but are exposed to the outside world as `/fcr:versions`.
This PR makes the subject returned when making an RDF request for the resource appear as this `/fcr:versions` URI.
Before PR.
1. Create a versionable resource FOO.
1. Get the Timemap at FOO/fcr:versions with any Accept type **except** application/link-format.
The subject of the response will be FOO/fedora:timemap
After PR.
1. Get the Timemap at FOO/fcr:versions with any Accept type **except** application/link-format.
The subject will now be FOO/fcr:versions.
Example:
* Does this change add any new dependencies? …

Translate TimeMap URIs as fcr:versions

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/FedoraLdpTest.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/utils/ContentDigest.java
fcrepo-kernel-api/src/test/java/org/fcrepo/kernel/api/utils/ContentDigestTest.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/integration/kernel/modeshape/FedoraBinaryImplIT.java

**JIRA Ticket**: https://jira.duraspace.org/projects/FCREPO/issues/FCREPO-2651
Changes the algorithm accepted and returned in Want-Digest from **sha-1** to **sha**
A simple find and replace and a tonne of tests updated.
```
> curl -i -G -H"Want-Digest: sha-1" http://localhost:8080/rest/louis -ufedoraAdmin:fedoraAdmin             
Date: Thu, 02 Nov 2017 05:12:55 GMT
ETag: "810323d9c6f1ffce9984556f3da0f68f798f4ecf"
Last-Modified: Thu, 02 Nov 2017 05:07:27 GMT
Content-Type: text/plain;charset=utf-8
Content-Length: 68
Server: Jetty(9.3.1.v20150714)
Unsupported digest algorithm provided in 'Want-Digest' header: sha-1
> curl -i -I -H"Want-Digest: sha" http://localhost:8080/rest/louis -ufedoraAdmin:fedoraAdmin 
Date: Thu, 02 Nov 2017 05:13:46 GMT
ETag: …
```

Replace want digest sha1 and with sha

---

fcrepo-webapp/src/main/resources/jbossts-properties.xml

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2664
Related to: https://github.com/fcrepo4/fcrepo4/pull/1278
Adds the [properties file](http://docs.jboss.org/jbosstm/5.0.0.M1/guides/narayana-jta-installation_guide/chap-JBossJTA_Installation_Guide-Test_Chapter.html) that Narayana-JTA (formally JBossJTA) reads its configuration from.
Sets the problematic property using an already [defined system property](https://github.com/fcrepo4/fcrepo4/blob/4.7-maintenance/fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/spring/DefaultPropertiesLoader.java#L51-L52).
This issue only occurs on certain system configurations. The [fcrepo4-vagrant](https://github.com/fcrepo4-exts/fcrepo4-vagrant) does seem to have the environment to cause this error. 
* `vagrant up` the …

Add jbossts-properties.xml to fcrepo-webapp

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java

- Allows binary to be retrieved even if mime-type is invalid
**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2520
This PR will allow a client to still be able to retrieve a binary, should the mime type field become syntactically incorrect.  This is possible solution (or a step in the right direction) for the above JIRA ticket. 
Another solution is to ensure that ebucore:hasMimeType field is not set to something invalid.  Not sure how hard that would be to implement. 
This change wraps up the MediaType.valueOf() call and catches an exception it might throw.  If it throws one, the exception gets logged and the code keeps going as if the mime type were 'application/octet-stream', versus returning a 500 …

Adds code to handle invalid mime-type

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/FedoraResourceImpl.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/integration/kernel/modeshape/FedoraResourceImplIT.java

**This is a continuation of the fix for FCREPO-2520. ebucore:hasMimeType triple will be syntatically validated on a sparql update or PUT request. 
***
JIRA Ticket: https://jira.duraspace.org/browse/FCREPO-2520
Introduces code that will run through the triples and make sure an object of a ebucore:hasMimeType triple is syntactically valid. 
This code adds on to the triple validation that is done in the kernel-modeshape module. It adds a check for syntax on mime type. 
You could test this change by sending in a sparql request with ebucore:hasMimeType set to something syntactically invalid - like "Junk Mime Type" - that should return a 400 error with a message about the mime type. 
Also, sending RDF via a PUT …

Check RDF mimetype in ebucore:hasMimeType triple

---

fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/FedoraResourceImpl.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2681
In the nt:file type there is jcr:content child, our new nt:versionedFile also has a fedora:timemap.
But because the jcr:content has the PRIMARY attribute it is returned when the getNode() function is accessed. So we need to go up to the containing resource (Description) and then access the timemap.
Build a versionable binary. Before on a GET you would get a 500 error. Now you should get the correct(ish) response. The address of the timemap in the returned RDF is wrong. There is a new ticket for that (https://jira.duraspace.org/browse/FCREPO-2690)
Example:
* Does this change require documentation to be updated? 
* Does this change add any new …

Adjust to get the timemap from the binary correctly.

---

fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/utils/FedoraTypesUtils.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/utils/FedoraTypesUtilsTest.java

Resolves: https://jira.duraspace.org/browse/FCREPO-2690
**Ensures that binary timemaps translate their paths correctly.**
* * *
**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2690
Ensures that binary timemaps translate their paths correctly.
FedoraTypes.getContainingNode(node) was modified to return the direct parent when the specified node is the TimeMap of a Non RDF Source Description.
Start the one-click jar.
1. ``` curl -v -XPUT  -H "Content-Type: text/plain" -H "Link: <http://fedora.info/definitions/fcrepo#VersionedResource>; rel=\"type\"" "http://localhost:8080/rest/test1234" -u fedoraAdmin:fedoraAdmin```
2. ```curl -v http://localhost:8080/rest/test2-1234/fedora:timemap```
3. Verify that subject URI is <http://localhost:8080/rest/test2-1234/fcr:versions> in the returned …

Ensures that binary timemaps translate their paths correctly.

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2694
Uses `.getDescribedResource()` to ensure that when we are viewing the RdfSource tied to a NonRdfSource object, we want the timemap and the timegate URI to be relative to the NonRdfSource URI.
Without this PR.
1. Make a versioned binary.
```
curl -v -XPUT -H "Content-Type: image/jpeg" -H "Link: <http://fedora.info/definitions/fcrepo#VersionedResource>; rel=\"type\"" "http://localhost:8080/rest/binaryVersion" -u fedoraAdmin:fedoraAdmin
```
2. HEAD the binary and the `fcr:metadata` and notice the timemap and timegate Link headers.
```
[whikloj@MacBook-Pro.local 19:03 ] 
[/Users/whikloj] 
> curl -I http://localhost:8080/rest/binaryVersion
Date: Tue, 06 Mar 2018 01:14:38 GMT
ETag: …
```

getDescribedResource to ensure timemap and timegate URIs are correct for binaries

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/FedoraLdpTest.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java

This PR makes HEAD response headers match the non-payload headers returned by a GET request to the same resource. Specifically, this PR ensures the "Vary:" and "Preference-Applied” headers are present for HEAD.
Resolves: https://jira.duraspace.org/browse/FCREPO-2661

Fcrepo 2661 redo

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraVersioning.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersioningIT.java

Disallow PUT and PATCH on LDPCv.
https://jira.duraspace.org/browse/FCREPO-2686
Removed the PUT method, added integration test fro PUT and PATCH.
- Create versioned resource
$ curl -i -XPUT -H "Link: <http://fedora.info/definitions/fcrepo#VersionedResource>; rel=\"type\"" "http://localhost:8080/rest/versionedResource123"
Date: Tue, 06 Mar 2018 22:34:27 GMT
ETag: W/"e762d7afd1d4e48bcb2c897ad2a5a7d8528747c0"
Last-Modified: Tue, 06 Mar 2018 22:34:27 GMT
Link: <http://fedora.info/definitions/fcrepo#VersionedResource>; rel="type"
Link: <http://localhost:8080/rest/versionedResource123>; rel="timegate"
Link: …

Disallowed PUT and PATCH on LDPCv

---

fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/RdfLexicon.java

Replace current Link type Header for LDPv  with Memento specified link.
https://jira.duraspace.org/browse/FCREPO-2678
- It failed to create versioned resource with the old Link type Header:
$ curl -i -XPUT -H "Link: <http://fedora.info/definitions/fcrepo#VersionedResource&gt; rel=\\"type\\"" "http://localhost:8080/rest/versionedResource123"
Date: Wed, 07 Mar 2018 18:27:43 GMT
Link: <http://localhost:8080/static/constraints/CannotCreateResourceException.rdf&gt;; rel="http://www.w3.org/ns/ldp#constrainedBy"
Content-Type: text/plain;charset=utf-8
Content-Length: 82
Server: Jetty(9.2.3.v20140905)
- It's able to create versioned resource with the memento specified link http://mementoweb.org/ns#OriginalResource:
$ curl -i -XPUT -H "Link: …

Replace current Link type Header for LDPv  with Memento specified link.

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/RdfLexicon.java

Replace outdated LDPRv link headers with Memento specified headers http://mementoweb.org/ns#TimeGate and http://mementoweb.org/ns#TimeMap.
https://jira.duraspace.org/browse/FCREPO-2679
1. Create LDPv versioned resource
`$ curl -i -XPUT -H "Link: <http://mementoweb.org/ns#OriginalResource>; rel=\"type\"" "http://localhost:8080/rest/versionedResource123"`
2. Verify the header links <http://mementoweb.org/ns#TimeGate&gt;, <http://mementoweb.org/ns#OriginalResource&gt;
`$ curl -i http://localhost:8080/rest/versionedResource123`
Date: Thu, 08 Mar 2018 17:30:51 GMT
ETag: W/"282640b6d95016247e7014ee34be960cd491bd09"
Last-Modified: Thu, 08 Mar 2018 17:29:06 GMT
Link: <http://www.w3.org/ns/ldp#Resource&gt;; rel="type"
Link: <http://www.w3.org/ns/ldp#Container&gt;; rel="type"
Link: …

Replace outdated LDPRv link headers with Memento specified headers

---

fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/URIConstants.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/RdfLexicon.java
fcrepo-kernel-modeshape/src/main/resources/fedora-node-types.cnd

https://fcrepo.github.io/fcrepo-specification/#link-acl-on-create for PUTs and POSTs.
Adds the following five tests to FedoraLdpIT.
* testPostCreateNonRDFSourceWithAcl
* testPutCreateNonRDFSourceWithAcl
* testPostCreateRDFSourceWithAcl
* testPutCreateRDFSourceWithAcl
* testPutCreateRDFSourceWithNonExistentAcl
**JIRA Ticket**: Resolves: https://jira.duraspace.org/browse/FCREPO-2688
Implements acl assignment on new resources using PUT and POST according to  https://fcrepo.github.io/fcrepo-specification/#link-acl-on-create
```
curl -v -XPUT  "http://localhost:8080/rest/acl1" -u fedoraAdmin:fedoraAdmin
curl -v -XPOST  -H "ContentType: text/plain" -H "Link: <http://localhost:8080/rest/acl1>; rel=\"acl\"" "http://localhost:8080/rest/" -H "Slug: test1" -u fedoraAdmin:fedoraAdmin --data-binary …
```

Implements ACL linking on resource creation as defined in

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersioningIT.java

Updated integration test for LDPCv DELETE.
https://jira.duraspace.org/browse/FCREPO-2684
1. Create versioned resource with TimeMap and a Memento:
`curl -i -XPOST -H "Slug:versionedResource123" -H "Link: <http://mementoweb.org/ns#OriginalResource>; rel=\"type\"" "http://localhost:8080/rest"`
`curl -i -XPOST -H "Memento-DateTime: Mon, 12 Mar 2018 13:29:06 GMT" -H "Content-Type: text/turtle" --data "<> <http://purl.org/dc/elements/1.1/title> \"The original title\" ." "http://localhost:8080/rest/versionedResource123/fcr:versions"`
2. Verify that the TimeMap and the Memento both are created:
`curl -i "http://localhost:8080/rest/versionedResource123/fcr:versions"`
`curl -i "http://localhost:8080/rest/versionedResource123/fedora:timemap/20180312132906"`
3. Delete the TimeMap:
`curl -i -XDELETE …

Updated integration test for LDPCv DELETE.

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/exceptionhandlers/InteractionModelViolationExceptionMapper.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/RdfLexicon.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/exception/InteractionModelViolationException.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/FedoraResourceImpl.java
fcrepo-webapp/src/main/webapp/static/constraints/InteractionModelViolationException.rdf

PUT must fail with 409 if trying to change interaction model to non-subtype.
https://jira.duraspace.org/browse/FCREPO-2594,
https://jira.duraspace.org/browse/FCREPO-2591
When attempting to change/delete the interaction model with PUT or PATCH, it returns status 409 with the constrainedBy link header: <http://localhost:8080/static/constraints/InteractionModelViolationException.rdf&gt;; rel="http://www.w3.org/ns/ldp#constrainedBy".
1. Create NnRdfSource binary resource:
`curl -i -XPUT -H "Content-Type: text/plain" "http://localhost:8080/rest/mytest" --data "binary"`
2. Verify PATCH to delete interation model failed with 409:
`curl -i -XPATCH -H "Content-Type: application/sparql-update" "http://localhost:8080/rest/mytest/fcr:metadata" --data "PREFIX ldp: <http://www.w3.org/ns/ldp#> \
PREFIX …

PUT must fail with 409 if trying to change interaction model to non-subtype.

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersioningIT.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/RdfLexicon.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/FedoraResourceImpl.java
fcrepo-kernel-modeshape/src/main/resources/fedora-node-types.cnd

Provide separate timemap for binary and description so that they can be managed separately
**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2707
Provides two timemaps for binaries:
http://localhost/binary/fcr:versions
http://localhost/binary/fcr:metadata/fcr:versions
* Two timemap nodes can be created as children of a binary, currently as outlined in the first example here:
* https://gist.github.com/bbpennel/a3682a61fdd030c03a9a3f63fb3dc9fc
* nt:versionFile allows for two children, fedora:timemap and fedora:binaryTimemap
* fedora:binaryTimemap is used for FedoraBinary resources
* fedora:timemap is used for other resources (including binary description)
* Adds test to check uris of timemap response for binary and description
```
curl -XPOST -H "Slug: versioned_bin2" -H "Link: …
```

Fcrepo 2707 - Provide separate timemap for binary and description

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraVersioning.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersioningIT.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/exceptionhandlers/MementoDatetimeFormatExceptionMapper.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/exception/MementoDatetimeFormatException.java

Remove support for Slug header on POST to LDPCv, and captured the memento DateTimeParseException to handle it with 400 bad request.
https://jira.duraspace.org/browse/FCREPO-2618
1. Create versioned resource with TimeMap and a Memento:
`curl -i -XPOST -H "Slug:versionedResource123" -H "Link: <http://mementoweb.org/ns#OriginalResource>; rel=\"type\"" "http://localhost:8080/rest"`
2. Verify that create memento with Slug header failed with 409 bad request:
`curl -i -XPOST -H "Memento-DateTime: Mon, 12 Mar 2018 13:29:06 GMT" -H "Slug: label123" -H "Content-Type: text/turtle" --data "<> <http://purl.org/dc/elements/1.1/title> \"The original title\" ." "http://localhost:8080/rest/versionedResource123/fcr:versions"`
Date: Tue, 13 Mar 2018 19:16:49 GMT
Content-Type: …

Remove support for Slug header on POST to LDPCv.

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/AbstractVersioningIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersioningIT.java

Support OPTIONS request on LDPRms.
https://jira.duraspace.org/browse/FCREPO-2615
```
1. Create versioned resource:
curl -i -XPOST -H "Slug: v1" -H "Link: <http://mementoweb.org/ns#OriginalResource>; rel=\"type\"" "http://localhost:8080/rest" -H "Content-Type: text/n3" --data-binary "<> <info:fedora/test/field> \"V 1\""
2. Create memento:
echo '<http://localhost:8080/rest/v1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://fedora.info/definitions/v4/repository#Container> .
<http://localhost:8080/rest/v1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://fedora.info/definitions/v4/repository#Resource> .
<http://localhost:8080/rest/v1> <http://fedora.info/definitions/v4/repository#lastModifiedBy> "bypassAdmin" .
<http://localhost:8080/rest/v1> …
```

Support OPTIONS request on LDPRms.

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraVersioning.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/AbstractVersioningIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersioningIT.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/api/rdf/HttpResourceConverter.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/api/rdf/HttpResourceConverterTest.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/FedoraTypes.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/models/FedoraTimeMap.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/FedoraResourceImpl.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/FedoraTimeMapImpl.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/services/VersionServiceImpl.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/utils/FedoraTypesUtils.java
fcrepo-kernel-modeshape/src/main/resources/fedora-node-types.cnd
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/integration/kernel/modeshape/FedoraTimeMapImplIT.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/utils/FedoraTypesUtilsTest.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2719
Refactor of http converter and other mechanisms required to get memento and timemap URIs translated back and forth between http and jcr path.
* Fixes memento uri so that it doesn't expose the node name of the timemap, instead correctly shows fcr:versions.
* FedoraTimeMap objects now track and provide helper to get the original resource the timemap applies to.
* adds memento:original property for fedora:TimeMap type
* Updates http uri conversion to account for mementos, forward and backward
* Switches binary timemaps and mementos to using fedora:binaryTimemap node for storage
* Updates http uri conversion to account for binary mementos using a different node name
* Adds unit tests for timemap and memento uri conversion
* …

Fcrepo 2719 - Path conversion for timemaps and mementos

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-webapp/src/main/webapp/static/constraints/InvalidACLException.rdf

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2687
This PR is to solve the issue that Fedora does not allow to create a link to an ACL resource that is outside of the repository. 
Example:
For example, the following should not be allowed: 
* create rdf resource with acl on POST 
```
curl -v -XPUT -H "Link: <http://google.com>; rel=\"acl\"" "http://localhost:8080/rest/test" 
```
1. create rdf resource with acl on POST 
```
curl -v -XPUT -H "Link: <http://google.com>; rel=\"acl\"" "http://localhost:8080/rest/test" 
```
2. It should return 409 CONFLICT with a message "Cross Domain ACLs is not allowed" 
Tag @awoods @dbernstein

Fix FCREPO-2687 - Restrict Cross Domain ACL

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraVersioning.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersioningIT.java

Resolves: https://jira.duraspace.org/browse/FCREPO-2728
**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2728
Changes the return code from 412 to 409 when creating mementos with identical date times.
```
curl -i -XPOST -H "Slug: versioned_resource_2" -H "Link: <http://mementoweb.org/ns#OriginalResource>; rel=\"type\"" "http://localhost:8080/rest"
curl http://localhost:8080/rest/versioned_resource_2 | curl -v -XPOST http://localhost:8080/rest/versioned_resource_2/fcr:versions -H "Memento-DateTime: Fri, 16 Mar 2018 20:52:17 GMT" -H "Content-Type: text/turtle" --data-binary "@-"
curl http://localhost:8080/rest/versioned_resource_2 | curl -v -XPOST …
```

Creating a Memento in the same second as an existing Memento throws 409.

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersioningIT.java

Prevent modification requests to LDPRm.
https://jira.duraspace.org/browse/FCREPO-2616
```
1. Create versioned resource:
curl -i -XPOST -H "Slug: v1" -H "Link: <http://mementoweb.org/ns#OriginalResource>; rel=\"type\"" "http://localhost:8080/rest" -H "Content-Type: text/n3" --data-binary "<> <info:fedora/test/field> \"V 1\""
2. Create memento:
echo '<http://localhost:8080/rest/v1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://fedora.info/definitions/v4/repository#Container> .
<http://localhost:8080/rest/v1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://fedora.info/definitions/v4/repository#Resource> .
<http://localhost:8080/rest/v1> <http://fedora.info/definitions/v4/repository#lastModifiedBy> "bypassAdmin" .
<http://localhost:8080/rest/v1> …
```

Prevent modification requests to LDPRm.

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraVersioning.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersioningIT.java

https://jira.duraspace.org/browse/FCREPO-2734
Add header link rel="original" to TimeMap.
```
1. Create versioned RDFSource
$ curl -i -XPOST -H "Slug: VersionedResource" -H "Link: <http://mementoweb.org/ns#OriginalResource>; rel=\"type\"" "http://localhost:8080/rest" -H "Content-Type: text/n3" --data-binary "<> <info:fedora/test/field> \"Versioned Resource\""
2. Verify the existing of header link rel="original"
$ curl -i http://localhost:8080/rest/VersionedResource/fcr:versions
Date: Mon, 16 Apr 2018 22:32:10 GMT
ETag: W/"8f487467747c9cb49fbf2ec7b96c2ae03bf67405"
Last-Modified: Mon, 16 Apr 2018 22:29:45 GMT
Link: <http://www.w3.org/ns/ldp#Resource>; rel="type"
Link: <http://www.w3.org/ns/ldp#RDFSource>; rel="type"
Link: <http://mementoweb.org/ns#TimeMap>; rel="type"
Link: …
```

Add header link rel="original" to TimeMap.

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java

Resolves https://jira.duraspace.org/browse/FCREPO-2733
Adds Link: \<link to LDPRv\>; rel="original" for a LDPRv
```
1. Create a versioned resource
$ curl -i -XPOST -H "Slug: VersionedResource" -H "Link: <http://mementoweb.org/ns#OriginalResource>; rel=\"type\"" "http://localhost:8080/rest" -H "Content-Type: text/n3" --data-binary "<> <info:fedora/test/field> \"Versioned Resource\""
2. Check for rel="original" link header
$ curl -i http://localhost:8080/rest/VersionedResource
...
Link: <http://www.w3.org/ns/ldp#Container>;rel="type"
Link: <http://www.w3.org/ns/ldp#BasicContainer>;rel="type"
Link: …
```

FCREPO-2733 Add header link rel=original to TimeGate

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraVersioning.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersioningIT.java

- Remove "\*/\*"
Resolves: https://jira.duraspace.org/browse/FCREPO-2731
* * *
**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2731
Change the 500 response to a '406 Not Acceptable' on TimeMap with bad Accept header
1. Create a versioned resource
```
curl -i -XPOST -H "Slug: obj" -H "Link: <http://mementoweb.org/ns#OriginalResource>; rel=\"type\"" 
"http://localhost:8080/rest/"
```
2. Verify response using following command list
Bad Accept header 
```
curl http://localhost:8080/rest/obj3/fcr:version -H"Accept: junk/format"
curl http://localhost:8080/rest/obj/fcr:versions -H"Accept: application/format-junk"
```
Good Accept header
``` …
```

Address 500 Response on TimeMap with bad Accept header

---

fcrepo-auth-webac/pom.xml
fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/WebACPermission.java
fcrepo-auth-webac/src/test/java/org/fcrepo/auth/webac/WebACPermissionTest.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2758
Create WebACPermission class and adds Apache Shiro 1.4.0 as a dependency to the fcrepo-auth-webac project.
Create a WebACPermission class that implements the Shiro Permission interface. The WebACPermission represents a particular mode of access (e.g., acl:read) to a particular resource; both mode and resource are URIs. The intended purposes of this class are:
* After parsing an ACL, the WebACAuthorizingRealm (see https://jira.duraspace.org/browse/FCREPO-2759 and https://jira.duraspace.org/browse/FCREPO-2760) will return an AuthorizationInfo object that contains WebACPermission instances that correspond to the current user's permissions on the requested resourc.
* In FedoraLdp, information from the HTTP request (request method, …

Create WebACPermission class.

---

fcrepo-auth-webac/pom.xml
fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/WebACAuthorizingRealm.java
fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/WebACPermission.java
fcrepo-auth-webac/src/test/java/org/fcrepo/auth/webac/WebACPermissionTest.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2759
* PR #1324 should be merged before this
* Implementation work will continue in https://jira.duraspace.org/browse/FCREPO-2760
Create WebACAuthorizingRealm class.
Authorization-only Shiro realm. Implementation (see https://jira.duraspace.org/browse/FCREPO-2760) will locate the ACL for the currently requested resource and parse the ACL RDF into a set of WebACPermission instances.
* Compile the `fcrepo-auth-webac` module with `mvn clean install`

Create WebACAuthorizingRealm class.

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/AbstractResourceIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersioningIT.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2614
Adds correct Link headers to Mementos
1. Create a versioned resource
```
curl -u fedoraAdmin:fedoraAdmin -i -XPOST -H "Slug: resource1" -H "Link: <http://mementoweb.org/ns#OriginalResource>; rel=\"type\"" "http://localhost:8080/rest"
```
1. Create a version
```
curl -u fedoraAdmin:fedoraAdmin -i -XPOST "http://localhost:8080/rest/resource1/fcr:versions"
```
1. GET the Memento
Old version
```
> curl -I -ufedoraAdmin:fedoraAdmin http://localhost:8080/rest/resource1/fcr:versions/20010308210303
Date: Wed, 18 Apr 2018 18:50:43 GMT
ETag: W/"4a6c1a2b7f38d9a2137e02c8dd936d100bf18830"
Last-Modified: Fri, 02 Mar 2018 19:43:57 GMT
Link: …
```

Add correct headers for Mementos

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-webapp/src/main/webapp/static/js/common.js

resources.
* * *
**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2767
This PR is a first step in bringing versioning support back into the HTML UI.  As a precondition for creating versions,  resources must be created with a link header that indicates the resource is to be versionable.  Now when you hit the "Create" button in the HTML UI, the resource is versionable.
From the UI perspective nothing visible has changed.
1.  build and start the webapp.
2.  create a container named "test"
3.  ``curl -v http://localhost:8080/rest/test``
4. check that the timemap, …

Ensure that all resources created via the HTML UI are versionable

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersioningIT.java

https://jira.duraspace.org/browse/FCREPO-2765
Add acl link header to TimeMap and remove the existing acl link header from Mementos.
```
1. Create versioned resource
curl -i -XPOST -H "Slug: VersionedResource" -H "Link: <http://mementoweb.org/ns#OriginalResource>; rel=\"type\"" "http://localhost:8080/rest" -H "Content-Type: text/n3" --data-binary "<> <info:fedora/test/field> \"Versioned Resource\""
2. Verify that the fcr:acl link header exists in TimeMap
$ curl -i http://localhost:8080/rest/VersionedResource/fcr:versions
Date: Thu, 19 Apr 2018 22:17:13 GMT
ETag: W/"b940adc98bd47077e86012f112a06caca1049a4e"
Last-Modified: Thu, 19 Apr 2018 22:15:42 GMT
Link: <http://www.w3.org/ns/ldp#RDFSource>;rel="type"
Link: …
```

Add ACL link header to TimeMap and remove it from Mementos.

---

fcrepo-webapp/src/main/webapp/static/js/common.js

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2697 and https://jira.duraspace.org/browse/FCREPO-2768
Allows you to use the Create Version button in the HTML UI, but not trying to send a Slug header.
Before PR, make a resource and press the button. Get an error.
After PR, make a resource and press the button. Get redirected to the fcr:versions page (which is blank). But if you `curl` the resource there is a version created.
Example:
* Does this change add any new dependencies?  no
* Does this change require any other modifications to be made to the repository (ie. Regeneration activity, etc.)?  no

Stop using Slug header for versions from HTML UI

---

fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/AbstractRolesAuthorizationDelegate.java
fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/WebACRolesProvider.java
fcrepo-auth-webac/src/main/resources/root-authorization.ttl
fcrepo-auth-webac/src/test/java/org/fcrepo/auth/webac/WebACRolesProviderTest.java
fcrepo-auth-webac/src/test/resources/acls/03/auth_open.ttl
fcrepo-auth-webac/src/test/resources/acls/04/auth1.ttl
fcrepo-auth-webac/src/test/resources/acls/05/auth_open.ttl
fcrepo-auth-webac/src/test/resources/acls/17/acl.ttl
fcrepo-auth-webac/src/test/resources/acls/17/auth_invalid_foaf_agent.ttl
fcrepo-auth-webac/src/test/resources/acls/17/auth_valid_foaf_agent.ttl

Resolves: https://jira.duraspace.org/browse/FCREPO-2632
An alternate implementation of PR: #1321 
Changes to treat foaf:Agent as an acl:agentClass instead of acl:agent.
The getRoles method in the roles provider class will also include agentClass roles for the foaf:Agent.
Maven build with tests.
@whikloj

FCREPO-2632. Use 'acl:agentClass foaf:Agent' to denote public access

---

fcrepo-auth-common/pom.xml
fcrepo-auth-common/src/main/java/org/fcrepo/auth/common/ContainerAuthToken.java
fcrepo-auth-common/src/main/java/org/fcrepo/auth/common/ContainerRolesPrincipalProvider.java
fcrepo-auth-common/src/main/java/org/fcrepo/auth/common/ServletContainerAuthFilter.java
fcrepo-auth-common/src/main/java/org/fcrepo/auth/common/ServletContainerAuthenticatingRealm.java
fcrepo-auth-webac/pom.xml
fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/WebACAuthorizingRealm.java
fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/WebACFilter.java
fcrepo-auth-webac/src/test/java/org/fcrepo/integration/auth/webac/WebACRecipesIT.java
fcrepo-auth-webac/src/test/resources/spring-test/master.xml
fcrepo-auth-webac/src/test/resources/spring-test/security.xml
fcrepo-auth-webac/src/test/resources/web.xml

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2761
* Part of https://jira.duraspace.org/browse/FCREPO-2753
* Prerequisite for https://jira.duraspace.org/browse/FCREPO-2760
Adds servlet container auth Shiro authorization realm and filter, and implemented fedoraAdmin role checking for WebAC.
Implemented servlet auth classes for Shiro that check the servlet request for user principal and roles and log in the user using those "credentials". Also created a WebAC filter class and test config that enables the test auth filter, servlet container auth filter, and WebAC auth filter. Currently the WebAC filter only checks for the fedoraAdmin role. Disable failing tests in the WebAC integration tests since they require implementation of ACL parsing in the WebAC authorization realm.
* Run …

Servlet container auth classes for Shiro

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraAcl.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraAclIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/api/rdf/HttpResourceConverter.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/api/rdf/HttpResourceConverterTest.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/FedoraTypes.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/models/FedoraResource.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/models/FedoraWebacAcl.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/FedoraResourceImpl.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/FedoraWebacAclImpl.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/identifiers/NodeResourceConverter.java
fcrepo-kernel-modeshape/src/main/resources/fedora-node-types.cnd
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/integration/kernel/modeshape/FedoraResourceImplIT.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/integration/kernel/modeshape/FedoraWebacAclImplIT.java

https://jira.duraspace.org/browse/FCREPO-2756
Create ACL resources via PUT.
Create ACL resources via PUT on the static fcr:acl URI http://resource/path/fcr:acl, and the ACL is created in container fedora:acl under the resource like TimeMap instead of linking with the acl:accessControl predicate.
```
1. Create RDFSource
$ curl -i -XPOST -H "Slug: TestObject" -H "Content-Type: text/n3" --data-binary "<> <info:fedora/test/field> \"Test Object\"" http://localhost:8080/rest/
2. Create ACL on the RDFSource and verify status 201 with the location header URI translated to fcr:acl
$ curl -i -XPUT http://localhost:8080/rest/TestObject/fcr:acl
Date: Mon, 23 Apr 2018 14:35:18 GMT
ETag: W/"75a70600c3237bd40744b79377f218d444fae0eb"
Last-Modified: Mon, 23 Apr 2018 14:35:18 GMT
Link: …
```

Create (via PUT) ACL resources.

---

fcrepo-auth-common/src/main/java/org/fcrepo/auth/common/AbstractPrincipalProvider.java
fcrepo-auth-common/src/main/java/org/fcrepo/auth/common/ContainerRolesPrincipalProvider.java
fcrepo-auth-common/src/main/java/org/fcrepo/auth/common/DelegateHeaderPrincipalProvider.java
fcrepo-auth-common/src/main/java/org/fcrepo/auth/common/HttpHeaderPrincipalProvider.java
fcrepo-auth-common/src/main/java/org/fcrepo/auth/common/PrincipalProvider.java
fcrepo-auth-common/src/main/java/org/fcrepo/auth/common/ServletContainerAuthenticationProvider.java
fcrepo-auth-common/src/test/java/org/fcrepo/auth/common/ContainerRolesPrincipalProviderTest.java
fcrepo-auth-common/src/test/java/org/fcrepo/auth/common/DelegateHeaderPrincipalProviderTest.java
fcrepo-auth-common/src/test/java/org/fcrepo/auth/common/HttpHeaderPrincipalProviderTest.java
fcrepo-auth-common/src/test/java/org/fcrepo/auth/common/ServletContainerAuthenticationProviderTest.java

Resolves: https://jira.duraspace.org/browse/FCREPO-2764
Reimplement the principal providers as Servlet Filters.
Added an AbstractPrincipalProvider class that takes care of adding principals to the session for Shiro.
IT tests needs to be added when all the issues under https://jira.duraspace.org/browse/FCREPO-2753 are complete.
The ServletContainerAuthenticationProvider class has been updated to make it compatible with the PrinicipalProvider interface changes to avoid build failure. The ServletContainerAuthenticationProvider class can be ultimately removed when the Shiro based implementation is completed.
@fcrepo4/committers, @peichman-umd

FCREPO-2764. Reimplement PrincipalProviders as Servlet Filters.

---

fcrepo-auth-common/src/main/java/org/fcrepo/auth/common/ServletContainerAuthFilter.java
fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/WebACFilter.java
fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/WebACPermission.java
fcrepo-auth-webac/src/test/java/org/fcrepo/auth/webac/WebACFilterTest.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2762
Implement WebAC permissions from 4.7.x in the new WebAC filter.
Require acl:read for GET requests and acl:write mode for all other request methods. Added a unit test for the WebACFilter that creates a mock user and request environment and ensures that the correct HTTP response code (currently, either 200 or 403) is returned. Added an equals() method to the WebACPermission class to make mocking easier, and it allows the intent of the implies() method to be read more cleanly.
* There is a new unit test class that exercises the filter against mock requests and permission sets to ensure it returns the correct HTTP response code. Run `mvn clean test -Dtest=WebACFilterTest`

Implement 4.7.x permissions in the WebAC filter

---

fcrepo-event-serialization/src/test/java/org/fcrepo/event/serialization/FedoraEventSerializerTestBase.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraAcl.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraVersioning.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersioningIT.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/responses/SynchonizedStreamRDFWrapper.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/exception/PreconditionException.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/utils/CacheEntry.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/utils/MessageExternalBodyContentType.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/observer/FedoraEventImpl.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/rdf/impl/RequiredPropertiesUtil.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/utils/FedoraSessionUserUtil.java
fcrepo-metrics/src/main/java/org/fcrepo/metrics/MetricsContextListener.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2774
There were a  number of compile warnings related to javadoc on a build using mvn verify. This PR removes all but one of those (@awoods advised to leave the HtmlTemplate class as it was)
@awoods @dbernstein

FCREPO-2774: fixes javadoc-related compile warnings

---

fcrepo-auth-common/src/main/java/org/fcrepo/auth/common/ContainerAuthToken.java
fcrepo-auth-common/src/main/java/org/fcrepo/auth/common/ServletContainerAuthFilter.java
fcrepo-auth-common/src/main/java/org/fcrepo/auth/common/ServletContainerAuthenticatingRealm.java
fcrepo-auth-webac/pom.xml
fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/WebACAuthorizingRealm.java
fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/WebACFilter.java
fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/WebACPermission.java
fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/WebACRolesProvider.java
fcrepo-auth-webac/src/test/java/org/fcrepo/auth/webac/WebACFilterTest.java
fcrepo-auth-webac/src/test/java/org/fcrepo/integration/auth/webac/WebACRecipesIT.java
fcrepo-auth-webac/src/test/resources/repository-test.json
fcrepo-auth-webac/src/test/resources/spring-test/repo.xml
fcrepo-auth-webac/src/test/resources/web.xml
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/test/util/TestAuthenticationRequestFilter.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2760
Use WebACRolesProvider to check ACLs in WebACAuthorizationRealm
Inject the servlet request into the WebACAuthorizationRealm so that it can find the node (or its parent, if the node doesn't exist yet) corresponding to the request URI. Once it has obtained that node, calls the WebACRolesProvider to get a list of user => mode mappings for the resource. These are translated into WebACPermission objects and added to the authorization info.
Additional fixes and cleanup:
* Removed the FAD and authN provider configuration from the repo.xml Spring configuration. The only remaining WebAC bean in repo.xml is the WebACRolesProvider, since it expects and injected NodeService.
* Fixed up the TestAuthenticationRequestFilter to properly …

Use WebACRolesProvider to check ACLs in WebACAuthorizationRealm

---

fcrepo-auth-common/src/main/java/org/fcrepo/auth/common/AbstractPrincipalProvider.java
fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/WebACFilter.java
fcrepo-auth-webac/src/test/java/org/fcrepo/integration/auth/webac/WebACRecipesIT.java
fcrepo-webapp/src/main/resources/spring/fcrepo-config.xml
fcrepo-webapp/src/main/webapp/WEB-INF/web.xml

Resolves: https://jira.duraspace.org/browse/FCREPO-2763
Alternate to #1339 
Enable Shiro in the fcrepo-webapp via Spring configuration.
-  Ignores removed for tests that were waiting on FCREPO-2760
- Fixed AbstractPrincipalProvider bug that was revealed while running the maven tests with spring configuration. Changes:
* The principals returned from the asSet() is unmodifiable. Creating a new HashSet from the returned set.
* Check for the null condition on Principal object retrieved from the session.
* Update/Set the principals to session only when there are new Principals.
* Filter chain be called.
1. Build and test with Maven
2. Manually test interacting with the fcrepo-webapp after starting it with `mvn jetty:run` (or other means).
@fcrepo4/committers, @peichman-umd

Enable Shiro in the fcrepo-webapp via Spring configuration

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersioningIT.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/FedoraResourceImpl.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/rdf/impl/InternalIdentifierTranslator.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/services/VersionServiceImpl.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/integration/kernel/modeshape/services/VersionServiceImplIT.java

https://jira.duraspace.org/browse/FCREPO-2710
Ignore referential integrity of memento properties by converting the referencing resource URI to internal identifier. The internal identifier will be converted back during memento retrieval and users won't see any changes.
Persist referencing resource identifier as internal identifier in mementos to pertain the resource reference even when the referencing resource is deleted.
```
1. Create a resource with a versioned resource that is referencing the resource:
curl -i -XPOST -H "Slug: ReferencingResource" "http://localhost:8080/rest"
curl -i -XPOST -H "Slug: VersionedResource" -H "Link: <http://mementoweb.org/ns#OriginalResource>; rel=\"type\"" "http://localhost:8080/rest" -H "Content-Type: text/n3" --data-binary "PREFIX pcdm: …
```

FCREPO-2710: Ignore referential integrity of memento properties.

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java

https://jira.duraspace.org/browse/FCREPO-2773
Fixes the Error on PUT to Binary Resource with status 409 instead.
```
1. Create binary resource
curl -i -ufedoraAdmin:fedoraAdmin -XPUT --data-binary "some-content" -H"Content-Type: text/plain" localhost:8080/rest/binary
2. PUT to add child resource and verify status 409 retuned with no error stacktrace
curl -i -ufedoraAdmin:fedoraAdmin -XPUT localhost:8080/rest/binary/xx
```

Fixes Error on PUT to Binary Resource with status 409.

---

fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/WebACRolesProvider.java
fcrepo-auth-webac/src/test/java/org/fcrepo/auth/webac/WebACRolesProviderTest.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraVersioning.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/url/HttpApiResources.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/FedoraLdpTest.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/url/HttpApiResourcesTest.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/AbstractResourceIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersioningIT.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/api/rdf/HttpResourceConverter.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/models/FedoraResource.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/services/BinaryService.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/services/VersionService.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/FedoraBinaryImpl.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/FedoraResourceImpl.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/NonRdfSourceDescriptionImpl.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/rdf/impl/ContentRdfContext.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/rdf/impl/RequiredPropertiesUtil.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/services/BinaryServiceImpl.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/services/VersionServiceImpl.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/rdf/impl/ContentRdfContextTest.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/services/BinaryServiceImplTest.java

**JIRA Tickets**: 
https://jira.duraspace.org/browse/FCREPO-2708
https://jira.duraspace.org/browse/FCREPO-2709
Adds support for creating binary and descriptions mementos from request body.
* Binary mementos can be created from submitted body or existing resource.
* Description mementos can be created from existing resource and submitted bodies. Can be created without a binary memento.
* When a binary memento is created from original resource, description is also created
* Binary mementos use content type from description memento at the same datetime if available, otherwise the default mimetype is returned.
* No longer uses modeshape copy to create binary mementos from existing resources
* describes and describedby links for mementos reference originals
* Binary properties provided with …

Fcrepo 2708/2709 - Binary and Description Mementos

---

fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/CachedSparqlRequest.java
fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/WebACFilter.java
fcrepo-auth-webac/src/test/java/org/fcrepo/auth/webac/WebACFilterTest.java
fcrepo-auth-webac/src/test/java/org/fcrepo/integration/auth/webac/WebACRecipesIT.java
fcrepo-auth-webac/src/test/resources/acls/18/acl.ttl
fcrepo-auth-webac/src/test/resources/acls/18/append_only.ttl
fcrepo-auth-webac/src/test/resources/acls/18/read_append.ttl
fcrepo-auth-webac/src/test/resources/acls/18/read_append_write.ttl

Resolves:
https://jira.duraspace.org/browse/FCREPO-2715
https://jira.duraspace.org/browse/FCREPO-2716
1. Adds Unit & IT Tests to verify acl:Append permission is not sufficient to make http DELETE requests.
2. Implements acl:Append PATCH logic to specifically deny patches that include Sparql DELETE statements and allow only specific requests. Also, adds Unit and IT tests to verify acl:Append PATCH logic.
Created a new CachedSparqlRequest class to support reading the InputStream from the request object multiple times (First time in the filter to verify that there are no delete statements and secondly in the FedoraLDP). The spring provided ContentCachingRequestWrapper could not be used as the MessageBodyReader in Fedora only has access to the request's InputStream, but not to the …

acl:Append DELETE and PATCH authorization

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/rdf/impl/ContentRdfContext.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/rdf/impl/ContentRdfContextTest.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2793
Fixes bug introduced by binary refactory which resulted in binary descriptions returning "describes" properties instead of "describedby" as in fcrepo 4.x.
Describedby property returned in triples for NonRdfSource
Describes property returned in triples for FedoraBinaryImpl (not clear how this is ever used, now or before)
Added check to verify that describedby property is returned in FedoraLdp
Creating a binary then making a GET request to its fcr:metadata endpoint to verify describedby property returned.
I'm not sure if returning "describes" for FedoraBinaryImpl is still needed (previously it was returned by NonRdfSourceDescription when that was used as the datastream instead of description). Tests pass without it (except for …

Fcrepo-2793 Describedby property from descriptions

---

fcrepo-auth-common/src/main/java/org/fcrepo/auth/common/ShiroAuthenticationProvider.java
fcrepo-auth-common/src/main/java/org/fcrepo/auth/common/ShiroSecurityContext.java
fcrepo-auth-webac/src/test/resources/repository-test.json
fcrepo-auth-webac/src/test/resources/spring-test/repo.xml

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2783
**Other Relevant Links**
* This is intended to supersede https://github.com/fcrepo4/fcrepo4/pull/1350
Modeshape authentication provider that inspects the Shiro SecurityUtils to get the current user. Uses a ShiroSecurityContext that is basically a thin wrapper around the Shiro current user Subject.
The ShiroSecurityContext wraps a Shiro Subject and responds "true" to all role queries for "read", "write", or "admin" (following the model of the ServletContainerAuthenticationProvider)
Running the WebAC integration tests (which now have this authentication provider configured) should pass. There are not yet unit tests for this class itself, or other integration tests.
This definitely needs more tests written, but I wanted to get …

Created ShiroAuthenticationProvider

---

fcrepo-configs/src/main/resources/config/servlet-auth/repository.json
fcrepo-webapp/src/main/resources/spring/fcrepo-config.xml
fcrepo-webapp/src/main/webapp/WEB-INF/web.xml

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2794
Add ShiroAuthenticationProvider to fcrepo-webapp config.
Include ShiroAuthenticationProvider as the Modeshape authentication provider in the spring config for fcrepo-webapp and the common fcrepo-config repository.json Modeshape configuration file for servlet-auth.
`mvn clean install` of the fcrepo4 project should return no errors.
I retained the BypassAdminAuthenticationProvider on every test repository.json except for the one that was using the ServletContainerAuthenticationProvider.

Add ShiroAuthenticationProvider to fcrepo-webapp config.

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersioningIT.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/FedoraResourceImpl.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/NonRdfSourceDescriptionImpl.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/rdf/impl/ContentRdfContext.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/services/VersionServiceImpl.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/integration/kernel/modeshape/services/VersionServiceImplIT.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2791
Fixes describedby property on a binary description response to return the external url, and related fixes.
* Adds internal identifier conversion when returning the triples of descriptions
* Fixes issue when converting from internal resource identifiers in mementos (properties which reference resources prefixed so that they ignore referential integrity), where internal modeshape paths were not being converted to external paths when generating triples (this meant that a describedby property would return the node name `id/fedora:description` instead of `id/fcr:metadata`)
* When listing children, no longer converts children from description to FedoraBinary since it is no longer necessary after binary/description refactor and it …

Fcrepo 2791 Convert internal identifiers for binary descriptions

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersioningIT.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/rdf/impl/ChildrenRdfContext.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2792
Fixes a bug that caused 404 response when getting RDF of a description timemap when a description memento existed without an associated binary memento
* Removes switching over to using described resource when populating children properties
* Adds integration test
Included integration test and testing described in the ticket.

Fcrepo-2792 Description Timemap without binary memento

---

fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/LocalFileBinary.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/UrlBinary.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/integration/kernel/modeshape/UrlBinaryIT.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/UrlBinaryTest.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2802
Removes call to set content size property for `UrlBinary`s on read requests (GET or HEAD), to prevent potential unwanted modifications.
* Calls to setContentSize for LocalFile and URL binaries removed from getContentSize call, now only being invoked when the binary is updated.
* Changed how size of an http url is determined to check for a Content-Length header, to avoid memory issues resulting from loading the remote binary into memory to calculate size.
```
curl -v -X PUT -H "Link: <https://duraspace.org/wp-content/themes/duraspace/assets/images/whitedura.png>; rel=\"http://fedora.info/definitions/fcrepo#ExternalContent\"; handling=\"proxy\"; type=\"image/png\"" http://localhost:8080/rest/duraspace-logo.png …
```

Fcrepo-2802 - Update content size for url binaries on 

---

fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/utils/ExternalResourceCacheEntry.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/integration/kernel/modeshape/LocalFileBinaryIT.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/UrlBinaryTest.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/utils/ExternalResourceCacheEntryTest.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2796
Fixes issue with retrieving external binary url properties during fixity checks and reenables `LocalFileBinaryIT.testCheckFixity`
Modeshape is translating the PROXY_URL property from a String into a Binary on `session.commit()`. As a result, `toString()` on the value returns a representation of a binary, while `getString()` returns the value of the binary. While this behavior is odd, `getString()` is probably desired and was used in the previous implementation:
https://github.com/fcrepo4/fcrepo4/blame/ffbd215c109bebf37279f858ec60ce76f3caa452/fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/utils/ExternalResourceCacheEntry.java#L70
It is an update to a test, so that should pass.
@bseeger @whikloj

FCR-2796 - Fix External Identifier Retrieval

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ExternalContentHandler.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2817
Fixes bug when combining a local file external content binary with the copy directive.
Uses uri path instead of serializing the entire uri when retrieving the content of a local file.
Adds integration test for local file with copy mode.
New integration test should pass.
The following command should work, and the resulting binary should be retrievable:
```
curl -i -H"Link: <file:///Users/whikloj/Desktop/wonderful.tiff>; rel=\"http://fedora.info/definitions/fcrepo#ExternalContent\"; handling=\"copy\"; type=\"image/tiff\"" -XPUT -ufedoraAdmin:fedoraAdmin http://localhost:8080/rest/test_redirect_local_file
curl -i -ufedoraAdmin:fedoraAdmin http://localhost:8080/rest/test_redirect_local_file
```
@whikloj @bseeger @dbernstein

Fcr 2817 - Fix local file uri

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2818
Removes the `Content-Length` header from responses for External-Content Redirect LDP-NRs.
To test the actual timing of a response you need a remote URI to redirect to, but you can test the change to the headers with a local file.
1. `curl -i -ufedoraAdmin:fedoraAdmin -XPUT -H"Link: <file:///path/to/your/file>; rel=\"http://fedora.info/definitions/fcrepo#ExternalContent\"; handling=\"redirect\"" http://localhost:8080/rest/my_redirect`
1. Before the PR
1. do a HEAD request. 
1. See the `Content-Length:` greater than 0
1. After the PR
1. do a HEAD request
1. See a `Content-Length: 0` header
If you have a remote webserver, you can use that URI and actually see how much faster it is with.
```
curl -G -L -ufedoraAdmin:fedoraAdmin …
```

Don't return Content-Length for LDP-NR redirect responses

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraVersioning.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/AbstractResourceIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersioningIT.java

* https://jira.duraspace.org/browse/FCREPO-2809
* https://jira.duraspace.org/browse/FCREPO-2811
* https://jira.duraspace.org/browse/FCREPO-2820
Adds some missing headers and changes the RDFSource type for a timemap to a Container type.
Build and do some `GET`, `HEAD` and `OPTIONS` requests against a `/fcr:versions` endpoint. 
Ensure that 
1. These appear
```
Link: <http://www.w3.org/ns/ldp#Container>;rel="type"
Link: <http://www.w3.org/ns/ldp#BasicContainer>;rel="type"
```
1. This appears
```
Accept-Post: text/turtle,text/rdf+n3,text/n3,application/rdf+xml,application/n-triples,application/ld+json,multipart/form-data,application/sparql-update
```
1. When you do an `OPTIONS` request is has these headers too.
Any additional information that you think would be helpful when …

Add Accept-Post, Options, and Container type

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraVersioning.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/AbstractResourceIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersioningIT.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/services/VersionService.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/services/VersionServiceImpl.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2815
Adds support and testing for external binaries when creating mementos
* Versioning controller now supports external content link header.
* Updated VersionService with a method signature for creating historic external binary mementos.
* Updated VersionServiceImpl to know how to create mementos from the current version of a external binary and from historic versions
* Adds integration tests for copy, proxy and redirect with historic mementos, proxy with current memento.
Memento from a current proxied binary:
```
curl -i -XPUT -H "Link: <http://mementoweb.org/ns#OriginalResource>; rel=\"type\"" -H "Link: <https://wiki.duraspace.org/download/attachments/19006307/Feedback_fr.txt>; …
```

Fcr 2815 - Support Mementos of External Binaries

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ExternalContentHandler.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/ExternalContentHandlerIT.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2827
Renames the ExternalContentHandler static `CONTENT_TYPE` to `EXT_CONTENT_TYPE` (which resolves to `type`) to avoid naming confusion with the various public statics `CONTENT_TYPE` which resolve to `Content-Type`.
Simple rename and a static import, along with a test.
Before the PR, created a proxied external content resource pointing at a remote web server that **does** return a `Content-Type` header. 
This header is not used and your resource with have a `Content-Type: application/octet-stream`.
After this PR your resource should have the same `Content-Type` that the remote server returns.
Example:
* Does this change …

Disambiguate content-type headers

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraAcl.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraAclIT.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/models/FedoraResource.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/FedoraResourceImpl.java

In implementing the feature, I also fixed the failure
to properly return a 404 on a non-existent ACL.
Resolves:
https://jira.duraspace.org/browse/FCREPO-2831
https://jira.duraspace.org/browse/FCREPO-2833
**Delete ACL Resource**
* * *
**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2833 and https://jira.duraspace.org/browse/FCREPO-2831
Adds support for deleting an ACL resource.  Also ensures that 404 is returned when the ACL does not exist.
`# create a container
curl -v -X PUT  http://localhost:8080/rest/container  -u fedoraAdmin:fedoraAdmin
curl -v -X GET  http://localhost:8080/rest/container/fcr:acl  -u fedoraAdmin:fedoraAdmin
curl -v -X PUT  http://localhost:8080/rest/container/fcr:acl  -u fedoraAdmin:fedoraAdmin
curl -v -X GET  http://localhost:8080/rest/container/fcr:acl  -u …

Adds support for deleting an ACL Resource.

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/ExternalContentHandlerIT.java

**JIRA Ticket**: None
https://github.com/fcrepo4/fcrepo4/pull/1367#discussion_r202041408
Replaces a static string with a random UUID
It only affects the internal test, so if Travis passes this should be fine.
Example:
@awoods

Test fix as requested in FCREPO-2827 code review

---

fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/exceptionhandlers/ExternalContentAccessExceptionMapper.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/exception/ExternalContentAccessException.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/UrlBinary.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/UrlBinaryTest.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2828
Wraps the `IOException` returned by a failed access of a remote site in a new `ExternalContentAccessException` and returns it as a `502 Bad Gateway` response.
Create a proxied external content to a controllable webserver. 
```
curl -ufedoraAdmin:fedoraAdmin -i http://localhost:8080/rest/simple_external -XPUT -H"Link: <http://static-ldp.localhost:8111/2012-12-01/IMG_20121201_113805.jpg>; rel=\"http://fedora.info/definitions/fcrepo#ExternalContent\"; handling=\"proxy\"" -H"Link: <http://www.w3.org/ns/ldp#NonRDFSource>;rel=\"type\""
```
`GET` the resource
```
> curl -i -u fedoraAdmin:fedoraAdmin http://localhost:8080/rest/simple_external
Date: Fri, 13 Jul 2018 15:37:16 GMT
Set-Cookie: …
```

Make useful exceptions for inaccessible external content

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraAclIT.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/FedoraResourceImpl.java

Resolves: https://jira.duraspace.org/browse/FCREPO-2832
**GET on LDP-NR ACL returns 200 (rather than 500)**
* * *
**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2832
Now GETs on  LDP-NR ACL return 200 rather than a 500 response code.
```
curl -v -X PUT -H "Content-Type: text/plain" --data-binary "This is a test body" http://localhost:8080/rest/test
curl -v -X PUT --data-binary "This is a test body" http://localhost:8080/rest/test/fcr:acl
curl -v -X GET http://localhost:8080/rest/test/fcr:acl
```

GET on LDP-NR ACL returns 200 (rather than 500).

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraAcl.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraAclIT.java

Resolves: https://jira.duraspace.org/browse/FCREPO-2808
Allows user to specify a RDF body in a PUT request on an ACL resource.
1. Save the following to a file call acl.ttl
```
@prefix acl: <http://www.w3.org/ns/auth/acl#> . 
@prefix foaf: <http://xmlns.com/foaf/0.1/> . 
@prefix ldp: <http://www.w3.org/ns/ldp#> . 
<#authorization_1> a acl:Authorization ; 
acl:agentClass foaf:Agent ; 
acl:accessToClass ldp:Resource ; 
acl:default <https://example.org/root/> ; 
acl:mode acl:Read .
```
2.  create a resource
```
curl -X PUT http://localhost:8080/rest/test
```
3. create the acl using a body
```
curl -v -X PUT  http://localhost:8080/rest/test/fcr:acl -H "Content-Type: text/turtle" --data-binary "@acl.ttl"
```
4. verify that the resource was properly created:
```
curl -v -X GET …
```

PUT requests to fcr:acl now accept RDF bodies.

---

fcrepo-auth-webac/src/test/resources/allowed_external_paths.txt
fcrepo-auth-webac/src/test/resources/spring-test/rest.xml
fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/ExternalContentHandler.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/ExternalContentHandlerFactory.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/ExternalContentPathValidator.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraVersioning.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/ExternalContentHandlerFactoryTest.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/ExternalContentPathValidatorTest.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/FedoraLdpTest.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/ExternalContentPathValidatorIT.java
fcrepo-http-api/src/test/resources/allowed_external_paths.txt
fcrepo-http-api/src/test/resources/spring-test/rest.xml
fcrepo-integration-rdf/src/test/resources/allowed_external_paths.txt
fcrepo-integration-rdf/src/test/resources/spring-test/rest.xml
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/spring/DefaultPropertiesLoader.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/spring/DefaultPropertiesLoaderTest.java
fcrepo-webapp/src/main/resources/spring/fcrepo-config.xml
fcrepo-webapp/src/main/webapp/static/constraints/ExternalMessageBodyException.rdf

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2835
Adds an optional configuration file for specifying what URIs external content may be created from. If no configuration is provided, then external binary creation is disabled.
* Adds java startup parameter "fcrepo.external.content.allowed" which allows users to optionally specify where the allowed list configuration file is.
* Introduces a ExternalContentPathValidator which verifies that a path is from the allowed list and does not contain relative modifiers.
* Introduces ExternalContentHandlerFactory which constructors ExternalContentHandlers and performs validation of links prior to returning the handler
* Validator configured by default to reload configuration file if it is modified (assuming it was provided at startup time) …

Fcrepo 2835 - Allowed external paths configuration

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2819
* Allows users to create external content binaries with post requests
* Fixes bonus bug that prevented mimetype from getting set when creating external binary via POST.
* Removes a check for null request bodies when creating external content
* Adds integration test for creating external content binaries with post.
```
mvn jetty:run -Dfcrepo.external.content.allowed=/Users/bbpennel/git/fcrepo4/fcrepo-http-api/src/test/resources/allowed_external_paths.txt 
curl -i -XPOST -H "Slug:post_ext" -H "Link: <https://duraspace.org/wp-content/themes/duraspace/assets/images/whitedura.png>; rel=\"http://fedora.info/definitions/fcrepo#ExternalContent\"; handling=\"proxy\"; type=\"image/png\"" "http://localhost:8080/rest/" …
```

Fcrepo 2819 - POST create External Content

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/AbstractResourceIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersioningIT.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/exceptionhandlers/RequestWithAclLinkHeaderExceptionMapper.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/exception/RequestWithAclLinkHeaderException.java
fcrepo-webapp/src/main/webapp/static/constraints/RequestWithAclLinkHeaderException.rdf

Respond with a 400 when a PUT/POST request has a rel="acl" Link header.
**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2822
```
1. Test POST with link header rel="acl"
$ curl -i -XPOST -H "Slug: newResource" -H "Link: <http://localhost:8080/rest/anyResource/fcr:acl>; rel=\"acl\"" "http://localhost:8080/rest"
Date: Wed, 25 Jul 2018 22:25:02 GMT
Link: <http://localhost:8080/static/constraints/RequestWithAclLinkHeaderException.rdf>; rel="http://www.w3.org/ns/ldp#constrainedBy"
Content-Type: text/plain;charset=utf-8
Content-Length: 62
Server: Jetty(9.2.3.v20140905)
Unable to handle request with the specified LDP-RS as the ACL.
2. Test PUT with link header rel="acl"
$ curl -i -XPUT -H "Link: <http://localhost:8080/rest/anyResource/fcr:acl>; rel=\"acl\"" …
```

Respond with a 400 if a PUT/POST request has a rel="acl" Link header.

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersioningIT.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/FedoraResourceImpl.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/NonRdfSourceDescriptionImpl.java

Resolves: https://jira.duraspace.org/browse/FCREPO-2771
This PR ensures that mementos return the original resource URI as the subject rather than the memento.
```
curl -u fedoraAdmin:fedoraAdmin -v -X PUT  http://localhost:8080/rest/test-ldpnr --data-binary "test" -H "Link: <http://mementoweb.org/ns#OriginalResource>; rel=\"type\""
curl -u fedoraAdmin:fedoraAdmin -v -X POST  http://localhost:8080/rest/test-ldpnr/fcr:versions
curl -v -L -X GET http://localhost:8080/rest/test-ldpnr/fcr:metadata -H "Accept-Datetime: Wed, 18 Jul 2018 22:42:34 GMT"  -u fedoraAdmin:fedoraAdmin
curl -u fedoraAdmin:fedoraAdmin -v -X PUT  http://localhost:8080/rest/test-ldpr  -H "Link: <http://mementoweb.org/ns#OriginalResource>; rel=\"type\""
curl -u fedoraAdmin:fedoraAdmin -v -X POST …
```

Ensures mementos return the correct subject.

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ExternalContentHandler.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/ExternalContentPathValidator.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/ExternalContentHandlerFactoryTest.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/ExternalContentPathValidatorTest.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/DirtyContextBeforeAndAfterClassTestExecutionListener.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/ExternalContentPathValidatorIT.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2840
Adds additional external content uri checks
* Decodes uris before validating
* Verifies that external content files exist
* Fixes issue with existing ExternalContentPathValidatorIT test due to a typo, resulting in needing to restart test fedora instance before the test to change allowed list file
* Adds integration and unit tests
* Moves a few validity checks over to the validator from the ExternalContentHandler
```
echo "https://
file:///Users/bbpennel/git/fcrepo4/fcrepo-http-api/" > allowed_list.txt
mvn jetty:run -Dfcrepo.external.content.allowed=allowed_list.txt
curl -v -X PUT -H "Link: <file:///Users/bbpennel/git/fcrepo4/fcrepo-http-api/../LICENSE>; rel=\"http://fedora.info/definitions/fcrepo#ExternalContent\"; …
```

Fcrepo 2840

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java

Verify HEAD and GET requests to External Content with Want-Digest header are correctly responded.
**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2752
Added tests for external resource (URL and local file) with different handling (redirect, proxy, copy) to verify HEAD and GET requests to External Content with Want-Digest header are correctly responded and contains the required headers.
```
0. Start the server with external content enabled: 
$ mvn jetty:run -Dfcrepo.external.content.allowed=/Users/danny/code/fcrepo4/fcrepo-http-api/src/test/resources/allowed_external_paths.txt
1. Create external resource (URL resource) and verify that Want-Digest header is presented for HEAD and GET
$ curl -i -ufedoraAdmin:fedoraAdmin -XPUT -H"Link: …
```

Added tests to verify HEAD and GET requests to External Content with Want-Digest header are correctly responded.

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java

Fix the ACL URL for the repository root.
**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2826
Corrected the double slash in the ACL link header URL for the repository root.
```
1. Verify the ACL URL with HEAH on repository root
curl -i -XHEAD http://localhost:8080/rest
Date: Wed, 08 Aug 2018 22:35:18 GMT
Link: <http://www.w3.org/ns/ldp#Container>;rel="type"
Link: <http://www.w3.org/ns/ldp#BasicContainer>;rel="type"
Accept-Patch: application/sparql-update
Accept-Post: text/turtle,text/rdf+n3,text/n3,application/rdf+xml,application/n-triples,application/ld+json
Allow: …
```

Fixed the ACL link header URL for repository root

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersioningIT.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2812
Change response from 404 to 406
Before this PR
Create new versioned resource
```
curl -i -ufedoraAdmin:fedoraAdmin http://localhost:8080/rest/empty_version -XPUT -H"Link: <http://mementoweb.org/ns#OriginalResource>; rel=\"type\""
```
Do GET with an `Accept-Datetime` header and see the 404
```
> curl -i -ufedoraAdmin:fedoraAdmin http://localhost:8080/rest/empty_version -H"Accept-Datetime: Thu, 1 Jan 1970 00:00:00 GMT"
HTTP/1.1 404 Not Found
Date: Thu, 09 Aug 2018 17:23:45 GMT
Set-Cookie: JSESSIONID=iicku0de4hnt17vf44kwmeeaa;Path=/
Set-Cookie: rememberMe=deleteMe; Path=/; Max-Age=0; Expires=Wed, 08-Aug-2018 17:23:45 GMT
Link: <http://www.w3.org/ns/ldp#Container>;rel="type" …
```

Return 406 when no mementos exist

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/ExternalContentHandlerIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2797
Moves all external content tests out of FedoraLdpIT to an external content related test
Also uses the same method for creating tmp files across tests.
Only integration tests were updated, no new functionality.
@bseeger

Fcrepo-2797 - Separate external content integration tests

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraVersioning.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersioningIT.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2846
Stops generating a timemap if one doesn't exist.
Internal test or
```
curl -i -X PUT --user fedoraAdmin:fedoraAdmin http://localhost:8080/rest/versioning/v3
curl -i --user fedoraAdmin:fedoraAdmin http://localhost:8080/rest/versioning/v3
curl -i -X POST --user fedoraAdmin:fedoraAdmin "http://localhost:8080/rest/versioning/v3/fcr:versions"
curl -i --user fedoraAdmin:fedoraAdmin http://localhost:8080/rest/versioning/v3
```
The third step should success (201 Created) before this PR and fail (404 Not Found) after.
Example:
* Does this change require any other modifications to be made to the repository (ie. Regeneration …

Don't create a timemap when trying to create a Memento

---

fcrepo-http-api/src/main/resources/root-authorization.ttl
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraAclIT.java
fcrepo-http-api/src/test/resources/test-root-authorization.ttl

Added acl:default statement to the default root ACL
**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2824
```
Verify that the acl:default statement presented in the root acl and linking to repository root <http://localhost:8080/rest/>:
$ curl -i -ufedoraAdmin:fedoraAdmin http://localhost:8080/rest/fcr:acl
Date: Wed, 22 Aug 2018 20:40:31 GMT
Set-Cookie: JSESSIONID=1wqg64680h5bj1skmofk8fsk0i;Path=/
Set-Cookie: rememberMe=deleteMe; Path=/; Max-Age=0; Expires=Tue, 21-Aug-2018 20:40:31 GMT
Content-Type: text/turtle;charset=utf-8
Content-Length: 1402
Server: Jetty(9.3.1.v20150714)
@prefix premis:  <http://www.loc.gov/premis/rdf/v1#> .
@prefix test:  <info:fedora/test/> .
@prefix memento:  <http://mementoweb.org/ns#> .
@prefix rdfs: …
```

Added acl:default statement to the default root ACL

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraAcl.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraAclIT.java

Fix the 500 error stacktrace while PUTing ACL with bad RDF content
**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2844
PUTing ACL with bad RDF content will produce a stacktrace with 500 error. The PR will fix it to return status 400 bad request.
```
1. Create resource:
$ curl -i -ufedoraAdmin:fedoraAdmin http://localhost:8080/rest/test -XPUT
2. Create ACL with bad RDF and verify status 400 returned:
$ echo -e '<> a junk:Object ;' | curl -i -ufedoraAdmin:fedoraAdmin http://localhost:8080/rest/test/fcr:acl -XPUT -H"Content-Type: text/turtle" --data-binary @-
Date: Wed, 29 Aug 2018 18:04:23 GMT
Set-Cookie: JSESSIONID=9qlvnhmcfpyz1by05yixj2ols;Path=/
Set-Cookie: rememberMe=deleteMe; Path=/; Max-Age=0; Expires=Tue, …
```

Fix the 500 error stacktrace for PUTing ACL with bad RDF content

---

fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/WebACFilter.java
fcrepo-auth-webac/src/test/java/org/fcrepo/auth/webac/WebACFilterTest.java
fcrepo-auth-webac/src/test/java/org/fcrepo/integration/auth/webac/WebACRecipesIT.java
fcrepo-auth-webac/src/test/resources/acls/20/acl.ttl

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2847
Allow OPTIONS when there is an acl:Read permission.
Permit OPTIONS requests when the current user has acl:Read mode permissions to the requested resource.
Includes unit and integration tests, so the standard `mvn clean test` should test.
@awoods, @fcrepo4/committers

Allow OPTIONS when there is an acl:Read permission.

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/FedoraLdpTest.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2814
Updates the code to advertise external content support whenever an options request is made against an LDPR (any resource in fedora).
* All OPTIONS requests now include the response: "Accept-External-Content-Handling: copy, redirect, proxy"
Make OPTIONS requests against each type of resource in Fedora.

Updated OPTIONS response to advertise support for external content.

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraBaseResource.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2861
Tombstone URI is generated based on the request URI, this ensures the created URI doesn't have a `//` in it.
1.
```
> curl -i -ufedoraAdmin:fedoraAdmin -XPUT http://localhost:8080/rest/deleteMe
Date: Fri, 14 Sep 2018 15:00:31 GMT
Set-Cookie: JSESSIONID=s0o2t4mivfb61xf1ugfajiy0n;Path=/
Set-Cookie: rememberMe=deleteMe; Path=/; Max-Age=0; Expires=Thu, 13-Sep-2018 15:00:31 GMT
ETag: W/"860f0238f8fec8e94215b2305948ff37cc5f0c94"
Last-Modified: Fri, 14 Sep 2018 15:00:31 GMT
Link: <http://localhost:8080/rest/deleteMe/fcr:acl>; rel="acl"
Location: …
```

Remove extra slash from tombstone URI

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersioningIT.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/services/VersionServiceImpl.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2850
Provides a message explicitly stating that empty models are disallowed when creating historic mementos
Added check for empty body when creating memento, and integration test
```
curl -i -XPUT --user fedoraAdmin:fedoraAdmin -H"Link: <http://mementoweb.org/ns#OriginalResource>; rel=\"type\""  http://localhost:8080/rest/test_resc
curl -i -XPOST --user fedoraAdmin:fedoraAdmin -H "Memento-Datetime: Wed, 30 May 2018 23:02:44 GMT" -H "Content-Type: text/turtle" http://localhost:8080/rest/test_resc/fcr:versions
< HTTP/1.1 400 Bad Request
< Cannot create historic memento from an empty body
```

Fcrepo-2850 - Improve error message for empty memento creation

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/FedoraLdpTest.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/AbstractResourceIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersioningIT.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2862
Adds the `http://www.w3.org/ns/ldp#RDFSource` Link header with `rel="type"` to all LDP-RSs. 
Put a LDP-RS and when you GET or HEAD it see the new type, same with TimeMaps and Binary descriptions.
Example:

Ensure ldp:RDFSource type is on LDP-RSs

---

fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/URIConstants.java
fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/WebACAuthorizingRealm.java
fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/WebACRolesProvider.java
fcrepo-auth-webac/src/test/java/org/fcrepo/auth/webac/WebACRolesProviderTest.java
fcrepo-auth-webac/src/test/java/org/fcrepo/integration/auth/webac/WebACRecipesIT.java
fcrepo-auth-webac/src/test/resources/acls/03/authenticated-agent.ttl
fcrepo-auth-webac/src/test/resources/acls/03/foaf-agent.ttl
fcrepo-auth-webac/src/test/resources/acls/26/authenticated-agent.ttl
fcrepo-auth-webac/src/test/resources/acls/26/foaf-agent.ttl

**acl:agentClass foaf:Agent and acl:AuthenticatedAgent are now respected.**
* * *
**JIRA Ticket**:  https://jira.duraspace.org/browse/FCREPO-2863
Ensures that acl:AuthenticatedAgent and foaf:Agent are respected.
Includes unit as well as integration tests.
For manual testing: 
Create a foaf-agent.ttl :
```
@prefix acl: <http://www.w3.org/ns/auth/acl#> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
<#foafAgent> a acl:Authorization ;
acl:agentClass foaf:Agent;
acl:mode acl:Read;
acl:accessTo </rest/foaf-agent> .
```
Create foaf resource and acl and perform GET verifying a 200 response.
```
curl -v -u fedoraAdmin:fedoraAdmin -X PUT  http://localhost:8080/rest/foaf-agent;
curl -v -u fedoraAdmin:fedoraAdmin -X PUT …
```

acl:agentClass foaf:Agent and acl:AuthenticatedAgent are now respected.

---

fcrepo-jms/src/test/java/org/fcrepo/integration/jms/observer/AbstractJmsIT.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/observer/EventType.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/FedoraJcrConstants.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/observer/FedoraEventImpl.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/observer/WrappedJcrEvent.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/observer/eventmappings/AllNodeEventsOneEvent.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/integration/kernel/modeshape/observer/SimpleObserverIT.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/observer/eventmappings/AllNodeEventsOneEventTest.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2804
When an inbound reference happens it causes the `jcr:lastModified` of the JCR node to be changed. This is the only change to that node, so we can alter them. 
A new predicate to check for a List of 1 Event with a type of PROPERTY_CHANGED and path that ends in `jcr:lastModified`.
The Modeshape event is wrapped so that we can return our fake event type and map that to the ActivityStreams Follow Activity.
Internal tests are in place, but you can also stick a consumer on the activemq topic and check for any events when you POST with a reference to an existing Resource.
Example:
* Does this change require documentation to be updated? Yes
* Does this …

Map inbound reference events to ActivityStreams Follow

---

fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/WebACRolesProvider.java
fcrepo-auth-webac/src/test/java/org/fcrepo/integration/auth/webac/WebACRecipesIT.java
fcrepo-auth-webac/src/test/resources/acls/agent-group-flat.ttl
fcrepo-auth-webac/src/test/resources/acls/agent-group-list-flat.ttl
fcrepo-auth-webac/src/test/resources/acls/agent-group-list.ttl
fcrepo-auth-webac/src/test/resources/acls/agent-group-with-hash-uri-authorized.ttl
fcrepo-auth-webac/src/test/resources/acls/agent-group-with-hash-uri-unauthorized.ttl

**ACLs that reference group list resource using a hash URI  in acl:agentGroup triples was not authorizing correctly.  This PR addresses the bug.**
* * *
**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2864
Now it is possible to use hash URIs as the object of an acl:agentGroup predicate.  Two integration tests were added to confirm that the functionality works. The first test ensures that members defined in hash-URI blocks are respected while acls referencing an unauthorized block within the same resource results in a 403.  The second test ensures that non-hash URIs work as expected.
Integration tests cover the new functionality and provides missing testing for existing functionality.  
* Does this change require documentation to be updated? No
* Does this change add any new …

Referencing acl:group lists using Hash URIs now works properly.

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersioningIT.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/FedoraResourceImpl.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2869
Fixes issue where requesting a memento by its exact memento datetime returns an older memento if available.
During negotiation, when filtering mementos to just those older or the same age as the `Accept-datetime` header, ensure that the header value is being compared against the memento datetime to the same level of precision. The issue was caused by the request header being accurate to the second, while system generated memento-datetimes are to the millisecond. As a result, the memento was technically after the header.
Also added an integration test to verify the behavior when submitting a Accept-datetime older than the first memento, to make sure no unrelated side effects occurred from this change.
Integration tests.
It can …

Fcrepo 2869 - Memento datetime negotiation with exact dates

---

fcrepo-http-api/src/test/java/org/fcrepo/http/api/FedoraLdpTest.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/utils/ContentDigest.java
fcrepo-kernel-api/src/test/java/org/fcrepo/kernel/api/utils/ContentDigestTest.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2876
Returning `sha-256` in Digest responses instead of sha256
Updates name of content digest and updates tests accordingly
```
echo -n "01234567890123456789012345678901234567890123456789" | curl -ufedoraAdmin:fedoraAdmin -XPUT --data "@-" http://localhost:8080/rest/sha256_test
curl -I -ufedoraAdmin:fedoraAdmin -H"Want-Digest: sha-256" http://localhost:8080/rest/sha256_test
```
@dbernstein

Fcrepo-2876 - Changed from sha256 to sha-256 when returning digests

---

fcrepo-auth-common/src/main/java/org/fcrepo/auth/common/AbstractPrincipalProvider.java
fcrepo-auth-common/src/main/java/org/fcrepo/auth/common/DelegateHeaderPrincipalProvider.java
fcrepo-auth-common/src/main/java/org/fcrepo/auth/common/HttpHeaderPrincipalProvider.java
fcrepo-auth-common/src/main/java/org/fcrepo/auth/common/ShiroSecurityContext.java
fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/WebACAuthorizingRealm.java
fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/WebACFilter.java
fcrepo-auth-webac/src/test/java/org/fcrepo/integration/auth/webac/WebACRecipesIT.java
fcrepo-auth-webac/src/test/resources/acls/04/acl.ttl
fcrepo-auth-webac/src/test/resources/acls/05/acl.ttl
fcrepo-auth-webac/src/test/resources/spring-test/security.xml

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2778
- Refactor to make PrincipalProviders work with Shiro Authorization.
- Refactor WebACFilter to allow authorization checks for unauthenticated requests.
- Configure PrincipalProviders in fcrepo-auth-webac test spring configuration.
- Reenable ignored tests and refactor for `acl:default` changes
Shiro does provide a direct way to add/update the current user principals. The refactor utilizes the runAs principal Shiro functionality to add the header provided principals to the BasicUserPrincipal obtained for the servlet authentication.
The WebACAuthorizingRealm is refactored to inspect all available principals instead of just the BasicUserPrincipal.
When …

PrincipalProvider and Authorization Refactor

---

fcrepo-webapp/pom.xml

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2695
Adds a list of binary file extensions to be excluded from maven-war-plugin filtering to prevent corruption.
Maven filtering (resources plugin / war plugin) corrupts binary files. Some of the common image extensions are excluded by default and we can configure a list of file extensions to be excluded.
- https://stackoverflow.com/questions/32690418/i-cant-load-fonts-while-using-tomcat
- https://maven.apache.org/plugins/maven-resources-plugin/examples/binaries-filtering.html
- https://maven.apache.org/plugins/maven-war-plugin/examples/adding-filtering-webresources.html
1. Checkout the PR changes and build
2. Run the fcrepo-webapp in tomcat
- Switch to fcrepo-webapp directory
- Create a Dockerfile with following content
```
FROM …
```

Configured maven filter exclusions for binary files.

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraAcl.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraAclIT.java

https://jira.duraspace.org/browse/FCREPO-2870
https://jira.duraspace.org/browse/FCREPO-2871
Root ACL should return 409 when attempting to DELETE/PATCH the backstop ACL. 
Added tests to verify:
- Cannot DELETE/PATCH backstop ACL
- Can PUT/PATCH/DELETE user-defined ACL.
- Verify that the tests pass for fcrepo-http-api

Root ACL should return 409 when attempting to DELETE/PATCH the backstop ACL

---

fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/utils/FedoraSessionUserUtil.java

**JIRA Ticket**: No ticket
Reduces log level to remove some messages 
Build and see much fewer
```
WARN 20:33:03.937 (FedoraSessionUserUtil) Default URI is created for user bypassAdmin: info:fedora/local-user#bypassAdmin
```
messages
Example:
@awoods @bbpennel @dbernstein

Change log level from WARN to TRACE

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraVersioning.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/responses/StreamingBaseHtmlProvider.java
fcrepo-http-api/src/main/resources/views/common-node-actions.vsl
fcrepo-http-api/src/main/resources/views/fcr-versions.vsl
fcrepo-http-api/src/test/java/org/fcrepo/http/api/responses/StreamingBaseHtmlProviderTest.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersioningIT.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/responses/ViewHelpers.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/responses/ViewHelpersTest.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/services/VersionService.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/services/VersionServiceImpl.java
fcrepo-webapp/src/main/webapp/static/js/common.js

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2730
Make the HTML UI work (mostly) with versions.
* Checks if an item is:
* the repository root or 
* a Memento or 
* is Versionable (has /fcr:versions container) or
*  is an a LDP-NR or its description.
It then changes the HTML interface based on the above to
* Allows you to enable versioning on LDP-RSes (but not LDP-NRs or LDP-RSs acting as descriptions)
* Allows you to make a version.
* Allows you to view the versions (but the triples appear under Other Resources, AND if you click the URL or dc:title instead of the plus sign you move away from the Memento).
Build it and play with the HTML UI.
Example:
* Does this change require documentation to be updated? Probably
* Does this …

Enable versioning, creation of Mementos and view Mementos in HTML UI

---

fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/FedoraContextLoaderListener.java

Resolves: https://jira.duraspace.org/browse/FCREPO-2885
Changes a single character in documentation URL from `4x` to `5x`:
- From: `https://wiki.duraspace.org/display/FEDORA4x/Application+Configuration`
- To: `https://wiki.duraspace.org/display/FEDORA5x/Application+Configuration`
1. Comment out the local JAVA_OPTS value of `-Dfcrepo.modeshape.configuration`
1. Observe in the Tomcat logs a message that now references the `5x` documentation

Change error message to reference `5x` documentation

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-integration-ldp/src/test/java/org/fcrepo/integration/ldp/LdpTestSuiteIT.java
fcrepo-integration-rdf/src/test/java/org/fcrepo/integration/rdf/AbstractIntegrationRdfIT.java
fcrepo-integration-rdf/src/test/java/org/fcrepo/integration/rdf/LdpIT.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/RdfLexicon.java

- https://jira.duraspace.org/browse/FCREPO-2877
- https://jira.duraspace.org/browse/FCREPO-2880
Ensure that all server managed triples are suppressed in RDF body when omitting Server Managed Triples
1. Verify that all the relevant SMTs are being tested for in FedoraLdpIT
- testGetObjectOmitMembership
- testGetObjectOmitContainment
- testGetObjectOmitServerManaged
2. Run the test to verify all the tests pass.
- Follow steps to reproduce the issue as per the description in FCREPO-2877. 
- Verify that the `ldp:BasicContainer` is no longer being returned.

Ensure that all server managed triples are suppressed on omit.

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraVersioning.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersioningIT.java

**Removes support for LDPCv DELETE**
* * *
**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2889
https://jira.duraspace.org/browse/FCREPO-2890
The PR simply removes the endpoint for LDPCv DELETE and updates the corresponding integration test to confirm that delete is not allowed.
Create a versioned resource: 
`curl -X POST -H "Link: <http://mementoweb.org/ns#OriginalResource>; rel=\"type\"" http://localhost:8080/rest/ -H "slug: testxyz" -u fedoraAdmin:fedoraAdmin`
Try deleting the timemap
`curl -X DELETE http://localhost:8080/rest/testxyz/fcr:versions -u fedoraAdmin:fedoraAdmin`
Verify 405 response
The code for enabling, disabling, and checking the versionability of resource has been left intact in case …

Removes support for LDPCv DELETE.

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/domain/ldp/LdpPreferTag.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2879
Suppress LDP Containment triples on omit server-managed-triples header unless if there is an explicit include prefer-containment header
FedoraLdpIT includes tests to verify that:
- PreferContainment triples are suppressed on `omit` ServerManaged Prefer header
- PreferContainment triples are NOT suppressed on `omit` ServerManaged and `include` PreferContainment Prefer header.
```
curl -u fedoraAdmin:fedoraAdmin "http://localhost:8080/rest/test-dc" -X PUT -H 'Link: <http://www.w3.org/ns/ldp#DirectContainer>;rel="type"' -H 'Content-Type: text/turtle' --data-binary '<> <http://purl.org/dc/elements/1.1/title> "Test"'
curl -u fedoraAdmin:fedoraAdmin "http://localhost:8080/rest/test-dc" -X POST
curl -u fedoraAdmin:fedoraAdmin …
```

Suppress ldp contains on omit smt

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/FedoraResourceImpl.java

no longer causes resources to disappear.
Instead a MalformedRdfException is thrown.
**Adding rdf:type memento:* - whether via PUT, POST or PATCH - no longer causes resources to disappear.**
**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2884
Adding `<> a memento:*` should result in a constraint exception since there are simply no cases where that should be allowed.  Furthermore,  we use the triple internally to and thus adding it to resources through the API wreaks havoc in the form of mysteriously disappearing resources.
This PR ensures that a constraint error is thrown whenever a client attempts to add such a triple via PUT, POST, or PATCH.
Integration tests cover the three cases.
1. POST a resource …

Adding rdf:type memento:* - whether via PUT, POST or PATCH -

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/FedoraResourceImpl.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2895
Validate PATCH request to ensure LDP Membership relation triple does not allow "ldp:contains" as the relationship.
1. Verify the new tests cover all the validation cases and they pass.
2. Follow the instructions on the Jira issue description to reproduce the problem and note that the PATCH request now correctly fails with 409 response.

Disallow PATCH of "ldp:contains" as (In)Direct ldp:hasMemberRelation

---

fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/responses/RdfStreamStreamingOutput.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/responses/RdfStreamStreamingOutputTest.java
fcrepo-integration-rdf/src/test/java/org/fcrepo/integration/rdf/RdfNamespaceMappingIT.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2887
Filters namespace prefixes in serialized RDF responses to just those which are present in the RDF being returned.
Filters the configured set of namespace prefixes down to just those present in either the predicates or rdf:type objects in the set of triples being serialized.
This applies to both block-streamed and serializations that require analysis of the entire model (rdf+xml, jsonld)
```
curl -ufedoraAdmin:fedoraAdmin -i -XPUT -H"Content-Type: text/turtle" http://localhost:8080/rest/ns_test1
curl -ufedoraAdmin:fedoraAdmin -i -H"Accept: text/turtle"  http://localhost:8080/rest/ns_test1
curl -ufedoraAdmin:fedoraAdmin -i -H"Accept: application/rdf+xml"  http://localhost:8080/rest/ns_test1
echo "INSERT { <> …
```

fcrepo-2887 - Remove unused namespace prefixes from responses

---

fcrepo-integration-ldp/src/test/java/org/fcrepo/integration/ldp/LdpTestSuiteIT.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2882
Resolves 401 errors in LdpTestSuite tests
- Verify that there are no more 401 errors in the LDP Testsuite logs.
- Also, note that the sum of failed tests plus skipped tests is now lower.

Resolves 401 errors in LdpTestSuite tests

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/services/functions/ConfigurableHierarchicalSupplier.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/utils/iterators/IteratorConsumer.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/utils/iterators/PersistingRdfStreamConsumer.java

- Change final field that is initialized to a compile-time static value to static final
- Remove throwing a runtime exception
Resolves: https://jira.duraspace.org/browse/FCREPO-2897
Non-functional clean-up of fcrepo codebase. Reduce 3 vulnerabilities and 2 bugs in Sonar report https://sonar.fcrepo.org/dashboard?id=org.fcrepo%3Afcrepo.  

Reduce Sonar Bugs and Vulnerabilities Issues

---

fcrepo-auth-common/src/main/java/org/fcrepo/auth/common/AbstractPrincipalProvider.java
fcrepo-auth-common/src/main/java/org/fcrepo/auth/common/BypassSecurityServletAuthenticationProvider.java
fcrepo-auth-common/src/main/java/org/fcrepo/auth/common/ContainerAuthToken.java
fcrepo-auth-common/src/main/java/org/fcrepo/auth/common/ServletContainerAuthFilter.java
fcrepo-auth-common/src/main/java/org/fcrepo/auth/common/ShiroSecurityContext.java
fcrepo-auth-common/src/test/java/org/fcrepo/auth/common/DelegateHeaderPrincipalProviderTest.java
fcrepo-auth-common/src/test/java/org/fcrepo/auth/integration/AbstractResourceIT.java
fcrepo-auth-common/src/test/java/org/fcrepo/auth/integration/RootTestResource.java

Additionally, tighten method and field qualifiers.
Resolves: https://jira.duraspace.org/browse/FCREPO-2900
Non-functional clean-up of fcrepo-auth-common

Remove the dead and redundant code from fcrepo-auth-common.

---

fcrepo-http-api/src/main/resources/views/common-node-actions.vsl
fcrepo-webapp/src/main/webapp/static/js/common.js
fcrepo-webapp/src/test/java/org/fcrepo/integration/FedoraHtmlResponsesIT.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2896
Add different container types to HTML UI dropdown.
* Removes the "container" entry from the create new object dropdown in the HTML UI
* Adds the 3 different container types to the dropdown ("basic container", "direct container", and "indirect container")
* Adds integration tests that ensure the containers created through the HTML UI this way have the correct RDF type
* Use `mvn clean install` to run the tests.
* Manual testing can be done by running the webapp via jetty:run, creating containers of the 3 types, and observing that the resulting objects have the correct RDF type.
* Does this change require documentation to be updated? If we refer to "Create a container" anywhere in the docs, that will need to be changed to be …

Add different container types to HTML UI dropdown.

---

fcrepo-jms/src/main/java/org/fcrepo/jms/AbstractJMSPublisher.java
fcrepo-jms/src/main/java/org/fcrepo/jms/DefaultMessageFactory.java
fcrepo-jms/src/main/java/org/fcrepo/jms/JMSEventMessageFactory.java
fcrepo-jms/src/main/java/org/fcrepo/jms/JMSQueuePublisher.java
fcrepo-jms/src/main/java/org/fcrepo/jms/JMSTopicPublisher.java
fcrepo-jms/src/test/java/org/fcrepo/integration/jms/observer/AbstractJmsIT.java

- Tighten method and field qualifiers.
Resolves: https://jira.duraspace.org/browse/FCREPO-2907
Non-functional clean-up of fcrepo-jms
- Successful build, deployment and one-click
- Consume and check messages produced while interacting with the repository
** https://wiki.duraspace.org/display/FEDORA5x/How+to+Inspect+Event+Messages+Generated+by+Fedora
** https://jsonformatter.org/json-pretty-print

Remove dead and redundant code from fcrepo-jms

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/AbstractResourceIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraHtmlIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/RdfLexicon.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/FedoraResourceImpl.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/integration/kernel/modeshape/observer/SimpleObserverIT.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2899
Prevent PATCH update containing server managed predicates and triples.
Adds memento namespace to managed type and managed predicate check.
- Run the tests to verify all passes
- Follow the instructions FCREPO-2899 description to replicate the problem and you should get a 409 on the third step.

Prevent PATCH containing server managed predicates and objects

---

.travis.yml

**JIRA Ticket**: N/A
Expands the testing matrix to test Oracle JDK 8, OpenJDK 8 and OpenJDK 11. But OpenJDK 11 is for informational purposes and is an allowed failure.
Changes in `.travis.yml`
Let travis run and pass.
Example:

Add more complex travis matrix

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/AbstractResourceIT.java
fcrepo-integration-rdf/src/test/java/org/fcrepo/integration/rdf/ServerManagedTriplesIT.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/RdfLexicon.java
fcrepo-kernel-api/src/test/java/org/fcrepo/kernel/api/RdfLexiconTest.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2923
Allows clients to delete or set premis:hasSize property.
* Removed premis:hasSize from set of server managed triples
* Added integration test that verifies the expected behavior of the four server generated triples for binaries: premis:hasSize, ebucore:filename, ebucore:hasMimeType, iana:describedby
* Removes duplicate testLdpContains test (it is already being tested in testLdpNamespace)
New integration test.
Create a binary, then issue a PATCH or PUT request to replace the premis:hasSize property. This can be done with a request similar to:
```
echo 'INSERT { <> <http://www.loc.gov/premis/rdf/v1#hasSize> "99"^^<http://www.w3.org/2001/XMLSchema#long> } WHERE { }' | curl -XPATCH -ufedoraAdmin:fedoraAdmin -H "Content-Type: …
```

Fcrepo-2923 - Allow modification of premis:hasSize property

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ExternalContentPathValidator.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/ExternalContentPathValidatorTest.java

External content allow list entry for http uri with a domain but no slash after it will log an error and be ignored.
```
echo "http://example.com" > /tmp/allowed.txt
mvn jetty:run -Dfcrepo.external.content.allowed=/tmp/allowed.txt
curl -v -X PUT -H "Link: <http://example.com/>; rel=\"http://fedora.info/definitions/fcrepo#ExternalContent\"; handling=\"proxy\"; type=\"text/plain\"" http://localhost:8080/rest/blocked_http -ufedoraAdmin:fedoraAdmin
rm /tmp/allowed.txt
echo "http://example.com/" > /tmp/allowed.txt
mvn jetty:run -Dfcrepo.external.content.allowed=/tmp/allowed.txt
curl -v -X PUT -H "Link: <http://example.com/>; rel=\"http://fedora.info/definitions/fcrepo#ExternalContent\"; handling=\"proxy\"; type=\"text/plain\"" http://localhost:8080/rest/http_bin -ufedoraAdmin:fedoraAdmin
curl …
```

Requiring allowed list http domains end with slash

---

fcrepo-http-api/src/main/resources/views/fcr-versions.vsl

Resolves:
**Removes empty accordion panels in the version list view in the HTML UI.**
* * *
**JIRA Ticket**:  https://jira.duraspace.org/browse/FCREPO-2925
create a resource
create a version of the resource
view the mementos
Observe the absence of an accordion panel for the newly created memento. New memento appears as a link in an unordered list.

Removes empty accordion panels in the version list view.

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersioningIT.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/api/rdf/HttpResourceConverter.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/api/rdf/HttpResourceConverterTest.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/utils/SubjectMappingUtil.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/FedoraResourceImpl.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2929
Allows for the creation of mementos from RDF Sources that contain hash uris
* Allow for hashes in any uri when converting forward from HTTP URI to a resource.
* When creating a memento, allow for hash components of subject uris to be retained when converting from the original as the subject to the memento for storage.
* When retrieving a memento's RDF which contains a hash uri, convert the hash uri subject from the memento's URI as the subject to the original suffixed with the hash component as the subject.
```
curl -XPUT -ufedoraAdmin:fedoraAdmin -"http://localhost:8080/rest/memento_hash_test"
echo 'INSERT { <#test> <http://example.com/label> "my hash resource title" } WHERE {} ' | curl -XPATCH -ufedoraAdmin:fedoraAdmin -H …
```

FCREPO-2929 - Hash URIs in mementos

---

fcrepo-http-api/src/main/resources/views/common-header.vsl
fcrepo-kernel-api/pom.xml
fcrepo-webapp/src/main/webapp/index.html
src/site/markdown/index.md.vm
src/site/site.xml

* * *
**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2933
Removes the "4" from the HTML UI navbar and a few other places in code
Purely a change in nomenclature.  References in text to "Fedora 4" are now just "Fedora" Should reduce confusion as to what Fedora people are running.
Bring up HTML UI and confirm appearance in the navbar.
@dbernstein @bbpennel

Removed "4" from reference to Fedora in text, including UI navbar header

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/responses/StreamingBaseHtmlProvider.java
fcrepo-http-api/src/main/resources/views/common-node-actions.vsl
fcrepo-http-api/src/main/resources/views/fcr-versions.vsl
fcrepo-webapp/src/test/java/org/fcrepo/integration/FedoraHtmlResponsesIT.java

**"View Versions" link in HTMLUI no longer returns 404 if no version is created yet for a resource.**
* * *
**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2934
Ensures that UI renders the versions list page even when there are no versions.  Previously the link would return 404 if there were no versions created.   Also includes an HTML UI integration test to verify this fix.
1. fire up HTML UI 
2. create a resource.
3. click on "View Versions" link.  
4. Verify that  a non 404 response is returned.

"View Versions" link in HTMLUI no longer returns 404 if no versions have been created

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersioningIT.java

Related to: https://jira.duraspace.org/browse/FCREPO-2932
This PR resolves an problem that was identified by the Memento Validator tool where a HEAD request to a memento fails if the Accept-Datetime header is present in the request. The memento spec allows this condition since it allows user agents to be a in a "date time negotiation mode" which is a typical use case.
The Accept-Datetime header is now ignored when performing HEAD on a memento. An integration test verifies the fix.
curl -i http://localhost:8080/rest -X POST -H "Slug: test-memento" -u fedoraAdmin:fedoraAdmin
curl -i http://localhost:8080/rest/test-memento/fcr:versions  -X POST -u fedoraAdmin:fedoraAdmin
curl -i http://localhost:8080/rest/test-memento/fcr:versions/<new memento> -I -u fedoraAdmin:fedoraAdmin
#perform the same …

HEAD on memento to ignore Accept-Datetime heaader

---

fcrepo-http-api/src/test/java/org/fcrepo/http/api/ExternalContentPathValidatorTest.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersioningIT.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/utils/AutoReloadingConfiguration.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/UrlBinaryTest.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/spring/DefaultPropertiesLoaderTest.java

[FCREPO-2693](https://jira.duraspace.org/browse/FCREPO-2963)
* Fixes several tests that fail on Windows due to differences in file paths
* Conditionally disables one test due to the usage of a feature in `wiremock` that does not work on Windows
* Updates `AutoReloadingConfiguration` to be tolerant of exceptions thrown upon `Paths.get(string)`
The only change to runtime fcrepo code is in `AutoReloadingConfiguration`.  This PR changes its behavior such that if an exception is thrown when attempting to read a file path via `Paths.get(string)`, monitoring the file is simply disabled.  The previous behavior was a uncaught runtime exception that prevented the fcrepo webapp from loading.
Just make sure tests still pass.

Allow fcrepo5 to build and run on Windows

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/AbstractResourceIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersioningIT.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/utils/JcrPropertyStatementListener.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/utils/iterators/RdfAdder.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/utils/iterators/RdfRemover.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2969
Adds rdf:types submitted via PUT and PATCH to binary descriptions
Also adds tests to verify behavior for PUT/PATCH and memento creation.
See example on ticket
rdf:types no longer being added to the binary node, only to the description node
@awoods @dbernstein

Fcrepo-2969 - Adding types to binaries

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersioningIT.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/api/rdf/HttpResourceConverter.java

Resolves: https://jira.duraspace.org/browse/FCREPO-2970
Change HttpResourceConverter hash regex to match on non-whitespace (\S) instead of word characters (\w)
See ticket description
@whikloj / @bbpennel / @dbernstein

Allow versioning of resources with blank nodes

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersioningIT.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/api/rdf/HttpResourceConverter.java

cherrypick  fcrepo-2970 (allowing blank node versioning) into 5x-maintenance

---

fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/models/FedoraResource.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/FedoraJcrConstants.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/FedoraResourceImpl.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/services/functions/AnyTypesPredicate.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/services/functions/JcrPropertyFunctions.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/utils/FedoraTypesUtils.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/integration/kernel/modeshape/FedoraResourceImplIT.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/rdf/JcrRdfToolsTest.java

Resolves: https://jira.duraspace.org/browse/FCREPO-2971
Removes references to obsolete JCR:Frozen resources.
No functionality is added or removed. This update should have no effect on the Fedora application.

Remove references to obsolete JCR:Frozen resources

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/AbstractResourceIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java

Resolves: https://jira.duraspace.org/browse/FCREPO-2968
Ensures that user-provided types on RDF and descriptions of nonRDF Sources are returned as `Link` headers in GET and HEAD requests.
1. Create a resource (binary or container)
1. Add a type property
```
INSERT {
<> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://pcdm.org/models#File> .
}
WHERE {}
```
1. Ensure that the new type is contained as a `Link` header in GET and HEAD requests

Include user-provided rdf:types a Link headers

---

fcrepo-event-serialization/src/test/java/org/fcrepo/event/serialization/JsonLDSerializerTest.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/FedoraLdpTest.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraTransactionsIT.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/AbstractResource.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/api/rdf/HttpResourceConverter.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/RdfLexicon.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/services/TimeMapService.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/AbstractFedoraBinary.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/FedoraResourceImpl.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/NonRdfSourceDescriptionImpl.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/services/TimeMapServiceImpl.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/services/VersionServiceImpl.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/integration/kernel/modeshape/FedoraResourceImplIT.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/integration/kernel/modeshape/FedoraTimeMapImplIT.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/integration/kernel/modeshape/services/TimeMapServiceImplIT.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2975
Resolves an NPE when committing transactions containing HEAD and DELETE requests to the same resource by creating timemaps at the same time that the original resource was created.
Creating timemap at the same time that a resource is created. 
* Implemented TimeMapService for the creation of timemaps
* Changed FedoraResourceImpl.getTimeMap() to never create timemaps
* Allow for responses for versioning disabled resources to not return a timemap uri
* Moved constant for fedora:timemap node to constants class for consistency and since it did not primarily belong to FedoraResourceImpl anymore.
* Added and updated tests
See example in ticket as well as new integration tests. 
This changes the approach in fcrepo5 regarding when …

Fcrepo 2975 - Create timemap when resource created

---

fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/WebACRolesProvider.java
fcrepo-auth-webac/src/test/java/org/fcrepo/auth/webac/WebACRolesProviderTest.java
fcrepo-auth-webac/src/test/java/org/fcrepo/integration/auth/webac/WebACRecipesIT.java
fcrepo-auth-webac/src/test/resources/acls/agent-access-to-class.ttl

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2977
Resolves issue where binaries incorrectly return a 403 when they should be granted access via accessToClass.
Updates retrieval of roles for acl determination to inspect resources as their type specific subclass instead of generic FedoraResourceImpl, and then uses the description for the resource when retrieving rdf:types for the resource.
Adds integration test for this case.
5.8-A-2 should now pass, along with the included integration test.
@peichman-umd @awoods

Fcrepo-2977 - Binary/Description accessToClass

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/FedoraLdpTest.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/LDPContainerIT.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/RdfLexicon.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/services/ContainerService.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/FedoraResourceImpl.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/services/ContainerServiceImpl.java

**JIRA Tickets**:
https://jira.duraspace.org/browse/FCREPO-2935
https://jira.duraspace.org/browse/FCREPO-2936
https://jira.duraspace.org/browse/FCREPO-2937
Populates default values for Indirect and DirectContainers based on the specification's suggestions.
* ldp:membershipResource defaults to the direct or indirect container itself
* ldp:hasMemberRelation defaults to ldp:member
* ldp:insertedContentRelation defaults to ldp:MemberSubject for IndirectContainers
* ContainerServiceImpl modified to accept an interaction model, and populates the mixin and default properties for that model as appropriate
* Default Indirect/DirectContainer properties repopulated when removed via PUT or PATCH.
* Added integration tests for population of ldp containers.
Create indirect/direct containers via curl. …

FCREPO-2935-7 - LDP Container default properties

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/services/TimeMapServiceImpl.java

https://jira.duraspace.org/browse/FCREPO-2986
Uses string concatenation instead of `Paths` to generate timemap paths.  `Paths` uses system-dependent filesystem semantics in its path logic, which resulted in exceptions when the path included a ":" character
Build and run on Windows successfully.  Other platforms should continue to run successfully.

Generate timemap paths in platform-independent way

---

fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/CachedHttpRequest.java
fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/WebACAuthorizingRealm.java
fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/WebACFilter.java
fcrepo-auth-webac/src/test/java/org/fcrepo/auth/webac/WebACFilterTest.java
fcrepo-auth-webac/src/test/java/org/fcrepo/integration/auth/webac/WebACRecipesIT.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/rdf/converters/PropertyConverter.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-1889
Currently you can create a direct or indirect container that would reference a resource you do **not** have `acl:Write` access to with its `ldp:membershipResource` and create triples on that resource.
This now checks for the creation or updating of Direct and Indirect containers to ensure you have `acl:Write` permissions is there is a `ldp:membershipResource` in the request.
@peichman-umd altered the WebACAuthorizingRealm to allow the addition of more than one URI to collect permissions on, this enables us to check both the target of the current request and the referenced URI 
1. Create a container (readonly) and give a user read only access to it.
1. Create a container (users) and give the same user read/write access to it. …

Don't allow ldp:membershipResource if you don't have acl:Write

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/StateTokensIT.java

**Adds Support for X-State-Token in GET and HEAD requests.**
* * *
**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2976
This PR adds the X-State-Token header into the http responses for LDP-RS and LDP-NS objects including ACLs and LDPCVs.
The change is very simple:  the value of the Etag for a resource is being plugged into the X-State-Token header on GET and HEAD requests.
Integration tests cover the functionality.  For manual tests, perform GETs and HEADs above mentioned classes of resources and you should see the  X-State-Token header in the responses.
Example:
* Does this change require documentation to be updated? …

Adds Support for X-State-Token in GET and HEAD requests.

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/api/rdf/HttpResourceConverter.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/api/rdf/HttpResourceConverterTest.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/services/AbstractService.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/services/NodeServiceImpl.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/integration/kernel/modeshape/services/BinaryServiceImplIT.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/integration/kernel/modeshape/services/ContainerServiceImplIT.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/integration/kernel/modeshape/services/NodeServiceImplIT.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/services/AbstractServiceTest.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/services/BinaryServiceImplTest.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/services/ContainerServiceImplTest.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/services/NodeServiceImplTest.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/services/RepositoryServiceImplTest.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2991
Previously prefixes in slugs and paths that were not registered in the Modeshape registry would fail, now they are URL encoded.
ie. `newNS:12345` becomes `newNS%3A12345`
Namespaces already in Modeshape (and `fcr`) are exempt from this encoding.
ie. All of [these](https://github.com/fcrepo4/fcrepo4/blob/master/fcrepo-kernel-modeshape/src/main/resources/fedora-node-types.cnd#L4-L45)
Everywhere we validate, save or retrieve a path we attempt to encode or decode it. 
Prior to PR doing
```
curl -i -XPUT -ufedoraAdmin:fedoraAdmin http://localhost:8080/rest/abc:123
```
Would return a 400 error with `Prefix abc has not been registered`
With this PR it will succeed.
Example:
* …

Allow undefined prefixes in paths by encoding their colons

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2996
Disallows deleting the internal description of a binary directly, instead you must delete the binary which removes the both.
* Internal tests but also
Before PR.
1. Create a binary `curl -ufedoraAdmin:fedoraAdmin -H"Content-type: text/plain" -d"Some text" -XPUT http://localhost:8080/rest/binary`
1. Delete the description `curl -ufedoraAdmin:fedoraAdmin -XDELETE http://localhost:8080/rest/binary/fcr:metadata` -> `204 No Content`
After the PR
1. Do the same as above but deleting the description (`/fcr:metadata`) results in `405 Method Not Allowed`
Example:
* Does this change require documentation to be updated?  no
* Does this change add any new dependencies?  no
* Does this change require any other modifications to be made to …

Don't allow NonRdfSourceDescriptions to be deleted directly

---

fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/RdfLexicon.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/utils/FedoraTypesUtils.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2997
Hides the `fedora:NonRdfSourceDescription` type so it does not appear in the binary description RDF.
Before the PR
1. Create a binary
1. Get the `binary/fcr:metadata` and see a `rdf:type` of `fedora:NonRdfSourceDescription`
After the PR
1. Create a binary
1. Get the `binary/fcr:metadata` and see **no** `rdf:type` of `fedora:NonRdfSourceDescription`
Example:
@fcrepo4/committers @peichman-umd

Hide fedora:NonRdfSourceDescription type

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/FedoraLdpTest.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/FedoraNodesTest.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/StateTokensIT.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/models/FedoraResource.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/FedoraResourceImpl.java

**Adds Support for X-If-State-Token on PUTs and PATCHs..**
* * *
**JIRA Tickets**: 
https://jira.duraspace.org/browse/FCREPO-2993
https://jira.duraspace.org/browse/FCREPO-2994
Ensures that PUTs and  PATCHs honor the X-If-State-Token header as defined by the Fedora specification.
I added a new method FedoraResource.getStateToken() in order to ensure that we distinguish between StateTokens and Etags.  Currently we are using weak etags.  However, that may change in Fedora 6.  Therefore we may want to handle the implementation differently in 6.
Integration tests cover success and failure for both PUTs and PATCHs  for rdf, nonrdf and acl's.
Example:
* Does this change require documentation to be updated? Yes 
* Does …

Adds Support for X-If-State-Token on PUTs and PATCHs.

---

fcrepo-auth-webac/pom.xml
fcrepo-parent/pom.xml

Related to: https://jira.duraspace.org/browse/FCREPO-2782
Introduces the DuraSpace checkstyle rules in favor of the Fedora-specific rules.
This update assumes a (currently unreleased) 5.0.0 version of fcrepo-build-tools.
To test this PR,
1. Wait for a 5.0.0 release of fcrepo-build-tools
1. Ensure that the build works as usual
1. Pull down the 5.0.0 release of [fcrepo-build-tools](https://github.com/fcrepo4/fcrepo-build-tools/pull/14), uncomment any of the [suppressions](https://github.com/fcrepo4/fcrepo-build-tools/blob/6f8e5a616cf27ff0cc2b829100a35d5b713afba5/src/main/resources/fcrepo-checkstyle/checkstyle-suppressions.xml)
- Verify build fails
1. Make a local change in Fedora that breaks unsuppressed [checkstyle rules](https://github.com/duraspace/codestyle/blob/master/src/main/resources …

Add DuraSpace checkstyle

---

.travis.yml
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/utils/iterators/RdfAdder.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/utils/iterators/RdfRemover.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-3015
I got the idea for this fix from https://github.com/fcrepo4/fcrepo4/pull/1491
Tries to add/remove the triples for binaries on the description (was using the actual binary).
See steps in associated ticket.
Create a binary, update the triples on the `/fcr:metadata` endpoint. 
Basically you can add triples but can't seemingly delete them. In practice I found when GET then PUT altered triples they were entirely ignored.
Example: …

Correctly persist NonRDFSource description triples

---

.travis.yml
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/utils/iterators/RdfAdder.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/utils/iterators/RdfRemover.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-3015
Release PR of #1532 
Tries to add/remove the triples for binaries on the description (was using the actual binary).
See steps in associated ticket.
Create a binary, update the triples on the `/fcr:metadata` endpoint.
Basically you can add triples but can't seemingly delete them. In practice I found when GET then PUT altered triples they were entirely ignored.
Example: …

Correctly persist NonRDFSource description triples (release mix)

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/services/TimeMapServiceImpl.java

**Generate timemap paths in platform-independent way**
* * *
**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2986 
* Generate timemap paths in platform-independent way
* Special case for resources ending in slash
* Emulates the previous behavior where path termination with a slash is
irrelevant
This commit was included in the 5.0.2 release but did not get merged into master. Thus it is missing on 5.1.0-RC and is the likely cause of failures of the code to build on winows.
To test, please build on windows and verify that it passes.
@birkland

Generate timemap paths in platform-independent way (#1516)

---

fcrepo-auth-webac/src/test/java/org/fcrepo/auth/webac/WebACRolesProviderTest.java

Addresses https://jira.duraspace.org/browse/FCREPO-3029 
- Fix deprecation warnings in fcrepo-auth-webac
Replaced all instances of `anyObject` with `any`
On branch fcrepo-3029
Changes to be committed:
modified:   fcrepo-auth-webac/src/test/java/org/fcrepo/auth/webac/WebACRolesProviderTest.java
I hope this meets your expectations @dbernstein Thanks for creating these tickets to get us started

Fix deprecation warnings in fcrepo-auth-webac

---

fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/utils/AutoReloadingConfiguration.java

- include add '@throws IOException' comment for init() method
Resolves: https://jira.duraspace.org/browse/FCREPO-3028
* * *
https://jira.duraspace.org/browse/FCREPO-3028
Fixes the Javadoc warning
Include add '@throws IOException' comment for init() method
By rebuilding and verifying warning disappears.
* Reproduce the problem you are fixing (if applicable) - remove @throws IOException' comment from init() method
* Test that the Pull Request does what is intended. - re-build 'fcrepo-kernel-api' and verify warning …

Address javadoc warnings in fcrepo-kernel-api

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/FedoraLdpTest.java
fcrepo-jms/src/test/java/org/fcrepo/integration/jms/observer/AbstractJmsIT.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/models/FedoraResource.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/services/ReplacePropertiesService.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/services/UpdatePropertiesService.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-3057
Creates two new service interfaces for updating and replacing properties.
Moves the methods `updateProperties` and `replaceProperties` out of the `FedoraResource` interface and into their own separate service interfaces.
* Just a standard `mvn clean install` should do.
None.

Move update and replace properties into services.

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraFixity.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/models/Binary.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/services/FixityService.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-3065
Moved fixity methods from the Binary interface to a new FixityService interface.
Extracted the getFixity() and checkFixity() methods from the Binary interface and placed them in a new FixityService interface. Modified their signatures to take a Binary as their first argument, instead of an idTranslator.
A standard `mvn clean install`.
None.
@bbpennel, @fcrepo4/committers

Created FixityService interface.

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraAcl.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/models/FedoraResource.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/services/WebacAclService.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/FedoraResourceImpl.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-3064
Removed findOrCreateAcl() method from FedoraResource.
Added a `WebacAclService` class that will handle the creation of ACLs. This service is the new home of the `findOrCreateAcl()` method, under the name `findOrCreate()`.
Standard `mvn clean install` build.
None
@bbpennel , @fcrepo4/committers

Removed findOrCreateAcl() method from FedoraResource.

---

fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/api/rdf/HttpIdentifierConverter.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/api/rdf/HttpIdentifierConverterTest.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-3088
https://docs.google.com/document/d/1IvZK_VInC8HhtMVs98jJ3czInpwX4Ro8MWJd8hb3W40/edit
Adds a new Converter to translate a URI to an internal Fedora ID.
In the most basic sense `doForward()` takes the URI, grabs the path without the base context. Then strips off any with `fcr:*` or `#something` and prepends `info:fedora/`
`doReverse` removes the `info:fedora/` prefix and makes what is left as the path of the URI template.
Due to the removal of `fcr:*`, etc this is not necessarily an strictly invertable conversion. 
For example:
`http://localhost:8080/fcrepo/rest/my_thing` -> `info:fedora/my_thing`
and
`info:fedora/my_thing` -> `http://localhost:8080/fcrepo/rest/my_thing`
But
`http://localhost:8080/fcrepo/rest/my_thing/fcr:acl` …

Add new identifier translator

---

fcrepo-persistence-ocfl/pom.xml
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/api/CommitOption.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/api/OCFLObjectSession.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/DefaultOCFLObjectSession.java
pom.xml

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-3101
* Introduces the interface and stubbed out implementation for an OCFLObjectSessions
* Adds ocfl-java client dependency
There isn't any testable functionality yet
This PR contains stubbed out implementations for methods with private method calls as pseudo-code to help understand if the structure matches the needed behavior.
The implementation will require publishing of updates to the ocfl-java before it can proceed.

FCREPO-3101 - OCFLObjectSession skeleton

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/TransactionsIT.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-3092
Include caching headers in transaction requests.
Removed the code that skipped adding cache-related headers (ETag, Last-Modified) if a request was part of a transaction.
Just building it, since the tests for Transactions are currently disabled.
This adds a test to the TransactionsIT, but that test is not currently being run because the transactions implementation is incomplete.
@dbernstein , @fcrepo4/committers

Include caching headers in transaction requests.

---

fcrepo-persistence-api/src/main/java/org/fcrepo/persistence/api/exceptions/PersistentSessionClosedException.java
fcrepo-persistence-api/src/main/java/org/fcrepo/persistence/api/exceptions/PersistentStorageException.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/api/OCFLObjectSession.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/DefaultOCFLObjectSession.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/DefaultOCFLObjectSessionTest.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-3095
Implements the core functionality involved in committing changes to an OCFL object.
* Implements all methods exception `prepare`
* Add unit tests for object session
* Adds additional methods to the object session interface: deleteObject, close
* Adds throws expectations
There is a unit test for now.
This PR does not address locking beyond synchronization to prevent simultaneous modifications to the same object session.
Also, if an object is deleted in a session, it will cause the OCFL object to be deleted at commit time. The same session can also create a new OCFL object with the same identifier.
@dbernstein, @pwinckles, @fcrepo4/committers

FCREPO-3095 - Implement OCFL Object Session

---

fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/api/rdf/HttpIdentifierConverter.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/api/rdf/HttpIdentifierConverterTest.java

Stops using the Converter interface and creates more developer friendly method names to make it clear what you are doing with the converter.

Refactor to a more understandable converter syntax

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/services/HttpRdfService.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/services/HttpRdfServiceTest.java

HttpRdfService will translate from resource URI to internal resource ID
This is part of https://jira.duraspace.org/browse/FCREPO-3060 and is used by any of the code that needs the URIs to be translated into internal fedora IDs. 
**JIRA Ticket**: part of https://jira.duraspace.org/browse/FCREPO-3060
Adds a service at the HTTP Layer that will look at the InputStream rdf and return it as a Model or RdfStream, having translated the URIs into internal fedora ids in the data. 
@whikloj @bbpennel

Adds HttpRdfService to help translate uris to fedora ids in the rdf.

---

fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/OCFLPersistentStorageSession.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/OCFLPersistentStorageUtils.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/DeleteResourcePersister.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/RDFSourcePersister.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/DeleteResourcePersisterTest.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/RDFSourcePersisterTest.java

Fix typo in class name
**JIRA Ticket**: https://jira.duraspace.org/projects/FCREPO/issues/FCREPO-3100
Adds a Delete Resource persister to do the deletion from the persistence layer.
Also fixes a small typo in a utility class name, sorry for all the import changes due to the class renaming.
Review, unit tests included

Add delete persister

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/Transactions.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/TransactionsTest.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/Transaction.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/exception/TransactionRuntimeException.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/TransactionImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/TransactionManagerImpl.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/TransactionImplTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/TransactionManagerImplTest.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-3128
Completes the implementation of the TransactionImpl
- Changed `getExpires` method on Transaction Interface to return `Instant` instead of `Optional<Instant>`
Verify that the build and tests pass.
Currently, the only time a Transaction get removed from the TransactionManager's list is when there is a request request to get a transaction which has expired. Do we need to remove transactions on commit/rollback or should we move the finished (commited/rolledback/expired) transaction to a different list. This discussion probably can wait until we move to a database backed transaction store.

FCREPO-3128. Complete TransactionImpl implementation.

---

fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/FedoraResourceImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/ResourceFactoryImpl.java
fcrepo-persistence-api/src/main/java/org/fcrepo/persistence/api/CommitOption.java
fcrepo-persistence-api/src/main/java/org/fcrepo/persistence/api/PersistentStorageSession.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/OCFLPersistentSessionManager.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/OCFLPersistentStorageSession.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/OCFLPersistentStorageUtils.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/api/OCFLObjectSession.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/api/OCFLObjectSessionFactory.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/DefaultOCFLObjectSession.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/DefaultOCFLObjectSessionFactory.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/NonRdfSourcePersister.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/RDFSourcePersister.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/OCFLPersistentSessionManagerTest.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/OCFLPersistentStorageSessionTest.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/DefaultOCFLObjectSessionTest.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/NonRdfSourcePersisterTest.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/RDFSourcePersisterTest.java

**Implements Implement OCFLPersistentStorageSession.getTriples() and OCFLPersistentStorageSession.getManagedProperties() for unversioned content.**
* * *
**JIRA Ticket**:  https://jira.duraspace.org/browse/FCREPO-3119
This PR implements the OCFLPersistentStorageSession.getTriples() and OCFLPersistentStorageSession.getManagedProperties()  methods when the version parameter is null.  Included is a unit test that writes resources to disk and then reads them out  before and after the commit.
PersistentStorageSession.commit() now has a CommitOption param. 
Covered by a unit test.
Folks should be aware of the change to the …

Implement OCFLPersistentStorageSession.getTriples()

---

fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/OCFLPersistentStorageSession.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/OCFLPersistentStorageUtils.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/api/OCFLObjectSession.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/DefaultOCFLObjectSession.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/OCFLPersistentStorageSessionTest.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/DefaultOCFLObjectSessionTest.java

**Implements OCFLPersistentStorageSession.getTriples() by version.**
* * *
**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-3126
Adds support for getTriples() using an Instant to identify a version
In addition I have added a listVersions(fedoraIdentifier) method to the OCFLPersistentStorageSession.java to help with testing.   If we decide we need this method for memento related operations,  we can promote it to the PersistentStorageSession interface.  In order to support retrieving triples by version, I've also added the OCFLObjectSession.listVersions() method.  
Covered by unit tests.
There is a TODO in the implementation of OCFLObjectSession.listVersions() that calls for making use of the …

Implements OCFLPersistentStorageSession.getTriples() by version.

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraBaseResource.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/api/rdf/HttpIdentifierConverter.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/api/rdf/HttpIdentifierConverterTest.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/TransactionManagerImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/ResourceFactoryImpl.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/FedoraOCFLMapping.java

**JIRA Ticket**: n/a
In trying to get the system to respond to a GET request to the repo root I found some small issues.
1. We pass in the path part only, so the HttpIdentifierConverter needs to handle that scenario as well as a full URI.
2. We need a ResourceFactory Injected into the HTTP layer to get resources, that or we need to start radically altering how to "get" a resource up from the base.
3. Some of the `private static` fields had Inject annotations on them and it seems like this is not allowed. So I made them non-static.
After all this I am getting to [here in OCFLPersistentStorageSession](https://github.com/fcrepo4/fcrepo4/blob/master/fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/OCFLPersistentStorageSession.java#L204) but it fails as its `null` because we …

Changes to get closer to running

---

fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/DefaultOCFLObjectSessionFactory.java

Resolves: https://jira.lyrasis.org/browse/FCREPO-3162
Fixes bug whereby the default OCFL persistence was going to a directory named `null` in the current working directory.
Additionally, names the default persistence directories based on the system-property values used to override their names.
- Build and run the one-click
- Observe logging to console that indicates location of OCFL persistence
- Verify directories mentioned in console logging exist

Bug fix: Ensure default OCFL persistence goes to tmp-dir

---

fcrepo-webapp/pom.xml

This update enables one to build the one-click  without having to build the jetty-console locally.

Updates jetty-console to 1.62 (java 11 support).

---

fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/DefaultOCFLObjectSessionFactory.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/FedoraToOCFLObjectIndexImpl.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/OCFLConstants.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/FedoraToOCFLObjectIndexImplTest.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3171
A simple text file containing the FedoraToOCFLObjectIndex so we can reload it between runs of Fedora.
Try both of these steps before and after PR.
1. Stand up Fedora
1. Create a resource.
1. `GET` the resource
1. Shutdown Fedora
1. Start Fedora, this step will throw errors before the PR.
1. `GET` the resource again, this step will only work after the PR.
This is not good I'm sure. My skill with creating and read/writing to files with java is weak so please provide any improvements you can think of.

Persist FedoraToOCFLIndex to disk

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/DefaultOCFLObjectSession.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/DefaultOCFLObjectSessionFactory.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/DefaultOCFLObjectSessionTest.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3174
Currently all storage requests generate operations that need to be checked for changes. These all share the exact same directory so when we do the check of operations the first operation persists all files to its OCFL object. This causes an error.
It still doesn't work but I was `POST`ing a new resource and would get a error related to rolling back the transaction. With this change you should get an error related to adding cache control headers. (See next PR for work on that)

Stage object sessions in their own subdirectories.

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraBaseResource.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/FedoraLdpTest.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/Transaction.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/models/Binary.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/TransactionImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/BinaryImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/FedoraResourceImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/NonRdfSourceDescriptionImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/ResourceFactoryImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/CreateResourceServiceImpl.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/models/ResourceFactoryImplTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/services/CreateResourceServiceImplTest.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3179
Binaries and their descriptions should not be created via POST.
* Implementation and creation of descriptions (Non-RDF source descriptions)
* Filling out and cleanup of Binary classes.
* getProxyUrl and getRedirectUrl were merged since they are now identical
* Some fixes regarding committing transactions for POST
* Avoid NPE if no content disposition provided during binary creation.
There are updated and reenabled tests. There are not many ways to manually test this until GET is implemented for binaries.
Note: digests are not evaluated yet.

FCREPO-3179 - POST to Create Binaries and descriptions

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraAcl.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraVersioning.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/models/Binary.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/BinaryImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/FedoraResourceImpl.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/OCFLPersistentStorageSession.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/OCFLPersistentStorageUtils.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/OCFLPersistentStorageSessionTest.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3079
Enables retrieval of binaries at the persistence and http layers.
* Implements getBinaryContent at persistence layer
* Reorganization of @GET method to skip unnecessary creation of rdf stream when getting binary content, and to separate binary from rdf retrieval, similar to how the HEAD method is organized.
* this included removing binary retrieval from the `getContent` method, and removing the `Range` parameter from various API methods that were only receiving it to pass it to `getContent` (where it was ignored since they didn't retrieve binaries)
* Fix issue with content size of binaries when content disposition is present but no content size specified
* Removes some more unused binary
* Reenables some binary related …

FCREPO-3079 - GET binary

---

fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/exceptionhandlers/PathNotFoundExceptionMapper.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/exceptionhandlers/PathNotFoundExceptionMapperTest.java

Resolves https://jira.lyrasis.org/browse/FCREPO-3177
* * *
https://jira.lyrasis.org/browse/FCREPO-3177
Solves the issue where using GET to get info on a non-existant item returns a 500 server error code, it should return a 404 error code. This code adds a specific exception handler for the PathNotFoundException that returns a 404 server error code whereas before it fell through to a WildcardException that would return a 500 error code. There is also a mockito test unit for the new exception handler
curl -u fedoraAdmin:fedoraAdmin http://localhost:8080/rest/blah

Added unique PathNotFoundExceptionMapper and mock test for that file

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/ExternalContentHandler.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraBaseResource.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraVersioning.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/models/ExternalContent.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/services/CreateResourceService.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/services/ReplaceBinariesService.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/operations/AbstractNonRdfSourceOperationBuilder.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/operations/CreateNonRdfSourceOperationBuilderImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/operations/NonRdfSourceOperationFactoryImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/operations/UpdateNonRdfSourceOperation.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/operations/UpdateNonRdfSourceOperationBuilder.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/CreateResourceServiceImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/ReplaceBinariesServiceImpl.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/operations/UpdateNonRdfSourceOperationBuilderTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/services/CreateResourceServiceImplTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/services/ReplaceBinariesServiceImplTest.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3103
Support PUT of binaries
* Remove duplicate parseDigestHeader, and change to return Collection<URI> since that is what is needed everywhere.
* Populate http resource headers during GET request
* Fix evaluation to determine if resource being created is a binary to not incorrectly assume it is a binary when no content type is provided
* Resolve some failures when content type is not provided
* Replace placeholder 'resource exists' checks with real ones for PUT
* Don't default content type to turtle when creating a binary
* Reenable a number of tests, in some cases explicitly create parent objects which were being produced as pairtrees before
* Implements …

FCREPO-3103 - PUT binaries

---

fcrepo-persistence-ocfl/pom.xml
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/RepositoryInitializer.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/api/FedoraToOCFLObjectIndex.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/api/FedoraToOCFLObjectIndexUtil.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/api/OCFLObjectSession.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/api/OCFLObjectSessionFactory.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/AbstractPersister.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/DefaultOCFLObjectSession.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/DefaultOCFLObjectSessionFactory.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/FedoraToOCFLObjectIndexImpl.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/FedoraToOCFLObjectIndexUtilImpl.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/OCFLPersistenceConfig.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/OCFLPersistentStorageUtils.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/DefaultOCFLObjectSessionTest.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/FedoraToOCFLObjectIndexUtilImplTest.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/OCFLPersistentStorageSessionTest.java
pom.xml

**Automatic rebuild of Fedora to OCFL Index on start**
* * *
**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3195
Enables automatic rebuild on start when fedora to ocfl index file is not present.
*  FedoraToOCFLIndexUtil component which implements the index rebuild logic.
*  Integration test covering the functionality.
* Minor related fixes.
* Update to the ocfl-java client to support the new feature.
```
java -Dfcrepo.ocfl.staging.dir=target/fcrepo-data/staging -Dfcrepo.ocfl.storage.root.dir=target/fcrepo-data/ocfl-root -Dfcrepo.ocfl.work.dir=target/fcrepo-data/work  -jar fcrepo-webapp/target/fcrepo-webapp-6.0.0-SNAPSHOT-jetty-console.jar --headless
curl -u fedoraAdmin:fedoraAdmin …
```

Automatic rebuild of Fedora to OCFL Index on start

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/AbstractResourceIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/DirtyContextBeforeAndAfterClassTestExecutionListener.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/ExternalContentHandlerIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/ExternalContentPathValidatorIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraAclIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraCrudConcurrentIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraFixityIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraHtmlIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraNodesIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraRelaxedLdpIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersioningIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/LDPContainerIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/StateTokensIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/TransactionsIT.java
fcrepo-webapp/src/test/java/org/fcrepo/integration/FedoraHtmlResponsesIT.java
fcrepo-webapp/src/test/java/org/fcrepo/integration/SanityCheckIT.java

Only updating tests in:
- fcrepo-http-api, and
- fcrepo-webapp
Resolves: https://jira.lyrasis.org/browse/FCREPO-3217
Re-enables integration tests that are currently passing.
Below is a record of the integration test results after updating test classes in the above modules:
```
fcrepo-http-api
[WARNING] Tests run: 207, Failures: 0, Errors: 0, Skipped: 172
* After ExternalContentHandlerIT
[WARNING] Tests run: 228, Failures: 0, Errors: 0, Skipped: 190
* After ExternalContentPathValidatorIT
[WARNING] Tests run: 232, Failures: 0, Errors: 0, Skipped: 191
* After FedoraAclIT
[WARNING] Tests run: 249, Failures: 0, Errors: 0, Skipped: 207
* After FedoraCrudConcurrentIT - no JIRA needed
[WARNING] Tests run: 249, Failures: 0, Errors: 0, Skipped: 206
* After FedoraFixityIT
[WARNING] Tests run: 253, …
```

Enable currently passing integration tests

---

fcrepo-parent/pom.xml

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3235
Removes the prerequisite block from fcrepo-parent pom.xml
Has no impact on main codebase as the main pom already has a maven enforcer plugin.
Other projects that inherit from the parent could be affected, but in those cases we either add an enforcer plugin to fcrepo-parent or (IMHO more appropriately) to those projects.

Remove prerequisite block

---

.travis.yml
fcrepo-http-api/src/main/java/org/fcrepo/http/api/ExternalContentHandler.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/FedoraToOCFLObjectIndexImpl.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/OCFLPersistentStorageUtils.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/FedoraToOCFLObjectIndexImplTest.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/MonotonicInstant.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/OCFLPersistentStorageSessionTest.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/UpdateNonRdfSourcePersisterTest.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/UpdateRDFSourcePersisterTest.java

**JIRA Ticket**: [FCREPO-3236](https://jira.lyrasis.org/browse/FCREPO-3236l)
* Configures Travis to perform a Windows build
* Fixes numerous file closing bugs that caused problems in WIndows
* Modifies tests that have assumptions about monotonically increasing dates/times.  Some servers apparently have coarse-grained clocks, so subsequent invocations of Instant.now() may produce equal values if they occur within the same "clock tick".
The most notable changes relate to tests that involve the ordering of time instants.  In some cases, ordering based on time is needed specifically to support tests, e.g. [here](https://github.com/birkland/fcrepo4/blob/windows-build/fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/OCFLPersistentStorageSession.java#L288).  In other cases, …

Enable WIndows build

---

fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/FedoraToOCFLObjectIndexUtilImpl.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/FedoraToOCFLObjectIndexUtilImplTest.java

**JIRA Ticket**: [FCREPO-3195](https://jira.lyrasis.org/browse/FCREPO-3195) && [FCREPO-3210](https://jira.lyrasis.org/browse/FCREPO-3210)
Fixes the problem @awoods reported with rebuilds not working correctly due to the difference between the Fedora object id and the OCFL object id. The rebuild logic now does not make any assumptions about the naming of sidecar files. It iterates over each sidecar in an ocfl object, if it discovers the object is an archival group, it updates the index mappings accordingly.
Follow @awoods steps as described in [FCREPO-3210](https://jira.lyrasis.org/browse/FCREPO-3210)
@awoods @bbpennel @dbernstein

Changed the name of the object metadata files

---

fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/WebACRolesProvider.java
fcrepo-auth-webac/src/test/java/org/fcrepo/integration/auth/webac/WebACRecipesIT.java

- Several @throws javadoc statements added to functions in WebACRecipesIT.java
- One @param javadoc statemnt added to WebACRolesProvider.java, line 102
Resolves https://jira.lyrasis.org/projects/FCREPO/issues/FCREPO-3026 (WebACRecipesIT.java)
WebACRolesProvider.java fix may or may not have a ticket
* * *
https://jira.lyrasis.org/projects/FCREPO/issues/FCREPO-3026
fix several javadoc warnings during the building of fcrepo-auth-webac
mvn clean install -pl fcrepo-auth-webac

Fixes javadoc warning during build

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/responses/StreamingBaseHtmlProvider.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraHtmlIT.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/ContainerImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/FedoraResourceImpl.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3222
**Note**: this PR only partially resolves the above ticket.
* Fixes the StreamingBaseHtmlProvider to use the correct `ldp:RDFSource` and `ldp:NonRDFSource` types for template matching. 
* Adds the `ldp:RDFSource` type to all `Container`s
* Re-instates one of the `FedoraHtmlIT` tests
Before the PR an RDF source (like a `ldp:BasicContainer`) would have only that type, after this PR it will also have the `ldp:RDFSource` type.

Add rdf:type ldp:RDFSource to Rdf source resources

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraVersioning.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/AbstractResourceIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersioningIT.java
fcrepo-http-api/src/test/resources/spring-test/test-container.xml
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/test/util/ContainerWrapper.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/operations/CreateVersionResourceOperation.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/operations/CreateVersionResourceOperationBuilder.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/operations/VersionResourceOperationFactory.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/services/VersionService.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/TransactionImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/FedoraResourceImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/ResourceFactoryImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/operations/CreateVersionResourceOperationBuilderImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/operations/CreateVersionResourceOperationImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/operations/VersionResourceOperationFactoryImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/VersionServiceImpl.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/services/VersionServiceImplTest.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/api/OCFLObjectSession.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/CreateVersionPersister.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/DefaultOCFLObjectSession.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/DefaultOCFLObjectSessionFactory.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/OCFLPersistentStorageSession.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/OCFLPersistentStorageUtils.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/CreateVersionPersisterTest.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/DefaultOCFLObjectSessionTest.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/OCFLPersistentStorageSessionTest.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/TestOcflObjectIndex.java

**JIRA Ticket**: [FCREPO-3232](https://jira.lyrasis.org/browse/FCREPO-3232)
Allows resources to be versioned on demand, and removes support for creating versions at specific timestamps.
`mvn jetty:run`
```
curl -u fedoraAdmin:fedoraAdmin http://localhost:8080/rest/version-test -H'Link: <http://www.w3.org/ns/ldp#BasicContainer>;rel="type"' -H'Link: <http://fedora.info/definitions/v4/repository#ArchivalGroup>;rel="type"' -v -H "Content-Type: text/turtle" -X PUT --data "<> <http://purl.org/dc/elements/1.1/title> 'AG Parent'"
curl -u fedoraAdmin:fedoraAdmin -v -H "Accept: text/turtle" http://localhost:8080/rest/version-test/fcr:versions
curl -u fedoraAdmin:fedoraAdmin -X POST -v http://localhost:8080/rest/version-test/fcr:versions
curl -u fedoraAdmin:fedoraAdmin -v -H "Accept: text/turtle" …
```

resource version creation

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraAcl.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraVersioning.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/responses/StreamingBaseHtmlProvider.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/services/HttpRdfService.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/services/HttpRdfServiceTest.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3161
Translates internal Fedora IDs back into external URIs when GETting a resource.
* Adds new translation function to the HttpRdfService.
* Modifies the `getContent` service to remove the RdfStream argument (as it was always an empty stream anyways)
* Modifies the `getResource` function in the StreamingHtmlProvider to properly get the resource.
Before the PR
1. PUT a resource.
1. GET the resource
1. Notice the address has the form "info:fedora/XXXX"
Build this PR
1. PUT a resource.
1. GET the resource
1. Notice the address has the form "http://localhost:8080/(fcrepo)/rest/XXXX"

Translate internal IDs to external URIs for GET

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/responses/StreamingBaseHtmlProvider.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraHtmlIT.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/RdfLexicon.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/RepositoryInitializer.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3222
**Note**: This PR does not completely resolve the above ticket
Adds the `http://fedora.info/definitions/v4/repository#RepositoryRoot` type to the repository root when it is initialized.
Also makes that type a static constant.
Before the PR, your root object had only the `ldp:BasicContainer` type.
After the PR, it also has the above mentioned `RepositoryRoot` type.

Add Repository Root type to Repository Root

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/responses/StreamingBaseHtmlProvider.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraHtmlIT.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/ContainerImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/FedoraResourceImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/NonRdfSourceDescriptionImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/ManagedPropertiesServiceImpl.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3222
Last PR for the above ticket
Creates a `getDescribedResource` method for `NonRdfSourceDescription`s so they can describe the correct resource.
Modifies the `managedPropertyService` to use the `getDescribedResource` to generate correct triples.
Cleans up some redundant logic in `StreamingBaseHtmlProvider`
Removes an un-used Predicate from `ContentExposingResource`, possibly might need to be re-added to a service later.
Uncomments the last test in `FedoraHtmlIT`
This test required the addition of a `createObject()` because it previously tried to 
```
PUT http://localhost:8080/1234-5678/file
```
But we currently  try to load `1234-5678` as a resource to be the parent, this will need to be fixed with the implementation of ghost …

Handle binary HTML test

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraBaseResource.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersioningIT.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/exception/InvalidMementoPathException.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/FedoraResourceImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/TimeMapImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/ManagedPropertiesServiceImpl.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/models/FedoraResourceImplTest.java

**JIRA Ticket**: [FCREPO-3245](https://jira.lyrasis.org/projects/FCREPO/issues/FCREPO-3245)
Adds the ability to retrieve mementos.
Test script:
```
curl -u fedoraAdmin:fedoraAdmin http://localhost:8080/rest/version-test-3 -H'Link: <http://www.w3.org/ns/ldp#BasicContainer>;rel="type"' -H'Link: <http://fedora.info/definitions/v4/repository#ArchivalGroup>;rel="type"' -v -H "Content-Type: text/turtle" -X PUT --data "<> <http://purl.org/dc/elements/1.1/title> 'AG Parent'"
curl -u fedoraAdmin:fedoraAdmin http://localhost:8080/rest/version-test-3/child1 -H "Link: <http://www.w3.org/ns/ldp#NonRDFSource>; rel=type" -v -H "Content-Type: text/plain" -X PUT --data-binary "testing"
curl -u fedoraAdmin:fedoraAdmin -H "Accept: text/turtle" -H "Accept-Datetime: Mon, 09 Mar 2020 17:00:00 GMT" -v …
```

added support for retrieving mementos

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/services/CreateResourceService.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/CreateResourceServiceImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/functions/FedoraIdUtils.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/services/CreateResourceServiceImplTest.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/DefaultOCFLObjectSession.java

Resolves: https://jira.lyrasis.org/browse/FCREPO-3259
Incremental resolution for: https://jira.lyrasis.org/browse/FCREPO-3223
Establishes resource URI in FedoraLDP for all creation requests
Fixes more FedoraLdpIT tests
1. PUT and POST of containers and binaries should work as before
1. PUT and POST of containers with RDF bodies should create the correct RDF subjects
1. POST with a slug of an existing resource should work as before
The following `curl` examples can be helpful in manually testing this pull-request
```
curl -XPUT localhost:8080/rest/put0
curl  localhost:8080/rest/put0
curl -XPOST localhost:8080/rest/ -H"slug: post0"
curl  localhost:8080/rest/post0
curl -XPOST localhost:8080/rest/ -H"slug: post0/1"
curl  localhost:8080/rest/post0/1
curl -i -XPUT --data-binary @binary.txt …
```

Ensure that <> in RDF bodies uses 'this' resource URI

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/NonRdfSourceDescriptionImpl.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3263
Fixes some headers on NonRDFSource descriptions
Makes the NonRdfSourceDescriptionImpl implement the NonRdfSourceDescription interface so it adds appropriate headers.
Also fixes an integration test to check for this link header and stop looking for a `describedby` triple in the body (its now only a Link header).
1. Make a binary
```
> curl -ufedoraAdmin:fedoraAdmin -XPOST -H"Slug: binary1" -H"Content-type: text/plain" --data-binary "This is some text" http://localhost:8080/rest
http://localhost:8080/rest/binary1
```
1. Get the `fcr:metadata` of the binary
````
> curl -ufedoraAdmin:fedoraAdmin -i http://localhost:8080/rest/binary1/fcr:metadata
Date: Wed, 01 Apr 2020 20:50:35 GMT
Set-Cookie: …
```

Make NonRdfSourceDescription implement the interface

---

fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/test/util/ContainerWrapper.java
fcrepo-parent/pom.xml

Updates to the way the `fcrepo.dynamic.test.port` is set for tests so that it works across intellij, eclipse, and maven.
* Changes syntax for setting property in ContainerWrapper
* Sets a default value for `fcrepo.dynamic.test.port`
Running `mvn clean install`
Running integration tests which use ContainerWrapper, such as FedoraLdpIT
You can also change the dynamic test port via commandline to verify that it still overrides the default:
`mvn verify -Dfcrepo.dynamic.test.port=8081 -pl fcrepo-http-api`
Similarly, you can set a custom value in your IDE by following the instructions for how to set environment variables during test runs for your IDE.
@pwinckles

Set default dynamic test port value with spring defaults

---

fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/TransactionManagerImpl.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/TransactionManagerImplTest.java

Fills in periodic cleanup of transactions.
Transactions are automatically rolled back if they expire.
Closed transactions will be remain available for retrieving status until their expiration time has passed. For transactions that expire automatically, they will stick around until the next garbage collection.
Transaction cleanup and tests.
You should be able to create a transaction, cancel it, check its status to see that it tells you it was rolled back, and then check its status again after 3 minutes to see that it now gives a 404.
Session cleanup timer currently just reuses the session timeout environment variable.

Periodic Transactions garbage collection

---

fcrepo-event-serialization/src/main/java/org/fcrepo/event/serialization/JsonLDEventMessage.java
fcrepo-event-serialization/src/test/java/org/fcrepo/event/serialization/EventSerializerTestBase.java
fcrepo-event-serialization/src/test/java/org/fcrepo/event/serialization/JsonLDSerializerTest.java

Fixes an NPE serializing events with null users.
Perform a mutating action in Fedora using an unauthenticated user and [an event should be generated](https://wiki.lyrasis.org/display/FEDORA51/How+to+Inspect+Event+Messages+Generated+by+Fedora). I do not know how preform actions in Fedora with an unauthenticated users, so I have not tried this myself, outside of a unit test.
@awoods

fix NPE in event serialization

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/OcflPersistenceIT.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/DeleteResourcePersister.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/OCFLPersistentStorageSession.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/OCFLPersistentStorageUtils.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/DeleteResourcePersisterTest.java

**JIRA Ticket**: https://jira.lyrasis.org/projects/FCREPO/issues/FCREPO-3278
When we write RDF we append the `.nt` extension to the id, but when we delete we just look for a file with the id name.
When trying to delete a child in an AG I got a 500 because it was trying to find a file called `test2`, but the actual file was `test2.nt`. 
This refactors the Delete operations to track whether we are deleting a RDFSource or NonRDFSource object.
Before the PR:
1. Create an Archival Group
```
curl -i -ufedoraAdmin:fedoraAdmin -H"Slug: parent" -H'Link: <http://fedora.info/definitions/v4/repository#ArchivalGroup>;rel="type"' -H"Content-type: text/turtle" -XPOST http://localhost:8080/rest
```
1. Create a child resource in the AG.
```
curl -i -ufedoraAdmin:fedoraAdmin -H"Slug: child" …
```

Use RDF extension when looking for files

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/OcflPersistenceIT.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/exceptionhandlers/TombstoneExceptionMapperTest.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/FedoraTypes.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/exception/TombstoneException.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/models/ResourceHeaders.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/services/VersionService.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/ResourceFactoryImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/TombstoneImpl.java
fcrepo-persistence-api/src/main/java/org/fcrepo/persistence/api/exceptions/PersistentStorageException.java
fcrepo-persistence-api/src/main/java/org/fcrepo/persistence/api/exceptions/PersistentStorageRuntimeException.java
fcrepo-persistence-common/src/main/java/org/fcrepo/persistence/common/ResourceHeadersImpl.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/DeleteResourcePersister.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/DeleteResourcePersisterTest.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3033
Changes how deletes work from an immediate purge to just removing the data files and setting the resources as deleted in their header files. This allows the ResourceFactory to determine if the requested resource was deleted and provide a tombstone link.
Before the PR all deleted objects would return a 404, now they should return a 410 GONE and include a Link header to a tombstone location. For NonRdfSourceDescription, TimeMaps and Mementos the link header refers to the original resource + `fcr:tombstone`

Change delete to remove data files and set headers to deleted.

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraAcl.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/FedoraLdpTest.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/StateTokensIT.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/services/ReplacePropertiesService.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/services/UpdatePropertiesService.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/ReplacePropertiesServiceImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/UpdatePropertiesServiceImpl.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/services/ReplacePropertiesServiceImplTest.java

**Implement PATCH for RDF**
* * *
**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3078
Adds support for PATCH and enables the following integration tests: 
- FedoraLdpIT.testUpdateObjectGraph()
- FedoraLdpIT.testDeleteMultipleMultiValuedProperties
- FedoraLdpIT.testPatchBinary()
- FedoraLdpIT.testPatchBinaryDescriptionWithBinaryProperties()
- FedoraLdpIT.testPatchBinaryNameAndType()
Basic PATCH support with 5 old integration tests brought online.  One vestigial integration test was removed.
```
curl -u fedoraAdmin:fedoraAdmin http://localhost:8080/rest/test1 -X PUT -H "Content-Type: text/turtle"
curl -i -XPATCH -H"Content-type:application/sparql-update" -ufedoraAdmin:fedoraAdmin -d "INSERT DATA {<> …
```

Adds support for PATCHing of RDF sources.

---

fcrepo-auth-common/src/test/java/org/fcrepo/auth/integration/AbstractResourceIT.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/test/util/ContainerWrapper.java
fcrepo-parent/pom.xml
fcrepo-webapp/src/test/java/org/fcrepo/integration/AbstractResourceIT.java
fcrepo-webapp/src/test/java/org/fcrepo/integration/SanityCheckIT.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3281
Re-enables dynamic port selection when the ITests are run from the CLI. ITests are still runnable using IDEs on port 8080.
1. Run the ITests from the cli while another process has 8080 bound
1. Run the ITests from Intellij or Eclipse
- [build-helper-maven-plugin cannot override a default port value](https://github.com/mojohaus/build-helper-maven-plugin/issues/17)
- [Intellij does not run build-helper-maven-plugin](https://youtrack.jetbrains.com/issue/IDEA-100272)
@awoods @bbpennel

re-enable dynamic port selection for cli ITest

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraAcl.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraAclIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/StateTokensIT.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/api/rdf/HttpIdentifierConverter.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/RdfLexicon.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/identifiers/FedoraId.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/services/WebacAclService.java
fcrepo-kernel-api/src/test/java/org/fcrepo/kernel/api/identifiers/FedoraIdTest.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/ContainmentIndexImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/NonRdfSourceDescriptionImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/ResourceFactoryImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/WebacAclImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/AbstractService.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/ReplacePropertiesServiceImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/WebacAclServiceImpl.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3134
Allows you to PUT/GET/DELETE and PATCH ACLs.
This does not ensure ACLs are enforced, that is next up.
I finally determined the issue with the FedoraId `resourceId` versus `fullId`. I need the resourceId to be the path as stored on disk. So for pretend things like fcr:tombstone and fcr:versions which don't exist it is the resource they hang off of, but for things that have an actual representation on disk (fcr:metadata and fcr:acl) we need their id (ie. info:fedora/object/fcr:metadata)
Try PUTting an ACL
Try GETting the ACL
Try PATCHing an ACL
Try DELETEing the ACL

Implement adding ACLs

---

fcrepo-parent/pom.xml

Resolves: https://jira.lyrasis.org/browse/FCREPO-3293
The pull-request only affects javadoc processing in Maven.
Since the fcrepo-configs project does not have any source files, all fcrepo modules that include fcrepo-configs as a dependency automatically search for fcrepo-configs javadocs during the Maven build.
Those javadocs do not exist... and an ERROR is displayed during build.
This pull-request tells Maven not to search for internal javadoc links.
This update does not appear to have any effect on whether links to local files are created in the javadocs... they did not appear to be generated before this update.
For example, observe that `ContainerRolesPrincipalProviderTest.java` has `@link` javadocs to internal files.
* Build the `master` branch of fcrepo
* Inspect the javadocs for: …

Configure maven-javadoc-plugin to not look for internal links

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/services/HttpRdfService.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/AbstractResourceIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java

Resolves: https://jira.lyrasis.org/browse/FCREPO-3297
Ensures that charset Content-Type parameter not included when mapping to RDF lang.
This bug was revealed when executing the Fedora API Test Suite.
Perform the test described in: https://jira.lyrasis.org/browse/FCREPO-3297

Ensure charset Content-Type parameter not included when mapping to RDF lang

---

.travis.yml
.travis/deploy.sh

Reverts some of the changes from the previous commit.
Uses `condition`  directive in the .travis.yml to ensure build does not happen on windows. 
I tested it successfully against the following branch:  https://github.com/fcrepo4/fcrepo4/tree/fix-broken-windows-build.  It succeeded here: https://travis-ci.com/github/fcrepo4/fcrepo4/jobs/329674431
I then simply changed the branch to `master`.

Fixes windows build issue.

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/Transactions.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/TransactionsIT.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/session/TransactionConstants.java

Resolves: https://jira.lyrasis.org/browse/FCREPO-3301
Removes the '/commit' suffix from the Transaction commit API.
The rationale for this is to be aligned with the rest of the transaction API:
- refresh transaction: POST tx-URI
- rollback transaction: DELETE tx-URI
- status of transaction: GET tx-URI
- Integration tests have been updated
- A manual test would be to verify the updated API by performing the following actions
```
curl -i -XPOST http://localhost:8080/rest/fcr:tx
curl -H"Atomic-ID: ${txURI}" -XPUT http://localhost:8080/rest/test
curl -XPUT ${txURI}
```

Remove '/commit' suffix from Transaction commit API

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersioningIT.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/api/OCFLObjectSession.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/DefaultOCFLObjectSessionFactory.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/OCFLPersistentStorageSessionTest.java

Resolves: https://jira.lyrasis.org/browse/FCREPO-3302
Changes the default versioning policy from autoversioning = `false`, to `true`.
1. Start Fedora with no versioning configuration
```
java -jar fcrepo-webapp/target/fcrepo-webapp-6.0.0-SNAPSHOT-jetty-console.jar --headless 
```
1. Create a resource
```
curl -i -XPUT localhost:8080/rest/test0
```
1. Inspect OCFL storage (/tmp/fcrepo.ocfl.storage.root.dir), looking for full OCFL version for the 'test0' resource
1. Stop Fedora
1. Start Fedora with autoversioning disabled:
```
java -Dfcrepo.autoversioning.enabled=false -jar fcrepo-webapp/target/fcrepo-webapp-6.0.0-SNAPSHOT-jetty-console.jar --headless 
```
1. Create a resource
```
curl -i -XPUT localhost:8080/rest/test1
```
1. Inspect OCFL storage (/tmp/fcrepo.ocfl.storage.root.dir), …

Change default versioning policy to autoversioning = true

---

fcrepo-http-api/src/test/resources/spring-test/fcrepo-config.xml
fcrepo-jms/src/test/resources/spring-test/fcrepo-config.xml
fcrepo-persistence-ocfl/pom.xml
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/RepositoryInitializer.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/OCFLPersistenceConfig.java
fcrepo-webapp/src/main/resources/spring/fcrepo-config.xml

Resolves: https://jira.lyrasis.org/browse/FCREPO-3283
**Ensures that containment index persists between reboots.**
* * *
**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3283
This PR changes the H2 database URL so that it persists the database to the fcrepo.ocfl.workdir.
In addition,  I moved the datasource and transaction manager configuration into the OCFLPersistenceConfig and removed the duplicate references from the spring configs.
1. Start up Fedora.
2. Add a resource. 
3. Stop Fedora 
4. Start up Fedora
5. Verify that the repository root contains the resource.

Ensures that containment index persists between reboots.

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3312
Properly removes any charset parts of Content-type header do make comparisons cleaner.
There is an integrated test, but essentially do a POST like
```
curl -ufedoraAdmin:fedoraAdmin -XPOST -H"Slug: object1" --data "<> a <http://example.org/Thing>" -H"Content-type: text/turtle" http://localhost:8080/rest
```
And one like
```
curl -ufedoraAdmin:fedoraAdmin -XPOST -H"Slug: object2" --data "<> a <http://example.org/Thing>" -H"Content-type: text/turtle;charset=utf-8" http://localhost:8080/rest
```
Then `GET` both the resources and notice that the second one (object2) is a NonRdfSource instead of a BasicContainer.
This PR should fix that.

Clean up content-types to remove charset.

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraFixity.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/services/FixityService.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/FixityServiceImpl.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3330
* Implements Want-Digest functionality
* Updates to the FixityService interface, removing some unused methods and adding the currently needed signature for getFixity
Fedora API Test Suite should now be passing for the 3.2.3 tests.

FCREPO-3330 - Implement Want-Digest

---

fcrepo-webapp/pom.xml
fcrepo-webapp/src/main/java/org/fcrepo/webapp/config/DatabaseConfig.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3347
The ITests in `fcrepo-webapp` now use an in memory H2.
1. Start the one-click Fedora with default settings
1. Build `fcrepo-webapp`
1. The ITests should not hang

change itests to use inmemory h2

---

fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/WebACRolesProvider.java
fcrepo-auth-webac/src/test/java/org/fcrepo/integration/auth/webac/WebACRecipesIT.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/FedoraLdpTest.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/models/FedoraResource.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/ContainerImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/FedoraResourceImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/NonRdfSourceDescriptionImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/TimeMapImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/WebacAclImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/ManagedPropertiesServiceImpl.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/models/FedoraResourceImplTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/models/TimeMapImplTest.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3279
Separates the inclusion of user defined types from system defined types. When getting types we now have to read the user's RDF and filter for types. 
Perhaps this information should be included in the header file and eventually be cached for quick access?
As a user could add or remove a `rdf:type` at any time it seems like we might need to do this at POST/PUT/PATCH? Perhaps in the persistence layer?
Not sure how this would expose itself through common use other than now the WebAC `acl:accessToClass` directives work because we get the user defined types back when we `getTypes()`

Simple attempt at including user types in getTypes

---

fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/WebACAuthorizingRealm.java
fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/WebACFilter.java
fcrepo-auth-webac/src/test/java/org/fcrepo/auth/webac/WebACFilterTest.java
fcrepo-auth-webac/src/test/java/org/fcrepo/integration/auth/webac/WebACRecipesIT.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3339
When passing a URI with an empty path segment into the WebAC Filter it ends up without roles, but we don't account for that so it does a stacktrace.
This now checks that it isn't null before proceeding, resulting in a 403 for the path with empty path segments.
Before this PR
1. Start a Fedora 5
1. Execute `curl -utestuser:testpass http://localhost:8080/rest/bob//bob`
1. See stacktrace.

Don't fail with stacktrace on empty path segment in WebAC Filter

---

fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/WebACAuthorizingRealm.java
fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/WebACFilter.java
fcrepo-auth-webac/src/test/java/org/fcrepo/integration/auth/webac/WebACRecipesIT.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3339
PR for 5.1 - https://github.com/fcrepo4/fcrepo4/pull/1704
Same as the 5.1 PR this tests the roles variable to make sure it isn't null before accessing it. But this also tries to use the URI to make a FedoraId which throws an Exception on empty path segments, so this properly throws a 400 Bad Request.
Before this PR
*  Start a Fedora 6
*  Execute `curl -utestuser:testpass http://localhost:8080/rest/bob//bob`
*  See stacktrace.
After this PR
* Repeat
* See 400 Bad Request.

Reject bad paths at Webac

---

fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/WebACFilter.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3358
When deployed in Tomcat the WebAC filter might get a path that is not part of the fedora instance at all. In which case the HttpIdentifierConverter will throw an IllegalArgumentException.
This PR just swallows that exception and lets the processing continue.
Deploy the WAR from main to a Tomcat instance.
Goto http://localhost:8080/fcrepo and see a 500 and stacktrace.
Pull in this PR, redeploy and try again.

Account for no fedora path in filter

---

fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/ContainmentIndexImpl.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3362
Fixes a containment index query so that it works on Postgres again.
Start Postgres:
```
docker run --name f6-postgres -e POSTGRES_USER=fcrepo-user -e POSTGRES_PASSWORD=fcrepo-pw -e POSTGRES_DB=fcrepo -p 5432:5432 -d postgres:12.3
```
Start Fedora:
```
mvn -Dfcrepo.home=target/fcrepo -Dfcrepo.db.url=jdbc:postgresql://localhost:5432/fcrepo -Dfcrepo.db.user=fcrepo-user -Dfcrepo.db.password=fcrepo-pw clean jetty:run
```
It should now start without throwing exceptions.

updated containment commit query to work on postgres

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/AbstractResourceIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/ClearDbTestExecutionListener.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/RebuildIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/RebuildTestExecutionListener.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/AbstractPersister.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/CreateNonRdfSourcePersister.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/CreateRDFSourcePersister.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/CreateVersionPersister.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/DefaultOCFLObjectSession.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/OCFLPersistentStorageUtils.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/integration/persistence/ocfl/impl/NonRdfSourcesPersistenceIT.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/CreateNonRdfSourcePersisterTest.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/CreateRDFSourcePersisterTest.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/DefaultOCFLObjectSessionTest.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/IndexBuilderImplTest.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/OCFLPersistentStorageSessionTest.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3317
I didn't read the ticket (which I had also written...) carefully enough, and I mistakenly updated how Fedora IDs are mapped to OCFL IDs before realizing that I was actually just supposed to be fixing a bug related to not using the mapping index when adding resources to AGs. So... I did them both.
The changes here are that now Fedora IDs are mapped directly to OCFL IDs, and the resource creation code correctly checks the mapping index for the OCFL ID when it adds a resources to an AG.
Start Fedora and create one or more resources. Check the OCFL storage root and you will find objects with OCFL IDs that match their corresponding Fedora ID.

changed the mapping of fedora ids to ocfl ids to be one-to-one

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraSearchIT.java
fcrepo-search-api/src/main/java/org/fcrepo/search/api/Condition.java
fcrepo-search-impl/src/main/java/org/fcrepo/search/impl/DbSearchIndexImpl.java
fcrepo-search-impl/src/main/resources/sql/default-search-index.sql

**Adds support for the mime_type and content_size parameters in simple search.**
* * *
**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3365 and https://jira.lyrasis.org/browse/FCREPO-3346
This PR adds support for content_size and mime_type fields.
It should be noted that currently only NonRDFSources have non-null content sizes and mime types.  If and when that changes, the search index will be updated accordingly without further code updates.
```
curl -u fedoraAdmin:fedoraAdmin  -X PUT http://localhost:8080/rest/test
curl -u fedoraAdmin:fedoraAdmin http://localhost:8080/rest/test -H "Slug:binary1" -H "Link: <http://www.w3.org/ns/ldp#NonRDFSource>; rel=type" -v -H "Content-Type: text/plain"  -X POST …
```

Adds support for the mime_type and content_size parameters in simple search.

---

fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/ContainmentIndex.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/ContainmentIndexImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/TransactionImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/TransactionManagerImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/observer/EventAccumulatorImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/AbstractService.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/ContainmentTriplesServiceImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/DeleteResourceServiceImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/PurgeResourceServiceImpl.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/ContainmentIndexImplTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/TransactionImplTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/models/ResourceFactoryImplTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/services/ContainmentTriplesServiceImplTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/services/CreateResourceServiceImplTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/services/DeleteResourceServiceImplTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/services/PurgeResourceServiceImplTest.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/api/IndexBuilder.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/api/OCFLObjectSession.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/api/OCFLObjectSessionFactory.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/DefaultOCFLObjectSession.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/DefaultOCFLObjectSessionFactory.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/IndexBuilderImpl.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/OCFLPersistentSessionManager.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/OCFLPersistentStorageSession.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/integration/persistence/ocfl/impl/NonRdfSourcesPersistenceIT.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/DefaultOCFLObjectSessionTest.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/IndexBuilderImplTest.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/OCFLPersistentSessionManagerTest.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/OCFLPersistentStorageSessionTest.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3350
1. Exceptions during rollbacks are logged; not rethrown
2. Staging directories are always cleaned up
3. General logic and logging cleanup 
Start F6:
```
mvn -Dfcrepo.home=target/fcrepo -Dfcrepo.log=DEBUG clean jetty:run
```
Create a resource in a transaction:
```
curl -u fedoraAdmin:fedoraAdmin -v -XPOST http://localhost:8080/rest/fcr:tx
txid=<TX_ID>
curl -u fedoraAdmin:fedoraAdmin -H"Atomic-ID: ${txid}" http://localhost:8080/rest/foo -H "Link: <http://www.w3.org/ns/ldp#NonRDFSource>; rel=type" -v -H "Content-Type: text/plain" -X PUT --data-binary "bar"
```
See the staging directory:
```
ls target/fcrepo/data/staging
```
Commit the transaction:
```
curl -u fedoraAdmin:fedoraAdmin -X PUT -v …
```

improved rollback logic

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraSearch.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraSearchIT.java
fcrepo-search-api/src/main/java/org/fcrepo/search/api/SearchParameters.java
fcrepo-search-impl/src/main/java/org/fcrepo/search/impl/DbSearchIndexImpl.java

**Adds support for order_by and order search parameters**
* * *
**JIRA Ticket**: Resolves: https://jira.lyrasis.org/browse/FCREPO-3343
You can now add order_by=<field> and order=<asc|desc> to your search querystring.
```
curl -u fedoraAdmin:fedoraAdmin http://localhost:8080/rest -H "Slug:b-text" -H "Link: <http://www.w3.org/ns/ldp#NonRDFSource>; rel=type" -v -H "Content-Type: text/plain"  -X POST --data "test" -i
curl -u fedoraAdmin:fedoraAdmin http://localhost:8080/rest -H "Slug:a-video" -H "Link: <http://www.w3.org/ns/ldp#NonRDFSource>; rel=type" -v -H "Content-Type: video/mpeg4"  -X POST --data "test" -i
curl -u fedoraAdmin:fedoraAdmin http://localhost:8080/rest/fcr:search | jq
curl -u fedoraAdmin:fedoraAdmin …
```

Adds support for order_by and order search parameters.

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraAcl.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/exceptionhandlers/TombstoneExceptionMapperTest.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/identifiers/FedoraId.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/services/VersionService.java
fcrepo-kernel-api/src/test/java/org/fcrepo/kernel/api/identifiers/FedoraIdTest.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/ContainmentIndexImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/BinaryImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/FedoraResourceImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/NonRdfSourceDescriptionImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/ResourceFactoryImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/TimeMapImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/WebacAclImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/CreateResourceServiceImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/WebacAclServiceImpl.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/models/FedoraResourceImplTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/models/ResourceFactoryImplTest.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/AbstractPersister.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/CreateNonRdfSourcePersister.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/CreateRDFSourcePersister.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3381
Refactors FedoarId in attempt to make it easier to understand. Changes:
1. `resolve()` now only adds a single child to the end of the original id's base id. The old method had extremely confusing behavior depending on whether of not the joining part was prefixed with a `/`.
2. Added a bunch of `asX()` methods that can be use to create versions of the original id that reference a related "sub" resource, like a memento or binary description.
Fire it up and create a resource. There's no new functionality to test or broken functionality that is now fixed that I know of.

refactored FedoraId in attempt to make it slightly easier to understand

---

pom.xml

**JIRA Ticket**: n/a
Follow-on to https://github.com/fcrepo4/fcrepo4/pull/1707
Adds the security-versions check
Build it and see the plugin report (it does NOT halt on an identified vulnerability)
i.e.
```
> mvn clean install
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] Fedora Commons :: Parent POM                                       [pom]
[INFO] Fedora Commons                                                     [pom]
[INFO] Fedora Repository Kernel API                                    [bundle]
[INFO] Fedora Repository Persistence API Module                        [bundle]
[INFO] Fedora Repository Persistence Common Module                     [bundle]
[INFO] Fedora Repository …
```

Add https://github.com/victims/maven-security-versions plugin

---

fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/DefaultOcflObjectSessionFactory.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/OcflPersistentSessionManager.java

**JIRA Ticket**: na
Does not per-emptively create staging directories. Previously, these empty directories would linger on the filesystem until the transaction that created them expired. Primarily a cosmetic issue.
```
mvn -Dfcrepo.home=target/fcrepo clean jetty:run
curl -u fedoraAdmin:fedoraAdmin http://localhost:8080/rest/foo -H "Link: <http://www.w3.org/ns/ldp#NonRDFSource>; rel=type" -v -H "Content-Type: text/plain" -X PUT --data-binary "bar"
curl -u fedoraAdmin:fedoraAdmin -v http://localhost:8080/rest/foo
```
Check the staging directory and you won't see any directories.

only create staging directories when resources are written

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/responses/StreamingBaseHtmlProvider.java
fcrepo-http-api/src/main/resources/views/common-metadata.vsl
fcrepo-http-api/src/main/resources/views/common-node-actions.vsl
fcrepo-webapp/src/main/webapp/static/js/common.js

Resolves: https://jira.lyrasis.org/browse/FCREPO-3336
This pull-requests adds the ability to create `Archival Groups` in the HTML UI.
1. Start Fedora
1. Browse to the HTML UI
1. Create a new resource by selecting the "archival group" choice from the **Type** drop-down
- Notice the new resource's HTML page indicates that it is an "Archival Group"
1. In the OCFL file system, navigate to the newly created resource
- Notice the property: `"archivalGroup":true` is present

Add support for creation of archival-groups in HTML UI

---

.gitignore
fcrepo-configs/src/main/java/org/fcrepo/config/FedoraPropsConfig.java

Resolves: https://jira.lyrasis.org/browse/FCREPO-3398
This pull-request changes the default Fedora data/home directory from `fcrepo` to `fcrepo-home`.
- Run the one-click application and see the Fedora home directory: `fcrepo-home`

Change default home Fedora data dir to `fcrepo-home`

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ExternalContentHandler.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/ExternalContentPathValidator.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/ExternalContentPathValidatorTest.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/FedoraLdpTest.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/ExternalContentHandlerIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/ExternalContentPathValidatorIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersioningIT.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/exception/ExternalMessageBodyException.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/models/Binary.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/models/ExternalContent.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/BinaryImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/CreateResourceServiceImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/ReplaceBinariesServiceImpl.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/services/CreateResourceServiceImplTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/services/ReplaceBinariesServiceImplTest.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/AbstractNonRdfSourcePersister.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/DeleteResourcePersister.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/UpdateNonRdfSourcePersister.java
pom.xml

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3239
Also addresses:
* https://jira.lyrasis.org/browse/FCREPO-3219
* https://jira.lyrasis.org/browse/FCREPO-3218
Implements external binaries in frepo6
* Persists PROXY and REDIRECT external binaries as header only records
* Implements Want-Digest and transmission fixity for external binaries
* Handles switching binaries between internal and external, cleaning up headers and content as needed
* Expands external binary tests to cover replacing external binaries and transmission fixity
* Returns a 4xx on creation if fedora cannot find or access the external content in all cases.
* Enables disabled external binary tests
Aside from updated tests, it can be manually tested as follows:
```
mvn -Dfcrepo.home=target/fcrepo …
```

FCREPO-3239 - External Binary implementation

---

pom.xml

**Backport of**: https://github.com/fcrepo4/fcrepo4/pull/1707
Removes the victims plugin for the 5.1.x branch since it does not work anymore.

Fedora 5.1.x - Remove the victims plugin

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/services/HttpRdfService.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/services/SparqlTranslateVisitor.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/FedoraLdpTest.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/services/HttpRdfServiceTest.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/exceptionhandlers/PathNotFoundRuntimeExceptionMapper.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/exception/PathNotFoundRuntimeException.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3311
We use the HttpRdfService on PUT/POST requests to ensure RDF has URIs for items in the repository converted to internal IDs. But for Sparql we didn't do this. So while the RDF appears correct the repository doesn't realize it is referencing an item inside the repository.
This adds an "UpdateVisitor" to generate a new Sparql request based on the old one but with any in domain URIs converted to internal IDs
I'm not sure if this is testable except by checking the actual RDF stored in the OCFL objects.
1. Create a RDFSource object.
`curl -i -ufedoraAdmin:fedoraAdmin -XPOST http://localhost:8080/rest `
1. Patch the resource with some internal IDs.
`curl -ufedoraAdmin:fedoraAdmin -i -XPATCH -d"INSERT DATA { …

Rewrite PATCH request repository URIs to internal IDs

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraSearch.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/api/rdf/HttpIdentifierConverter.java
fcrepo-jms/src/main/java/org/fcrepo/jms/AbstractJMSPublisher.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/TransactionImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/TransactionManagerImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/observer/EventAccumulatorImpl.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/OcflPersistentStorageSession.java
fcrepo-webapp/src/main/resources/logback.xml

..and finetune the logging levels across the codebase.
Resolves: https://jira.lyrasis.org/browse/FCREPO-3415
- Start Fedora and see if you like the default logging
- Start Fedora with different logging levels (other than the default, INFO) for specific modules 
- e.g. `-Dfcrepo.log.storage=DEBUG`

Ensure that all Fedora modules are included in the default logback.xml

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/BinaryImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/ContainerImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/FedoraResourceImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/ManagedPropertiesServiceImpl.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/models/FedoraResourceImplTest.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3269
Adds in some remaining server managed triples for Binaries (and actually for Containers too).
1. Create a binary
```
curl -i -ufedoraAdmin:fedoraAdmin -H"Content-type: text/plain" -d"Some example text" -XPOST -H"Slug: binary" http://localhost:8080/rest
```
1. Get the NonRdfSourceDescription
```
curl -i -ufedoraAdmin:fedoraAdmin http://localhost:8080/rest/binary
```
1.  Before this PR see:
```
<http://localhost:8081/rest/binary>
fedora:created "2020-04-01T20:50:09.916295Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> ;
fedora:lastModified "2020-04-01T20:50:09.916295Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> ;
rdf:type ldp:NonRDFSource ;
fedora:hasFixityService <http://localhost:8081/rest/binary/fcr:fixity> .
```
1. After …

Add remaining SMTs

---

fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/ContainmentIndex.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/models/FedoraResource.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/models/ResourceFactory.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/ContainmentIndexImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/ContainerImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/FedoraResourceImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/ResourceFactoryImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/ContainmentTriplesServiceImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/DeleteResourceServiceImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/PurgeResourceServiceImpl.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/ContainmentIndexImplTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/models/ContainerImplTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/models/FedoraResourceImplTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/models/ResourceFactoryImplTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/services/ContainmentTriplesServiceImplTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/services/CreateResourceServiceImplTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/services/DeleteResourceServiceImplTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/services/PurgeResourceServiceImplTest.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3431
* Implements getChildren for FedoraResource, Container and ResourceFactory
* All ContainmentIndex methods now take FedoraIds instead of FedoraResource.
* Deprecates unused `getChild` method (which seems modeshape oriented)
New tests were added. No functional changes.

FCREPO-3431 - Implement getChildren

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-jms/src/test/java/org/fcrepo/integration/jms/observer/AbstractJmsIT.java
fcrepo-jms/src/test/resources/spring-test/fcrepo-config.xml
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/services/ReferenceService.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/TransactionImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/TransactionManagerImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/AbstractService.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/CreateResourceServiceImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/DeleteResourceServiceImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/ReferenceServiceImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/ReplacePropertiesServiceImpl.java
fcrepo-kernel-impl/src/main/resources/sql/default-references.sql
fcrepo-kernel-impl/src/main/resources/sql/mysql-references.sql
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/TransactionImplTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/TransactionManagerImplTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/services/CreateResourceServiceImplTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/services/DeleteResourceServiceImplTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/services/ReferenceServiceImplTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/services/ReplacePropertiesServiceImplTest.java
fcrepo-kernel-impl/src/test/resources/containmentIndexTest.xml
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/FcrepoOcflObjectSessionWrapper.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/IndexBuilderImpl.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/IndexBuilderImplTest.java
fcrepo-persistence-ocfl/src/test/resources/spring-test/fcrepo-config.xml

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3166
Adds an API and implementation of a new service to parse incoming RDF for internal references and stores them in a new index, then allows this index to be queried.
1. Create a resource.
1. Create another resource with any reference to the first ie. `<> <http://awoods.com/pointsTo> <http://localhost:8080/rest/firstResource>`
1. Get the first resource, see no inbound reference triples
1. Get the first resource with the header `Prefer: return=representation; include="http://fedora.info/definitions/fcrepo#PreferInboundReferences"`, see the inbound reference.
For binaries when requesting the inbound references on the `fcr:metadata` endpoint you will get both references to the actual binary URI and the `fcr:metadata` URI.
**Note**: I …

Inbound references service

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/services/HttpRdfService.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/FedoraLdpTest.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/exceptionhandlers/UnsupportedMediaTypeExceptionMapper.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/exception/UnsupportedMediaTypeException.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3429
Previously we allowed people to POST/PUT with application/sparql-update. This is no longer supported and as such we need to reject the mimetype. This adds a new Exception and Mapper and throws it from the HttpRdfService if we can't get a Jena RDF format from the mimeType.
Also corrects some tickets and removes an old test.
Before the PR.
Post with application/sparql-update
```
curl -i -ufedoraAdmin:fedoraAdmin -H"Content-type: application/sparql-update" -d"INSERT { <> <http://purl.org/dc/elements/1.1/title> \"title\" } WHERE {}" -XPOST http://localhost:8080/rest
```
Get a `500 Server Error`.
Pull in this PR.
Do the same thing, get a `415 Unsupported Media Type` 

Reject sparql-update as rdf for object creation.

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/domain/PreferTag.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/domain/ldp/LdpPreferTag.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/RdfLexicon.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3037
Adds a check for specifically omitting a minimal container representation to exclude user RDF.
Also defines some LDP prefer headers in RdfLexicon for consistency and modifies some tests.
With an object like
```
> curl -ufedoraAdmin:fedoraAdmin http://localhost:8080/rest/userRdf 
@prefix rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix fedora:  <http://fedora.info/definitions/v4/repository#> .
@prefix ldp:  <http://www.w3.org/ns/ldp#> .
@prefix dc:  <http://purl.org/dc/elements/1.1/> .
<http://localhost:8080/rest/userRdf>
dc:title               "Some title" ;
dc:author              "Some author" ;
fedora:created         "2020-09-11T17:51:46.806653Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> ;
fedora:lastModified …
```

Support omit minimal container to restrict user rdf

---

fcrepo-event-serialization/src/main/java/org/fcrepo/event/serialization/JsonLDEventMessage.java
fcrepo-event-serialization/src/test/java/org/fcrepo/event/serialization/JsonLDSerializerTest.java
fcrepo-jms/src/main/java/org/fcrepo/jms/AbstractJMSPublisher.java
fcrepo-jms/src/test/java/org/fcrepo/integration/jms/observer/AbstractJmsIT.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/services/ReferenceService.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/observer/ResourceOperationEventBuilder.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/operations/ReferenceOperation.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/operations/ReferenceOperationBuilder.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/AbstractService.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/CreateResourceServiceImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/ReferenceServiceImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/ReplacePropertiesServiceImpl.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/services/ReferenceServiceImplTest.java
fcrepo-kernel-impl/src/test/resources/containmentIndexTest.xml
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/IndexBuilderImpl.java

Fix AbstractJmsIT to stop checking message headers.
Fix JsonLdEventMessage to have only one type for Object and Actor.
**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3434
Implements the INBOUND_REFERENCE event type when you reference an item.
Fixes the fcrepo-jms tests to stop relying on the message headers and actually decode the body of the message.
1. Setup a JMSClient to listen to Fedora.
1. Create two resources.
1. Make one reference the other ie. `<http://localhost:8080/rest/first> <http://example.org/pointsTo> <http://localhost:8080/rest/second>`
1. Check your JMSClient for a Follow event, like
```
{"id":"urn:uuid:8cea1bab-c1c1-4b9b-ac5d-a666aa6abad1","type":["Follow"],"name":"refer to resource","published":"2020-09-25T20:57:08.641850Z","actor":[{"type":"Person","id":"info: …
```

Refactor referenceService to emit events.

---

fcrepo-configs/src/main/java/org/fcrepo/config/DatabaseConfig.java

Below are the newly configurable properties and their defaults
fcrepo.db.connection.checkout.timeout: 10000  (ms) (unchanged)
fcrepo.db.connection.idle.test.period: 0 (sec) (unchanged)
fcrepo.db.connection.test.on.checkout: true  (new)
With this new configuration, connections are tested on checkout by default
using the JDBC Connection isValid() operation.
Idle uncheckout connections will not be tested (c3po default behavior), but
in case we want to change it via system properties we can.
Resolves: https://jira.lyrasis.org/browse/FCREPO-3401
*Adds additional data source configuration parameters.**
* * *
**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3401
Adds additional data source configuration …

Adds additional data source configuration parameters as well as changes the defaults of select properties

---

fcrepo-configs/pom.xml
fcrepo-configs/src/main/java/org/fcrepo/config/MetricsConfig.java
fcrepo-http-api/pom.xml
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraAcl.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraFixity.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraSearch.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraTombstones.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraVersioning.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/Transactions.java
fcrepo-http-commons/pom.xml
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/FedoraApplication.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/PrometheusMetricsServlet.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/metrics/MicrometerFeature.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/metrics/PrometheusMetricsServlet.java
fcrepo-webapp/src/main/jetty-console/WEB-INF/web.xml
fcrepo-webapp/src/main/webapp/WEB-INF/web.xml
pom.xml

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3443
This PR is intended to demonstration a possible metrics integration. It uses [Micrometer](https://micrometer.io/) for collecting metrics within the app and reports them to [Prometheus](https://prometheus.io/). Micrometer could also be configured to report to any number of alternative metrics backends. Prometheus is very powerful, though it is not the most intuitive to use.
Regardless, if we do want to support capturing metrics, I think it would likely make sense to offer a number of different backends so that the metrics could more easily integrate with whatever service an institution is already using. For example, [Graphite](https://graphiteapp.org/) is also popular. However, the bigger question is in regards to if we want to …

add metrics framework

---

fcrepo-configs/src/main/java/org/fcrepo/config/OcflPropsConfig.java
fcrepo-configs/src/main/java/org/fcrepo/config/Storage.java
fcrepo-persistence-ocfl/pom.xml
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/OcflPersistenceConfig.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/OcflPersistentStorageUtils.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/IndexBuilderImplTest.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/OcflPersistentStorageSessionTest.java
pom.xml

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3436
Allows you to configure Fedora to write directly to S3 rather than the filesystem.
Note: This integration seems VERY SLOW. I have not done any investigation into the root cause, but I suspect it's a combination of inefficiencies in Fedora (eg repeatedly reading the resource headers) and inefficiencies in the ocfl-java S3 implementation, which works but is not as optimized as it could be.
Another note, ocfl-java only supports H2 and Postgres, and really the H2 support only exists for testing. The database is necessary to work around eventual consistency issues. After the troubles I've seen here when working with MySQL, I'm less inclined to add support for additional databases...
1. Create a AWS user and bucket with the [necessary …

get fedora working against s3

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3445
For one call in `getContent` we call the `resource()` method which in a version listing you actually get the Original Resource, which then breaks the StreamingBaseHtmlProvider.
Assuming auto versioning.
Create a resource in the HTML UI (or curl), then check the versions page for that resource with a web browser. You should see the initial version.
Make a change to the resource (again either the HTML UI or curl) and check the versions page again. You should see 2 versions, etc.

Use the resource passed into getContent

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraBaseResource.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/FedoraLdpTest.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/exceptionhandlers/GhostNodeExceptionMapper.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/ContainmentIndex.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/exception/GhostNodeException.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/models/ResourceFactory.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/models/ResourceHelper.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/ContainmentIndexImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/ContainmentIndexMetrics.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/ResourceFactoryImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/ResourceHelperImpl.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/ContainmentIndexImplTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/models/ResourceFactoryImplTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/models/ResourceHelperImplTest.java
fcrepo-search-impl/src/main/java/org/fcrepo/search/impl/SearchIndexUpdater.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3256
Makes it so you can't create a real resource at the address of a ghost node.
Testing steps in the ticket or
1. Create a resource `a/b/c` - `curl -i -ufedoraAdmin:fedoraAdmin -XPUT http://localhost:8080/rest/a/b/c`
1. Try to create resource `a/b` - `curl -i -ufedoraAdmin:fedoraAdmin -XPUT http://localhost:8080/rest/a/b`
Without this PR get a `201 Created`, with this PR get a `409 Conflict`.
1. Delete resource `a/b/c` - `curl -i -ufedoraAdmin:fedoraAdmin -XDELETE http://localhost:8080/rest/a/b/c`
1. With the PR, you still can't create at `a/b` due to the tombstone. Running step 2 still returns a 409 Conflict.
1. Delete the `a/b/c/fcr:tombstone` - `curl -i -ufedoraAdmin:fedoraAdmin -XDELETE …

Make ghost nodes immutable - FCREPO-3256

---

fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/TransactionManagerImpl.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/TransactionManagerImplTest.java
fcrepo-persistence-api/src/main/java/org/fcrepo/persistence/api/PersistentStorageSessionManager.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/OcflPersistentSessionManager.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/OcflPersistentSessionManagerTest.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3454
Removes the storage session that's associated to a transaction as part of transaction cleanup
Everything should work the same as before but there should be a storage session related memory leak

fix storage session leak

---

fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/BinaryImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/ContainerImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/FedoraResourceImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/NonRdfSourceDescriptionImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/ResourceFactoryImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/TimeMapImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/TombstoneImpl.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/models/FedoraResourceImplTest.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3452
My original analysis was slightly off. The types _are_ cached in the FedoraResource currently. I was confused because I saw them being loaded so many times when I debugging, but this is just because the FedoraResource itself is not cached.
So, all this PR does is remove the need to reload the resource headers when computing system types, and moves the type URIs themselves to static fields.
Everything should work the same as before, but with a few fewer loads of the resource headers.

do not reload resource headers when computing types

---

fcrepo-auth-common/src/test/resources/application.properties
fcrepo-auth-webac/src/test/resources/application.properties
fcrepo-auth-webac/src/test/resources/spring-test/application.properties
fcrepo-configs/src/main/java/org/fcrepo/config/MetricsConfig.java
fcrepo-configs/src/main/java/org/fcrepo/config/OcflPropsConfig.java
fcrepo-http-api/src/test/resources/application.properties
fcrepo-jms/src/test/resources/application.properties
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/FcrepoOcflObjectSessionWrapper.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/OcflPersistenceConfig.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/OcflPersistentSessionManager.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/ResourceHeadersAdapter.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/IndexBuilderImplTest.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/OcflPersistentStorageSessionTest.java
fcrepo-persistence-ocfl/src/test/resources/application.properties

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3453
This PR depends on this PR https://github.com/fcrepo-exts/fcrepo-storage-ocfl/pull/11, and it will not build until the other PR has been committed.
Configures Fedora to cache resource headers by default. Throughout the lifetime of a request a resource's headers are read repeatedly. This cache is intended to reduce some of this overhead at the cost of memory. This is particularly important when the storage layer is in S3.
There should be no behavior changes in Fedora. If you run Fedora with either of the following flags you will be able to see the cache in action: `-Dfcrepo.log.storage=trace -Dfcrepo.metrics.enable=true`.
The first should produce caching related log messages, and the second enables metrics collection. The cache …

configured to use resource headers cache

---

pom.xml

Upgrades the version of ocfl-java. This must be merged in conjunction with https://github.com/fcrepo-exts/fcrepo-storage-ocfl/pull/12. This will fix the ocfl-java memory leak that was recently discovered.
Run the load test and you should not see resource accumulation in the InMemoryObjectLock.

upgrade ocfl-java version

---

fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/ResourceHelperImpl.java
fcrepo-persistence-ocfl/pom.xml
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/OcflPersistentStorageSession.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/OcflPersistentStorageSessionTest.java
pom.xml

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3456
The read-only session now expires object sessions that have not been accessed within 10 minutes.
Fedora should work the same, and the load test should not see the accumulation of object sessions within the read-only session.

read-only session expires old object sessions

---

fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/ContainmentIndexImpl.java
fcrepo-kernel-impl/src/main/resources/sql/postgres-containment.sql

**JIRA Ticket**: n/a
Tries to add an additional index for Postgres if your LC_TYPE is not C so that LIKE queries can use this index.
Build and run and watch that the `hasResourcesStartingWith` does not slow incrementally with database size.
@fcrepo/committers (@awoods)

Add an additional index if the lc_collate is not C

---

fcrepo-http-api/pom.xml
fcrepo-http-api/src/main/java/org/fcrepo/http/api/responses/StreamingBaseHtmlProvider.java
fcrepo-http-api/src/main/resources/views/common-node-actions.vsl
fcrepo-webapp/src/main/webapp/static/css/common.css

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3446
If autoversioning is enabled (as it is by default) then the "Create Version" button is replaced by the text "Autoversioning is enabled. Versions are created with each update to a resource." 
Versioning of binaries is still disabled from the HTML UI, though as binary and binary description versioning is now tied together we might be able to enable this.
Also includes a little CSS change as long binary checksum were breaking the HTML.
Build this branch and run it. Make a container and see the new message.
Stop Fedora
Run again with `-Dfcrepo.autoversioning.enabled=false` and see the same object show the "Create Version" button.
The button **only** creates a version if something has changed. We will need to make sure this is clear …

Reflect autoversioning state in HTML UI

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/services/HttpRdfService.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/services/SparqlTranslateVisitor.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/AbstractResourceIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/exceptionhandlers/ConstraintExceptionMapper.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/exceptionhandlers/MultipleConstraintViolationExceptionMapper.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/exception/MultipleConstraintViolationException.java
fcrepo-webapp/src/test/java/org/fcrepo/webapp/ConstraintExceptionsTest.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3257
Combines all exceptions related to internal constraints around server managed types and properties together into one response.
Previously if you put more than one invalid statement in your RDF you would only get an error for the first statement to get checked.
Now you will get all messages together.
This also modifies the old behaviour if your RDF mixes altering managed types and managed properties. In Fedora 5 you get a constrainedby link to a [generic description](https://github.com/fcrepo/fcrepo/blob/6d902757fc7d6d09ccbb77c51cdfb3fee6d60c7c/fcrepo-webapp/src/main/webapp/static/constraints/ConstraintViolationException.rdf).
In this PR you will actually get 2 constrainedby link headers.
Fedora 5:
```
> curl -i …
```

Combine all SMT exceptions together and provide valid constraints

---

.travis.yml

Fix the travis postgres build. The build broke because travis decided to include the newly released Postgres 13 in the image by default.
The ci build should pass.

Fix travis postgres issues

---

fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/exceptionhandlers/TombstoneExceptionMapper.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3515
Doesn't dump the stacktrace when you get a Tombstone (and we throw a TombstoneException). Instead just log the message.
Start Fedora with DEBUG logging
Create a resource.
Delete the resource
Get the resource.
Check the Fedora logs.
Before see:
```
org.fcrepo.kernel.api.exception.TombstoneException: Discovered tombstone resource at /box, departed at: 2020-11-06T19:15:16.005957Z
at org.fcrepo.http.api.ContentExposingResource.getResourceFromPath(ContentExposingResource.java:1059)
at org.fcrepo.http.api.ContentExposingResource.resource(ContentExposingResource.java:437)
at org.fcrepo.http.api.FedoraLdp.getResource(FedoraLdp.java:258)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at …
```

Don't dump a stacktrace for a tombstone

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/FedoraLdpTest.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/models/ResourceHeaders.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/operations/CreateNonRdfSourceOperationBuilder.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/operations/NonRdfSourceOperation.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/operations/NonRdfSourceOperationBuilder.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/services/CreateResourceService.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/services/ReplaceBinariesService.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/operations/AbstractNonRdfSourceOperation.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/operations/AbstractNonRdfSourceOperationBuilder.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/operations/CreateNonRdfSourceOperationBuilderImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/CreateResourceServiceImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/ReplaceBinariesServiceImpl.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/operations/CreateNonRdfSourceOperationBuilderTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/operations/UpdateNonRdfSourceOperationBuilderTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/services/CreateResourceServiceImplTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/services/ReplaceBinariesServiceImplTest.java
fcrepo-persistence-common/src/main/java/org/fcrepo/persistence/common/ResourceHeaderUtils.java
fcrepo-persistence-common/src/main/java/org/fcrepo/persistence/common/ResourceHeadersImpl.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/AbstractPersister.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/ResourceHeadersAdapter.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/integration/persistence/ocfl/impl/NonRdfSourcesPersistenceIT.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/CreateNonRdfSourcePersisterTest.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/OcflPersistentStorageSessionTest.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/UpdateNonRdfSourcePersisterTest.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3524
**This PR depends on https://github.com/fcrepo/fcrepo-storage-ocfl/pull/20**
Changes the type of `contentSize` from `Long` to `long`. `-1L` indicates that content size is unknown or there is no content. This will avoid further NPE bugs related to content size.
No visible changes. Everything should still work. If you have migrated content with a null `contentSize`, such as in the linked ticket, then you should not get NPEs.

changed content size to long

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersioningIT.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3479
Removed `DELETE` from the `Allow` header for Mementos.
Create a resource, get the initial memento. 
The allow will be `GET,HEAD,OPTIONS,DELETE`
Pull in this PR, rebuild, restart.
Get the same Memento, allow will be `GET,HEAD,OPTIONS`
Also the API testsuite now skips test 4.2.6

Remove DELETE from Memento Allow header

---

fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/WebACAuthorizingRealm.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraAcl.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraBaseResource.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/FedoraLdpTest.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraTombstonesIT.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/ContainmentIndex.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/models/ResourceHelper.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/ContainmentIndexImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/ContainmentIndexMetrics.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/ResourceHelperImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/CreateResourceServiceImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/ReferenceServiceImpl.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/ContainmentIndexImplTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/models/ResourceHelperImplTest.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/IndexBuilderImpl.java
fcrepo-search-impl/src/main/java/org/fcrepo/search/impl/SearchIndexUpdater.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3523
Currently you can create a resource as a child of a tombstone because when looking for parents we don't check for deleted resources. The changes here make it so you can (depending on the need) check for only active resources or check for both active or deleted resources.
In some use cases (like the search index and inbound references) we don't want deleted resources to count, but in the CRUD areas a tombstone is a thing and should be returned and dealt with.
The simplest use case is (as described in the ticket)
* `curl -i -ufedoraAdmin:fedoraAdmin -XPUT http://localhost:8080/rest/box`
* `curl -i -ufedoraAdmin:fedoraAdmin -XDELETE http://localhost:8080/rest/box`
* `curl -i -ufedoraAdmin:fedoraAdmin -XPUT …

Check for deleted resources before creating new ones

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/FedoraResourceImpl.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/RepositoryInitializer.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3422
Currently when the repository is reinitialized the root resource is created with the RepositoryRoot type as user rdf. So it returns as a user type. This removes that and returns it as a system type.
Before GETting the root resource should return the triple in the RDF but not the headers. Now it should appear as both.

Return RepositoryRoot as system type

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersioningIT.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/CreateVersionPersister.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/FcrepoOcflObjectSessionWrapper.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/CreateVersionPersisterTest.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3465
This PR depends on https://github.com/fcrepo/fcrepo-storage-ocfl/pull/19
Changes the memento creation behavior so that it always creates a memento on a resource regardless of whether or not that resource has outstanding, unversioned changes. This is inline with the behavior in F5.
```
curl -u fedoraAdmin:fedoraAdmin http://localhost:8080/rest/box -H'Link: <http://www.w3.org/ns/ldp#BasicContainer>;rel="type"' -v -H "Content-Type: text/turtle" -X PUT --data "<> <http://purl.org/dc/elements/1.1/title> 'Box'"
curl -u fedoraAdmin:fedoraAdmin http://localhost:8080/rest/box/fcr:versions
curl -u fedoraAdmin:fedoraAdmin -X POST http://localhost:8080/rest/box/fcr:versions
curl -u fedoraAdmin:fedoraAdmin …
```

always create a memento regardless of resource state

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersioningIT.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3223
Another iteration on re-enabling integration tests.
Ensure the changes made to the tests (or application) are correct.
In this exciting episode:
1. When adding a blank node to a resource's graph, we no longer allow you to directly access the blank node as a URI (I was not aware you could ever do that). Instead we just check that the blank node is part of the resource's graph.
1. We ensure that GET -> PUT interactions omit server managed triples.
1. We change the expectations for binary and binary description ETags. They used to be separate and so changing one would not affect the other. They now a linked together.

More integration tests

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/responses/StreamingBaseHtmlProvider.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraAclIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersioningIT.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3424
HTML UI performs extra processing to allow interactions so we load the resource we are looking at, for "fake" resources like the default ACL this fails to load. Handle this more cleanly.
Build PR, browse to `http://localhost:8080/rest/fcr:acl` with a web browser. See the results. Use cURL for alternate serializations and still see the results. Put a new default ACL and see it displays too.

Display root resource/ACL correctly in HTML UI

---

fcrepo-search-impl/src/main/java/org/fcrepo/search/impl/DbSearchIndexImpl.java

Removes need to disable triggers on PostgresQL which was causing a problem database administrator does not have super admin control as is the case on AWS RDS.
**JIRA Ticket**:  https://jira.lyrasis.org/browse/FCREPO-3540
No functional change.  
* Removes the need to disable triggers on truncation in postgresql
Integration tests should already cover it.
I build a new docker image and deployed it to fcrepo/fcrepo:6.0.0-SNAPSHOT-3540-test and verified that postgresql now works when I deploy using this PR of fcrepo-aws-deployer: https://github.com/fcrepo-exts/fcrepo-aws-deployer/pull/3
You can test these changes in AWS yourself using the instructions in the aforementioned PR. 
@awoods

Removes need to disable triggers on PostgresQL

---

fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/ContainmentIndexImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/MembershipIndexManager.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/ContainmentIndexImplTest.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3507
Instead of querying for a list, which could be too large to return in memory this creates a stream backed by a paged query of the database.
Should have absolutely no discernable effect except that objects with an extremely large number of contained children or membership properties should still be retrieveable in a timely fashion.
@fcrepo/committers (@bbpennel as it was your ticket)

Stream containment and membership via paged DB queries

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/TransactionsIT.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/FcrepoOcflObjectSessionWrapper.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/OcflPersistentStorageSession.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/OcflPersistentStorageSessionTest.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3130
**This PR depends on the following PRs being merged first:**
- https://github.com/fcrepo/fcrepo-storage-ocfl/pull/24
- https://github.com/fcrepo/fcrepo/pull/1816
Adds support for rolling back OCFL changes when a transaction commit fails. This only works when auto-versioning is used.
1. Start a transaction
2. Make some changes
3. Corrupt the database in some way so that the transaction commit will fail
4. Commit the transaction
5. Verify that none of the changes were persisted to the database or on disk

Adds OCFL rollback

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/ContainmentIndex.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/ContainmentIndexImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/ContainmentIndexMetrics.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/ResourceFactoryImpl.java
fcrepo-kernel-impl/src/main/resources/sql/default-containment.sql
fcrepo-kernel-impl/src/main/resources/sql/mysql-containment.sql
fcrepo-kernel-impl/src/main/resources/sql/postgres-containment.sql
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/ContainmentIndexImplTest.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3541
We don't change the ETag when a container has a new or deleted contained resource.  This attempts to fix that by generating a hash of all the children of the requested resource.
I think this might be slowing down ingest as I was creating 5,000 children of a single parent and it seemed to average about 0.14 per resource (which is slower than normal on my machine).
Also there is probably a limit to how many contained resources this might work with. Probably need the big test machine to see if and when this crashes.
Create a container, note it's ETag and Last Modified time.
Create a child of the container, note it's ETag changes, but it's Last Modified is unchanged.
Tag (@ mention) interested parties or, if unsure, …

Alter ETag based on contained resources

---

fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/WebACFilter.java
fcrepo-auth-webac/src/test/java/org/fcrepo/auth/webac/WebACFilterTest.java
fcrepo-auth-webac/src/test/java/org/fcrepo/integration/auth/webac/WebACRecipesIT.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/url/HttpApiResources.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/FedoraLdpTest.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/url/HttpApiResourcesTest.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/api/rdf/HttpTripleUtil.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/api/rdf/UriAwareResourceModelFactory.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/domain/ldp/LdpPreferTag.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/api/rdf/HttpTripleUtilTest.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/rdf/LdpTriplePreferences.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/services/ResourceTripleService.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/BinaryImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/ResourceTripleServiceImpl.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3525
It adds WebAC checks for the contained resources when asking for the `http://www.w3.org/ns/oa#PreferContainedDescriptions` 
Adds a new `ResourceTripleService` that wraps the other services, so it can be called for the contained resources too.
Cleans up the UriAwareResourceModelFactory to remove references to the deprecated IdentifierConverter.
1. Create a container and a child container.
1. Get the container with the `return=representation; include="http://www.w3.org/ns/oa#PreferContainedDescriptions"` Prefer header. 
1. See the child resource in the output.
1. Add an ACL to the container allowing access and add an ACL to the child container disallowing access to a user.
1. Retry the above request as the user. Get denied access. …

Embedded Resource representation

---

fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/RdfLexicon.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/TimeMapImpl.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/models/TimeMapImplTest.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3007
Removes the `fedora:TimeMap` type from the link headers of timemaps. `memento:TimeMap` exists in its place.
1. Make an object (ie. `curl -i -ufedoraAdmin:fedoraAdmin -XPUT http://localhost:8080/rest/test`)
1. Get the object's timemap (ie. `curl -i -ufedoraAdmin:fedoraAdmin http://localhost:8080/rest/test/fcr:versions`)
1. See two Timemap headers
```
Link: <http://fedora.info/definitions/v4/repository#TimeMap>; rel="type"
Link: <http://mementoweb.org/ns#TimeMap>; rel="type"
```
1. Build this PR, do the GET again and see only one header
```
Link: <http://mementoweb.org/ns#TimeMap>; rel="type"
```

Remove fedora:TimeMap type

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraAcl.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/services/HttpRdfService.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/services/HttpRdfServiceTest.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/api/rdf/HttpIdentifierConverter.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/api/rdf/HttpIdentifierConverterTest.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/identifiers/FedoraId.java
fcrepo-kernel-api/src/test/java/org/fcrepo/kernel/api/identifiers/FedoraIdTest.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3539
* Adds a new `getEncodedFullId()` method to the `FedoraId` class to ensure when clients use spaces in their IDs they don't mess up the RDF.  
* It stops encoding the path as it is translated from internal to external URIs.
* Removes the `bodyToInternalStream()` method as it was only referenced by its own test.
Create objects with complex and strange URIs both as POST and PUT and ensure that the resulting graph looks correct.

Encode internal URIs in stored RDF documents.

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/exceptionhandlers/InvalidResourceIdentifierExceptionMapper.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/identifiers/FedoraId.java
fcrepo-kernel-api/src/test/java/org/fcrepo/kernel/api/identifiers/FedoraIdTest.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3537
Enforces id constraints for strings that are problematic based on the storage layout: https://wiki.lyrasis.org/display/FF/Design+-+Fedora+OCFL+Object+Structure
See the example queries in the jira: https://jira.lyrasis.org/browse/FCREPO-3537

enfoce id constraints

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/TransactionsIT.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/session/TransactionProvider.java
fcrepo-kernel-impl/pom.xml
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/TransactionImpl.java
fcrepo-persistence-api/src/main/java/org/fcrepo/persistence/api/PersistentStorageSession.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/RepositoryInitializer.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/DbFedoraToOcflObjectIndex.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/OcflPersistentStorageSession.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/OcflPersistentStorageSessionMetrics.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/integration/persistence/ocfl/impl/NonRdfSourcesPersistenceIT.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/OcflPersistentStorageSessionTest.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/ReindexManagerTest.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/ReindexServiceTest.java
pom.xml

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3581 and https://jira.lyrasis.org/browse/FCREPO-3543
* MySQL can fail if a competing transaction updates the same record. The only solution is to retry. This PR adds retries to the transaction commit.
* Reorders the commit operations so that all of the db changes are committed before the ocfl changes
Everything should still work and MySQL should not fail due to a race condition. I ran the test that exposed the problem, `FedoraLdpIT.testConcurrentPutsWithPairtrees()`, 20+ times with this PR and it did not fail.

fixed MySQL transaction problems and improved commit robustness

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/services/EtagService.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/FedoraLdpTest.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/AbstractResourceIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/LDPContainerIT.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/services/MembershipService.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/ResourceFactoryImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/MembershipIndexManager.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/MembershipServiceImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/ResourceTripleServiceImpl.java
fcrepo-kernel-impl/src/main/resources/sql/default-membership.sql
fcrepo-kernel-impl/src/main/resources/sql/mariadb-membership.sql
fcrepo-kernel-impl/src/main/resources/sql/mysql-membership.sql
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/services/MembershipServiceImplTest.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3541
* Determines last updated timestamp of membership for a resource
* Etags and state tokens now diverge for RDF sources, as etags now reflect
* State token
* Requested mimetype
* Prefer headers that affect the included triples
* Last updated from containment index
* Last updated from membership index
* Adds a service for calculating etags
* Removes inclusion of containment last updated from state token calculation, as it is happening at request time now
You can see a few other examples of DirectContainer operations that could be used for testing in:
https://github.com/fcrepo/fcrepo/pull/1781
```
curl -XPUT http://localhost:8080/rest/mem_resc1 -ufedoraAdmin:fedoraAdmin
echo "
<http://localhost:8080/rest/dc_hm> …
```

FCREPO-3541 - Etags reflect membership and other request preferences

---

fcrepo-persistence-ocfl/pom.xml
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/OcflPersistentStorageUtils.java
pom.xml

**Jira:** https://jira.lyrasis.org/browse/FCREPO-3590
**This PR depends on https://github.com/fcrepo/fcrepo-storage-ocfl/pull/27**
Upgrades ocfl-java to the latest version.
A key difference in this version is that the storage layout extension definition is moved into the `extensions` directory. While the layout extension we're using has not been merged yet, it is unlikely that it'll need to be updated again.
This change does mean that the layout config in the storage root will no longer be read. Existing repositories with the storage layout in the old location are still usable, but `ocfl-java` will **not** write the storage layout to the new location for an existing repository. You either need to recreate the repository or write it manually.
To manually create it, write the following to …

upgraded to ocfl-java 0.2

---

fcrepo-parent/pom.xml

** Gets integration tests running again.**
* * *
**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3600
Downgrades the maven-failsafe-plugin to 3.0.0. 
This change fixes the problem of integration tests not running.  It is not clear why.
Run the build (mvn clean install) 
Verify that the number of integration tests run in all modules with integration tests is greater than zero.

Downgrades the maven-failsafe-plugin to 3.0.0. 

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraVersioning.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersioningIT.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/exceptionhandlers/CannotCreateMementoExceptionMapper.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/exception/CannotCreateMementoException.java
fcrepo-webapp/src/main/webapp/static/constraints/CannotCreateMementoException.rdf

…onse in order to align with the API test suite.
**Removes the "Vary-Post: Memento-Datetime" heaader from the LDPCv response**
* * *
**JIRA Ticket**:  https://jira.lyrasis.org/browse/FCREPO-3480
Since we no longer support POST's to LDPCv with Memento-Datetime, the Vary-Post header should be removed on LDPCv.  In this way, the test suite can discern that the feature is not supported.
Create a resource and verify that the when you curl the time map (http://localhost:8080/rest/resource/fcr:versions no longer contains the "Vary-Post: Memento-Datetime" header.
* …

Removes the "Vary-Post: Memento-Datetime" heaader from the LDPCv response

---

fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/WebACFilter.java
fcrepo-http-api/pom.xml
fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/services/EtagService.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/AbstractResourceIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/LDPContainerIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/PrefersLdpIT.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/domain/ldp/LdpPreferTag.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/domain/ldp/LdpPreferTagTest.java
fcrepo-jms/pom.xml
fcrepo-jms/src/test/java/org/fcrepo/integration/jms/observer/AbstractJmsIT.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/rdf/LdpTriplePreferences.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/ResourceTripleServiceImpl.java
pom.xml

Setup new ITs.
**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3334
Makes an new enum to allow for identifying include, exclude or silent prefer headers.
Made new `PrefersLdpIT` to hold prefer header tests. Moved several tests from `FedoraLdpIT`  to `PrefersLdpIT`
As this is essentially about minimal container triples.
Make a resource, add some Rdf, and a contained resource.
GET the resource.
See user triples, server managed triples and containment triples.
GET the resource with `Prefer: return=representation; include="https://www.w3.org/ns/ldp#PreferMinimalContainer"`
See user triples and server managed triples.
GET the resource with `Prefer: return=representation; omit="https://www.w3.org/ns/ldp#PreferMinimalContainer"`
See containment triples.
Tag (@ mention) interested parties …

Alter preferTags to use enum (Minimal container triples)

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/LDPContainerIT.java

I think the problem was that the resource was created before it was added to the indirect container, so whether or not the original version was a member of the indirect container varied based on whether or not the resource and the proxy were created in the same second.

fix flapping indirect container test

---

fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/RdfLexicon.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3616
Changes the Prefer URI used to include/omit Server Managed Triples to the new one from the Fedora specification
https://github.com/fcrepo/fcrepo-specification/pull/412
1. Create an RDF resource.
2. Before the PR, do a GET of that resource with the Fedora API prefer header.
```
curl -i -ufedoraAdmin:fedoraAdmin http://localhost:8080/rest/test_resource -H"Prefer: return=representation; omit=\"http://fedora.info/definitions/fcrepo#ServerManaged\""
```
1. Get all the server managed triples.
2. Pull in this PR
3. Do the same GET and see no server managed triples.

Change ServerManaged URI

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraSearchIT.java
fcrepo-search-api/src/main/java/org/fcrepo/search/api/PaginationInfo.java
fcrepo-search-impl/src/main/java/org/fcrepo/search/impl/DbSearchIndexImpl.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3548
Adds a new value to the JSON response with the total number of results for the current query to assist in paging.
Create some resources in Fedora.
Do a generic search ie. `curl -i -ufedoraAdmin:fedoraAdmin 'http://localhost:8080/rest/fcr:search?condition=fedora_id=*&fields=fedora_id'`
There is no `totalResults` value in `paginationInfo` element.
Pull in this PR, run the same query and see the new element
ie.
```
{"pagination":{"offset":0,"maxResults":100,"totalResults":28}, "items": {...
```

Add total search results to response

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraSearchIT.java
fcrepo-search-impl/src/main/java/org/fcrepo/search/impl/DbSearchIndexImpl.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3615
This PR relies on #1853, I will leave this as draft until that one is merged.
Escapes underscores in conditions when the condition also has a wildcard.
* Make a resource called `fedora_11` and a resource called `fedora211`
```
> curl -ufedoraAdmin:fedoraAdmin -XPUT 'http://localhost:8080/rest/fedora_11'
> curl -ufedoraAdmin:fedoraAdmin -XPUT 'http://localhost:8080/rest/fedora211'
```
* Do a query for `fedora_1*`
```
> curl -ufedoraAdmin:fedoraAdmin 'http://localhost:8080/rest/fcr:search?condition=fedora_id=fedora_1*&fields=fedora_id'
```
* Get both results back.
```
{"pagination":{"offset":0,"maxResults":100},"items":[{"fedora_id":"http://localhost:8080/rest/fedora211"},{"fedora_id":"http://localhost:8080/rest/fedora_11"}]}
``` …

Escape underscores in wildcard searches

---

pom.xml

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3623
**Related to PR https://github.com/fcrepo/fcrepo-storage-ocfl/pull/30**
Upgrades to the latest version of ocfl-java. This is a breaking change to any existing repository that contains objects using the mutable HEAD extension.
Everything should work as normal. If you create a new object with a mutable head, you should see it appear in the object at `extensions/0005-mutable-head`. If you point it at a repository with an object with an existing mutable HEAD, you should see an exception when attempting to access the object.

upgrade to ocfl-java 1.0.1

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersioningIT.java
fcrepo-persistence-common/src/main/java/org/fcrepo/persistence/common/ResourceHeaderUtils.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/CreateVersionPersister.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/CreateVersionPersisterTest.java

**JIRA Ticket**: Follow on from https://jira.lyrasis.org/browse/FCREPO-3608
Updates the CreateVersionPersister to only update the mementoCreatedDate on a new version.
Also adds a new test to ensure the memento and original resource remain the same.
Create a resource, get the body of the resource.
Create a memento of the resource, get the body of the Memento.
They should match.
Get a new copy of the resource body.
It should also match the two previous. 

Only update mementoCreatedDate on new version

---

fcrepo-configs/src/main/java/org/fcrepo/config/FedoraPropsConfig.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/AbstractResourceIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/RebuildIT.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/IndexBuilderImpl.java

will cause the indices to be rebuilt on restart.
**JIRA Ticket**:  https://jira.lyrasis.org/browse/FCREPO-3611
Adds a new property that allows the user to force Fedora to reindex all content on restart.
`mvn clean install -Pone-click`
1. Start Fedora and add an item via the UI.
2. Delete the corresponding OCFL object from the disk.
3. Verify that the object is still visible as a child of the repository root
4. Attempting to retrieving the link should result in an error.
5. Restart Fedora and verify the deleted links are still present
6. Restart Fedora again with `-Dfcrepo.rebuild.on.start=true`
7. Verify that the link to the resource is gone. (be sure to do a hard refresh of your browser)
Tag (@ mention) …

Adds support for the fcrepo.rebuild.on.start property which

---

fcrepo-webapp/src/main/jetty-console/WEB-INF/web.xml
fcrepo-webapp/src/main/webapp/WEB-INF/no-auth-web.xml
fcrepo-webapp/src/main/webapp/WEB-INF/web.xml

**Jira**: https://jira.lyrasis.org/browse/FCREPO-3634
* Adds a version of the web.xml with auth disabled that is bundled in the war
Everything should work the same as before. The auth disabled web.xml must be manually specified: https://wiki.lyrasis.org/display/FEDORA6x/Disable+Authentication+and+Authorization

add web.xml with auth disabled

---

fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/AbstractNonRdfSourcePersister.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/UpdateNonRdfSourcePersister.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/integration/persistence/ocfl/impl/NonRdfSourcesPersistenceIT.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/AbstractReindexerTest.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/OcflPersistentStorageSessionTest.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/ReindexServiceTest.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3606
**This PR depends on https://github.com/fcrepo/fcrepo-storage-ocfl/pull/33**
* Test updates so that the tests produce valid resource headers
* Small behavior tweak when an internal resource is changed to an external resource so that its headers remain valid
No behavior changes. It should not be possible for Fedora to generate invalid headers unless there is a bug somewhere.

updated to account for header validation on write

---

fcrepo-configs/src/main/java/org/fcrepo/config/ConditionOnProperty.java

**Jira** https://jira.lyrasis.org/browse/FCREPO-3637
Fixes bug where `@Conditional` tests were not seeing properties defined in property files.
Create a property file that contains:
```
fcrepo.auth.enabled=false
```
Start Fedora:
```
mvn -Dfcrepo.config.file=fcrepo.properties jetty:run
```
See that auth is disabled

allow conditions to see values definied in prop files

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/services/HttpRdfService.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/services/SparqlTranslateVisitor.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/FedoraLdpTest.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/services/HttpRdfServiceTest.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraRelaxedLdpIT.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/utils/RelaxedPropertiesHelper.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/operations/AbstractRdfSourceOperationBuilder.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/operations/CreateRdfSourceOperationBuilderTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/services/CreateResourceServiceImplTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/services/ReplacePropertiesServiceImplTest.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3225
Alters the HTTP layer to not throw exceptions for SMTs if we are in relaxed mode and instead continue passing the model down.
Then it changes the kernel layer to filter any SMTs so they are not persisted to the user RDF and are only used by the relaxedProperties method.
Lastly it uses some existing work from @mikedurbin because the tests we had put `Date`s in the RDF but when we actually get the RDF back it is a `XSDDateTime` and these methods properly parse that.
Switch the server to relaxed mode by adding a `fcrepo.properties.management=relaxed` to your configuration file. Then try PUT/POST or PATCH with server managed triples.
ie.
```
curl -ufedoraAdmin:fedoraAdmin -H"Slug: test" -XPOST -H"Content-type: text/turtle" -d" <> …
```

Enable updating SMTs when in relaxed mode

---

fcrepo-configs/src/main/java/org/fcrepo/config/FedoraPropsConfig.java

**Turns off fixity check on rebuild by default**
* * *
**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3641
It's all in the title: changes the default value of "fcrepo.rebuild.validation.fixity" to false.
1) Start fedora.
2) Create a binary
3) Tamper with the binary on disk
4) Start Fedora 
5) Verify it comes up without errors.
6) Restart Fedora with `-Dfcrepo.rebuild.validation.fixity=true -Dfcrepo.rebuild.on.start=true`
7) Verify that there is a fixity error in the logs

Turns off fixity check on rebuild by default.

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3650
* Removes the `fedora:` prefix path restriction
* Adds a restrictions that paths cannot contain parts prefixed with `fcr:` that are not `fcr:acl` or `fcr:metadata`
Try to create/update/delete resources with parts with `fcr:` prefixes.

reject paths that contain the 'fcr:' prefix

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3648
Adds a check to stop an attempt to `PUT` a binary description to a binary that doesn't exist
Before PR
```
> curl -i -ufedoraAdmin:fedoraAdmin http://localhost:8080/rest/bob                   
HTTP/1.1 404 Not Found
Date: Fri, 19 Feb 2021 15:50:08 GMT
Set-Cookie: JSESSIONID=node01ggergt4zt1gw1nxk193s7u6cg0.node0; Path=/
Set-Cookie: rememberMe=deleteMe; Path=/; Max-Age=0; Expires=Thu, 18-Feb-2021 15:50:09 GMT; SameSite=lax
Content-Type: text/turtle;charset=utf-8
Content-Length: 48
Server: Jetty(9.4.34.v20201102)
Error: No OCFL mapping found for info:fedora/bob
> curl -i -ufedoraAdmin:fedoraAdmin http://localhost:8080/rest/bob/fcr:metadata -XPUT
HTTP/1.1 500 Internal Server Error
Set-Cookie: …
```

Don't try to PUT descriptions to non-existant binaries

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraFixity.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraFixityIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3649
Disallows many methods on the `fcr:fixity` endpoints.
See various examples in the ticket, but essentially you should no longer get any response except a 405 Method Not Allowed for any of `DELETE`, `HEAD`, `PUT`, `POST` or `PATCH`

Reject disallowed fcr:fixity methods

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/services/HttpRdfService.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/services/SparqlTranslateVisitor.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/AbstractResourceIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraRelaxedLdpIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersioningIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/PrefersLdpIT.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/exceptionhandlers/MultipleConstraintViolationExceptionMapper.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/RdfLexicon.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/exception/RelaxableServerManagedPropertyException.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/utils/RelaxedPropertiesHelper.java
fcrepo-webapp/src/test/java/org/fcrepo/webapp/ConstraintExceptionsTest.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3645
To more closely mimic Fedora 5s behaviour this alters Fedora 6 to throw an exception when a user adds a managed type in their RDF when the server is in relaxed mode. Previously it just ignored the triple.
1. Start Fedora in relaxed mode. ie. (`fcrepo.properties.management=relaxed`)
1. Create a resource a new resource.
1. GET the resource without server managed properties, or remove them from the result to make it easier to see what is happening.
1. Add a server managed type to the body, like `<> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/ldp#NonRDFSource>`
1. Try to PUT this back to the server.
1. In `main` you will succeed but nothing changes.
1. In this PR you will get a 409 Conflict. …

Throw exceptions for managed types when in RELAXED mode

---

fcrepo-configs/src/main/java/org/fcrepo/config/FedoraPropsConfig.java
fcrepo-webapp/src/main/java/org/fcrepo/webapp/WebappConfig.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3587
Makes the guava event bus that's used to emit messages asynchronous, which is, I believe, how people were already assuming it was operating.
Fire up Fedora, listen for events, create a resource, and see that events still work.

make the event bus async

---

fcrepo-configs/src/main/java/org/fcrepo/config/OcflPropsConfig.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/ReindexManager.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3666
Fixes the default thread count calculation so that there will always be at least 1 reindex thread
Run Fedora on a system that only as a single available processor and see that it still creates a reindex thread.

fix reindx thread count calculation

---

fcrepo-configs/src/main/java/org/fcrepo/config/FedoraPropsConfig.java
fcrepo-webapp/src/main/java/org/fcrepo/webapp/AuthConfig.java
fcrepo-webapp/src/test/java/org/fcrepo/integration/SanityCheckIT.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3667
* Non-ASCII, `\`, and `:` are no longer blocked
Try creating a resource containing unicode chars before and after this PR.

allow unicode chars by default

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/AbstractResourceIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3668
* Changes the `Slug` header to be interpreted as a url-encoded string, allowing it to support unicode characters.
The following does not work before this PR and works after.
```
echo "hello world" | curl -ufedoraAdmin:fedoraAdmin http://localhost:8080/rest/ -H'Link: <http://www.w3.org/ns/ldp#NonRDFSource>; rel="type"' -H"Slug: %E2%98%9E%E2%98%95%E2%98%9C%E2%98%91" --data-binary @- -XPOST -v
curl -u fedoraAdmin:fedoraAdmin http://localhost:8080/rest/%E2%98%9E%E2%98%95%E2%98%9C%E2%98%91
```

corrected slugs to be interpreted as url encoded strings

---

fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/DeleteResourcePersister.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/integration/persistence/ocfl/impl/DeleteResourcePersisterIT.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/DeleteResourcePersisterTest.java
fcrepo-persistence-ocfl/src/test/resources/manual_versioning.properties
fcrepo-persistence-ocfl/src/test/resources/spring-test/manual-versioning-config.xml

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3289
Forces a new version to be generated when you delete an atomic resource or an Archival Group (but not a part of an Archival Group)
Start a manually versioned repository.
Create a resource.
Delete the resource.
Investigate the OCFL on disk to see that the only version in the OCFL object has the object as not deleted.
Pull in this PR and repeat.
See that now the object will have a second version persisting the changes to the header's sidecar file.

Create automatic version when deleting a resource in a manual versioned repository

---

fcrepo-configs/src/main/java/org/fcrepo/config/OcflPropsConfig.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/OcflPersistenceConfig.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/OcflPersistentStorageUtils.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3690
Exposes two new properties for customizing the S3 endpoint:
1. `fcrepo.s3.endpoint`: URL of a non-aws s3 endpoint
2. `fcrepo.s3.path.style.access`: Set to `true` if your endpoint needs path style access
Running Fedora against a non-aws endpoint should work if you start Fedora [configured to use s3](https://wiki.lyrasis.org/display/FEDORA6x/Amazon+S3), set `fcrepo.s3.endpoint` to the custom endpoint, and it should work.

expose properties for customizing the s3 endpoint

---

fcrepo-configs/src/main/java/org/fcrepo/config/OcflPropsConfig.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/OcflPersistenceConfig.java
pom.xml

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3711
**This PR will not build until https://github.com/fcrepo/fcrepo-storage-ocfl/pull/38 is merged**
Adds an option for enabling unsafe OCFL writes. When this option is enabled, the OCFL client will not calculate a digest for files that are added to objects. This should be faster, but is less safe as the object will be corrupted if the digest is incorrect.
Set `fcrepo.ocfl.unsafe.write.enabled=true` to enable unsafe writes.
Fedora should behave the same with or without this feature. It should be impossible to make Fedora create a bad object, including by intentionally giving it an incorrect digest like:
```
curl -u fedoraAdmin:fedoraAdmin http://localhost:8080/rest/binary -H "Link: …
```

add option to enable unsafe ocfl writing

---

fcrepo-configs/src/main/java/org/fcrepo/config/OcflPropsConfig.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/DbFedoraToOcflObjectIndex.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/DbFedoraToOcflObjectIndexTest.java

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3712
Relies on: https://github.com/fcrepo/fcrepo-storage-ocfl/pull/39
Add a caffeine cache to the `DbFedoraToOcflIndex` for the `getMapping` calls.
There should  be no functional difference, though I hope it is faster.

Add cache to FedoraToOcflIndex getMapping

---

fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/exceptionhandlers/InvalidChecksumExceptionMapper.java

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3647
Checksum mismatches are no longer logged as ERROR
```
echo "test content" | curl -ufedoraAdmin:fedoraAdmin -XPUT http://localhost:8080/rest/binary_with_sha1 --data-binary @- -H "Digest: sha=bad4fe2b8dd12cd9cd6a413ea960cd8c09c25f19527"
```
There should be nothing in the server log

do not log checksum mismatches as error

---

fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/OcflPersistentStorageSession.java

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3652
Changes the error message that's returned when a resource isn't found to be more user friendly
Attempt to get a resource that does not exist and see a message like:
> Error: Resource /test2 not found

improve message when resource not found

---

fcrepo-parent/pom.xml

**JIRA Ticket**: na
Changes the snapshot repo to https in an attempt to fix the build. Maven 3.8 only supports https
The GH Actions build should work.

change snapshot repo to https to work with mvn 3.8

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/FedoraLdpTest.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/exception/PathNotFoundRuntimeException.java

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3714
Currently if you try to POST to a URI that does not exist, Fedora appends the Slug to the provided URI and creates it as huge long URI.
See the attached ticket for differences from Fedora 5 behaviour.
Before the PR
```
> curl -i -ufedoraAdmin:fedoraAdmin http://localhost:8080/rest/test/bob      
HTTP/1.1 404 Not Found
Date: Thu, 06 May 2021 16:36:07 GMT
Set-Cookie: JSESSIONID=node02dgglis27umjisgjghf2yj951.node0; Path=/
Set-Cookie: rememberMe=deleteMe; Path=/; Max-Age=0; Expires=Wed, 05-May-2021 16:36:07 GMT; SameSite=lax
Content-Type: text/turtle;charset=utf-8
Content-Length: 53
Server: Jetty(9.4.34.v20201102)
Error: Resource /test/bob not found% …
```

Don't allow POSTing to non-existant resource

---

fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/ContainmentIndexImpl.java

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3708
Adds a second cache to the containment index to track `resourceExists` requests. 
I left this to use the same settings as the existing containment cache, we could just update the documentation to make clear this is happening or I can separate the settings into two sets.
I also left this under the original containment cache ticket (which was closed), but I couldn't find another ticket and wasn't sure if a new one was needed.
Should have no functional difference, just some performance improvements from less DB queries.

Add resourceExists cache

---

fcrepo-auth-common/src/test/java/org/fcrepo/auth/common/ContainerRolesPrincipalProviderTest.java
fcrepo-auth-common/src/test/java/org/fcrepo/auth/common/HttpHeaderPrincipalProviderTest.java
fcrepo-auth-common/src/test/java/org/fcrepo/auth/integration/AbstractResourceIT.java
fcrepo-auth-webac/pom.xml
fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/ACLHandleImpl.java
fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/WebACAuthorizationImpl.java
fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/WebACRolesProvider.java
fcrepo-auth-webac/src/test/java/org/fcrepo/auth/webac/WebACAuthorizationTest.java
fcrepo-auth-webac/src/test/java/org/fcrepo/auth/webac/WebACRolesProviderTest.java
fcrepo-configs/src/main/java/org/fcrepo/config/FedoraPropsConfig.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/AbstractResourceIT.java
fcrepo-jms/src/test/java/org/fcrepo/integration/jms/observer/AbstractJmsIT.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/auth/ACLHandle.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/auth/WebACAuthorization.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/AbstractDeleteResourceService.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/UpdatePropertiesServiceImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/WebacAclServiceImpl.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/services/DeleteResourceServiceImplTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/services/PurgeResourceServiceImplTest.java
fcrepo-webapp/src/main/java/org/fcrepo/webapp/WebappConfig.java

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3322
It adds a cache to the WebAC layer which stores the resource that contains the ACL for the given target resource and list of all the authorizations in that ACL.
These authorizations are still processed against the target resource to filter for applicable authorizations (if any).
This PR should have no functional difference and the performance implications are un-clear.

Cache WebAC effectiveAcl locations and authorizations

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraAcl.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraBaseResource.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3728
When a MySQL deadlock occurs, Fedora retries the request. However, if the initial attempt consumed the request's input stream, the retry will fail. This PR fixes this problem by:
1. Moving the logic that parses RDF outside of the retryable block so that the stream is only read once
2. Makes non-RDF requests non-retryable
The concurrency itest that was flapping should flap no more

make binaries non-retryable

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/TransactionsIT.java

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3729
Applies preconditions to long-running transactions the same as short-lived.
Execute a PUT in a long-running tx with `If-Match` set to a bogus value and see the request rejected. Execute with the correct value and see the request accepted.

apply preconditions on long-running transactions

---

fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/OcflPersistenceConfig.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/AbstractReindexerTest.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/OcflPersistentStorageSessionTest.java

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3693
**Depends on https://github.com/fcrepo/fcrepo-storage-ocfl/pull/42**
Wires in the new root resource id cache.
Everything should work the same as before. It should be slightly faster, but it's unclear if it'd be that noticeable, especially when using a local disk.

update to use root resource id cache

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/TestIsolationExecutionListener.java

**JIRA Ticket**: na
Moves the db cleanup to run after each test rather than before in an attempt to fix some issues with tests affecting each other across test class boundaries.
All tests should pass

move db cleanup to run after each test

---

fcrepo-http-api/src/main/resources/views/common-node-actions.vsl
fcrepo-webapp/src/main/webapp/static/css/common.css
fcrepo-webapp/src/main/webapp/static/js/common.js

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3741
1. Adds a field for specifying mime type when adding/updating binaries
2. Fixes bug where content type was being set to an empty string
Ideally, the type would be pre-populated with the existing mime type on update, but I don't know how to do that.
Do the following for adding and updating binaries:
1. Open the console
2. Add/update a binary _without_ a file extension and _without_ a mime type, and see it default to `application/octet-stream`
3. Add/update a binary _with_ a file extension and _without_ a mime type and see it guess the mime type
4. Add/update a binary _without_ a file extension and _with_ a mime type and see it use the specified type

added field for specifying mime type in web console

---

fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/MembershipServiceImpl.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/ReindexManager.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/ReindexService.java

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3750
Keeps the tx alive while reindexing membership
Reindexing a large repo that uses membership should succeed when the membership indexing takes longer to complete than the tx timeout.

keep tx alive while reindexing

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ExternalContentHandler.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/BinaryImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/CreateResourceServiceImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/ReplaceBinariesServiceImpl.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/AbstractNonRdfSourcePersister.java
pom.xml

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3758
**This PR depends on https://github.com/fcrepo/fcrepo-storage-ocfl/pull/43**
Upgrades to the latest version of ocfl-java and adds buffers to a few input streams. The latest version of ocfl-java adds buffering to all input streams, including streams that are returned via the api. This will resolve a couple of buffering related bugs in this code base as well, and hopefully make it much faster on systems running on a NAS.
No functional changes

upgrade ocfl-java; add buffers to streams where needed

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/operations/RdfSourceOperationFactory.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/operations/ResourceOperationType.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/observer/ResourceOperationEventBuilder.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/operations/RdfSourceOperationFactoryImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/operations/UpdateRdfHeadersOperation.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/operations/UpdateRdfHeadersOperationBuilder.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/ManagedPropertiesServiceImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/ReplacePropertiesServiceImpl.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/services/ReplacePropertiesServiceImplTest.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/OcflPersistentStorageSession.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/UpdateRdfHeadersPersister.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/UpdateRdfHeadersPersisterTest.java

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3752
This updates the metadata handling for server managed properties to be applied to the binary headers rather than the binary description. This allows for the ManagedPropertiesService to resolve all managed properties from the binary.
* Create a new operation for updating only the binary headers
* Create a new persister for updating the binary headers
* When updating a description, create two operations for managed and unmanaged properties
* Resolve managed properties from the Binary when possible
There are two things to test here - the binary metadata being pulled from the correct source and that updates to server managed properties are done to the correct file.
* Start fedora
* Create a binary
```
curl -X PUT -H …
```

FCREPO-3752: Altering the external content URL does not update the binary metadata's last-modified date

---

fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/TransactionImpl.java

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3765
1. No longer logs exceptions that are rolled back as part of normal cleanup
Execute a GET against Fedora, wait around for 5 minutes or so, and see that no rollback messages were logged.

do not log normal tx rollbacks

---

fcrepo-configs/src/main/java/org/fcrepo/config/FedoraPropsConfig.java
fcrepo-kernel-api/pom.xml
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/cache/UserTypesCache.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/models/FedoraResource.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/TransactionImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/TransactionManagerImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/cache/UserTypesCacheImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/BinaryImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/ContainerImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/FedoraResourceImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/NonRdfSourceDescriptionImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/ResourceFactoryImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/TimeMapImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/TombstoneImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/WebacAclImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/AbstractService.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/CreateResourceServiceImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/MembershipServiceImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/ReplacePropertiesServiceImpl.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/TransactionImplTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/TransactionManagerImplTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/cache/UserTypesCacheImplTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/models/ContainerImplTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/models/FedoraResourceImplTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/models/TimeMapImplTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/services/CreateResourceServiceImplTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/services/ReplacePropertiesServiceImplTest.java
fcrepo-kernel-impl/src/test/resources/membershipServiceTest.xml
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/OcflPersistentStorageSession.java

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3732
Adds a cache for user rdf types so that they do not need to be repeatedly loaded from disk.
Everything should work the same as before except triples should never be loaded from disk when creating or updating resources. I added a new debug log that will log every time a resource's triples are loaded. If you enable debug logging you should be able to confirm that the triples are no longer read when creating resources.
Key things to look at:
1. Triples are not read when creating/updating any resource
2. Updating resources in transactions works and does not bleed outside the tx

add user rdf types cache

---

fcrepo-http-api/src/main/resources/views/resource.vsl
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraHtmlIT.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/responses/ViewHelpers.java

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3773
When displaying triples in the HTML UI we expect the subject of all triples to be a URI. Blank nodes (while not recommended) are supported and don't have a URI in Jena.
This checks for the type of resource and finds something to use.
Make a RDFResource with a blank node, get it with `Accept: text/turtle` and see the output. Get it with the HTML UI and get a 500 server error.
Pull in this PR and be able to see the blank node resource in the HTML UI.
There is a test as the first commit if you want to verify it fails before the actual fix.

Display blank node triples in HTML UI

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3700
Allows users to specify filenames that contain non-ascii characters. This must be done in the form of `filename*=UTF-8''URL_ENCODED_NAME`.
Create a resource with special characters:
```
curl -v -H'Link: <http://www.w3.org/ns/ldp#NonRDFSource>; rel="type"' --data-binary @README.md -H"Content-Disposition: attachment; filename*=UTF-8''%E6%B5%85%E9%A1%B6%E8%BD%AF%E5%91%A2%E5%B8%BD%E5%B2%A9%E7%9F%B3" -H"Content-type: text/plain" -XPOST http://localhost:8080/rest/ -ufedoraAdmin:fedoraAdmin
```
Check the headers:
```
curl -I -u fedoraAdmin:fedoraAdmin http://localhost:8080/rest/d788d515-4a6d-4f27-a005-6433f4a879a6
```
Check the binary description:
```
curl -v -u fedoraAdmin:fedoraAdmin …
```

fixed utf-8 support for filenames

---

fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/WebACFilter.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraAcl.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraFixity.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraVersioning.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/domain/RDFMediaType.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/responses/RdfStreamProvider.java
pom.xml

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3767
Upgrades Jena to 4.2.0. This includes removing the mime type `application/x-turtle` because it was removed from Jena (https://issues.apache.org/jira/browse/JENA-2076)
Everything should still work the same, but Fedora will no longer accept `application/x-turtle`

upgrade to jena 4.2.0

---

fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/ReadOnlyTransaction.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/Transaction.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/TransactionImpl.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/TransactionImplTest.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/ReindexWorker.java

**Suppress events on rebuild.**
* * *
**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3792
This PR causes Fedora to suppress all events during the rebuild process.  Prior to this change,  object creation events were not being generated on rebuild since they are recorded during creation of the ocfl resource.  As a result only events that involve index updates (such as inbound reference updates) were being generated.  Since event generation is connected to the request (from which the base url is resolved) this was causing the NPE symptom since rebuild make use of the fcrepo.jms.baseUrl property.  
Since we neither want to require the use of fcrepo.jms.baseUrl nor generate a subset of repo …

Suppress events on rebuild.

---

fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/RepositoryInitializationFilter.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/RepositoryInitializer.java
fcrepo-webapp/src/main/java/org/fcrepo/webapp/WebappConfig.java
fcrepo-webapp/src/main/jetty-console/WEB-INF/web.xml
fcrepo-webapp/src/main/webapp/WEB-INF/no-auth-web.xml
fcrepo-webapp/src/main/webapp/WEB-INF/web.xml

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3735
This makes the RepositoryInitializer async and adds a filter to block requests on `/rest/` until initialization is complete.
In order to test this I had the `RepositoryInitializer` sleep in `onApplicationEvent` in order to simulate a long rebuild and issued a GET on `/rest/` during the rebuild.
start fedora:
```
mvn jetty:run -pl fcrepo-webapp -Dfcrepo.log=DEBUG
```
then issue a request on `/rest/` expecting a 503 to be returned:
```
curl -u fedoraAdmin:fedoraAdmin http://localhost:8080/rest
```
also issue a request on `/prometheus` expecting it not to be caught by the filter:
```
curl -u fedoraAdmin:fedoraAdmin http://localhost:8080/prometheus
```
Although the ticket mentions this for only the rebuild, I opted to …

Async repository initialization

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/FedoraLdpTest.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/AbstractResourceIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/ExternalContentHandlerIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3791 & https://fedora-repository.atlassian.net/browse/FCREPO-1843
Adds a query parameter `inline`, that if set to `true` will result in the Content-Disposition being set to `inline`. Otherwise it remains `attachment`
This is also changed for HEAD requests, mementos and external content.
Add a binary to a repository using main. 
GET the binary
* Through the HTML UI, see that pressing the "Download Content" button causes a save file dialog
* Through curl see the `Content-Disposition: attachment; size=79; creation-date="Wed, 24 Nov 2021 14:52:17 GMT"; modification-date="Wed, 24 Nov 2021 14:52:17 GMT"` header
Pull in this PR
GET the binary
* Through the HTML UI you cannot easily see this behaviour but if you go to a binary …

Make a query param to change content-disposition from attachment to inline

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/AbstractResourceIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/TestIsolationExecutionListener.java

Fixes the itests so that they are reset correctly between tests. Without this, GH Actions runs consistently fail. The problem is related to [the change](https://github.com/fcrepo/fcrepo/commit/5503287dd7b62eaaf3d6f4031cae82994c8dfc9d) that made Fedora start before the repo was initialized. In some instances the tests were being run while the initialization was still going. The code was changed to wait for the initialization to complete.
Tests should pass

Fix itest reset

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3810
Re-adds wildcards to the Jersey endpoints otherwise Jersey rejects `Accept` headers that aren't in the list (which are all RDF types and `text/plain` and `text/html`).
Also makes HEAD requests respond the same as a GET request.
Before this PR.
Put up a binary that is not `text/plain` or `text/html` (you can put up plain text and claim it is `application/pdf` though)
ie.
```
> curl -ufedoraAdmin:fedoraAdmin -XPUT -H"Content-type: application/pdf" --data-binary "Some fake binary" http://localhost:8080/rest/test_binary
```
Do a HEAD request to see the Content-type is set correctly.
```
> curl -I -ufedoraAdmin:fedoraAdmin http://localhost:8080/rest/test_binary
...
Content-Type: …
```

Re-add wildcard types and modify checks for acceptable types.

---

fcrepo-http-api/src/main/resources/views/search.vsl
fcrepo-webapp/src/main/webapp/static/js/common.js

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3549 and https://fedora-repository.atlassian.net/browse/FCREPO-3551
* Add page controls to the search ui
* Add field selection to the search ui
* Allow multiple conditions when searching in the search ui
* Start a Fedora instance
* Add some resources
* Navigate to `http://localhost:8080/rest/fcr:search` or where the search ui is located for your instance
* Query using multiple conditions, and restricting the page/field display options

Updates to the HTML Search UI

---

fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/api/rdf/HttpIdentifierConverter.java

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3818
**Note**: This does _not_ solve the issue, it does make it give out some useful information as to what URL is being called when the machine fails.
Updates the Exception message to include the original URI that attempted to be converted to an internal ID.
This exception most often appears when running Fedora inside of Tomcat and accessing either the splash page or repository root, but otherwise it can be random.

Show the failed URI during identifier conversion

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersioningIT.java

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3824
Changes response on DELETE to a Memento from `409 Conflict` to `405 Method Not Allowed`
Before PR create an object, then create a new version, then try to delete the version. Get:
```
> curl -i -ufedoraAdmin:fedoraAdmin http://localhost:8080/rest/test_version/00e7d1de-1758-4cb9-8044-6a762e8c2a14/fcr:versions/20220512161636 -XDELETE
HTTP/1.1 409 Conflict
Date: Thu, 12 May 2022 16:16:57 GMT
Set-Cookie: JSESSIONID=node01soir2ymob8vom0ew3290ysd283.node0; Path=/
Set-Cookie: rememberMe=deleteMe; Path=/; Max-Age=0; Expires=Wed, 11-May-2022 16:16:57 GMT; SameSite=lax
Link: <http://localhost:8080/static/constraints/ServerManagedTypeException.rdf>; …
```

405 on DELETE Memento

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersioningIT.java

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3825
Timemaps are displaying a Link header for an ACL off of the Timemap (i.e. `RESOURCE/fcr:versions/fcr:acl` instead of `RESOURCE/fcr:acl`). That is an invalid identifier and so it not accessible.
This PR changes the link header to the Original Resource's ACL.
Before the PR, create any resource, get the Timemap and review the headers. See the `rel="acl"` one.
Pull in this PR and see how the Link header has changed.

Timemaps should use the ACL of the original resource

---

fcrepo-webapp/src/main/webapp/static/js/common.js

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3831
Currently when you upload a binary you get a  `fedora:hasFixityService` triple, it is getting redirected to `http://localhost:8080/rest/<uri>/fcr:fixity/fcr:metadata`. This should not be redirected.
Before the PR add a binary and click the `fedora:hasFixityService` link in the HTML UI. Get an 404 white page in the browser.
Pull in the PR and try again, get the fixity result.

Don't re-write fcr:fixity links

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraVersioning.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersioningIT.java

This PR is simply fixing my mistaken merge of this fix onto `6.2.0-RC` instead of `main`.
See https://github.com/fcrepo/fcrepo/pull/1992

Use Set to deduplicate any extra versions

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraSearchIT.java
fcrepo-search-api/src/main/java/org/fcrepo/search/api/Condition.java

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3828
Return a bad request for invalid fields in simple search
* Ensure the integration test passes: `mvn clean verify`
* Build the one click application: `mvn  install -pl fcrepo-webapp -P one-click`
* Run the one click app: `java -jar fcrepo-webapp/target/fcrepo-webapp-6.3.0-SNAPSHOT-jetty-console.jar`
* Query the search API with an invalid search field:  `curl --verbose "http://localhost:8080/rest/fcr:search?condition=blob_size<=12"`
* Check that the response from the above request is a 400

Return a bad request for invalid fields in simple search

---

fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/WebACFilter.java
fcrepo-auth-webac/src/test/java/org/fcrepo/integration/auth/webac/WebACRecipesIT.java

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3848
When a normal user tried to delete a tombstone a check is done on its interaction model. But a tombstone returns `null` which was not accounted for in the code. This modifies the two checks.
1. Create a container and add an ACL for a normal user.
```shell
> curl -u fedoraAdmin:fedoraAdmin -X PUT someBox http://localhost:8080/rest
> curl -u fedoraAdmin:fedoraAdmin -X PUT -H"Content-type: text/turtle" --data "@prefix acl: <http://www.w3.org/ns/auth/acl#> . <#authz> a acl:Authorization; acl:agent \"testuser\"; acl:mode acl:Read, acl:Write, acl:Append; acl:accessTo </rest/someBox>; acl:default </rest/someBox> ." http://localhost:8080/rest/someBox/fcr:acl 
```
1. Have the normal user create a new container inside the …

Tombstones have null interaction model

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/NonRdfSourceDescriptionImpl.java

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3859
Changes the NonRdfSourceDescription to stop rewrite ALL subjects of triples and only rewrites the NonRdfSourceDescription to match its described binary.
Steps in the ticket or test added in this PR are best. Essentially make a binary, update the description to include a triple with some external URI as the subject. When you GET that description see that all triples have the same subject (that is the binary's URI).
```
> curl -u fedoraAdmin:fedoraAdmin http://localhost:8080/rest/ashley.art/fcr:metadata
@prefix premis: <http://www.loc.gov/premis/rdf/v1#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix fedora: <http://fedora.info/definitions/v4/repository#> .
@prefix ebucore: …
```

Only rewrite NonRdfSourceDescription subjects

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/responses/StreamingBaseHtmlProvider.java

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3818
When accessing Fedora through a reverse proxy and using the HTML UI you can get a state where the first request comes from the external URI, but a second comes from the internal URI. Because we generate a HttpIdentifierConverter from the external URI it won't match the internal URI.
This generates a Map of HttpIdentifierConverters (though at most you should only create 2).
The only real way is to setup a reverse proxy and ensure you have `ProxyPreserveHost On` in it.
Then when accessing the HTML UI with a browser (or an `Accept: text/html` header) you should get a stack trace in Fedora like
```
WARN 17:24:48.854 [qtp1749712938-32] (WildcardExceptionMapper) Unmapped exception
java.lang.IllegalArgumentException: …
```

Generate new HttpIdentifierConverter for new baseURIs

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/TransactionsIT.java

Fixes the build by ensuring that the database is cleared after the TransactionsIT.   The final test in TransactionsIT drops the containment table in order to generate an error.   Flyway doesn't appear to know that that happened so it does not attempt to regenerate the db before the next test. This PR ensures that the database schema is removed after the TransactionsIT.   

Clean db after transaction IT

---

fcrepo-persistence-common/src/main/java/org/fcrepo/persistence/common/MultiDigestInputStreamWrapper.java

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3872
* Adds a buffer when reading input streams during fixity check
* Ingest a largeish binary
* If needed one is provided in the ticket
* Call `fcr:fixity` on the ingested binary 
* e.g. `curl -u fedoraAdmin:fedoraAdmin http://localhost:8080/rest/binary-id/fcr:fixity`
* `time curl ...` can be used to note the amount of time the call takes
* Build + run the changes from this PR
* Rerun the curl call on `fcr:fixity` and compare the response times
Buffer size was informed by guava

Add buffer when reading input stream during fixity check

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/StreamingBaseHtmlProviderIT.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/api/rdf/HttpIdentifierConverter.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/api/rdf/HttpIdentifierConverterTest.java

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3869
Switch from the Java [URLDecoder](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/net/URLDecoder.html) to Spring [StringUtils](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/util/StringUtils.html#uriDecode(java.lang.String,java.nio.charset.Charset)) when decoding uris for internal ids.
* Build + Run Fedora
* Using a snippet of the script in the issue, the test cases can be run
```
#!/bin/sh
info_fedora="http://localhost:8080/rest"
put="curl -XPUT -u fedoraAdmin:fedoraAdmin -H'Content-Type:application/ld+json'"
for n in 'c&h' 'c+h' 'c_h'; do
encoded=$(jq -sRr --arg x $n '$x|@uri');
v=$(echo -n "info:fedora/$n" | shasum -a 256); echo $n $encoded $v;
curl …
```

FCREPO-3689: Switch URL Decoder

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraVersioning.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/FedoraResourceImpl.java

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3876
This updates fixes NPEs in two API calls - one for fcr:versions and the other using `Accept-Datetime` header. The NPE was being caused by trying to get the memento datetime on a tombstone, which obviously does not exist. Adding an additional check to make sure the resources are mementos resolves this issue.
Additionally, after fixing the NPE for the `Accept-Datetime` call an HTTP 500 was being returned. This was being caused by the `Content-Length` header being set and having no body in the response. Normally we would expect to see a 302 so I wasn't entirely sure what was going on, but jetty was not happy with this when finishing the response and was creating the exception. To resolve this I opted to pass a flag …

FCREPO-3876: NPEs when using Archive Groups

---

fcrepo-configs/src/main/java/org/fcrepo/config/FedoraPropsConfig.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/TransactionsIT.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/exceptionhandlers/ConcurrentUpdateExceptionMapper.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/exceptionhandlers/ExceptionDebugLogging.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/responses/ConcurrentExceptionResponse.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/exception/ConcurrentUpdateException.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/lock/InMemoryResourceLockManager.java

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3893
* #2040 
This updates the Concurrent Update handling to allow the transaction ids to be included in various places. When logging the existing transaction id is always present, and in the http response the existing and conflicting ids can be enabled via a property (`fcrepo.response.include.transaction`).
* Adds property to include transaction ids in 409s
* Moved exception messages into ConcurrentUpdateException
* Added transaction ids to ConcurrentUpdateException
* Added model for ConcurrentUpdateException response body
* Removed unused placeholder in ExceptionDebugLogging
* Note - I tested this with an existing container …

Include Transction ID in Conflict Response

---

fcrepo-http-api/src/main/resources/views/binary.vsl

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3904
You can have a hash uri in the metadata of a binary. It displays except when you view the HTML UI. This is because the velocity templates don't currently display these other properties.
Create a binary and update the metadata with a hash uri.
i.e.
```bash
> curl -ufedoraAdmin:fedoraAdmin -v -H"Content-type: image/jpeg" -d "@test_image.jpg" -H"Slug: test_image" -XPOST http://localhost:8080/rest
> curl -ufedoraAdmin:fedoraAdmin -v -XPATCH -d " INSERT DATA { <#somePart> <http://purl.org/dc/elements/1.1/title> 'Some part' . <> <http://purl.org/dc/elements/1.1/title> 'Binary thing' . }" -H"Content-type: application/sparql-update" http://localhost:8080/rest/test_image/fcr:metadata
```
View the binary description RDF as …

Add other resources part to NonRdfSourceDescription HTML template

---

pom.xml

**Bumping ActiveMQ to non-exploited version**
* * *
**JIRA Ticket**: https://fedora-repository.atlassian.net/jira/software/c/projects/FCREPO/issues/FCREPO-3911
only bumps minor version of activemq

bumping ActiveMQ to non-exploited version

---

fcrepo-auth-webac/src/test/java/org/fcrepo/auth/webac/WebACFilterTest.java
fcrepo-auth-webac/src/test/java/org/fcrepo/auth/webac/WebACRolesProviderTest.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/responses/StreamingBaseHtmlProviderTest.java
fcrepo-integration-rdf/pom.xml
fcrepo-integration-rdf/src/test/java/org/fcrepo/integration/rdf/AbstractIntegrationRdfIT.java
fcrepo-integration-rdf/src/test/java/org/fcrepo/integration/rdf/B3KatIT.java
fcrepo-integration-rdf/src/test/java/org/fcrepo/integration/rdf/BibOntologyIT.java
fcrepo-integration-rdf/src/test/java/org/fcrepo/integration/rdf/BibframeIT.java
fcrepo-integration-rdf/src/test/java/org/fcrepo/integration/rdf/GeonameIT.java
fcrepo-integration-rdf/src/test/java/org/fcrepo/integration/rdf/LdpIT.java
fcrepo-integration-rdf/src/test/java/org/fcrepo/integration/rdf/MiscExamplesIT.java
fcrepo-integration-rdf/src/test/java/org/fcrepo/integration/rdf/ModsRdfIT.java
fcrepo-integration-rdf/src/test/java/org/fcrepo/integration/rdf/MusicOntologyIT.java
fcrepo-integration-rdf/src/test/java/org/fcrepo/integration/rdf/OpenAnnotationIT.java
fcrepo-integration-rdf/src/test/java/org/fcrepo/integration/rdf/RdfNamespaceMappingIT.java
fcrepo-integration-rdf/src/test/java/org/fcrepo/integration/rdf/ServerManagedTriplesIT.java
fcrepo-integration-rdf/src/test/java/org/fcrepo/integration/rdf/TgnIT.java
fcrepo-integration-rdf/src/test/java/org/fcrepo/integration/rdf/VivoIT.java
fcrepo-integration-rdf/src/test/java/org/fcrepo/integration/rdf/WebAccessControlIT.java
fcrepo-integration-rdf/src/test/resources/spring-test/fcrepo-config.xml
fcrepo-integration-rdf/src/test/resources/spring-test/test-container.xml
fcrepo-persistence-ocfl/pom.xml

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3925
Re-enables tests
Still blocks 4 assertions because the setup is allowing an action that I independently tested and they are blocked
Tests are run and pass

Re-enable a bunch of tests.

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/AbstractResourceIT.java
fcrepo-integration-rdf/src/test/java/org/fcrepo/integration/rdf/ServerManagedTriplesIT.java

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3927
This updates the ServerManagedTriplesIT to add the DirectContainer link header in order for the constraints to be properly checked. This ensures that the checks in `AbstractService#ensureValidDirectContainer` are run and the proper 409 response is returned.
* Test that Fedora rebuilds and tests pass with `mvn install`

Add DirectContainer link header to ldp:hasMemberRelation checks

---

fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/WebACFilter.java
fcrepo-auth-webac/src/test/java/org/fcrepo/integration/auth/webac/WebACRecipesIT.java
fcrepo-webapp/src/main/webapp/static/js/common.js

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3922
* Adds versions endpoint to matcher
* Handle invalid memento exception in the WebACFilter
The admin ui will incorrectly try to navigate to `fcr:metadata` when accessing tombstone versions of resources. This prevents it from doing so by checking if the url ends with `fcr:versions` in order to prevent it from appending `fcr:metadata` again. In my limited use with the ui I haven't seen anything be broken, but it could use more thorough testing.
In addition when this bug was discovered we saw that the server was returning a 500 with a stacktrace instead of a 400. The `InvalidMementoPathException` was never being handled in the `WebACFilter` which has been updated to return a 400 with a `constrainedBy` link header. We …

FCREPO-3922: NonRdfSource metadata throws stacktrace once deleted

---

README.md
fcrepo-webapp/pom.xml

**JIRA Ticket**: https://fedora-repository.atlassian.net/jira/software/c/projects/FCREPO/issues/FCREPO-3923
Removes the one-click profile as it is deprecated and updates the README to remove mention of it. 
* Attempt to run the one-click
* confirm that any dependencies which were only used by the one-click profile;e have been removed from the pom files

removing one-click profile

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/RangeIT.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/domain/Range.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/domain/RangeTest.java

**JIRA Ticket**: https://fedora-repository.atlassian.net/jira/software/c/projects/FCREPO/issues/FCREPO-3955
Fixes Fedora's handling of Range requests that are too long and if they don't specify a starting position.
Create a binary and check it's content length.
Before this PR
Make a request for the binary with `Range: 0-<content length + 1>` get 416
Make a request for the binary with `Range: -5` get a response with `Content-Range: 0-5`
After this PR
Make a request for the binary with `Range: 0-<content length + 1>` get 206 with the full object 
Make a request for the binary with `Range: -5` get a response with `Content-Range: <content length - 5>-<content length - 1>`
Tag (@ mention) interested parties or, if …

Fix too long ranges and end start ranges

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/TransactionsIT.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/TransactionImpl.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/TransactionImplTest.java

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3951
When any request refreshes the expiration time of a transaction, by default the new expiration time will now be three minutes from the current time. 
Before this PR, it was set to the previous expiration time plus 3 minutes. The result of this was that if you had a transaction that you make 10 requests to, the expiration time would have been roughly 30minutes after the last request. Now it will be 3 minutes after the last request.
Without this PR, create a transaction, 1) GET it to see its Atomic-Expires, 2) create a resource, GET the TX again, 3) make a GET request to the created resource, then make a GET request to the TX. By the third request to get the TX you should see an Atomic-Expires roughly 9 minutes in …

FCREPO-3951 - Transaction updateExpiry sets rather than adds

---

fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/ContainmentIndex.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/services/MembershipService.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/services/ReferenceService.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/ContainmentIndexImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/ContainmentIndexMetrics.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/TransactionManagerImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/MembershipIndexManager.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/MembershipServiceImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/ReferenceServiceImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/ReferenceServiceMetrics.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/ContainmentIndexImplTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/TransactionManagerImplTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/services/MembershipServiceImplTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/services/ReferenceServiceImplTest.java
fcrepo-persistence-api/src/main/java/org/fcrepo/persistence/api/PersistentStorageSessionManager.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/api/FedoraToOcflObjectIndex.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/DbFedoraToOcflObjectIndex.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/FedoraToOcflObjectIndexMetrics.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/OcflPersistentSessionManager.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/OcflPersistentStorageSession.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/DbFedoraToOcflObjectIndexTest.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/OcflPersistentSessionManagerTest.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/OcflPersistentStorageSessionTest.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/TestOcflObjectIndex.java
fcrepo-search-api/src/main/java/org/fcrepo/search/api/SearchIndex.java
fcrepo-search-impl/src/main/java/org/fcrepo/search/impl/DbSearchIndexImpl.java
fcrepo-search-impl/src/main/java/org/fcrepo/search/impl/SearchIndexMetrics.java

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3952
When shutting down fedora, the application will attempt to rollback all active or expired-but-not-rolledback transactions, along with associated OCFL sessions. This should result in no leftover staged files or residual transaction database entries.
If the application shuts down in a non-graceful manner, the transaction tables also get truncated during startup and any leftover files in the staging directory are cleaned up.
ReferenceIndexService `reset` method now also clears the transaction table, which I'm guessing was overlooked before.
This PR also cleans up session information in the OCFL index when an OCFL session is rolled back (previously only committed OCFL sessions would roll back)
This can be tested using …

FCREPO-3952 - Cleanup transactions around application restarts

---

fcrepo-webapp/src/main/java/org/fcrepo/webapp/AuthConfig.java
fcrepo-webapp/src/test/java/org/fcrepo/integration/SanityCheckIT.java

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3933
Change configuration to allow encoded forward slashes (`%2F`) in the path since Shiro 1.13
There is a test in fcrepo-webapp and this does seem to appear only with Tomcat.
Build the WAR before this PR and deploy it to Tomcat.
Perform a PUT with an encoded slash
```
curl -ufedoraAdmin:fedoraAdmin  -XPUT -d" @prefix dc: <http://purl.org/dc/elements/1.1/> . <> dc:title 'Some object' ." -H"Content-type: text/turtle" "http://localhost:8080/fcrepo/rest/admin_set%2Fdefault" -i
```
See a 400 Bad Request
Build with this PR, and try again. Get a 201 Created or 204 No Content (depending on if it exists already).

Allow encoded forward slashes

---

.github/workflows/build.yml
README.md
fcrepo-http-api/src/test/java/org/fcrepo/http/api/ExternalContentHandlerFactoryTest.java
fcrepo-parent/pom.xml
pom.xml

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3967
* Configures CodeCov for fcrepo, so that coverage reports will get uploaded and hopefully displayed in PRs
* Changes a test that referenced fedora.info to point to example.com instead, since the former is moving
* Updates jacoco to the most recent version and adjusts config to work with codecov, and merge unit and IT coverage
* During a PR, only the "pull_request" set of builds will run now. The "push" set of builds will only run after a merge into main. This should significantly reduce the amount of time waiting for a PR to build.
* Adds a codecov badge to the readme
There aren't any functional changes to test. Looking at the results in codecov is about the best we can do

FCREPO-3967 - Minimal codecov and jacoco setup

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/services/ContainmentTriplesService.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/services/MembershipService.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/ContainmentIndexImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/ContainmentTriplesServiceImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/MembershipIndexManager.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/MembershipServiceImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/ResourceTripleServiceImpl.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/ContainmentIndexImplTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/services/ContainmentTriplesServiceImplTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/services/MembershipServiceImplTest.java

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3589
Restores inclusion of membership relations in GET responses when preferring inbound references. This was present in fedora 4 and 5.
When requesting inbound references, the `ldp:contains` relation from the parent to the child will now appear. I believe this is a new behavior, but it seems consistent and there was consensus for it on the ticket.
I also expanded the existing integration test for verifying this behavior to also demonstrate it works with resources that are contained by multiple indirect containers. Added a test to verify the behavior for direct containers, and did a little DRYing up related to indirect containers.
Test the following against main and then this branch:
Steps to setup a direct container …

FCREPO-3589 - Inbound references add membership and contains relations

---

fcrepo-kernel-api/pom.xml
fcrepo-kernel-api/src/test/java/org/fcrepo/kernel/api/RdfCollectorsTest.java
fcrepo-kernel-api/src/test/java/org/fcrepo/kernel/api/RdfLexiconTest.java
fcrepo-kernel-api/src/test/java/org/fcrepo/kernel/api/identifiers/FedoraIdTest.java
fcrepo-kernel-api/src/test/java/org/fcrepo/kernel/api/observer/EventTypeTest.java
fcrepo-kernel-api/src/test/java/org/fcrepo/kernel/api/rdf/DefaultRdfStreamTest.java
fcrepo-kernel-api/src/test/java/org/fcrepo/kernel/api/rdf/RdfNamespaceRegistryTest.java
fcrepo-kernel-api/src/test/java/org/fcrepo/kernel/api/services/functions/ConfigurableHierarchicalSupplierTest.java
fcrepo-kernel-api/src/test/java/org/fcrepo/kernel/api/utils/ContentDigestTest.java
fcrepo-kernel-api/src/test/java/org/fcrepo/kernel/api/utils/GraphDifferencerTest.java
pom.xml

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3973
Switch from `junit:junit` to `org.jupiter.junit:junit-jupiter` in `fcrepo-kernel-api`
Tests should still run and pass as before

Switch fcrepo-kernel-api to Junit5

---

fcrepo-auth-common/pom.xml
fcrepo-auth-common/src/test/java/org/fcrepo/auth/common/ContainerRolesPrincipalProviderTest.java
fcrepo-auth-common/src/test/java/org/fcrepo/auth/common/DelegateHeaderPrincipalProviderTest.java
fcrepo-auth-common/src/test/java/org/fcrepo/auth/common/HttpHeaderPrincipalProviderTest.java
fcrepo-auth-common/src/test/java/org/fcrepo/auth/common/ServletContainerAuthenticatingRealmTest.java
fcrepo-auth-common/src/test/java/org/fcrepo/auth/integration/AbstractResourceIT.java
fcrepo-auth-common/src/test/java/org/fcrepo/auth/integration/ServletContainerAuthenticatingRealmIT.java
fcrepo-auth-common/src/test/resources/spring-test/test-container.xml

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3980
* Update tests in fcrepo-auth-common to junit 5. 
* Remove port param from containerWrapper so that tests will pass in an IDE by default, bringing it in line with other test-container.xml files in the project

FCREPO-3980 - Update tests in fcrepo-auth-common to junit 5

---

fcrepo-event-serialization/pom.xml
fcrepo-event-serialization/src/test/java/org/fcrepo/event/serialization/EventSerializerTest.java
fcrepo-event-serialization/src/test/java/org/fcrepo/event/serialization/EventSerializerTestBase.java
fcrepo-event-serialization/src/test/java/org/fcrepo/event/serialization/JsonLDSerializerTest.java
fcrepo-event-serialization/src/test/java/org/fcrepo/event/serialization/TurtleSerializerTest.java

**upgrade fcrepo-event-serialization to JUnit5**
* * *
**JIRA Ticket**: https://fedora-repository.atlassian.net/jira/software/c/projects/FCREPO/issues/FCREPO-3976
updates namespaces and syntax for JUnit5
* ensure tests pass as expected

upgrade fcrepo-event-serialization to JUnit5

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/LDPContainerIT.java

Updates test to correctly pass if memento does not have any membership, which will happen if the proxy is modified the second after the memento is created.
Tests should pass

Allow test to pass if timing causes memento to not list any membership

---

fcrepo-configs/pom.xml
fcrepo-configs/src/main/java/org/fcrepo/config/DigestAlgorithm.java
fcrepo-configs/src/main/java/org/fcrepo/config/OcflPropsConfig.java
fcrepo-configs/src/test/java/org/fcrepo/config/AuthPropsConfigTest.java
fcrepo-configs/src/test/java/org/fcrepo/config/ConditionOnPropertyFalseTest.java
fcrepo-configs/src/test/java/org/fcrepo/config/ConditionOnPropertyTrueTest.java
fcrepo-configs/src/test/java/org/fcrepo/config/DatabaseConfigTest.java
fcrepo-configs/src/test/java/org/fcrepo/config/DigestAlgorithmTest.java
fcrepo-configs/src/test/java/org/fcrepo/config/FedoraPropsConfigTest.java
fcrepo-configs/src/test/java/org/fcrepo/config/MetricsConfigTest.java
fcrepo-configs/src/test/java/org/fcrepo/config/OcflPropsConfigTest.java
fcrepo-configs/src/test/java/org/fcrepo/config/SystemInfoConfigTest.java

**JIRA Ticket**: https://github.com/fcrepo/fcrepo/issues/2164
Adds test coverage for fcrepo-configs
Minor adjustment to validation of s3 properties so it will disallow blank ocflS3Bucket when s3 is enabled. In tests, ocflS3Bucket was defaulting to "" rather than null.
Run the tests.

2164 - Test coverage for fcrepo-configs

---

pom.xml

**JIRA Ticket**: https://github.com/fcrepo/fcrepo/issues/2157
Updates logback to most recent 1.4.x and slf4j to most recent 2.0.x
Note: 1.5.x is the most recent logback series, but it conflicts with dependencies in the older version of jetty we are currently using, causing some ITs to fail. So we can circle back to logback after updating jetty in

2157 - Update logback to 1.4 and slf4j to 2.0

---

fcrepo-http-api/src/test/resources/logback-test.xml
fcrepo-webapp/pom.xml
fcrepo-webapp/src/test/java/org/fcrepo/integration/FedoraHtmlResponsesIT.java
fcrepo-webapp/src/test/resources/logback-test.xml
pom.xml

**JIRA Ticket**: https://github.com/fcrepo/fcrepo/issues/2218
* Upgrades htmlunit from version 2 to 4.4. 
* The most recent version is 4.13, but 4.5+ all fail because of an error parsing/executing jquery 1.12 which is used in the UI. We could probably upgrade further if we upgraded jquery, but I assume we are not going to prioritize that since we are planning to replace the UI.

GH-2218 - Upgrade to htmlunit 4.4

---

fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/RdfLexicon.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/FixityServiceImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/ManagedPropertiesServiceImpl.java
fcrepo-webapp/src/main/resources/namespaces.yml

PREMIS 3 support
**JIRA Ticket**: None
These changes provide support for [PREMIS 3](https://www.loc.gov/standards/premis/ontology/owl-version3.html), which has been out for over a decade.
Implementation checklist:
Relevant documentation:
* https://id.loc.gov/ontologies/premis-3-0-0.html
* https://www.loc.gov/standards/premis/ontology/pdf/premis3-owl-guidelines-20220426.pdf
* https://id.loc.gov/vocabulary/preservation/cryptographicHashFunctions/sha512.html
* https://id.loc.gov/vocabulary/preservation/eventOutcome.html
`mvn test`

PREMIS 3 support
