fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/exceptionhandlers/ParamExceptionMapper.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/exceptionhandlers/ParamExceptionMapperTest.java

Resolves: https://jira.duraspace.org/browse/FCREPO-1295

Add ParamExceptionMapper for Jersey errors.

---

fcrepo-kernel-impl/pom.xml

See: https://docs.jboss.org/author/display/MODE40/Getting+Started#GettingStarted-Usingatransactionmanager
Resolves: https://jira.duraspace.org/browse/FCREPO-1293

Replace DummyTransactionManager with JBoss Transaction Manager

---

fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/rdf/impl/RootRdfContext.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/integration/kernel/impl/FedoraResourceImplIT.java
fcrepo-kernel/src/test/java/org/fcrepo/kernel/RdfLexiconTest.java
fcrepo-transform/src/main/java/org/fcrepo/transform/http/FedoraTransform.java
fcrepo-transform/src/main/resources/ldpath.cnd

See: https://jira.duraspace.org/browse/FCREPO-1309
See also this PR: https://github.com/fcrepo4/ontology/pull/16
and this discussion: https://github.com/fcrepo4/ontology/issues/14

aligned RDF properties with repository ontology

---

pom.xml

- https://wiki.duraspace.org/display/FF/Fedora+Committers
Resolves: https://jira.duraspace.org/browse/FCREPO-1350

Trim list of developers to official committers:

---

fcrepo-connector-file/src/main/java/org/modeshape/connector/filesystem/ExternalJsonSidecarExtraPropertyStore.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/api/rdf/HttpResourceConverter.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/spring/ModeShapeRepositoryFactoryBean.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/utils/iterators/PersistingRdfStreamConsumer.java
fcrepo-kernel/src/main/java/org/fcrepo/kernel/utils/iterators/IteratorConsumer.java
fcrepo-mint/src/main/java/org/fcrepo/mint/HttpPidMinter.java
fcrepo-transform/src/main/java/org/fcrepo/transform/transformations/LDPathTransform.java

https://jira.duraspace.org/browse/FCREPO-1317?jql=key%20in%20(FCREPO-1317)
http://sonar.fcrepo.org/drilldown/issues/1?&rule=squid%3AS00112&rule_sev=MAJOR&severity=MAJOR#

Change generic exceptions to more specific exceptions

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraNodes.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/rdf/impl/RootRdfContext.java
fcrepo-transform/src/main/java/org/fcrepo/transform/http/FedoraTransform.java

https://jira.duraspace.org/browse/FCREPO-1334

Fix sonar warnings

---

fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/domain/ContentLocationMessageBodyReader.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/TransactionServiceImpl.java
fcrepo-kernel/src/main/java/org/fcrepo/kernel/services/TransactionService.java
fcrepo-transform/src/main/java/org/fcrepo/transform/http/responses/ResultSetStreamingOutput.java

https://jira.duraspace.org/browse/FCREPO-1325

Remove redundant throws declaration

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/ContainerImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/TombstoneImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/rdf/impl/LdpRdfContext.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/rdf/impl/NodeRdfContext.java

- Avoid unused private fields
- Remove unused import
Resolves: https://jira.duraspace.org/browse/FCREPO-1327

Reduce Sonar major issue - "Unused Private Field"

---

fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/api/rdf/HttpResourceConverter.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/observer/DefaultFilter.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/observer/eventmappings/AllNodeEventsOneEvent.java

- Rebase and make change base on the code review
Resolves: https://jira.duraspace.org/browse/FCREPO-1337

Reduce Sonar major issues

---

fcrepo-auth-common/src/test/java/org/fcrepo/auth/integration/ContainerRolesPrincipalProviderIT.java
fcrepo-auth-common/src/test/java/org/fcrepo/auth/integration/HttpHeaderPrincipalProviderIT.java
fcrepo-auth-common/src/test/java/org/fcrepo/auth/integration/ModeShapeHonorsFADResponseIT.java
pom.xml

IT tests had to be updated possibly due to MODE-2414

Upgrade ModeShape to version 4.2.0.Final

---

fcrepo-webapp/pom.xml

https://jira.duraspace.org/browse/FCREPO-1376

https://jira.duraspace.org/browse/FCREPO-1376

---

fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/domain/PreferTag.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/domain/PreferTagTest.java

Fixes https://jira.duraspace.org/browse/FCREPO-1406

Making sure prefer header params isn't null (FCREPO-1406)

---

fcrepo-http-api/pom.xml
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraBaseResource.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraNodes.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/FedoraLdpTest.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/AbstractResource.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/AbstractResourceTest.java
fcrepo-jms/src/main/java/org/fcrepo/jms/headers/DefaultMessageFactory.java
fcrepo-jms/src/test/java/org/fcrepo/jms/headers/DefaultMessageFactoryTest.java

Fixes https://jira.duraspace.org/browse/FCREPO-1420

Adding userID and userAgent to events

---

fcrepo-jms/src/main/java/org/fcrepo/jms/headers/DefaultMessageFactory.java

- Non-functional update to fix sonar issue

Removing unused private field

---

fcrepo-jms/src/test/java/org/fcrepo/integration/jms/observer/HeadersJMSIT.java

Fixes https://jira.duraspace.org/browse/FCREPO-1419

Expanding IT to cover all audit event types except fixity

---

fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/rdf/converters/PropertyConverter.java

https://jira.duraspace.org/browse/FCREPO-1381

Log a warning if a user-supplied namespace was misinterpreted by Jena

---

README.md

IMHO, just having a simple note about JAVA_HOME and how to check/set it is much better than pointing to an issue with a back-and-forth discussion.

Updating JAVA_HOME info with simple explanation of Maven using JAVA_HOME

---

fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/rdf/Deskolemizer.java

Fixes https://jira.duraspace.org/browse/FCREPO-1483

Catching tombstone errors when checking for skolem nodes

---

fcrepo-auth-common/pom.xml
fcrepo-boms/fcrepo-jcr-bom/pom.xml
fcrepo-connector-file/pom.xml
fcrepo-connector-file/src/main/java/org/fcrepo/connector/file/FedoraFileSystemConnector.java
fcrepo-http-api/pom.xml
fcrepo-http-commons/pom.xml
fcrepo-jms/pom.xml
fcrepo-jms/src/main/java/org/fcrepo/jms/headers/DefaultMessageFactory.java
fcrepo-jms/src/main/java/org/fcrepo/jms/observer/JMSEventMessageFactory.java
fcrepo-jms/src/main/java/org/fcrepo/jms/observer/JMSTopicPublisher.java
fcrepo-kernel-impl/pom.xml
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/observer/eventmappings/AllNodeEventsOneEvent.java
fcrepo-kernel/src/main/java/org/fcrepo/kernel/observer/FedoraEvent.java
fcrepo-webapp/pom.xml

Resolves: https://jira.duraspace.org/browse/FCREPO-1487

Lessen leakage of JCR dependent code that extends beyond the kernel.

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/FedoraLdpTest.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/rdf/impl/LdpRdfContext.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/rdf/impl/LdpRdfContextTest.java

Fixes https://jira.duraspace.org/browse/FCREPO-1521

NonRDFSources now include rdf:type=ldp:NonRDFSource triple

---

.travis.yml
pom.xml

https://jira.duraspace.org/browse/FCREPO-1399

Shift compilation to Java 8

---

fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/observer/SuppressByMixinFilter.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/rdf/impl/DefaultIdentifierTranslator.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/rdf/impl/PrefixingIdentifierTranslator.java

Relates to: https://jira.duraspace.org/browse/FCREPO-1549

Minor, update javadocs

---

pom.xml
src/site/site.xml

https://github.com/fcrepo4/fcrepo4/commit/561036dc2e3351de5e938cdf91f5edeb7c67c7ff#diff-600376dffeb79835ede4a0b285078036R669
Partial resolution of: https://jira.duraspace.org/browse/FCREPO-1557

Update maven site related versions in response to:

---

pom.xml

See: https://jira.duraspace.org/browse/FCREPO-1595

removed maven.fcrepo.org repository

---

fcrepo-connector-file/src/main/java/org/fcrepo/connector/file/ExternalJsonSidecarExtraPropertyStore.java
fcrepo-connector-file/src/main/java/org/fcrepo/connector/file/FedoraFileSystemConnector.java
fcrepo-connector-file/src/test/java/org/fcrepo/connector/file/ExternalJsonSidecarExtraPropertyStoreTest.java
fcrepo-connector-file/src/test/java/org/fcrepo/connector/file/FedoraFileSystemConnectorTest.java
fcrepo-connector-file/src/test/java/org/fcrepo/integration/connector/file/AbstractFedoraFileSystemConnectorIT.java
fcrepo-connector-file/src/test/java/org/fcrepo/integration/connector/file/BasicReadWriteFedoraFileSystemConnectorIT.java
fcrepo-connector-file/src/test/java/org/fcrepo/integration/connector/file/ReadOnlyExternalPropertiesFedoraFileSystemConnectorIT.java

https://jira.duraspace.org/browse/FCREPO-1602

Minor code cleanup

---

fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/rdf/impl/RootRdfContext.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/integration/kernel/impl/FedoraResourceImplIT.java

Resolves: https://jira.duraspace.org/browse/FCREPO-1617

Remove fedora:hasNodeType triples from root description

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/responses/RdfStreamStreamingOutput.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/responses/WriterConfigHelper.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/responses/WriterConfigHelperTest.java
fcrepo-integration-ldp/pom.xml
fcrepo-kernel/pom.xml
pom.xml

Resolves: https://jira.duraspace.org/browse/FCREPO-1615

Enable JSON-LD profiles for response serializations

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/rdf/impl/PropertiesRdfContext.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/integration/kernel/impl/FedoraResourceImplIT.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/rdf/converters/PropertyConverterTest.java
fcrepo-kernel/src/main/java/org/fcrepo/kernel/FedoraJcrTypes.java
fcrepo-transform/src/test/java/org/fcrepo/integration/LDPathServiceIT.java
fcrepo-transform/src/test/java/org/fcrepo/integration/SparqlQueryTransformIT.java

Resolves: https://jira.duraspace.org/browse/FCREPO-1539

Eliminate the publishing of UUID triples

---

pom.xml

See: https://jira.duraspace.org/browse/FCREPO-1626

update mailing list address

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-kernel-impl/src/main/resources/fedora-node-types.cnd
fcrepo-kernel/src/main/java/org/fcrepo/kernel/FedoraJcrTypes.java

Fixes https://jira.duraspace.org/browse/FCREPO-1531

Using premis:hasMessageDigest for checksums

---

fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/utils/FedoraTypesUtils.java

See: https://jira.duraspace.org/browse/FCREPO-1633

fixed minor typo

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java

Make the logic a bit more clear

invert logic for clarity

---

pom.xml

Resolves: https://jira.duraspace.org/browse/FCREPO-1634

Reintroduce javadoc plugin into build process

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/AbstractResourceIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/api/rdf/HttpResourceConverter.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/exceptionhandlers/InvalidResourceIdentifierExceptionMapper.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/api/rdf/HttpResourceConverterTest.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/exception/InvalidResourceIdentifierException.java

Resolves: https://jira.duraspace.org/browse/FCREPO-1537

Respond with 400 status on request with empty path segments

---

fcrepo-webapp/pom.xml
fcrepo-webapp/src/test/resources/jetty-test.xml
pom.xml

- Add minor exclusion for jacoco analysis
Resolves: https://jira.duraspace.org/browse/FCREPO-1643

Upgrade jetty-maven-plugin

---

fcrepo-mint/pom.xml
fcrepo-mint/src/main/java/org/fcrepo/mint/HttpPidMinter.java

See: https://jira.duraspace.org/browse/FCREPO-1646
Also (in the name of reducing dependencies) adjusted maven configuration of `spring-context` to be scoped to `test`

remove dependency on guava

---

fcrepo-http-api/src/main/resources/views/common.js

Resolves: https://jira.duraspace.org/browse/FCREPO-1649

Update HTML UI to only add '/' if new resource id is provided

---

pom.xml

See: https://jira.duraspace.org/browse/FCREPO-1656

suppress informational javadoc output

---

fcrepo-connector-file/src/main/java/org/fcrepo/connector/file/ExternalJsonSidecarExtraPropertyStore.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/exception/IncorrectTripleSubjectException.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/observer/FedoraEvent.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/utils/UncheckedBiConsumer.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/utils/UncheckedFunction.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/utils/UncheckedPredicate.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/rdf/converters/ValueConverter.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/utils/JcrPropertyStatementListener.java
fcrepo-transform/src/main/java/org/fcrepo/transform/TransformationFactory.java

See: https://jira.duraspace.org/browse/FCREPO-1655

add documentation where the javadoc plugin had been spewing warnings

---

.travis.yml

See: https://jira.duraspace.org/browse/FCREPO-1657

remove redundant javadoc commands

---

pom.xml

See: https://jira.duraspace.org/browse/FCREPO-1676

update servlet-api version

---

fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/responses/RdfStreamStreamingOutputTest.java
fcrepo-integration-ldp/pom.xml
fcrepo-integration-rdf/src/test/java/org/fcrepo/integration/rdf/AbstractIntegrationRdfIT.java
pom.xml

See: https://jira.duraspace.org/browse/FCREPO-1675

update jena version

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/main/resources/views/common.vsl
fcrepo-http-api/src/test/java/org/fcrepo/http/api/FedoraLdpTest.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/webxml/WebAppConfig.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/RdfLexicon.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/observer/FedoraEvent.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/utils/NamespaceTools.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/utils/UncheckedPredicate.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/utils/iterators/RdfStream.java
fcrepo-kernel-api/src/test/java/org/fcrepo/kernel/api/RdfLexiconTest.java
fcrepo-kernel-api/src/test/java/org/fcrepo/kernel/api/utils/iterators/RdfStreamTest.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/FedoraResourceImpl.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/identifiers/HierarchyConverter.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/rdf/JcrRdfTools.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/rdf/ManagedRdf.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/rdf/impl/LdpContainerRdfContext.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/rdf/impl/NodeTypeRdfContext.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/rdf/impl/SkolemNodeRdfContext.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/rdf/impl/VersionsRdfContext.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/rdf/impl/mappings/ItemDefinitionToTriples.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/utils/iterators/PersistingRdfStreamConsumer.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/integration/kernel/modeshape/FedoraResourceImplIT.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/ContainerImplTest.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/FedoraResourceImplTest.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/rdf/JcrRdfToolsTest.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/rdf/impl/NamespaceContextTest.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/utils/iterators/ManagedRdfTest.java
fcrepo-webapp/src/test/java/org/fcrepo/integration/FedoraHtmlResponsesIT.java

https://jira.duraspace.org/browse/FCREPO-1681

Replace guava's Function and Predicate with Java8 idioms

---

fcrepo-auth-common/src/test/java/org/fcrepo/auth/common/ServletContainerAuthenticationProviderTest.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/FedoraFixityTest.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/FedoraLdpTest.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/FedoraVersioningTest.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/api/rdf/HttpResourceConverter.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/observer/FedoraEvent.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/utils/iterators/RdfStream.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/FedoraResourceImpl.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/rdf/impl/HashRdfContext.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/rdf/impl/LdpContainerRdfContext.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/rdf/impl/NodeTypeRdfContext.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/rdf/impl/PropertiesRdfContext.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/rdf/impl/ReferencesRdfContext.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/rdf/impl/SkolemNodeRdfContext.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/rdf/impl/VersionsRdfContext.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/integration/kernel/modeshape/FedoraResourceImplIT.java
fcrepo-transform/src/main/java/org/fcrepo/transform/TransformationFactory.java
fcrepo-transform/src/test/java/org/fcrepo/transform/http/FedoraTransformTest.java
fcrepo-webapp/src/test/java/org/fcrepo/integration/FedoraHtmlResponsesIT.java

https://jira.duraspace.org/browse/FCREPO-1685

Reduce compiler warnings

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/exceptionhandlers/HeaderValueExceptionMapper.java

Resolves: https://jira.duraspace.org/browse/FCREPO-1668

Proper feedback on malformed client-provided etag header

---

fcrepo-webapp/src/test/java/org/fcrepo/integration/AbstractResourceIT.java

https://jira.duraspace.org/browse/FCREPO-1687

add missing javadoc parameters

---

README.md
pom.xml

https://jira.duraspace.org/browse/FCREPO-1698

Removing remaining references to PermGen

---

index.html

Related to: https://jira.duraspace.org/browse/FCREPO-1683

update URLs in gh docs

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/repository/FedoraRepositoryExport.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/repository/FedoraRepositoryImport.java

FCREPO-1666
https://jira.duraspace.org/browse/FCREPO-1666

Mark fcr:import/fcr:export as deprecated.

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java

Resolves: https://jira.duraspace.org/browse/FCREPO-1667

Catch empty body PUT request error

---

fcrepo-boms/fcrepo-jcr-bom/pom.xml
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-http-commons/pom.xml

Part 1 of 2: Adding an IT to demonstrate FCREPO-1712.

Adding IT to demonstrate FCREPO-1712

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-kernel-modeshape/src/main/resources/fedora-node-types.cnd

- mimetype and filename
Resolves: https://jira.duraspace.org/browse/FCREPO-1720
Follow-on to: https://jira.duraspace.org/browse/FCREPO-1532

Update CND to define cardinality of binary properties:

---

fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/RdfLexicon.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/rdf/converters/ValueConverter.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/rdf/impl/SkolemNodeRdfContext.java

Some code cleanup before moving on to the SkolemNode unit tests

code cleanup

---

fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/RdfLexicon.java

See: https://jira.duraspace.org/browse/FCREPO-1722

made inaccessibleResource individual lowercase to align with ontology

---

fcrepo-boms/fcrepo4-bom/pom.xml
fcrepo-parent/pom.xml

See: https://jira.duraspace.org/browse/FCREPO-1728

set build-tools version

---

fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/RdfLexicon.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/rdf/impl/FixityRdfContext.java

See: https://jira.duraspace.org/browse/FCREPO-1746

use premis:hasEventOutcome for fixity results, and don't set it as immutable

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraVersioning.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraBackupIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraFixityIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersionsIT.java

Resolves: https://jira.duraspace.org/browse/FCREPO-1755

Version creation should return 201

---

pom.xml

See: https://jira.duraspace.org/browse/FCREPO-1796

update max metaspace size

---

fcrepo-parent/pom.xml
pom.xml

See: https://jira.duraspace.org/browse/FCREPO-1783

define scm directly instead of relying on inheritance

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java

Fixes https://jira.duraspace.org/browse/FCREPO-1800

Filtering out server-managed triples about hash URI fragments

---

fcrepo-http-api/src/main/resources/views/common-metadata.vsl
fcrepo-http-api/src/main/resources/views/common-node-actions.vsl
fcrepo-http-api/src/main/resources/views/fcr-versions.vsl
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraHtmlIT.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/responses/ViewHelpers.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/responses/ViewHelpersTest.java

https://jira.duraspace.org/browse/FCREPO-1813

Code cleanup in ViewHelpers

---

fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/rdf/impl/FixityRdfContext.java

* Also using List instead of Set for predictable triple ordering (makes output RDF prettier)
Fixes https://jira.duraspace.org/browse/FCREPO-1669

Removing ContentLocation which just reiterated the file path and leaked JCR impl. details

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraVersions.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersionsIT.java

Fixes https://jira.duraspace.org/browse/FCREPO-1702

Removing FedoraVersions instance variable that was hiding superclass instance

---

fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/responses/ViewHelpersTest.java

See: https://jira.duraspace.org/browse/FCREPO-1811

add guard for non-literal titles

---

fcrepo-http-api/src/main/resources/views/common-node-actions.vsl
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/responses/ViewHelpers.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/responses/ViewHelpersTest.java

Fixes regression described here: https://github.com/fcrepo4/fcrepo4/commit/0014cd7c6440b5e22112db146970a58c7d623fad#commitcomment-14671594

fix frozen node regression

---

fcrepo-jms/pom.xml
fcrepo-jms/src/main/java/org/fcrepo/jms/headers/DefaultMessageFactory.java
fcrepo-jms/src/test/java/org/fcrepo/jms/headers/DefaultMessageFactoryTest.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/observer/FedoraEvent.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/observer/FedoraEventImpl.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/observer/GetNamespacedProperties.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/observer/eventmappings/AllNodeEventsOneEvent.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/observer/eventmappings/OneToOne.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/observer/FedoraEventTest.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/observer/GetNamespacedPropertiesTest.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/observer/SimpleObserverTest.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/observer/eventmappings/OneToOneTest.java

Resolves: https://jira.duraspace.org/browse/FCREPO-1848
Doing so also move us closer to a resolution of fcrepo-1847

change FedoraEvent to an interface, remove jcr/modeshape dependency from jms module

---

index.html

See: https://jira.duraspace.org/browse/FCREPO-1862

update developer documentation page

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/models/FedoraBinary.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/FedoraBinaryImpl.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/FedoraBinaryImplTest.java

See: https://jira.duraspace.org/browse/FCREPO-1891

remove jcr.Binary from the kernel-api

---

fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/models/FedoraResource.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/FedoraResourceImpl.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/rdf/impl/LdpContainerRdfContext.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/rdf/impl/LdpIsMemberOfRdfContext.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/integration/kernel/modeshape/FedoraResourceImplIT.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/FedoraResourceImplTest.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/rdf/impl/LdpIsMemberOfRdfContextTest.java

See: https://jira.duraspace.org/browse/FCREPO-1894

remove jcr.Property from fcrepo-kernel-api

---

pom.xml

Resolves: https://jira.duraspace.org/browse/FCREPO-1886

Bump ModeShape version to 4.5.0.Final

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/repository/FedoraRepositoryNodeTypes.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/repository/FedoraRepositoryNodeTypesTest.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraNodeTypesIT.java

See: https://jira.duraspace.org/browse/FCREPO-1892

add Warning header to /fcr:nodetypes endpoint

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraNodes.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraNodesIT.java

Fixes https://jira.duraspace.org/browse/FCREPO-1873

Fixing binary move/rename (and improving test coverage)

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/repository/FedoraRepositoryNodeTypes.java

Related to https://jira.duraspace.org/browse/FCREPO-1892

Adding specific version to deprecation warning

---

fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/rdf/converters/PropertyConverter.java

Fixes https://jira.duraspace.org/browse/FCREPO-1920

Only warn about namespaces mismatches if there are any user-defined namespaces

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java

- https://jira.duraspace.org/browse/FCREPO-1878

Remove dead code created by:

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraBaseResource.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraFixity.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraVersioning.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraVersions.java

Resolves: https://jira.duraspace.org/browse/FCREPO-1932

Refactor translator().reverse().convert(resource).asNode()

---

fcrepo-http-api/pom.xml
fcrepo-http-api/src/main/java/org/fcrepo/http/api/responses/StreamingBaseHtmlProvider.java
fcrepo-http-api/src/main/resources/views/binary.vsl
fcrepo-http-api/src/main/resources/views/common.css
fcrepo-http-api/src/main/resources/views/default.vsl
fcrepo-http-api/src/main/resources/views/fcr-fixity.vsl
fcrepo-http-api/src/main/resources/views/fcr-versions.vsl
fcrepo-http-api/src/main/resources/views/resource.vsl
fcrepo-http-api/src/main/resources/views/root.vsl
fcrepo-http-api/src/test/java/org/fcrepo/http/api/responses/StreamingBaseHtmlProviderTest.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraHtmlIT.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/rdf/impl/RootRdfContext.java

See: https://jira.duraspace.org/browse/FCREPO-1934
This introduces an RDFS Class: `fedora:RepositoryRoot`. Once we have the green light on this impl, that class will need to be added to the core ontology.

rework HTML template rendering

---

fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/rdf/impl/RootRdfContext.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/integration/kernel/modeshape/FedoraResourceImplIT.java

Resolves: https://jira.duraspace.org/browse/FCREPO-1939

add fedora RDF types to Root resource

---

fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/api/rdf/HttpResourceConverter.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/api/rdf/HttpResourceConverterTest.java

Resolves: https://jira.duraspace.org/browse/FCREPO-1884

Allow references to the Root resource to omit a trailing slash

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/repository/FedoraRepositoryNodeTypes.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/repository/FedoraRepositoryNodeTypesTest.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraNodeTypesIT.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/services/NodeService.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/rdf/impl/NodeTypeRdfContext.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/services/NodeServiceImpl.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/rdf/impl/NodeTypeRdfContextTest.java

Resolves: https://jira.duraspace.org/browse/FCREPO-1966

Deprecate FedoraNodeTypes

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/api/rdf/HttpResourceConverter.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/services/NodeServiceImpl.java

Fixes https://jira.duraspace.org/browse/FCREPO-1837

Translating invalid path requests to InvalidResourceIdentifierException/400 Bad Request

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraExport.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraImport.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraExportIT.java

Resolves: https://jira.duraspace.org/browse/FCREPO-1977

Add Warning headers to deprecated endpoints

---

fcrepo-http-api/src/main/resources/views/resource.vsl

Resolves: https://jira.duraspace.org/browse/FCREPO-1986

add 'other resources' section to container template

---

fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/FedoraResourceImpl.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/integration/kernel/modeshape/FedoraResourceImplIT.java

Resolves: https://jira.duraspace.org/browse/FCREPO-1985

Clean up orphaned hash URIs

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java

Resolves: https://jira.duraspace.org/browse/FCREPO-1993

Read PATCH requests as UTF-8 encoded input streams

---

fcrepo-http-api/src/main/resources/views/common.js
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/TombstoneImpl.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/integration/kernel/modeshape/TombstoneImplIT.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/TombstoneImplTest.java

Resolves: https://jira.duraspace.org/browse/FCREPO-1997

Remove JCR details from Tombstone

---

fcrepo-parent/pom.xml

Resolves: https://jira.duraspace.org/browse/FCREPO-2004

Update fcrepo-parent to use the latest version of fcrepo-build-tools

---

fcrepo-webapp/src/main/webapp/index.html

* Adding spans with IDs around release info in HTML UI, to make it easier to parse.
Potential low-impact solution to https://jira.duraspace.org/browse/FCREPO-1774

Adding spans around release info

---

fcrepo-auth-common/src/main/java/org/fcrepo/auth/common/FedoraUserSecurityContext.java
fcrepo-auth-common/src/test/java/org/fcrepo/auth/common/FedoraUserSecurityContextTest.java

https://jira.duraspace.org/browse/FCREPO-2024

Allow any user to register namespaces and types.

---

fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/FedoraResourceImpl.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/rdf/impl/PropertiesRdfContext.java

Amends https://jira.duraspace.org/browse/FCREPO-1742 to support advanced authorization scenarios.

Updated to code to gracefully handle failure to migrate property.

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/FedoraBinaryImpl.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/integration/kernel/modeshape/FedoraBinaryImplIT.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/FedoraBinaryImplTest.java

Resolves: https://jira.duraspace.org/browse/FCREPO-1983
Resolves: https://jira.duraspace.org/browse/FCREPO-1754

Fix ETag handling for Binaries and Binary descriptions

---

fcrepo-http-api/src/test/java/org/fcrepo/http/api/url/HttpApiResourcesTest.java
fcrepo-jms/src/test/java/org/fcrepo/integration/jms/observer/HeadersJMSIT.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/integration/kernel/modeshape/services/BinaryServiceImplIT.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/integration/kernel/modeshape/services/RepositoryServiceImplIT.java

Resolves: https://jira.duraspace.org/browse/FCREPO-2046

Replace use of org.jgroups methods with standard junit or java.util equivalents

---

fcrepo-auth-common/src/test/java/org/fcrepo/auth/integration/ContainerRolesPrincipalProviderIT.java
fcrepo-auth-common/src/test/java/org/fcrepo/auth/integration/DelegatedUserIT.java
fcrepo-auth-common/src/test/java/org/fcrepo/auth/integration/HttpHeaderPrincipalProviderIT.java
fcrepo-auth-common/src/test/java/org/fcrepo/auth/integration/ModeShapeHonorsFADResponseIT.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraTransactions.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/domain/ContentLocationMessageBodyReader.java

Resolves: https://jira.duraspace.org/browse/FCREPO-2047
Note: this does not change the instances of @Autowired that are removed in #1043

Replace @Autowired annotations with the standard @Inject annotation

---

fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/services/Service.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/services/policy/StoragePolicy.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/services/policy/StoragePolicyDecisionPoint.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/FedoraBinaryImpl.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/services/BinaryServiceImpl.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/services/ContainerServiceImpl.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/services/NodeServiceImpl.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/services/BinaryServiceImplTest.java

Resolves: https://jira.duraspace.org/browse/FCREPO-2048

Remove all trace of javax.jcr.Node from the kernel-api

---

.gitignore
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/FedoraContextLoaderListener.java
fcrepo-webapp/pom.xml
fcrepo-webapp/src/main/resources/spring/repo.xml
fcrepo-webapp/src/main/webapp/WEB-INF/web.xml

* Enable default ModeShape config for the one-click
* To build one-click, user Maven profile -Pone-click
Resolves: https://jira.duraspace.org/browse/FCREPO-2052

Remove default ModeShape configuration for deployable war

---

pom.xml

Resolves: https://jira.duraspace.org/browse/FCREPO-2062

Upgrade to ModeShape 5.1.0.Final

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java

Addresses [FCREPO-2075](https://jira.duraspace.org/browse/FCREPO-2075)

Throw an exception if a non-SHA1 digest is passed

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/responses/ViewHelpers.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/responses/ViewHelpersTest.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/RdfLexicon.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/rdf/impl/ChildrenRdfContext.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/integration/kernel/modeshape/FedoraResourceImplIT.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/rdf/impl/ChildrenRdfContextTest.java

Resolves: https://jira.duraspace.org/browse/FCREPO-1880

Remove fedora:numberOfChildren predicate

---

fcrepo-connector-file/src/main/java/org/fcrepo/connector/file/FedoraFileSystemConnector.java

Just until we actually move it.
Related to [FCREPO-2028](https://jira.duraspace.org/browse/FCREPO-2028)

Add a logger warning when using fcrepo-connector-file

---

fcrepo-http-api/src/main/resources/views/common-node-actions.vsl
fcrepo-http-api/src/main/resources/views/common.js

Resolves: https://jira.duraspace.org/browse/FCREPO-2080

Adjust HTML UI (JavaScript) to prevent double-click events from causing unintended duplicate actions

---

fcrepo-webapp/pom.xml
fcrepo-webapp/src/main/webapp/WEB-INF/web.xml

Resolves: https://jira.duraspace.org/browse/FCREPO-2083

Add a servlet filter for handling ETags for static resources

---

fcrepo-http-api/src/main/resources/views/common-header.vsl
fcrepo-http-api/src/main/resources/views/common-node-actions.vsl
fcrepo-http-api/src/main/resources/views/common.css
fcrepo-http-api/src/main/resources/views/common.js

Resolves: https://jira.duraspace.org/browse/FCREPO-2081

Remove jQuery dependencies on the javascript code in fcrepo-http-api

---

fcrepo-auth-common/pom.xml
fcrepo-boms/fcrepo-jcr-bom/pom.xml
fcrepo-boms/fcrepo4-bom/pom.xml
fcrepo-boms/pom.xml
fcrepo-configs/pom.xml
fcrepo-connector-file/pom.xml
fcrepo-event-serialization/pom.xml
fcrepo-http-api/pom.xml
fcrepo-http-commons/pom.xml
fcrepo-integration-ldp/pom.xml
fcrepo-integration-rdf/pom.xml
fcrepo-jms/pom.xml
fcrepo-kernel-api/pom.xml
fcrepo-kernel-modeshape/pom.xml
fcrepo-metrics/pom.xml
fcrepo-parent/pom.xml
fcrepo-webapp/pom.xml
pom.xml

Addresses: https://jira.duraspace.org/browse/FCREPO-2091

Increment to 4.7.0-SNAPSHOT for next development cycle

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/rdf/converters/ValueConverter.java

Resolves: https://jira.duraspace.org/browse/FCREPO-2090
Note: this should be merged _after_ https://jira.duraspace.org/browse/FCREPO-2091 but before #1075 (which can be simplified after this change)

Allow deletion of non-string literals via sparql-update

---

fcrepo-webapp/src/main/webapp/index.html

Resolves: https://jira.duraspace.org/browse/FCREPO-2085

Clean up intro text in index.html

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java

Resolves: https://jira.duraspace.org/browse/FCREPO-2098

Properly support HTTP Patch with If-Match header checking

---

fcrepo-configs/src/main/resources/config/servlet-auth/repository.json

Related to: https://jira.duraspace.org/browse/FCREPO-2110

Add repository configuration for AuthZ

---

fcrepo-webapp/src/main/resources/logback.xml

Resolves: https://jira.duraspace.org/browse/FCREPO-2109

Enable inheritance of logging levels

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/FedoraLdpTest.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java

Resolves: https://jira.duraspace.org/browse/FCREPO-2022

Ensure HEAD on external binary content responds with redirect

---

fcrepo-http-api/src/main/resources/views/common.vsl
fcrepo-http-api/src/main/resources/views/fcr-fixity.vsl
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/responses/ViewHelpers.java

Resolves: https://jira.duraspace.org/browse/FCREPO-2124
Related to: https://jira.duraspace.org/browse/FCREPO-1672

Fix bug in HTML UI due to upgrade to Jena 3

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/FedoraLdpTest.java

Resolves: https://jira.duraspace.org/browse/FCREPO-1851

Remove deprecated checksum query param

---

fcrepo-http-api/src/main/resources/views/binary.vsl
fcrepo-http-api/src/main/resources/views/common-node-actions.vsl
fcrepo-http-api/src/main/resources/views/common.vsl

Resolves: https://jira.duraspace.org/browse/FCREPO-2094
Resolves: https://jira.duraspace.org/browse/FCREPO-2125

Removed dead and duplicative HTML template code

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/FedoraResourceImpl.java

Resolves: https://jira.duraspace.org/browse/FCREPO-2213

Update lastModified when child resources are deleted

---

fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/exceptionhandlers/MalformedRdfExceptionMapper.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/exceptionhandlers/MalformedRdfExceptionMapperTest.java

Resolves: https://jira.duraspace.org/browse/FCREPO-2235

Ensure Link header is not longer than 1-KB

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraFixityIT.java
fcrepo-kernel-modeshape/src/main/resources/fedora-node-types.cnd
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/integration/kernel/modeshape/FedoraResourceImplIT.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/rdf/impl/PropertiesRdfContextTest.java

Also make fedoraconfig: non-resolvable
Resolves: https://jira.duraspace.org/browse/FCREPO-2247

Remove test: namespace from the modeshape config

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java

Addresses: https://jira.duraspace.org/browse/FCREPO-1882

Update HTTP Headers in response

---

fcrepo-kernel-modeshape/src/main/resources/fedora-node-types.cnd

Resolves: https://jira.duraspace.org/browse/FCREPO-2258

Add namespaces to the default CND configuration

---

fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/responses/ViewHelpers.java

Addresses: https://jira.duraspace.org/browse/FCREPO-1694

Remove dependency on Modeshape module from the fcrepo-http-commons module

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraFixity.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraVersioning.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraVersions.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/responses/StreamingBaseHtmlProvider.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/responses/StreamingHtmlProvider.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/responses/RdfStreamProvider.java

Resolves: https://jira.duraspace.org/browse/FCREPO-2267

Remove XHTML "support"

---

pom.xml

Resolves: https://jira.duraspace.org/browse/FCREPO-1959

Upgrade to guava 19.0

---

fcrepo-parent/pom.xml

Resolves: https://jira.duraspace.org/browse/FCREPO-1964

Remove sonatype's oss-parent pom

---

fcrepo-http-api/src/test/java/org/fcrepo/http/api/DefaultPathLockManagerTest.java

fixes https://jira.duraspace.org/browse/FCREPO-2270

Fixed a bug that cause intermitted test failures.

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/DefaultPathLockManager.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/PathLockManager.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/DefaultPathLockManagerTest.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/FedoraLdpTest.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/exceptionhandlers/InterruptedExceptionMapper.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/exception/InterruptedRuntimeException.java

https://jira.duraspace.org/browse/FCREPO-2271

Back-ported two commits.

---

fcrepo-auth-common/src/test/java/org/fcrepo/auth/integration/RootTestResource.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraBaseResource.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraFixity.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraNodes.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraTombstones.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraTransactions.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraVersioning.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraVersions.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/repository/FedoraRepositoryBackup.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/repository/FedoraRepositoryRestore.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/FedoraLdpTest.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/FedoraNodesTest.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/FedoraTombstonesTest.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/FedoraTransactionsTest.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/FedoraVersionsTest.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/repository/FedoraRepositoryBackupTest.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/repository/FedoraRepositoryRestoreTest.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/url/HttpApiResourcesTest.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/FedoraApplication.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/api/rdf/HttpResourceConverter.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/session/HttpSession.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/session/SessionFactory.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/session/SessionProvider.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/api/rdf/HttpResourceConverterTest.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/session/HttpSessionTest.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/session/SessionFactoryTest.java

Resolves: https://jira.duraspace.org/browse/FCREPO-2278

Add a batch-aware HttpSession class

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraFixity.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraVersioning.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraVersions.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/responses/RdfStreamProvider.java

Resolves: https://jira.duraspace.org/browse/FCREPO-2266

Remove support for application/xml mime type

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/repository/FedoraRepositoryBackup.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/repository/FedoraRepositoryRestore.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/repository/FedoraRepositoryBackupTest.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/repository/FedoraRepositoryRestoreTest.java

Addresses: https://jira.duraspace.org/browse/FCREPO-2044

Add warning that the backup and restore endpoints will be externalized

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraFixity.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraVersioning.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraVersions.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/ViewAssets.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/responses/StreamingBaseHtmlProvider.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/responses/StreamingHtmlProvider.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/domain/RDFMediaType.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/responses/RdfStreamProvider.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/test/util/TestHelpers.java

Resolves: https://jira.duraspace.org/browse/FCREPO-1750

Add charset encoding for text/* content-type serializations

---

fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/exceptionhandlers/TombstoneExceptionMapper.java

Resolves: https://jira.duraspace.org/browse/FCREPO-2123

Set the tombstone response type as text/plain

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraVersioning.java
fcrepo-kernel-api/pom.xml
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/FedoraVersion.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/models/FedoraResource.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/services/CredentialsService.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/services/Service.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/services/policy/StoragePolicyDecisionPoint.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/FedoraBinaryImpl.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/FedoraResourceImpl.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/FedoraVersionImpl.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/NonRdfSourceDescriptionImpl.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/rdf/impl/VersionsRdfContext.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/services/CredentialsServiceImpl.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/integration/kernel/modeshape/FedoraResourceImplIT.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/FedoraResourceImplTest.java

Remove jcr-based Version references
Remove miscellaneous JCR references from the kernel-api
Resolves: https://jira.duraspace.org/browse/FCREPO-1867
Resolves: https://jira.duraspace.org/browse/FCREPO-1847

Remove JCR from the kernel-api

---

fcrepo-boms/fcrepo-jcr-bom/pom.xml
fcrepo-integration-ldp/pom.xml
fcrepo-webapp/pom.xml
pom.xml

Addresses: https://jira.duraspace.org/browse/FCREPO-2285
Resolves: https://jira.duraspace.org/browse/FCREPO-2279

Update dependency versions

---

fcrepo-event-serialization/src/main/java/org/fcrepo/event/serialization/JsonLDSerializer.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/FedoraLdpTest.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/FedoraApplication.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/responses/RangeRequestInputStreamTest.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/test/util/TestHelpers.java
fcrepo-integration-rdf/src/test/java/org/fcrepo/integration/rdf/AbstractIntegrationRdfIT.java
fcrepo-jms/src/test/java/org/fcrepo/integration/jms/observer/AbstractJmsIT.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/utils/ContentDigest.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/FedoraResourceImpl.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/rdf/converters/PropertyConverter.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/integration/kernel/modeshape/ContainerImplIT.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/integration/kernel/modeshape/FedoraResourceImplIT.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/FedoraResourceImplTest.java
fcrepo-parent/pom.xml

Resolves: https://jira.duraspace.org/browse/FCREPO-2294

Replace deprecated methods with better versions

---

pom.xml

Resolves: https://jira.duraspace.org/browse/FCREPO-2293

Update ModeShape version to 4.6.2.Final

---

fcrepo-http-api/src/test/java/org/fcrepo/http/api/DefaultPathLockManagerTest.java

Related to: https://jira.duraspace.org/browse/FCREPO-2270

Fixed a bug that cause intermittent test failures.

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/FedoraBinaryImpl.java

Resolves: https://jira.duraspace.org/browse/FCREPO-2317

Ensure XSDType not in Content-Disposition filename response header

---

fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/FedoraResourceImpl.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/rdf/impl/SkolemNodeRdfContext.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/rdf/impl/mappings/PropertyToTriple.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/integration/kernel/modeshape/FedoraResourceImplIT.java

Back-port to the 4.6-maintenance branch of:
- https://jira.duraspace.org/browse/FCREPO-2323

Backport of fcrepo-2363

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java

Resolves [FCREPO-2370](https://jira.duraspace.org/browse/FCREPO-2370) for 4.7.1-RC

Explicitly encode test objects as utf8

---

fcrepo-kernel-modeshape/src/main/resources/fedora-node-types.cnd

Fixes https://jira.duraspace.org/browse/FCREPO-2375

Restoring test namespace

---

fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/exceptionhandlers/WebApplicationExceptionMapper.java

Resolves: https://jira.duraspace.org/browse/FCREPO-2385

Reduce logging level of WebApplicationException

---

fcrepo-parent/pom.xml
pom.xml

Impact from: https://jira.duraspace.org/browse/FCREPO-1964

Update pom files adding 'repository' to 'distributionManagement'

---

fcrepo-parent/pom.xml
pom.xml

Reverts fcrepo4/fcrepo4#1161
Not quite the right fix, yet.

Revert "Update pom files adding 'repository' to 'distributionManagement'"

---

jena-patch/pom.xml

Related to: https://jira.duraspace.org/browse/FCREPO-2374

Enable javadocs, but disable failure on error: jena-patch

---

pom.xml

Fixes https://jira.duraspace.org/browse/FCREPO-2392

Updating to Modeshape 5.3.0.Final

---

fcrepo-http-api/src/main/resources/views/common.js

Resolves https://jira.duraspace.org/browse/FCREPO-2387

HTML UI: External Content redirects to binary description

---

fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/utils/JcrPropertyStatementListener.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/integration/kernel/modeshape/FedoraResourceImplIT.java
fcrepo-kernel-modeshape/src/test/resources/patch-test/delete-where.txt
fcrepo-kernel-modeshape/src/test/resources/patch-test/insert-data.txt

- buffer unique statement operations to prevent OOM on large sparql update solution products

FCREPO-2391: buffer unique statement operation when processing PATCH

---

fcrepo-parent/pom.xml
pom.xml

* Add in needed sonatype repo information. (#1164)
* Add scm and developers to fcrepo-parent pom (#1165)
- Required by release plugin
Resolves: https://jira.duraspace.org/browse/FCREPO-2394

Update pom.xml configuration for release

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraFixityIT.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/RdfLexicon.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/utils/FixityResult.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/rdf/impl/FixityRdfContext.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/utils/BasicCacheEntry.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/utils/FixityResultImpl.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/utils/FixityResultImplTest.java

https://jira.duraspace.org/browse/FCREPO-2297

Improve Fixity Result response

---

fcrepo-configs/src/main/resources/config/clustered-mysql/repository.json
fcrepo-configs/src/main/resources/config/file-simple/repository.json
fcrepo-configs/src/main/resources/config/jdbc-mysql/repository.json
fcrepo-configs/src/main/resources/config/jdbc-postgresql/repository.json
fcrepo-configs/src/main/resources/config/servlet-auth/repository.json

Resolves:  https://jira.duraspace.org/browse/FCREPO-2406

Adds default garbage collection configuration to repository.json files

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/FedoraLdpTest.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java

Resolves https://jira.duraspace.org/browse/FCREPO-2399

LDP-RS that describe LDP-NR correctly advertise allowable methods.

---

fcrepo-http-commons/pom.xml

Resolves: https://jira.duraspace.org/browse/FCREPO-2416

Ensure vulnerable libraries are excluded from Fedora

---

fcrepo-http-commons/pom.xml

See: 
* https://jira.duraspace.org/browse/FCREPO-2416
* https://github.com/fcrepo4/fcrepo4/pull/1179
* https://github.com/fcrepo4/fcrepo4/pull/1180

Ensure vulnerable libraries are excluded from Fedora.

---

fcrepo-configs/src/main/resources/config/clustered-mysql/repository.json
fcrepo-configs/src/main/resources/config/file-simple/repository.json
fcrepo-configs/src/main/resources/config/jdbc-mysql/repository.json
fcrepo-configs/src/main/resources/config/jdbc-postgresql/repository.json
fcrepo-configs/src/main/resources/config/servlet-auth/repository.json
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/responses/RdfStreamStreamingOutput.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/responses/SynchonizedStreamRDFWrapper.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/rdf/impl/ReferencesRdfContext.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/utils/StreamUtils.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/rdf/impl/ReferencesRdfContextTest.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/testutilities/TestPropertyIterator.java

https://jira.duraspace.org/browse/FCREPO-2105

Fcrepo 2105 final

---

fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/exceptionhandlers/ConstraintExceptionMapper.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/exceptionhandlers/ConstraintViolationExceptionMapper.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/exceptionhandlers/IncorrectTripleSubjectExceptionMapper.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/exceptionhandlers/OutOfDomainSubjectExceptionMapper.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/exceptionhandlers/ServerManagedPropertyExceptionMapper.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/exceptionhandlers/ServerManagedTypeExceptionMapper.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/exceptionhandlers/ConstraintViolationExceptionMapperTest.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/test/util/TestHelpers.java

- uses context from servlet to get correct location of file
Resolves: https://jira.duraspace.org/browse/FCREPO-2379

Makes ldp:constrainedBy point to correct location

---

fcrepo-webapp/pom.xml

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2422
Points to correct configuration file to allow for one-click property to filter into the packaged webapp.
1. Build everything : `mvn clean install`
1. Build fcrepo-webapp : `mvn clean install -Pone-click`
1. Double click the file `target/fcrepo-4.8.0-SNAPSHOT-jetty-console.jar` or `java -jar target/fcrepo-4.8.0-SNAPSHOT-jetty-console.jar`
1. Press the Start button
Did the repository start? Then 👍 
Example:
* Could this change …

Point to correct configuration file for one-click webapp

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/AbstractResourceIT.java
fcrepo-integration-rdf/src/test/java/org/fcrepo/integration/rdf/AbstractIntegrationRdfIT.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/rdf/JcrRdfTools.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/utils/BNodeSkolemizationUtil.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/utils/JcrPropertyStatementListener.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/utils/iterators/PersistingRdfStreamConsumer.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/integration/kernel/modeshape/FedoraResourceImplIT.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/rdf/JcrRdfToolsTest.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/utils/JcrPropertyStatementListenerTest.java

This pull request includes Esme's completing for https://jira.duraspace.org/browse/FCREPO-2108 as well as my modifications to support  https://jira.duraspace.org/browse/FCREPO-2431.

Fcrepo 2431

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/FedoraResourceImpl.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/rdf/converters/PropertyConverter.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/utils/iterators/RdfAdder.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/utils/iterators/RdfAdderTest.java

Fixes https://jira.duraspace.org/browse/FCREPO-2376

User-supplied namespace prefixes

---

fcrepo-auth-common/pom.xml
fcrepo-boms/fcrepo-jcr-bom/pom.xml
fcrepo-boms/fcrepo4-bom/pom.xml
fcrepo-boms/pom.xml
fcrepo-configs/pom.xml
fcrepo-event-serialization/pom.xml
fcrepo-http-api/pom.xml
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraFixityIT.java
fcrepo-http-commons/pom.xml
fcrepo-integration-ldp/pom.xml
fcrepo-integration-rdf/pom.xml
fcrepo-jms/pom.xml
fcrepo-kernel-api/pom.xml
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/FedoraTypes.java
fcrepo-kernel-modeshape/pom.xml
fcrepo-kernel-modeshape/src/main/resources/fedora-node-types.cnd
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/integration/kernel/modeshape/FedoraResourceImplIT.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/rdf/impl/PropertiesRdfContextTest.java
fcrepo-metrics/pom.xml
fcrepo-parent/pom.xml
fcrepo-webapp/pom.xml
fcrepo-webapp/src/test/java/org/fcrepo/integration/FedoraHtmlResponsesIT.java
jena-patch/pom.xml
pom.xml

housekeeping to fix 4.7 maintenance branch.

4.7 maintenance repair

---

fcrepo-webapp/pom.xml

This reverts commit 9afdf9ab54679c645f92294ab22bbe7407c91259.

Revert "Point to correct configuration file for one-click (#1189)"

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/responses/RangeRequestInputStreamTest.java

Fixes https://jira.duraspace.org/browse/FCREPO-2536

Using range length for content-length header

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraFixityIT.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/FedoraTypes.java
fcrepo-kernel-modeshape/src/main/resources/fedora-node-types.cnd
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/integration/kernel/modeshape/FedoraResourceImplIT.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/rdf/impl/PropertiesRdfContextTest.java
fcrepo-webapp/src/test/java/org/fcrepo/integration/FedoraHtmlResponsesIT.java

Revert CND/namespace changes.
Bring the equivalent of the following commits into the master branch: 
https://github.com/fcrepo4/fcrepo4/commit/6a0bcda5ed1d3fc93375302091aa20fe80b7bfc3 
https://github.com/fcrepo4/fcrepo4/commit/000236204185c22d6623d04f90e5f2bc9ee73d1c 
https://github.com/fcrepo4/fcrepo4/commit/eb0ca36940aaaf4c6351d977cd8da720dcb3987f 
https://github.com/fcrepo4/fcrepo4/commit/d70c35bf460cefe8890aee4712dab1d5f7d646c4
Resolves:
https://jira.duraspace.org/browse/FCREPO-2538
p.s. Please Do Not Squash This PR

Fcrepo 2538

---

fcrepo-http-api/src/main/resources/views/common.js

Cherry pick of [commit to master](https://github.com/fcrepo4/fcrepo4/commit/34795a15074984f1a238eecbbff16ccf8004f41b).
Also resolves: https://jira.duraspace.org/browse/FCREPO-2539

Fix redirection of URIs ending /fcr:tx in HTML UI

---

fcrepo-auth-common/pom.xml
fcrepo-boms/fcrepo-jcr-bom/pom.xml
fcrepo-boms/fcrepo4-bom/pom.xml
fcrepo-boms/pom.xml
fcrepo-configs/pom.xml
fcrepo-event-serialization/pom.xml
fcrepo-http-api/pom.xml
fcrepo-http-commons/pom.xml
fcrepo-integration-ldp/pom.xml
fcrepo-integration-rdf/pom.xml
fcrepo-jms/pom.xml
fcrepo-kernel-api/pom.xml
fcrepo-kernel-modeshape/pom.xml
fcrepo-metrics/pom.xml
fcrepo-parent/pom.xml
fcrepo-webapp/pom.xml
pom.xml

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2575
Just bumps the version of Fedora to `5.0.0-SNAPSHOT`
Development on master breaks the 5.0.0 threshold, and invites breaking API changes.
* Ideally, remove Fedora artifacts from your local repository `~/.m2/repository`
* Build Fedora `mvn clean install`
* Check artifacts in `~/.m2/repository/org/fcrepo` for anything untoward

Update version to 5.0.0-SNAPSHOT

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/FedoraLdpTest.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/models/FedoraBinary.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/utils/CacheEntry.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/utils/ContentDigest.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/FedoraBinaryImpl.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/utils/BasicCacheEntry.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/integration/kernel/modeshape/FedoraBinaryImplIT.java

Fixes https://jira.duraspace.org/browse/FCREPO-2601
Add support for Want-Digest header with fixity check on NonRDFSource.

Support Want-Digest header with fixity check for NonRDFSource.

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/FedoraLdpTest.java
fcrepo-webapp/src/main/webapp/static/constraints/ContainerConstraints.rdf

Fixes https://jira.duraspace.org/browse/FCREPO-2592?filter=14302

Add Link rel=ldp:constrainedby header for Containers

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java

Fixes https://jira.duraspace.org/browse/FCREPO-2598

Adding tests verifying the Digest header is consistent for GET and HEAD

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/domain/PreferTag.java

Fixes https://jira.duraspace.org/browse/FCREPO-2596
Updated to add appropriate Preference-Applied header for Get request.

Ensure correct behavior of returning Preference-Applied header for Get request.

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/domain/PreferTag.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/domain/ldp/LdpPreferTag.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/domain/ldp/LdpPreferTagTest.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/RdfLexicon.java

Fixes https://jira.duraspace.org/browse/FCREPO-2595

Support oa:PreferContainedDescriptions prefer header

---

fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/utils/NodePropertiesTools.java

Resolves: https://jira.duraspace.org/browse/FCREPO-2629
To test: run script in above ticket:
https://gist.github.com/kefo/3272ec4fa07da7ab9855db843922b295
..the error command should now pass (./langtag_test update_resource).

Handle update to properties with lang value

---

fcrepo-auth-webac/src/test/java/org/fcrepo/integration/auth/webac/WebACRecipesIT.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/url/HttpApiResources.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/url/HttpApiResourcesTest.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraFixityIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersionsIT.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/responses/ViewHelpers.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/responses/ViewHelpersTest.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/FedoraBinaryImpl.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/FedoraResourceImpl.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/FedoraVersionImpl.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/NonRdfSourceDescriptionImpl.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/rdf/impl/VersionsRdfContext.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/services/VersionServiceImpl.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/integration/kernel/modeshape/FedoraResourceImplIT.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/integration/kernel/modeshape/services/VersionServiceImplIT.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/services/VersionServiceImplTest.java

Related to: https://jira.duraspace.org/browse/FCREPO-2634

Reintroduce Versioning placeholders

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java

Removes an 'i' from 'Algorithim' in an error message.

Fix misspelled error message.

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/FedoraLdpTest.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/exceptionhandlers/UnsupportedAccessTypeExceptionMapper.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/exception/UnsupportedAccessTypeException.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/models/FedoraBinary.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/FedoraBinaryImpl.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/utils/BasicCacheEntry.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/utils/ExternalResourceCacheEntry.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/utils/impl/CacheEntryFactory.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/integration/kernel/modeshape/FedoraBinaryImplIT.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/utils/ExternalResourceCacheEntryTest.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/utils/impl/CacheEntryFactoryTest.java

Fixes https://jira.duraspace.org/browse/FCREPO-2587
Add support for Head and Get with Want-Digest header to external content.

Support Want-Digest for external content with Head and Get

---

fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/FedoraTypes.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/models/FedoraResource.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/models/FedoraTimeMap.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/FedoraResourceImpl.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/FedoraTimeMapImpl.java
fcrepo-kernel-modeshape/src/main/resources/fedora-node-types.cnd
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/integration/kernel/modeshape/FedoraResourceImplIT.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/integration/kernel/modeshape/FedoraTimeMapImplIT.java

Fixes https://jira.duraspace.org/browse/FCREPO-2639
Create LDPCv resource for TimeMap.

Create LDPCv resource for TimeMap.

---

fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/WebACRolesProvider.java
fcrepo-auth-webac/src/test/java/org/fcrepo/integration/auth/webac/WebACRecipesIT.java
fcrepo-event-serialization/src/main/java/org/fcrepo/event/serialization/JsonLDEventMessage.java
fcrepo-event-serialization/src/test/java/org/fcrepo/event/serialization/FedoraEventSerializerTestBase.java
fcrepo-jms/src/test/java/org/fcrepo/jms/DefaultMessageFactoryTest.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/FedoraSession.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/observer/FedoraEvent.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/FedoraSessionImpl.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/observer/FedoraEventImpl.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/observer/SimpleObserver.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/utils/FedoraSessionUserUtil.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/integration/kernel/modeshape/FedoraSessionImplIT.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/observer/FedoraEventImplTest.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/kernel/modeshape/services/BatchServiceImplTest.java

Fixes https://jira.duraspace.org/browse/FCREPO-2628
Rename signature UserAgent to UserURI in FedoraSession and FedoraEvent.

Rename signature UserAgent to UserURI in FedoraSession and FedoraEvent.

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraVersioning.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/AbstractResourceIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersioningIT.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/domain/RDFMediaType.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/responses/LinkFormatProvider.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/responses/LinkFormatStream.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/RdfLexicon.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2623
Adds response to GET/HEAD requests to the Memento TimeMap located at /fcr:versions.
1. Adds a Link header with a placeholder TimeMap RDF type to the response
1. Adds a new MessageBodyWriter for a stream of Links for the body of the application/link-format content.
1. Create a versionable resource.
```
> curl -i -XPUT -H"Link: <http://fedora.info/definitions/fcrepo#VersionedResource>; rel=\"type\"" http://localhost:8080/rest/versionableObject
Date: Thu, 26 Oct 2017 03:30:21 GMT
ETag: W/"04ca9b02c77e7a3a0af40b59cd29669ff223094b"
Last-Modified: Thu, 26 Oct 2017 03:30:21 GMT
Link: …
```

Add TimeMap response headers and body.

---

fcrepo-webapp/src/main/resources/jbossts-properties.xml

Add jbossts-properties.xml file (the release branch remix)

---

fcrepo-auth-common/pom.xml
fcrepo-boms/fcrepo-jcr-bom/pom.xml
fcrepo-boms/fcrepo4-bom/pom.xml
fcrepo-boms/pom.xml
fcrepo-configs/pom.xml
fcrepo-event-serialization/pom.xml
fcrepo-http-api/pom.xml
fcrepo-http-commons/pom.xml
fcrepo-integration-ldp/pom.xml
fcrepo-integration-rdf/pom.xml
fcrepo-jms/pom.xml
fcrepo-kernel-api/pom.xml
fcrepo-kernel-modeshape/pom.xml
fcrepo-metrics/pom.xml
fcrepo-parent/pom.xml
fcrepo-webapp/pom.xml
fcrepo-webapp/src/main/resources/jbossts-properties.xml
jena-patch/pom.xml
pom.xml

Completes 4.7.5 release by merging 4.7.5-maintenance into 4.7-maintenance.

Close the loop on 4.7.5 release

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/RdfLexicon.java

Changed the PreferInboundReferences URI in Prefer header.
https://jira.duraspace.org/browse/FCREPO-2675

Changed the PreferInboundReferences URI in Prefer header.

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersionsIT.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/domain/PreferTag.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/domain/ldp/LdpPreferTag.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/domain/ldp/LdpPreferTagTest.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/RdfLexicon.java

Change the EmbedResources URI in Prefer header.
https://jira.duraspace.org/browse/FCREPO-2696

Change the EmbedResources URI in Prefer header.

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersioningIT.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2736
Remove unused/incorrect tests for Mementos.
Refactors some utility functions.
Replaces use of `"text/n3"` with `RDFMediaType.N3`
* `public void testVersionHeaders()` only checks for a `NON_RDF_SOURCE` type link header and the (possibly incorrect) describedby link.
* `public void testVersionListHeaders()` only checks for `RDF_SOURCE` which we have decided is incorrect in cases where we have a better type.
The above tests were replaced by the better `public void testGetMementoHeaders()` (now called `public void testGetLDPRSMementoHeaders()`) and the coming `public void testGetLDPNRMementoHeaders()` (`@Ignore`d for the time being).
This is all test refactoring, so if they pass and make sense then we are good.
Example:
* Does this …

Remove RDFSource link header expectation from FedoraVersioning ITs.

---

fcrepo-parent/pom.xml

I am no longer involved with this codebase; please remove my name from the developer list.

Update developer list

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraAcl.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraAclIT.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2806
Adds a GET method for the fcr:acl endpoint.
Added a method to `FedoraAcl` that returns the RDF serialization of the ACL on an HTTP GET request. The method is largely copied from the corresponding method in the `FedoraLdp` class.
* Run standard integration test in FedoraAclIT

FCREPO-2806. Added GET method for fcr:acl endpoint.

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersioningIT.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/api/rdf/HttpResourceConverter.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/exceptionhandlers/InvalidMementoPathExceptionMapper.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/exception/InvalidMementoPathException.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/utils/NamespaceTools.java
fcrepo-webapp/src/main/webapp/static/constraints/InvalidMementoPathException.rdf

Return 405 on PUT, POST and PATCH to LDPCv.
* * *
**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2821
Return status 405 on PUT, POST and PATCH to LDPCv,  and include the option headers for the existing memento resource.

Return 405 on PUT, POST and PATCH to LDPCv.

---

fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/WebACFilter.java
fcrepo-auth-webac/src/test/java/org/fcrepo/auth/webac/WebACFilterTest.java
fcrepo-auth-webac/src/test/resources/web.xml

**JIRA Tickets**: https://jira.duraspace.org/browse/FCREPO-2717, https://jira.duraspace.org/browse/FCREPO-2718
Implement acl:Append checks for POST and PUT.
- POST with just acl:Append only allowed for LDP-RS
- PUT with just acl:Append only allowed if resource is new and user has acl:Append permissions on the nearest existing parent resource
- Added some shorthand toRead, toWrite, and toAppend pre-created permissions for making the code easier to read.
Standard `mvn clean test` to run all tests should pass.
@dbernstein , @fcrepo4/committers

Implement acl:Append checks for POST and PUT.

---

fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/WebACFilter.java
fcrepo-auth-webac/src/test/java/org/fcrepo/auth/webac/WebACFilterTest.java
fcrepo-auth-webac/src/test/java/org/fcrepo/integration/auth/webac/WebACRecipesIT.java
fcrepo-auth-webac/src/test/resources/acls/23/acl.ttl
fcrepo-auth-webac/src/test/resources/acls/24/acl.ttl

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2845
Test append to container and append to binary.
Adds integration tests to confirm the functionality of acl:Append mode access for containers and for binaries.
Run these tests! 😄 
**Important:** The tests are *currently failing* because of issues identified in:
* https://jira.duraspace.org/browse/FCREPO-2857
* https://jira.duraspace.org/browse/FCREPO-2858
@whikloj , @fcrepo4/committers

Integration tests for acl:Append.

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ExternalContentHandler.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/ExternalContentHandlerIT.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2829
Makes behavior of creating external binary resources more predictable when referencing unavailable URIs. Should maintain use case of storing unresolvable binary URIs
* Catching additional errors when retrieving external content for streaming or for metadata retrieval:
* If a copy external binary creation request references a uri that is unreachable/not found, a 502 status is returned.
* If proxy/redirect binaries referencing bad URIs are received, creation should succeed, but retrieval: 
* with proxy, will result in a 502
* with redirect, will redirect to the unreachable URI.
* Adds integration tests for these error cases.
New integration tests.
From ticket:
```
> curl -i -XPOST -H"Link: …
```

FCREPO-2829 - Handle unreachable binary content

---

fcrepo-webapp/src/main/webapp/static/constraints/ACLAuthorizationConstraintViolationException.rdf
fcrepo-webapp/src/main/webapp/static/constraints/CannotCreateResourceException.rdf
fcrepo-webapp/src/main/webapp/static/constraints/ConstraintViolationException.rdf
fcrepo-webapp/src/main/webapp/static/constraints/ContainerConstraints.rdf
fcrepo-webapp/src/main/webapp/static/constraints/ExternalMessageBodyException.rdf
fcrepo-webapp/src/main/webapp/static/constraints/IncorrectTripleSubjectException.rdf
fcrepo-webapp/src/main/webapp/static/constraints/InteractionModelViolationException.rdf
fcrepo-webapp/src/main/webapp/static/constraints/InvalidACLException.rdf
fcrepo-webapp/src/main/webapp/static/constraints/InvalidMementoPathException.rdf
fcrepo-webapp/src/main/webapp/static/constraints/MalformedRdfException.rdf
fcrepo-webapp/src/main/webapp/static/constraints/NonRDFSourceConstraints.rdf
fcrepo-webapp/src/main/webapp/static/constraints/OutOfDomainSubjectException.rdf
fcrepo-webapp/src/main/webapp/static/constraints/RequestWithAclLinkHeaderException.rdf
fcrepo-webapp/src/main/webapp/static/constraints/ServerManagedPropertyException.rdf
fcrepo-webapp/src/main/webapp/static/constraints/ServerManagedTypeException.rdf

Resolves: https://jira.duraspace.org/browse/FCREPO-2893
Removes DOCTYPE directive from RDF constraint documents.
No functional change. Build should continue to work.

Remove DOCTYPE directive from RDF constraint documents

---

fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/ACLHandle.java
fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/CachedSparqlRequest.java
fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/URIConstants.java
fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/WebACAuthorizingRealm.java
fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/WebACFilter.java
fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/WebACPermission.java
fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/WebACRolesProvider.java
fcrepo-auth-webac/src/test/java/org/fcrepo/auth/webac/WebACAuthorizationTest.java
fcrepo-auth-webac/src/test/java/org/fcrepo/auth/webac/WebACFilterTest.java
fcrepo-auth-webac/src/test/java/org/fcrepo/auth/webac/WebACRolesProviderTest.java
fcrepo-auth-webac/src/test/java/org/fcrepo/integration/auth/webac/WebACRecipesIT.java
fcrepo-auth-webac/src/test/resources/repository-test.json

Additionally, tighten method and field qualifiers.
Resolves: https://jira.duraspace.org/browse/FCREPO-2901
Non-functional clean-up of fcrepo-auth-webac

Remove dead and redundant code from fcrepo-auth-webac

---

fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/CachedSparqlRequest.java
fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/WebACPermission.java

- Add corresponding definition of 'hashCode()'.
- Make a inner class to be a static inner class
Resolves: https://jira.duraspace.org/browse/FCREPO-2897
Non-functional clean-up of fcrepo codebase. Reduce 2 bugs (1 blocker and 1 major) in Sonar report https://sonar.fcrepo.org/dashboard?id=org.fcrepo%3Afcrepo.

Reduce Sonar Bugs and Vulnerabilities Issues - part 2

---

fcrepo-webapp/src/main/resources/spring/fcrepo-config.xml

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2268
Added topic/queue usage comments to Spring config.
Just comments, no testing needed? :-)
Documentation pages updated:
* https://wiki.duraspace.org/display/FEDORA5x/How+to+Switch+from+a+JMS+Topic+to+a+Queue
* https://wiki.duraspace.org/display/FEDORA5x/How+to+Disable+Messaging
@birkland, @fcrepo4/committers

Added topic/queue usage comments to Spring config.

---

fcrepo-webapp/src/main/resources/spring/fcrepo-config.xml
fcrepo-webapp/src/main/webapp/static/constraints/owl2html.xsl
fcrepo-webapp/src/test/java/org/fcrepo/integration/AbstractResourceIT.java
fcrepo-webapp/src/test/java/org/fcrepo/integration/SanityCheckIT.java

- Tighten method and field qualifiers.
Resolves: https://jira.duraspace.org/browse/FCREPO-2906
Non-functional clean-up of fcrepo-webapp

Remove dead and redundant code from fcrepo-webapp

---

fcrepo-integration-rdf/src/test/java/org/fcrepo/integration/rdf/ServerManagedTriplesIT.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2888
Adds a test which verifies all the expected server managed triples behave as expected
`mvn clean install`

Fcrepo 2888 - Verify server managed triples

---

fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/AbstractResource.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/api/rdf/HttpResourceConverter.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/domain/PreferTag.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/domain/Range.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/exceptionhandlers/ExceptionDebugLogging.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/exceptionhandlers/ParamExceptionMapper.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/responses/LinkFormatProvider.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/responses/LinkFormatStream.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/responses/RdfStreamStreamingOutput.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/responses/ViewHelpers.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/session/SessionFactory.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/session/SessionProvider.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/AbstractResourceTest.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/api/rdf/HttpResourceConverterTest.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/domain/MultiPreferTest.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/domain/PreferTagTest.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/domain/SinglePreferTest.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/domain/ldp/LdpPreferTagTest.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/exceptionhandlers/ConstraintViolationExceptionMapperTest.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/responses/RangeRequestInputStreamTest.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/responses/RdfStreamProviderTest.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/responses/RdfStreamStreamingOutputTest.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/responses/ViewHelpersTest.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/session/HttpSessionTest.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/session/SessionFactoryTest.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/session/SessionProviderTest.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/test/util/TestAuthenticationRequestFilter.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/test/util/TestHelpers.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/webxml/WebAppConfig.java

- Tighten method and field qualifiers.
Resolves: https://jira.duraspace.org/browse/FCREPO-2908
Non-functional clean-up of fcrepo-http-commons

Remove dead and redundant code from fcrepo-http-commons

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersioningIT.java

- remove the DELETE option from the OPTIONS returned to a user
Resolves: https://jira.duraspace.org/browse/FCREPO-2920
* * *
**JIRA Ticket**: (link)
A in-depth description of the changes made by this PR. Technical details and possible side effects.
Example:
* Changes x feature to such that y
* Added x
* Removed y
* …

Remove DELETE from the LDPCv OPTIONS header

---

fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/domain/PreferTag.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/domain/ldp/LdpPreferTag.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/RdfLexicon.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/spring/ModeShapeRepositoryFactoryBean.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2919
Cleans up/documents constants and references related to server managed triples
`mvn clean install`

Fcrepo-2919 - Reconcile/cleanup SMT constants

---

fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/RdfCollectors.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/utils/AutoReloadingConfiguration.java
fcrepo-parent/pom.xml
pom.xml

Related to 
https://jira.duraspace.org/browse/FCREPO-2881
Updates versions of maven plugins used.
`mvn clean install`
@birkland @whikloj

Update plugin versions

---

fcrepo-http-api/src/main/resources/views/common-node-actions.vsl

**UI: Changes label text "Create Version Snapshot" to "Versions"**
* * *
**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2927
UI: Changes label text "Create Version Snapshot" to "Versions"
Also changes "View Mementos" link text to "View Versions".
Open the UI, create a basic container and verify that above changes have been made.

UI: Changes label text "Create Version Snapshot" to "Versions".

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/responses/StreamingBaseHtmlProvider.java
fcrepo-http-api/src/main/resources/views/common-metadata.vsl
fcrepo-http-api/src/main/resources/views/default.vsl
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/responses/ViewHelpers.java

Resolves: https://jira.duraspace.org/browse/FCREPO-2926
**Improves the display of mementos**
* * *
**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2926, https://jira.duraspace.org/browse/FCREPO-2928
https://jira.duraspace.org/browse/FCREPO-2929
This PR ensures that mementos are displayed in a way that  mirrors the original resource, by making sure that the velocity template is using the original resource rather than the memento URI (which formerly was resolved from the URIInfo).
Now you should be able to view mementos like ordinary RDF resources in the HTML UI.  The properties are now rendered instead of appearing blank ( the issue called out by https://jira.duraspace.org/browse/FCREPO-2926). …

Ensures that the properties of the memento are displayed.

---

fcrepo-auth-common/pom.xml
fcrepo-auth-webac/pom.xml
fcrepo-configs/pom.xml
fcrepo-event-serialization/pom.xml
fcrepo-http-api/pom.xml
fcrepo-http-commons/pom.xml
fcrepo-integration-ldp/pom.xml
fcrepo-integration-rdf/pom.xml
fcrepo-jms/pom.xml
fcrepo-kernel-api/pom.xml
fcrepo-kernel-modeshape/pom.xml
fcrepo-parent/pom.xml
fcrepo-webapp/pom.xml
pom.xml

Updates the version of the master branch to make way for the release candidate branch.

Updates version to 5.1.0-SNAPSHOT for continued development.

---

README.md

Removes Fedora 4 references and updates links to the documentation.

Updates README.

---

fcrepo-webapp/pom.xml

Resolves: https://jira.duraspace.org/browse/FCREPO-2960

Ensures version and build info are appearing in the html ui.

---

fcrepo-parent/pom.xml
pom.xml

Cosmetic 11th hour pre-release update.

Removes Fedora 4 references from poms.

---

LICENSE

A minor cherry-picked commit from master.

Update LICENSE (#1487)

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/AbstractResourceIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersioningIT.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/utils/JcrPropertyStatementListener.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/utils/iterators/RdfAdder.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/utils/iterators/RdfRemover.java

Resolves: https://jira.duraspace.org/browse/FCREPO-2969
(cherry-picked from master)

Fcrepo-2969 - Adding types to binaries (#1491)

---

fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/WebACRolesProvider.java
fcrepo-auth-webac/src/test/java/org/fcrepo/auth/webac/WebACRolesProviderTest.java
fcrepo-auth-webac/src/test/java/org/fcrepo/integration/auth/webac/WebACRecipesIT.java
fcrepo-auth-webac/src/test/resources/acls/agent-access-to-class.ttl

The purpose of this PR is to move the fix for https://jira.duraspace.org/browse/FCREPO-2977 which is currently on master into the 5.x-maintenance branch.

Binary/Description accessToClass

---

fcrepo-event-serialization/src/test/java/org/fcrepo/event/serialization/JsonLDSerializerTest.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/FedoraLdpTest.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraTransactionsIT.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/AbstractResource.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/api/rdf/HttpResourceConverter.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/RdfLexicon.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/services/TimeMapService.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/AbstractFedoraBinary.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/FedoraResourceImpl.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/NonRdfSourceDescriptionImpl.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/services/TimeMapServiceImpl.java
fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/services/VersionServiceImpl.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/integration/kernel/modeshape/FedoraResourceImplIT.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/integration/kernel/modeshape/FedoraTimeMapImplIT.java
fcrepo-kernel-modeshape/src/test/java/org/fcrepo/integration/kernel/modeshape/services/TimeMapServiceImplIT.java

The purpose of this PR is to move the already merged fix for https://jira.duraspace.org/browse/FCREPO-2975 into the 5.x-maintenance branch

Create timemap when resource created

---

pom.xml

Resolves: https://jira.duraspace.org/browse/FCREPO-2972

Update jackson-databind to 2.9.8

---

fcrepo-webapp/pom.xml
pom.xml

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2978
Replaces the c3p0 library with apache commons-dbcp2
Setup a repository using MySQL and/or PostgreSQL for its back-end
Example:
* Does this change add any new dependencies? yes and removes one

Switch from c3p0 to commons-dbcp2

---

fcrepo-webapp/pom.xml
pom.xml

Resolves: https://jira.duraspace.org/browse/FCREPO-2978

Switch from c3p0 to commons-dbcp2 (#1511)

---

fcrepo-auth-common/pom.xml
fcrepo-auth-webac/pom.xml
fcrepo-configs/pom.xml
fcrepo-event-serialization/pom.xml
fcrepo-http-api/pom.xml
fcrepo-http-commons/pom.xml
fcrepo-integration-ldp/pom.xml
fcrepo-integration-rdf/pom.xml
fcrepo-jms/pom.xml
fcrepo-kernel-api/pom.xml
fcrepo-kernel-modeshape/pom.xml
fcrepo-parent/pom.xml
fcrepo-webapp/pom.xml
pom.xml

push 5.0.2 release branch on to the maintenance branch

5.0.2 maintenance

---

fcrepo-parent/pom.xml

**JIRA Ticket**: n/a
Update the puppycrawl dependency.
Build it.

update puppycrawl dependency

---

pom.xml

**JIRA Ticket**: (https://jira.duraspace.org/browse/FCREPO-3004)
Update jackson2.version to 2.9.9
Checkout FCREPO-3004 and mvn clean install
Tag (@awoods , @dbernstein )

update jackson2.version to 2.9.9

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraVersioning.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraTransactionsIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersioningIT.java

- Add missing @param, @return and @throws comments
Resolves: https://jira.duraspace.org/browse/FCREPO-3025
* * *
**JIRA Ticket**: (link)
A in-depth description of the changes made by this PR. Technical details and possible side effects.
Example:
* Changes x feature to such that y
* Added x
* Removed y
* Please be as …

Address Javadoc warnings in fcrepo-http-api module

---

.travis.yml
README.md
fcrepo-auth-common/src/main/java/org/fcrepo/auth/common/AbstractPrincipalProvider.java
fcrepo-http-commons/pom.xml
fcrepo-parent/pom.xml
pom.xml

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-3038
Make build under Java 11.
Adds XML JavaEE modules, removes some unneeded `@Overrides`, etc.
Build using java 8 and 11.
Example:
* Does this change require documentation to be updated? maybe

Build in Java 11

---

fcrepo-kernel-impl/pom.xml
pom.xml

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-3046
Add a new module fcrepo-kernel-impl
Verify the maven build includes the fcrepo-kernel-impl module
@whikloj

Added fcrepo-kernel-impl module

---

fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/FedoraTransaction.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/FedoraTransactionManager.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/FedoraTransactionImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/FedoraTransactionManagerImpl.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/FedoraTransactionManagerTest.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-3046
- #1545 
Creates the Interfaces and simple implementation classes related to FedoraTransaction
Adds interfaces
- FedoraTransaction
- FedoraTransactionManager
Adds implementations
- FedoraTransactionImpl
- FedoraTransactionManagerImpl
Verify that the build and the tests pass.
This PR does not include the changes to delete FedoraSession. I will create a separate PR for that.
@dbernstein

 FCREPO-3046. Create Fedora Transaction Interfaces and classes

---

fcrepo-persistence-api/pom.xml
fcrepo-persistence-api/src/main/java/org/fcrepo/persistence/api/PersistentStorageFactory.java
fcrepo-persistence-api/src/main/java/org/fcrepo/persistence/api/PersistentStorageSession.java
fcrepo-persistence-api/src/main/java/org/fcrepo/persistence/api/PersistentStorageSessionFactory.java
fcrepo-persistence-api/src/main/java/org/fcrepo/persistence/api/exceptions/PersistentStorageException.java
fcrepo-persistence-ocfl/pom.xml
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/OCFLPersistentSessionFactory.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/OCFLPersistentStorageSession.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/OCFLPersistentSessionFactoryTest.java
pom.xml

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-3047
Makes a "Persistent Storage Session" class which mediates the CRUD operations. It is instantiated by using a factory class
Review only, no implementation.
No idea if this the correct way to setup a Factory class, I would normally do it as a static method. But I am unclear how you do that in an abstract class where the actual implementation doesn't yet exist.

Make session interface and factory class and some of an impl

---

fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/models/ResourceFactory.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/ResourceFactoryImpl.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-3090
Adds a method
Review
@fcrepo4/committers @mohideen

Add getResource without transaction

---

.travis.yml
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/Transaction.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/models/ResourceHeaders.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/operations/NonRdfSourceOperationBuilder.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/operations/ResourceOperation.java
fcrepo-parent/pom.xml

Updates Travis to remove Java 8
Travis still builds

Remove Java 8 from testing matrix

---

fcrepo-parent/pom.xml

**Pulls in snapshot dependencies**
* * *
**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-3108
Ensures that users can build the software with configuring a special profile in their settings.xml.
1. remove the ocfl java client from the maven cache
rm -rf  ~/.m2/repository/edu/wisc/library
2. make sure you are not using the settings.xml file in ~/.m2/settings.xml . To do so, temporarily move it to  ~/.m2/settings.xml.orig
3. Verify the build now succeeds:
mvn clean install
4.Verify that the ~/.m2/repository/edu/wisc/library now exists.

Ensures maven can pull in snapshot dependencies.

---

fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/OCFLPeristentStorageUtils.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/OCFLPersistentStorageSession.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/api/Persister.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/AbstractPersister.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/CreateRDFSourcePersister.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/CreateRDFSourcePersisterTest.java

**Implements CreateRDFSourcePersister.persist()**
* * *
**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-3094
It implements the CreateRDFSourcePersister.persist() method which mediates the interaction between the OCFLObjectSession and the ResourceOperation. It includes a unit test.

Implements CreateRDFSourcePersister.persist().

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/Transactions.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/TransactionsTest.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/session/TransactionProvider.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/Transaction.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/TransactionImpl.java

**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-3074
- Update Transactions endpoint to use TransactionManager
- Use the URL based Transaction management as specified in https://github.com/fcrepo/fcrepo-specification-atomic-operations/pull/8
We may want to review and merge https://github.com/fcrepo/fcrepo-specification-atomic-operations/pull/8 before merging this PR.
@dbernstein @bbpennel @peichman-umd

FCREPO-3074. Update Transactions endpoint to use TransactionManager

---

fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/WebACRolesProvider.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraAcl.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraVersioning.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/FedoraLdpTest.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/BinaryImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/operations/NonRdfSourceOperationFactoryImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/AbstractService.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/operations/CreateNonRdfSourceOperationBuilderTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/services/CreateResourceServiceImplTest.java
fcrepo-parent/pom.xml
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/AbstractPersister.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/CreateNonRdfSourcePersister.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/DefaultOCFLObjectSession.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/DeleteResourcePersister.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/FedoraToOCFLObjectIndexImpl.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/OCFLPersistentStorageSession.java

Non-functional changes to shorten lines that exceed 120 characters
Resolves: https://jira.lyrasis.org/browse/FCREPO-3167
Updates the codestyle version to re-enforce line length limit of 120 characters
- Create a line in the code base that is longer than 120 characters
- Observe failing build

Upgrade version of checkstyle rules

---

fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/services/CreateResourceService.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/CreateResourceServiceImpl.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/services/CreateResourceServiceImplTest.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3175
We need to return the identifier from the kernel/service level to the HTTP level to send out a response. This PR starts returning the identifier from the service layer.
This will still throw errors on a POST, but its incremental and tests have been updated.

Return identifier from CreateResourceService

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraBaseResource.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3178
Gets the identifier back and gets the resource so a proper response can be made.
Do a POST before and see:
```
> curl -i -XPOST -H"Content-type: text/turtle" -ufedoraAdmin:fedoraAdmin http://localhost:8080/rest
HTTP/1.1 500 Internal Server Error
Date: Mon, 27 Jan 2020 16:20:54 GMT
Set-Cookie: JSESSIONID=node017rvmgnvvfy1ts6fqojuyw3nt0.node0; Path=/
Set-Cookie: rememberMe=deleteMe; Path=/; Max-Age=0; Expires=Sun, 26-Jan-2020 16:20:54 GMT
Content-Type: text/plain;charset=utf-8
Content-Length: 7244
Server: Jetty(9.4.24.v20191120)
java.lang.NullPointerException
at org.fcrepo.http.api.ContentExposingResource.addCacheControlHeaders(ContentExposingResource.java:736)
at …
```

Enable POST response

---

fcrepo-http-api/pom.xml
fcrepo-http-api/src/test/resources/spring-test/fcrepo-config.xml
fcrepo-kernel-impl/pom.xml
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/ContainmentIndexImpl.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/ContainmentIndexImplTest.java
fcrepo-kernel-impl/src/test/resources/containmentIndexTest.xml
fcrepo-webapp/pom.xml
fcrepo-webapp/src/main/resources/spring/fcrepo-config.xml

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3106
Uses JDBC to connect to a SQL database and track containment relationships inside and outside of transactions.
* Added a ContainmentIndex interface and ContainmentIndexImpl implementation
* Unit tests have been included; run a standard `mvn clean test`
* Note that currently, something is failing in the fcrepo-http-api module that appears to be due to Spring and related to the containment index in some way. I have yet to be able to determine what the problem is.
* This PR supersedes #1584 
@dbernstein , @whikloj , @fcrepo4/committers

Create containment index implementation

---

README.md

Switch badge to travis-ci.com

---

fcrepo-auth-common/pom.xml
fcrepo-auth-webac/pom.xml
fcrepo-parent/pom.xml

Update dependencies that need security patches

---

fcrepo-http-api/src/test/resources/spring-test/fcrepo-config.xml
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/ContainmentIndex.java
fcrepo-kernel-impl/pom.xml
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/ContainmentIndexImpl.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/ContainmentIndexImplTest.java
fcrepo-kernel-impl/src/test/resources/containmentIndexTest.xml
fcrepo-webapp/pom.xml
fcrepo-webapp/src/main/resources/spring/fcrepo-config.xml
pom.xml

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3164
Adds some more methods to the API.
Implements a commit and rollback method.
Adds some more tests.
Alters the database setup structure.
Right now this is just via the tests, so it should build and the tests should handle expectations.
Next phase is wiring it into the kernel.
@fcrepo4/committers @pwinckles

First pass at containment index

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/StateTokensIT.java

* these tests were already working
Related to: https://jira.lyrasis.org/browse/FCREPO-3228

Enable two more StateToken integration tests

---

fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/identifiers/FedoraID.java
fcrepo-kernel-api/src/test/java/org/fcrepo/kernel/api/identifiers/FedoraIDTest.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3254
Creates a new immutable class to hold the fedora ID but allow more context. ie. For a Memento we need the original resource to find the memento but need the memento information for context. This stores and makes available both.
This is just to ensure it is what everyone expects, follow on work can wire this into the kernel layer.
@fcrepo4/committers @pwinckles

Add a FedoraID class

---

fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/OCFLPersistentSessionManager.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/OCFLPersistentStorageSession.java

Fixes a few concurrency bugs in Fedora's ocfl code.

fix concurrency bugs

---

fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/AbstractNonRdfSourcePersister.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/AbstractRDFSourcePersister.java

Fixes an incorrect string comparison.

fix equality check

---

.travis/deploy.sh

**Ensures deployment to sonatype only happens on the linux build.**
* * *
**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3303
Improves upon work in to https://jira.lyrasis.org/browse/FCREPO-3291

Ensures deployment to sonatype only happens on the linux build.

---

.github/PULL_REQUEST_TEMPLATE.md

Resolves: https://jira.lyrasis.org/browse/FCREPO-3304
Removes extraneous text from PULL_REQUEST_TEMPLATE.md
Create a pull-request... and enjoy the reduced amount of requested input :)

Remove extraneous text from PULL_REQUEST_TEMPLATE.md

---

fcrepo-http-api/pom.xml
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraSearch.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraSearchIT.java
fcrepo-search-api/pom.xml
fcrepo-search-api/src/main/java/org/fcrepo/search/api/InvalidQueryException.java
fcrepo-search-api/src/main/java/org/fcrepo/search/api/PaginationInfo.java
fcrepo-search-api/src/main/java/org/fcrepo/search/api/Query.java
fcrepo-search-api/src/main/java/org/fcrepo/search/api/SearchParameters.java
fcrepo-search-api/src/main/java/org/fcrepo/search/api/SearchResult.java
fcrepo-search-api/src/main/java/org/fcrepo/search/api/SearchService.java
fcrepo-search-impl/pom.xml
fcrepo-search-impl/src/main/java/org/fcrepo/search/impl/SearchServiceImpl.java
pom.xml

**Initial starting point for simple search implementation **
* * *
**JIRA Ticket**: Resolves: https://jira.lyrasis.org/browse/FCREPO-3282 
* Adds two new modules: fcrepo-search-api and fcrepo-search-impl
* Adds an integration test to ensure that the search api is returning a valid json result.
```
java  -Dfcrepo.ocfl.staging.dir=target/fcrepo-data/staging -Dfcrepo.ocfl.storage.root.dir=target/fcrepo-data/ocfl-root -Dfcrepo.ocfl.work.dir=target/fcrepo-data/work    -jar fcrepo-webapp/target/fcrepo-webapp-6.0.0-SNAPSHOT-jetty-console.jar --headless
```
```
curl -u fedoraAdmin:fedoraAdmin http://localhost:8080/rest/fcr:search -i
```
Verify that it returns 200 and some json.  Ignore the values within the search …

Adds search endpoint with a minimal integration test.

---

fcrepo-http-api/src/test/resources/spring-test/fcrepo-config.xml
fcrepo-jms/src/test/resources/spring-test/fcrepo-config.xml
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/ContainmentIndexImpl.java
fcrepo-kernel-impl/src/main/resources/sql/default-containment.sql
fcrepo-kernel-impl/src/main/resources/sql/mysql-containment.sql
fcrepo-persistence-ocfl/pom.xml
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/OCFLPersistenceConfig.java
fcrepo-webapp/pom.xml
fcrepo-webapp/src/main/java/org/fcrepo/webapp/config/DatabaseConfig.java
pom.xml

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3331
Adds support for PostgreSQL, MariaDB, and MySQL (only tested with the latest versions of each).
Startup a DB and Fedora using the following instructions and then create, retrieve, delete resources as you would normally.
Start the DB:
```
docker run --name f6-mariadb -e MYSQL_ROOT_PASSWORD=root-pw -e MYSQL_DATABASE=fcrepo -e MYSQL_USER=fcrepo-user -e MYSQL_PASSWORD=fcrepo-pw -p 3306:3306 -d mariadb:10.5.3
```
Access the CLI:
```
docker exec -it f6-mariadb mysql -ufcrepo-user -pfcrepo-pw -Dfcrepo
```
Start F6:
```
mvn -Dfcrepo.db.url=jdbc:mariadb://localhost:3306/fcrepo -Dfcrepo.db.user=fcrepo-user -Dfcrepo.db.password=fcrepo-pw clean jetty:run
```
Stop DB & cleanup:
```
docker stop f6-mariadb
docker rm f6-mariadb
```
Start the …

add support for PostgreSQL, MariaDB, and MySQL

---

pom.xml

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3342
Updates the ocfl-java version. I just fixed two issues:
https://github.com/UW-Madison-Library/ocfl-java/issues/5
https://github.com/UW-Madison-Library/ocfl-java/issues/8
ocfl-java should now cleanup the ocfl storage hierarchy when objects are purged.
After creating, deleting and purging an atomic resource, the path to the purged OCFL object remains, which is invalid.
```
curl -i -XPUT -H"Content-Type: text/turtle" -d "<> <http://example.org#title> 'a title'" localhost:8080/rest/container
curl -i localhost:8080/rest/container
find /tmp/fcrepo.ocfl.storage.root.dir -name container
curl -i -XDELETE localhost:8080/rest/container
curl -i localhost:8080/rest/container/fcr:tombstone
curl -i -XDELETE …
```

update to the newest ocfl-java snapshot

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraSearchIT.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/ContainmentIndexImpl.java
fcrepo-search-api/src/main/java/org/fcrepo/search/api/SearchParameters.java
fcrepo-search-impl/src/main/java/org/fcrepo/search/impl/SearchServiceImpl.java

Includes additional debug logging
Resolves: https://jira.lyrasis.org/browse/FCREPO-3352
Fixes the flapping FedoraSearchIT
A successful build is success

Add stability to FedoraSearchIT

---

pom.xml

Removes the victims rule plugin.  No functional change.
mvn clean install

Removes victims plugin (until http://wwww.victi.ms) is fixed.

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/TransactionsIT.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/AbstractDeleteResourceService.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/services/DeleteResourceServiceImplTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/services/PurgeResourceServiceImplTest.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/api/OCFLObjectSession.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/DefaultOCFLObjectSession.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/DeleteResourcePersister.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/PurgeResourcePersister.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/DeleteResourcePersisterTest.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/PurgeResourcePersisterTest.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3340
Handles deleting resources that were never committed to the repository.
See simple steps in the associated ticket or the 3 new integration tests for steps.

Don't delete if never created

---

fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/DefaultOCFLObjectSession.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/OCFLPersistentStorageSession.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3380
Stops trying to delete directories that don't exist
Start F6 and create a resource, and you shouldn't see any warnings.

do not attempt to delete directories that do not exist

---

fcrepo-auth-common/pom.xml
fcrepo-auth-webac/pom.xml
fcrepo-configs/pom.xml
fcrepo-event-serialization/pom.xml
fcrepo-http-api/pom.xml
fcrepo-http-commons/pom.xml
fcrepo-integration-ldp/pom.xml
fcrepo-integration-rdf/pom.xml
fcrepo-jms/pom.xml
fcrepo-kernel-api/pom.xml
fcrepo-kernel-modeshape/pom.xml
fcrepo-parent/pom.xml
fcrepo-webapp/pom.xml
pom.xml

Updates the pom versions on the release candidate branch.

Updates version to 5.1.1-SNAPSHOT.

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/ExternalContentHandlerIT.java

**JIRA Ticket**: relates to https://jira.lyrasis.org/browse/FCREPO-3239
Fixes a few issues with the integration test:
* Don't post to non-exist parents
* fix name of two test methods which incorrectly said 'proxy' but were testing 'redirect'
* add a few extra transmission fixity tests

FCREPO-3239 - Integration test updates

---

fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/IndexBuilderImpl.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/IndexBuilderImplTest.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3338
No longer indexes deleted resources on rebuild.
Follow the steps in the jira ticket.

do not index deleted resources on rebuild

---

fcrepo-configs/src/main/java/org/fcrepo/config/DatabaseConfig.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/ContainmentIndexImpl.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/DbFedoraToOcflObjectIndex.java
fcrepo-search-impl/src/main/java/org/fcrepo/search/impl/DbSearchIndexImpl.java

**Jira**: https://jira.lyrasis.org/browse/FCREPO-3406 
1. Changes the transaction code to use Spring annotations
2. Adds some connection pool configuration
There are no behavior changes. Everything should work the same as before.

cleanup db transaction code; add connection pool configuration

---

fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/WebACFilter.java
fcrepo-auth-webac/src/test/java/org/fcrepo/integration/auth/webac/WebACRecipesIT.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/session/TransactionConstants.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/FedoraTypes.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3321
Allows any authenticated user to create a transaction by allowing POST to the /fcr:tx endpoint as long as the current user is authenticated.
* Run the WebACRecipesIT integration tests
* Build and run using `mvn jetty:run` then test by doing: `curl -u testuser:testpass -i -X POST http://localhost:8080/rest/fcr:tx`. You should get a `201 Created` response.
@fcrepo4/committers, @awoods

Allow any authenticated user to POST to /fcr:tx

---

fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/FcrepoOcflObjectSessionWrapper.java

Removes the exception from the close signature due to this change https://github.com/fcrepo4-exts/fcrepo-storage-ocfl/pull/8

remove exception from sig

---

fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/MembershipServiceImpl.java

Fixes a couple of exceptions with changed signatures.
Should build

fixed exceptions

---

fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/WebACFilter.java
fcrepo-auth-webac/src/test/java/org/fcrepo/auth/webac/WebACFilterTest.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraVersioning.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/services/HttpRdfService.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/url/HttpApiResources.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/FedoraLdpTest.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/url/HttpApiResourcesTest.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/AbstractResourceIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraFixityIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersioningIT.java
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/responses/ViewHelpers.java
fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/responses/ViewHelpersTest.java
fcrepo-integration-rdf/src/test/java/org/fcrepo/integration/rdf/ServerManagedTriplesIT.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/FedoraTypes.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/RdfLexicon.java
fcrepo-webapp/src/test/java/org/fcrepo/integration/FedoraHtmlResponsesIT.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3444
Removes a bunch of static constants that related to Modeshape and its requirements. This PR should not have any effect on the way Fedora currently operates.
Fedora still does Fedora.

Remove unnecessary Modeshape code/constants.

---

fcrepo-search-impl/src/main/java/org/fcrepo/search/impl/DbSearchIndexImpl.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3455
Reduces the number of `for` loops with individual queries or inserts in favour of single batchs of multiple records.
The ol' @awoods batch ingest test would be best.

Reduce number of queries and make updates batched in SearchIndex

---

fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/OcflPersistentStorageUtils.java
pom.xml

**Jira**: https://jira.lyrasis.org/browse/FCREPO-3508
Depends on: https://github.com/fcrepo/fcrepo-storage-ocfl/pull/16

ocfl-java version bump

---

pom.xml

This PR depends on https://github.com/fcrepo/fcrepo-storage-ocfl/pull/18

upgrade to ocfl-java 0.1.0

---

fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/WebACAuthorizingRealm.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/TombstoneImpl.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3516
Stops trying to load the ACL roles for a tombstone.
1. Create resource
`curl -i -ufedoraAdmin:fedoraAdmin http://localhost:8080/rest/box -XPUT`
1. Delete resource
`curl -i -ufedoraAdmin:fedoraAdmin http://localhost:8080/rest/box -XDELETE`

Don't load a tombstone for ACLs

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/StateTokensIT.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3228
Enable last test in `StateTokensIT`
Test passes.

Final state token test

---

fcrepo-auth-common/pom.xml
fcrepo-auth-webac/pom.xml
fcrepo-auth-webac/src/test/java/org/fcrepo/integration/auth/webac/WebACRecipesIT.java
fcrepo-http-api/pom.xml
fcrepo-http-commons/pom.xml
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/responses/RdfStreamStreamingOutput.java
fcrepo-jms/pom.xml
fcrepo-persistence-ocfl/pom.xml
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/AbstractRdfSourcePersister.java
fcrepo-webapp/pom.xml
pom.xml

**Jira**: https://jira.lyrasis.org/browse/FCREPO-3526
Upgrades fcrepo dependencies to latest versions when possible.
Everything should still work.

big dep upgrade

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraAcl.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraAclIT.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3518
Translate the Sparql request to ensure identifiers are properly translated and matched against the target model.
Patch an ACL, where you change a triple that has an internal URI of the object. 
Before the PR nothing will change even though you get a 204 No Content response, with the PR the change occurs.

Translate ACL Patch requests

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersioningIT.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/ContainmentIndex.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/ContainmentIndexImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/ContainmentIndexMetrics.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/ContainmentTriplesServiceImpl.java
fcrepo-kernel-impl/src/main/resources/sql/default-containment.sql
fcrepo-kernel-impl/src/main/resources/sql/mysql-containment.sql
fcrepo-kernel-impl/src/main/resources/sql/postgres-containment.sql
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/ContainmentIndexImplTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/services/ContainmentTriplesServiceImplTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/services/CreateResourceServiceImplTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/services/DeleteResourceServiceImplTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/services/MembershipServiceImplTest.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3450
Contains the past containment relationships for those things that did exist and are now deleted (but not purged).
**Note**: this does not include the repository rebuild processing. I figured I'd work that once this seemed correct.
**Note note**: I renamed the `resources` table to `containment` and the `transaction_operations` table to `containment_transactions`. The old names were not super clear and we have a lot more tables now.
Create a resource (parent)
Create a child resource (child)
Create a version of parent (I patch it)
Delete child.
Get the memento you created, before there were no ldp:contains, now you should see child.

Memento containment

---

fcrepo-webapp/pom.xml

Resolves: https://jira.lyrasis.org/browse/FCREPO-3530
Upgrade version of jetty-console
- Build build one-click
```
mvn clean install -Pone-click
```
- Run one-click and notice reduced, extraneous logging messages on start-up

Upgrade jetty-console to 1.63

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/package-info.java

Resolves: https://jira.lyrasis.org/browse/FCREPO-3087
Trivial removal of text in documentation.

Remove mention of '/fcr:backup'

---

pom.xml

Adds a profile that can be used to build fcrepo quickly without running any tests or checks.

added profile for doing a fast build

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/AbstractResourceIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/TransactionsIT.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/TransactionImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/TransactionManagerImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/MembershipServiceImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/ReferenceServiceImpl.java
fcrepo-kernel-impl/src/main/resources/sql/mysql-containment.sql
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/TransactionImplTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/TransactionManagerImplTest.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3529
Fixes the transaction commit code so that all db commits are within the same transaction so that either they are all applied or none of them are.
This PR only fixes the db transactions. It will no cleanup already persisted OCFL changes. This should be handled by https://jira.lyrasis.org/browse/FCREPO-3130
This is difficult to test. You'd need to create a Fedora transaction and then corrupt a db table before committing the transaction so that the Fedora transaction does not commit cleanly.

all db commits within the same db transaction

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraFixity.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/AbstractResourceIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraFixityIT.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/RdfLexicon.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/services/FixityService.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/FixityServiceImpl.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3535
Implements a fixity checking service.
Put a binary in, then go to it's `fcr:fixity` endpoint. Try both cUrl and a web browser.
Assuming the result is `SUCCESS` try altering your binary and run the request again.
See the `BAD_CHECKSUM` result. 
In Fedora 5 you would get a `BAD_SIZE` outcome as well, I feel like if the size changes the checksum changes and we aren't all that concerned about ever getting a `BAD_SIZE` without a `BAD_CHECKSUM`. But if desired we'd have to add this functionality to the fixity service.
@fcrepo/committers (specifically @bbpennel) and @dwilcox

Fixity Service

---

fcrepo-auth-webac/src/test/java/org/fcrepo/integration/auth/webac/WebACRecipesIT.java
fcrepo-http-api/src/main/resources/root-authorization.ttl

Resolves: https://jira.lyrasis.org/browse/FCREPO-3534
Trivial fixes to typos

Remove 'respository' typos

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraSearch.java
fcrepo-http-api/src/main/java/org/fcrepo/http/api/responses/SearchResultProvider.java
fcrepo-http-api/src/main/resources/views/common-header.vsl
fcrepo-http-api/src/main/resources/views/common-search-result.vsl
fcrepo-http-api/src/main/resources/views/search-header.vsl
fcrepo-http-api/src/main/resources/views/search.vsl
fcrepo-http-commons/pom.xml
fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/responses/ViewHelpers.java
fcrepo-search-api/src/main/java/org/fcrepo/search/api/Condition.java
fcrepo-webapp/src/main/webapp/static/css/common.css
fcrepo-webapp/src/main/webapp/static/js/common.js

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3351
Makes a page that builds a search tool, gives you a select box with fields and operators and a text box to enter your value.
Does not but is built to allow us to add more sets of query boxes to make compound queries.
Parses the URL to populate the query boxes.
Formats the results into a table.
Build it, add some objects. Try using the search.

Search page in HTML UI

---

fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/WebACFilter.java
fcrepo-auth-webac/src/test/java/org/fcrepo/integration/auth/webac/WebACRecipesIT.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3115
Checks the contained resources when trying to 
1. Create a container, add an ACL giving the test user access.
```
@prefix acl: <http://www.w3.org/ns/auth/acl#> .
<#readauthz> a acl:Authorization ;
acl:agent "testuser" ;
acl:mode acl:Read, acl:Write ;
acl:accessTo </rest/topContainer> ;
acl:default </rest/topContainer> .
```
1.  Add a child (as many children and levels as you wish).
1. Add an ACL to one of the children restricting `acl:Write` access for the testuser.
```
@prefix acl: <http://www.w3.org/ns/auth/acl#> .
<#readauthz> a acl:Authorization ;
acl:agent "fedoraAdmin" ;
acl:mode acl:Read, acl:Write ;
acl:accessTo </rest/topContainer/myChild/someGrandChild> .
```
1. Try to delete `http://localhost:8080/rest/topContainer` …

Check contained resource permissions before deleting a tree

---

fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/IndexBuilderImpl.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3355
On startup, Fedora will reindex if `info:fedora/` is not found in the index or it is not found in the OCFL repo.
1. Start F6
2. Create a resource
3. Stop F6
4. `rm fcrepo-webapp/target/fcrepo-home/data/fcrepo-h2.mv.db`
5. Start F6 and see it reindex
6. Stop F6
7. `rm -r fcrepo-webapp/target/fcrepo-home/data/ocfl-root/141`
8. Start F6 and see it reindex

reindex when repo root not found

---

fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/WebACFilter.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3565
Adds a utility method to build a response. Using the `sendError(int, String)` works for some messages and not others. It relies on the server to generate a HTML page. 
Now we generate a direct response which is consistent.
Without this PR, start Fedora and try
```
> curl -u fedoraAdmin:fedoraAdmin http://localhost:8080/rest/ag-01/fcr-root -H "Link: <http://www.w3.org/ns/ldp#NonRDFSource>; rel=type" -H "Content-Type: text/plain" -X PUT --data-binary "testing" -i
Set-Cookie: JSESSIONID=node014ceou6egqtht1u5uvjpgi6wnk0.node0; Path=/
Set-Cookie: rememberMe=deleteMe; Path=/; Max-Age=0; Expires=Fri, 04-Dec-2020 03:20:05 GMT; SameSite=lax
Content-Length: 0
Server: Jetty(9.4.34.v20201102)
```
or
```
> curl -u …
```

Display exception message from contextrequestfilter

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersioningIT.java

This test was flapping a lot this morning. I think adding this additional sleep should fix it.
This ITest should hopefully pass consistently.

attempt to improve memento test stability

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3223
Un-ignores a test
The test should pass on build

Embedded resource test

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersioningIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/TestIsolationExecutionListener.java

This PR hopefully fixes a couple of ITests that intermittently fail. No promises.
A successful run: https://github.com/pwinckles/fcrepo4/actions/runs/451290244

fix itests

---

fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/WebACFilter.java
fcrepo-auth-webac/src/test/java/org/fcrepo/integration/auth/webac/WebACRecipesIT.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3519
Tries to get a transaction using the ID from a request and display errors properly if the transaction is closed or doesn't exist.
Before PR:
Try to GET as non-admin user with a fake transaction ID and see a stack trace.
```
curl -i -utestuser:testpass http://localhost:8080/rest/ -H"Atomic-ID: http://localhost:8080/rest/fcr:tx/cee0cf97-b912-407d-9d3c-82cfe72d6da1"
```
Also  
* create a transaction
* commit the transaction
* as a non-admin user try a GET with the committed transaction ID to see another stacktrace.
Build this PR and both of these are replaced by nice 409 Conflict messages.

Display exception for bad transaction IDs at WebAC layer

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/AbstractResourceIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/TransactionsIT.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3229
Unignores last 2 tests in TransactionIT
Should build and all tests pass.

Unignore last 2 TransactionIT tests

---

fcrepo-webapp/src/test/java/org/fcrepo/integration/SanityCheckIT.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3231
Unignores all tests
It builds and all tests pass.

Unignore all tests in SanityCheckIT

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersioningIT.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3226
Un-ignores the last test.
It builds and the test passes.

Unignore last test

---

fcrepo-http-api/src/main/resources/views/resource.vsl
fcrepo-webapp/src/main/webapp/static/js/common.js
fcrepo-webapp/src/test/java/org/fcrepo/integration/AbstractResourceIT.java
fcrepo-webapp/src/test/java/org/fcrepo/integration/FedoraHtmlResponsesIT.java
fcrepo-webapp/src/test/resources/logback-test.xml
pom.xml

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3230
Removes all Ignores except the one that needs IndirectContainers.
Builds and all tests pass.

Remove Ignores from FedoraHtmlResponsesIT

---

fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/models/ResourceHelperImplTest.java
fcrepo-kernel-impl/src/test/resources/containmentIndexTest.xml
fcrepo-kernel-impl/src/test/resources/membershipServiceTest.xml

Fixes the test that was failing because Flyway wasn't running

fix ResourceHelperImplTest

---

fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/IndexBuilderImpl.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/ReindexManager.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/ReindexWorker.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3467
Adds a log message that reports on the status of the rebuild process
Start Fedora on a large migrated repo and see it report its progress in the logs.

add rebuild progress message

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/models/Binary.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/BinaryImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/FixityServiceImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/ManagedPropertiesServiceImpl.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/models/ResourceFactoryImplTest.java

**Ensures that all digests are returned in RDF metadata.**
* * *
**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3646
Ensures all digests are returned in the RDF metadata rather than simply the first one in the list.
See the instructions for reproducing in the JIRA above.  Verify that it is no longer returning only one digest.

Ensures that all digests are returned in RDF metadata.

---

README.md

To be merged right before beta is cut.

Updates the notice at the top of the readme.

---

fcrepo-configs/src/main/resources/sql/h2/R__Create_containment.sql
fcrepo-configs/src/main/resources/sql/mariadb/R__Create_containment.sql
fcrepo-configs/src/main/resources/sql/mysql/R__Create_containment.sql
fcrepo-configs/src/main/resources/sql/mysql/V1__Add_containment_index.sql
fcrepo-configs/src/main/resources/sql/postgresql/R__Create_containment.sql
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/TransactionsIT.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/ContainmentIndexImpl.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/ContainmentIndexImplTest.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3369
Alters the way records are added to the containment transaction and main tables to use upserts to avoid too many conflicts.
1. Create a resource.
1. Create a transaction.
1. Inside the transaction
1. Delete the resource
2. Delete the resource's tombstone
3. Re-add the same resource
4. Commit the transaction
Before the PR you get a 409 conflict and a stacktrace, after you should be fine.

Use upserts for containment

---

fcrepo-configs/src/main/java/org/fcrepo/config/BasePropsConfig.java
fcrepo-configs/src/main/java/org/fcrepo/config/FedoraPropsConfig.java
fcrepo-configs/src/main/java/org/fcrepo/config/OcflPropsConfig.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/OcflPersistentStorageUtils.java

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3654
Fedora no longer fails to start if `fcrepo.home` is a symlink.
Start Fedora with `fcrepo.home` pointing at a symlinked directory and Fedora should start normally.

allow fcrepo home to be a symlink

---

fcrepo-webapp/pom.xml
fcrepo-webapp/src/test/java/org/fcrepo/integration/FedoraHtmlResponsesIT.java
pom.xml

Updates to dependencies for fcrepo 5

Fcrepo 5 dependency updates - 2020-05

---

fcrepo-search-impl/src/main/java/org/fcrepo/search/impl/DbSearchIndexImpl.java

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3726
Caches rdf types used in the search index so that they do not need to be queried as frequently
Everything should work the same as before. Resources should have their rdf type indexed correctly in the search index.

optimize search index rdf type insertions

---

fcrepo-auth-webac/src/main/java/org/fcrepo/auth/webac/WebACFilter.java
fcrepo-auth-webac/src/test/java/org/fcrepo/auth/webac/WebACFilterTest.java
fcrepo-auth-webac/src/test/java/org/fcrepo/auth/webac/WebACRolesProviderTest.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/TestIsolationExecutionListener.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/TimeMapImpl.java

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3731
**This only partially resolves the above ticket**
Switches the direct/indirect container test to use the interaction model instead of types.
This should have no functional impact.

Use interaction model in WebAC direct/indirect tests

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraSearch.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraSearchIT.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/ReindexService.java
fcrepo-search-api/src/main/java/org/fcrepo/search/api/SearchParameters.java
fcrepo-search-impl/src/main/java/org/fcrepo/search/impl/DbSearchIndexImpl.java

**Optimizes the search query so that it performs reasonably for large repos**
* * *
**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3733
This PR optimizes the search query when the user specifies the default fields or explicitly returns or filters on rdf_type.
Run on a mysql backed  repo with at least a million items.
This should return in a few seconds:  
```
http://fcrepo-staging.eba-muvve2sq.us-east-1.elasticbeanstalk.com/fcrepo/rest/fcr:search
```
This should be lightning quick
```
http://fcrepo-staging.eba-muvve2sq.us-east-1.elasticbeanstalk.com/fcrepo/rest/fcr:search?max_results=10&condition=rdf_type=http://example.com/type
```
Tag (@ mention) interested parties or, if unsure, …

Optimizes the search query so that it performs reasonably for large repos

---

fcrepo-auth-common/pom.xml
fcrepo-auth-webac/pom.xml
fcrepo-common/pom.xml
fcrepo-configs/pom.xml
fcrepo-event-serialization/pom.xml
fcrepo-http-api/pom.xml
fcrepo-http-commons/pom.xml
fcrepo-integration-rdf/pom.xml
fcrepo-jms/pom.xml
fcrepo-kernel-api/pom.xml
fcrepo-kernel-impl/pom.xml
fcrepo-parent/pom.xml
fcrepo-persistence-api/pom.xml
fcrepo-persistence-common/pom.xml
fcrepo-persistence-ocfl/pom.xml
fcrepo-search-api/pom.xml
fcrepo-search-impl/pom.xml
fcrepo-webapp/pom.xml
pom.xml

In preparation for cutting the release candidate:
```
Release candidate branches CANNOT have the same version property as the branch you are branching from (ie main or n.x-maintenance branch, depending on whether this is a major, minor, or patch release)  in the pom.xml file. The versions on the original branch will need to be incremented at the same time you create the release branches. You will need to pull in another community member to create a pull request with the version change, or another committer if you are going to create the pull requests yourself.
```
https://wiki.lyrasis.org/display/FF/Fedora+Release+Process

Increment version to prevent version collisions with 6.0.0 rc 1

---

pom.xml

Updates modeshape version to 5.5.0.fcr
There shouldn't be any visible functionality changes. Running the compatibility test suite should produce the same result as before.

Update modeshape version to 5.5.0.fcr

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/test/java/org/fcrepo/http/api/FedoraLdpTest.java
fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/models/FedoraResource.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/FedoraResourceImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/models/ResourceFactoryImpl.java

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3295
Searches the ancestry of a resource to see if any parent is an Archival Group and adds a Link header if one exists
* Create an Archival Group
* Create some resources underneath the Archival Group
* Perform some HEAD requests on the child resources and check for the Archival Group Link header

Add Link header for the ArchivalGroup of a resource

---

fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/DbFedoraToOcflObjectIndex.java

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3356
* Log a message when a duplicate key exception occurs with the offending id
I made a quick test to simulate inserting duplicate entries with the same key which I put in `RebuildIT` as it makes use of the `FedoraToOcflObjectIndex`:
```
@Test
public void testDuplicateKey() {
final Transaction tx = txManager.create();
final FedoraId fedoraId = FedoraId.create(UUID.randomUUID().toString());
final String ocflId = "ocfl-id-" + UUID.randomUUID();
index.addMapping(tx, fedoraId, fedoraId, ocflId);
index.commit(tx);
index.addMapping(tx, fedoraId, fedoraId, ocflId);
index.commit(tx);
}
```
I then ran this against the different databases and checked the log for output (the test itself should fail w/ the …

Improve duplicate key exception when adding to the OCFL index

---

fcrepo-parent/pom.xml

- Updates a few maven plugins so that the project is able to be build with java 17
Build the project

update maven plugins so that it builds with java 17

---

fcrepo-http-api/src/test/java/org/fcrepo/http/api/ExternalContentHandlerFactoryTest.java

Fixes broken test in /ExternalContentHandlerFactoryTest.

---

pom.xml

**Related to** https://github.com/fcrepo/fcrepo-storage-ocfl/pull/44
Upgrades the version of ocfl-java. This keeps it in sync with fcrepo-storage-ocfl: https://github.com/fcrepo/fcrepo-storage-ocfl/pull/44
Everything should work the same

upgraded ocfl-java

---

fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/FedoraContextLoaderListener.java
fcrepo-webapp/src/main/webapp/index.html
src/site/markdown/index.md.vm

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3749
Changes the remaining references to duraspace to lyrasis
No functional changes. Click the links on the splash page.

duraspace => lyrasis

---

pom.xml

Updates modeshape version to 5.5.1-fcr to prepare for fcrepo 5.1.2 release

Update modeshape to 5.5.1-fcr

---

fcrepo-parent/pom.xml

**.Upgrade to new Sonatype build infrastructure.**
* * *
**JIRA Ticket**: [(link)](https://fedora-repository.atlassian.net/browse/FCREPO-3794)

Upgrade to new Sonatype build infrastructure.

---

fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/OcflPersistentStorageUtils.java
pom.xml

**Upgrades ocfl-java to 1.4.3**
* * *
**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3793
No functional change.

Upgrades ocfl-java to 1.4.3

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/ContentExposingResource.java
fcrepo-http-api/src/main/resources/views/common-node-actions.vsl
fcrepo-webapp/src/main/webapp/static/js/common.js

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3517
* Add an additional describedby link header for the memento description
* Update the HTML UI to show Binary versions and link to them using the memento description
* Start Fedora
* Create a binary
* Update the binary
* Use the `View Versions` to navigate to the Binary version listing
* Browse to either version for the Binary and validate that:
* the metadata is correct for the version
* the page shows it's a historical version and is read only

Version Listing for Binaries

---

fcrepo-configs/src/main/resources/sql/h2/R__Create_search.sql
fcrepo-search-impl/src/main/java/org/fcrepo/search/impl/DbSearchIndexImpl.java
pom.xml

Upgrade flyway to support h2 upgrade.

---

pom.xml

Addresses recommendation in https://github.com/fcrepo/fcrepo/security/dependabot/15

Fixes security issuse in jackson.databind dependency

---

fcrepo-configs/src/main/resources/sql/h2/R__Create_search.sql
fcrepo-kernel-impl/pom.xml
fcrepo-search-impl/src/main/java/org/fcrepo/search/impl/DbSearchIndexImpl.java
pom.xml

**Upgrades H2 and related dependencies to address security issue.**
* * *
**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3817

Upgrades H2 and related dependencies to address security issue.

---

pom.xml

Upgrade ocfl-java to 1.4.6

---

fcrepo-http-api/src/main/resources/views/common-header.vsl
fcrepo-webapp/src/main/webapp/static/js/common.js

- removed the JS listener calls in common.js
- removed the menu items in common-header.vsl
Resolves: https://fedora-repository.atlassian.net/browse/FCREPO-3829

remove transaction UI elements from HTML user interface

---

fcrepo-webapp/src/main/webapp/static/js/common.js

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3835
Removes listeners referencing HTML IDs that have already been removed and functions they called.
As these functions are already removed this PR should have no effect on the HTML UI

Remove unused JS functions

---

fcrepo-configs/src/main/java/org/fcrepo/config/FedoraPropsConfig.java
fcrepo-configs/src/main/java/org/fcrepo/config/OcflPropsConfig.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/OcflPersistenceConfig.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/OcflPersistentStorageUtils.java
fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/ReindexService.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/AbstractReindexerTest.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/OcflPersistentStorageSessionTest.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/ReindexServiceTest.java

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3823
* Add prop for setting verify inventory flag for ocfl

Add ocfl verify inventory prop

---

fcrepo-integration-ldp/pom.xml
fcrepo-persistence-ocfl/pom.xml
pom.xml

Update remaining 6.3.0-SNAPSHOT references to 6.3.1-SNAPSHOT

Update remaining 6.3.0 references

---

fcrepo-auth-common/pom.xml
fcrepo-auth-webac/pom.xml
fcrepo-common/pom.xml
fcrepo-configs/pom.xml
fcrepo-event-serialization/pom.xml
fcrepo-http-api/pom.xml
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/TransactionsIT.java
fcrepo-http-commons/pom.xml
fcrepo-integration-ldp/pom.xml
fcrepo-integration-rdf/pom.xml
fcrepo-jms/pom.xml
fcrepo-kernel-api/pom.xml
fcrepo-kernel-impl/pom.xml
fcrepo-parent/pom.xml
fcrepo-persistence-api/pom.xml
fcrepo-persistence-common/pom.xml
fcrepo-persistence-ocfl/pom.xml
fcrepo-search-api/pom.xml
fcrepo-search-impl/pom.xml
fcrepo-stats-api/pom.xml
fcrepo-stats-impl/pom.xml
fcrepo-webapp/pom.xml
pom.xml

Standard practice as part of the release process.

Merge the Release Branch Back into Main

---

pom.xml

**Update the jackson-databind-yaml dependency**
* * *
**JIRA Ticket**: https://fedora-repository.atlassian.net/jira/software/c/projects/FCREPO/issues/FCREPO-3879
Updates jackson databind and jackson core version to address https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-25857

updated jackson databind dep

---

fcrepo-configs/src/main/java/org/fcrepo/config/DatabaseConfig.java

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3903
This alters how we configure the HikariCP to allow inserting a separate file of configuration properties.
Instead of needing us to expose all the various [configuration](https://github.com/brettwooldridge/HikariCP#gear-configuration-knobs-baby) from HikariCP, this allows users to tweak any configuration knobs on their own...for better or worse.
I'm suggesting this as an alternative to #2043 so I would suggest using the same method with a slight tweak.
Setup and then stop a mysql container.
```sh
> docker run --name fcrepo-database -e MYSQL_ROOT_PASSWORD=root-pw -e MYSQL_DATABASE=fcrepo -e MYSQL_USER=fcrepo-user -e MYSQL_PASSWORD=fcrepo-pw -p 3306:3306 -d mysql:8.0
> docker container stop fcrepo-database
```
Create …

Change how we configure the HikariCP

---

pom.xml

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3911
* Update ActiveMQ
* Remove enforce-victims-rule execution

Update ActiveMQ for Fedora 4

---

pom.xml

Resolves: https://fedora-repository.atlassian.net/browse/FCREPO-3911 for the 5.1.2+
* * *
**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3911 for the 5.1.2+
Updates ActiveMQ to the latest secure release for Java 8.

Upgrade ActiveMQ to latest java 8 compatible version: v5.16.7

---

pom.xml

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3911
Updates the version of Activemq we use.
This should have no functional difference from an existing application.
All internal tests should succeed and I did run the API testsuite against it and the numbers matched the last run.

Update activemq for CVE-2023-46604

---

pom.xml

Updates spring version to 5.3.30 for fedora 5.x

Update spring version to 5.3.30

---

.github/workflows/build.yml
pom.xml

**JIRA Ticket**: Not actually related to https://fedora-repository.atlassian.net/browse/FCREPO-3911 but since we're doing work
Update spring-web dependency versions to avoid https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2016-1000027
No functional changes
Should build and run integration tests.

Update spring as well

---

pom.xml

Update 4.x spring to 5.3.30

---

fcrepo-auth-common/pom.xml
fcrepo-auth-webac/pom.xml
fcrepo-common/pom.xml
fcrepo-configs/pom.xml
fcrepo-event-serialization/pom.xml
fcrepo-http-api/pom.xml
fcrepo-http-commons/pom.xml
fcrepo-integration-ldp/pom.xml
fcrepo-integration-rdf/pom.xml
fcrepo-jms/pom.xml
fcrepo-kernel-api/pom.xml
fcrepo-kernel-impl/pom.xml
fcrepo-parent/pom.xml
fcrepo-persistence-api/pom.xml
fcrepo-persistence-common/pom.xml
fcrepo-persistence-ocfl/pom.xml
fcrepo-search-api/pom.xml
fcrepo-search-impl/pom.xml
fcrepo-stats-api/pom.xml
fcrepo-stats-impl/pom.xml
fcrepo-webapp/pom.xml
pom.xml

6.5.0 Release

---

fcrepo-configs/src/main/java/org/fcrepo/config/FedoraPropsConfig.java
fcrepo-http-api/src/main/resources/views/common-register-header.vsl

This fixes a typo -- the contraction "it's" should be changed to the possessive "its."
As long as the changed wording doesn't break any test assertions, I don't think this should be an impactful change.

Remove unnecessary apostrophe from messages.

---

fcrepo-configs/src/main/java/org/fcrepo/config/FedoraPropsConfig.java
fcrepo-http-api/src/main/resources/views/common-register-header.vsl
fcrepo-webapp/src/main/webapp/index.html

* * *
**JIRA Ticket**: https://fedora-repository.atlassian.net/jira/software/c/projects/FCREPO/issues/FCREPO-3945
Simply updates the registry URL in 3 places

Changing URL for repo registry

---

pom.xml

**JIRA Ticket**: N/A
Updates the version of spring used to the most recent non-6.x version of spring in order to address 3 out of the 4 security vulnerabilities coming from spring-web:
https://mvnrepository.com/artifact/org.springframework/spring-web/5.3.39
versus
https://mvnrepository.com/artifact/org.springframework/spring-web/5.3.27
There shouldn't be any directly observable changes, this is just a dependency update.

Update to spring 5.3.39 to address security vulnerabilities

---

fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersioningIT.java

Modifies a flapping IT that was failing on one or two builds in every PR by allowing it to expect there be one or two mementos after deletion, since that depends on whether the creation and deletion happened in the same second.
Prior to this PR, you could make the test consistently fail by adding a `Thread.sleep(1000)` here:
https://github.com/fcrepo/fcrepo/blob/main/fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraVersioningIT.java#L1547
Since that would make the create and delete always happen on separate seconds (rather than randomly happening like it was doing). With this PR, the wait wouldn't impact whether the test passes. Although mostly the way to test this is to see the build in ghactions pass for all jobs without hitting this error:
```
INFO 14:59:55.022 …
```

Make Versioning IT tolerant of timing inconsistencies

---

fcrepo-persistence-ocfl/pom.xml
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/integration/persistence/ocfl/impl/DeleteResourcePersisterIT.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/integration/persistence/ocfl/impl/NonRdfSourcesPersistenceIT.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/integration/persistence/ocfl/impl/OverwriteRdfTombstonePersisterIT.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/AbstractPersisterTest.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/AbstractReindexerTest.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/CreateNonRdfSourcePersisterTest.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/CreateRdfSourcePersisterTest.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/CreateVersionPersisterTest.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/DbFedoraToOcflObjectIndexTest.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/DeleteResourcePersisterTest.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/OcflPersistentSessionManagerTest.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/OcflPersistentStorageSessionTest.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/PurgeResourcePersisterTest.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/ReindexManagerTest.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/ReindexServiceTest.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/ResourceHeadersAdapterTest.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/UpdateNonRdfSourceHeadersPersisterTest.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/UpdateNonRdfSourcePersisterTest.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/UpdateRDFSourcePersisterTest.java

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3985
Updates fcrepo-persistence-ocfl to use junit 5 for testing

FCREPO-3985 - Update fcrepo-persistence-ocfl to junit 5

---

fcrepo-webapp/pom.xml
fcrepo-webapp/src/test/java/org/fcrepo/integration/AbstractResourceIT.java
fcrepo-webapp/src/test/java/org/fcrepo/integration/FedoraHtmlResponsesIT.java
fcrepo-webapp/src/test/java/org/fcrepo/integration/SanityCheckIT.java
fcrepo-webapp/src/test/java/org/fcrepo/webapp/ConstraintExceptionsTest.java

**Updates to bring fcrepo-webapp up to unit 5**
* * *
https://fedora-repository.atlassian.net/jira/software/c/projects/FCREPO/issues/FCREPO-3975
* Ensure tests run and results are as expected

upgrade to  junit5 in fcrepo-webapp

---

fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraSearchIT.java
fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/TransactionsIT.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/CreateResourceServiceImpl.java
fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/ReplaceBinariesServiceImpl.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/services/ReplaceBinariesServiceImplTest.java

Some change in Github actions has a test that is setting the session timeout to 5 seconds causing errors in other tests. This might be due to change test ordering, concurrency or perhaps a failure in that particular test.
Regardless, this change is to set it to the default of 180000ms or 3 minutes between each test.
Tests should pass on Github

Reset session timeout between tests

---

fcrepo-search-api/pom.xml
fcrepo-search-api/src/test/java/org/fcrepo/search/api/ConditionTest.java
fcrepo-search-api/src/test/java/org/fcrepo/search/api/PaginationInfoTest.java
fcrepo-search-api/src/test/java/org/fcrepo/search/api/SearchParametersTest.java
fcrepo-search-api/src/test/java/org/fcrepo/search/api/SearchResultTest.java

**JIRA Ticket**: https://github.com/fcrepo/fcrepo/issues/2177
Add tests for fcrepo-search-api
Running the tests

2177 - Add tests for fcrepo-search-api

---

fcrepo-stats-impl/pom.xml
fcrepo-stats-impl/src/test/java/org/fcrepo/stats/impl/DbRepositoryStatsImplTest.java
fcrepo-stats-impl/src/test/java/org/fcrepo/stats/impl/utils/StatsTestConfiguration.java

**JIRA Ticket**: https://github.com/fcrepo/fcrepo/issues/2180
Add test for DbRepositoryStatsImplTest, the only class in fcrepo-stats-impl
By running the test

2180 - Add tests for fcrepo-stats-impl

---

fcrepo-common/pom.xml
fcrepo-common/src/test/java/org/fcrepo/common/test/utils/MockitoMockFactoryBean.java
fcrepo-kernel-impl/pom.xml
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/services/ReplacePropertiesServiceImplTest.java
fcrepo-kernel-impl/src/test/resources/containmentIndexTest.xml
fcrepo-kernel-impl/src/test/resources/membershipServiceTest.xml
fcrepo-persistence-ocfl/pom.xml
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/RepositoryInitializationFilterTest.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/RepositoryInitializerTest.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/FcrepoOcflObjectSessionWrapperTest.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/IndexBuilderImplTest.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/OcflPersistenceConfigTest.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/OcflPersistentStorageUtilsTest.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/ReindexResourcePersisterTest.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/impl/ResourceHeadersAdapterTest.java
fcrepo-persistence-ocfl/src/test/java/org/fcrepo/persistence/ocfl/utils/MockitoMockFactoryBean.java
fcrepo-persistence-ocfl/src/test/resources/spring-test/fcrepo-config.xml
fcrepo-persistence-ocfl/src/test/resources/spring-test/manual-versioning-config.xml
pom.xml

**JIRA Ticket**: https://github.com/fcrepo/fcrepo/issues/2176
https://github.com/fcrepo/fcrepo/issues/2124
* Adds tests for fcrepo-persistence-ocfl
* Adds upgrades mockito to 5.17 in order to allow for static mocking
Tests should pass

2176 - Test coverage for fcrepo-persistence-ocfl

---

fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/TransactionImpl.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/TransactionImplTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/models/BinaryImplTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/models/ContainerImplTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/models/FedoraResourceImplTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/models/NonRdfSourceDescriptionImplTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/models/ResourceFactoryImplTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/models/TimeMapImplTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/models/TombstoneImplTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/models/WebacAclImplTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/operations/ReferenceOperationBuilderTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/operations/ReindexResourceOperationBuilderTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/operations/UpdateNonRdfSourceHeadersOperationImplTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/services/FixityServiceImplTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/services/ReindexServiceImplTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/services/ResourceTripleServiceImplTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/services/UpdatePropertiesServiceImplTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/services/WebacAclServiceImplTest.java
fcrepo-kernel-impl/src/test/java/org/fcrepo/kernel/impl/util/UserUtilTest.java

**JIRA Ticket**: https://github.com/fcrepo/fcrepo/issues/2172

2172 - Add coverage for fcrepo-kernel-impl

---

fcrepo-http-api/src/test/java/org/fcrepo/http/api/responses/SearchResultProviderTest.java

**JIRA Ticket**: https://github.com/fcrepo/fcrepo/issues/2166
Adds tests for SearchResultProvider

Increasing Test coverage 

---

pom.xml

**JIRA Ticket**: https://github.com/fcrepo/fcrepo/issues/2127
Small version bump from 0.13.3 to 0.13.6
Check tests pass

upgrading jsonld to 0.13.6

---

pom.xml

**JIRA Ticket**: https://github.com/fcrepo/fcrepo/issues/2133
Simple version bump to 1.18.0
check tests pass

upgrading commons codec to 1.18.0

---

fcrepo-auth-common/pom.xml
fcrepo-auth-webac/pom.xml
fcrepo-common/pom.xml
fcrepo-configs/pom.xml
fcrepo-event-serialization/pom.xml
fcrepo-http-api/pom.xml
fcrepo-http-commons/pom.xml
fcrepo-jms/pom.xml
fcrepo-kernel-api/pom.xml
fcrepo-kernel-impl/pom.xml
fcrepo-parent/pom.xml
fcrepo-persistence-api/pom.xml
fcrepo-persistence-common/pom.xml
fcrepo-persistence-ocfl/pom.xml
fcrepo-search-api/pom.xml
fcrepo-search-impl/pom.xml
pom.xml

Remove felix and osgi config, everything is jars now, since we no longer work with OSGI/karaf

Remove felix and osgi config

---

fcrepo-common/pom.xml
fcrepo-common/src/main/java/org/fcrepo/common/db/DbTransactionExecutor.java
fcrepo-kernel-impl/pom.xml
pom.xml

**JIRA Ticket**: https://github.com/fcrepo/fcrepo/issues/2227
* Update failsafe dependency, and remove unnecessary include

GH-2227 - Update failsafe dependency, and remove unnecessary include

---

pom.xml

Adding specific version for changelog plugin in the pom file to stop maven build warnings
* Check build still succeeds

Adding specific version for maven-changelog plugin

---

fcrepo-configs/src/main/java/org/fcrepo/config/DatabaseConfig.java
fcrepo-configs/src/test/java/org/fcrepo/config/DatabaseConfigTest.java

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-4039
Adds internal HikariCP metrics to the Fedora Prometheus endpoint to allow monitoring.
Pull in this PR, start Fedora, setup a prometheus and grafana setup. Set Prometheus to scrape Fedora at `/rest/prometheus`. In grafana, set up a datasource for prometheus, then add a panel that pulls the `hikaricp_*` metrics.
Example Grafana dashboard
[Example-Fedora-Dashboard.json](https://github.com/user-attachments/files/22642664/Example-Fedora-Dashboard.json)
Prometheus config file
[prometheus.yml](https://github.com/user-attachments/files/22642675/prometheus.yml)
Prometheus and Grafana Docker Compose …

add HikariCP metrics

---

fcrepo-http-api/src/main/resources/views/common-node-actions.vsl

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-4031
Adds a simple javascript alert to add a confirmation step to the Delete button in the UI
Test functionality in common browsers

adding simple verificaiton to DELETE form

---

fcrepo-persistence-ocfl/pom.xml
pom.xml

Minor update to use the existing variable for fcrepo-storage-ocfl's version, and to set it to the correct value
build passing

Use variable for fcrepo-storage-ocfl version
